/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.app.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.remote.app.model.RemoteAppEntryLocalization;
import com.liferay.remote.app.model.RemoteAppEntryLocalizationModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RemoteAppEntryLocalization service. Represents a row in the &quot;RemoteAppEntryLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RemoteAppEntryLocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RemoteAppEntryLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RemoteAppEntryLocalizationImpl
 * @generated
 */
public class RemoteAppEntryLocalizationModelImpl
	extends BaseModelImpl<RemoteAppEntryLocalization>
	implements RemoteAppEntryLocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a remote app entry localization model instance should use the <code>RemoteAppEntryLocalization</code> interface instead.
	 */
	public static final String TABLE_NAME = "RemoteAppEntryLocalization";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"remoteAppEntryLocalizationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"remoteAppEntryId", Types.BIGINT},
		{"languageId", Types.VARCHAR}, {"description", Types.CLOB},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteAppEntryLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteAppEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RemoteAppEntryLocalization (mvccVersion LONG default 0 not null,remoteAppEntryLocalizationId LONG not null primary key,companyId LONG,remoteAppEntryId LONG,languageId VARCHAR(75) null,description TEXT null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table RemoteAppEntryLocalization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY remoteAppEntryLocalization.remoteAppEntryLocalizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RemoteAppEntryLocalization.remoteAppEntryLocalizationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REMOTEAPPENTRYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REMOTEAPPENTRYLOCALIZATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RemoteAppEntryLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _remoteAppEntryLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRemoteAppEntryLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _remoteAppEntryLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RemoteAppEntryLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return RemoteAppEntryLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RemoteAppEntryLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RemoteAppEntryLocalization, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RemoteAppEntryLocalization, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(RemoteAppEntryLocalization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RemoteAppEntryLocalization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RemoteAppEntryLocalization, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RemoteAppEntryLocalization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RemoteAppEntryLocalization, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RemoteAppEntryLocalization, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RemoteAppEntryLocalization>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RemoteAppEntryLocalization.class.getClassLoader(),
			RemoteAppEntryLocalization.class, ModelWrapper.class);

		try {
			Constructor<RemoteAppEntryLocalization> constructor =
				(Constructor<RemoteAppEntryLocalization>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<RemoteAppEntryLocalization, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<RemoteAppEntryLocalization, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<RemoteAppEntryLocalization, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RemoteAppEntryLocalization, Object>>();
		Map<String, BiConsumer<RemoteAppEntryLocalization, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<RemoteAppEntryLocalization, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", RemoteAppEntryLocalization::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<RemoteAppEntryLocalization, Long>)
				RemoteAppEntryLocalization::setMvccVersion);
		attributeGetterFunctions.put(
			"remoteAppEntryLocalizationId",
			RemoteAppEntryLocalization::getRemoteAppEntryLocalizationId);
		attributeSetterBiConsumers.put(
			"remoteAppEntryLocalizationId",
			(BiConsumer<RemoteAppEntryLocalization, Long>)
				RemoteAppEntryLocalization::setRemoteAppEntryLocalizationId);
		attributeGetterFunctions.put(
			"companyId", RemoteAppEntryLocalization::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<RemoteAppEntryLocalization, Long>)
				RemoteAppEntryLocalization::setCompanyId);
		attributeGetterFunctions.put(
			"remoteAppEntryId",
			RemoteAppEntryLocalization::getRemoteAppEntryId);
		attributeSetterBiConsumers.put(
			"remoteAppEntryId",
			(BiConsumer<RemoteAppEntryLocalization, Long>)
				RemoteAppEntryLocalization::setRemoteAppEntryId);
		attributeGetterFunctions.put(
			"languageId", RemoteAppEntryLocalization::getLanguageId);
		attributeSetterBiConsumers.put(
			"languageId",
			(BiConsumer<RemoteAppEntryLocalization, String>)
				RemoteAppEntryLocalization::setLanguageId);
		attributeGetterFunctions.put(
			"description", RemoteAppEntryLocalization::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<RemoteAppEntryLocalization, String>)
				RemoteAppEntryLocalization::setDescription);
		attributeGetterFunctions.put(
			"name", RemoteAppEntryLocalization::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<RemoteAppEntryLocalization, String>)
				RemoteAppEntryLocalization::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getRemoteAppEntryLocalizationId() {
		return _remoteAppEntryLocalizationId;
	}

	@Override
	public void setRemoteAppEntryLocalizationId(
		long remoteAppEntryLocalizationId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remoteAppEntryLocalizationId = remoteAppEntryLocalizationId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getRemoteAppEntryId() {
		return _remoteAppEntryId;
	}

	@Override
	public void setRemoteAppEntryId(long remoteAppEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remoteAppEntryId = remoteAppEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRemoteAppEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("remoteAppEntryId"));
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RemoteAppEntryLocalization.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RemoteAppEntryLocalization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RemoteAppEntryLocalization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RemoteAppEntryLocalizationImpl remoteAppEntryLocalizationImpl =
			new RemoteAppEntryLocalizationImpl();

		remoteAppEntryLocalizationImpl.setMvccVersion(getMvccVersion());
		remoteAppEntryLocalizationImpl.setRemoteAppEntryLocalizationId(
			getRemoteAppEntryLocalizationId());
		remoteAppEntryLocalizationImpl.setCompanyId(getCompanyId());
		remoteAppEntryLocalizationImpl.setRemoteAppEntryId(
			getRemoteAppEntryId());
		remoteAppEntryLocalizationImpl.setLanguageId(getLanguageId());
		remoteAppEntryLocalizationImpl.setDescription(getDescription());
		remoteAppEntryLocalizationImpl.setName(getName());

		remoteAppEntryLocalizationImpl.resetOriginalValues();

		return remoteAppEntryLocalizationImpl;
	}

	@Override
	public RemoteAppEntryLocalization cloneWithOriginalValues() {
		RemoteAppEntryLocalizationImpl remoteAppEntryLocalizationImpl =
			new RemoteAppEntryLocalizationImpl();

		remoteAppEntryLocalizationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		remoteAppEntryLocalizationImpl.setRemoteAppEntryLocalizationId(
			this.<Long>getColumnOriginalValue("remoteAppEntryLocalizationId"));
		remoteAppEntryLocalizationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		remoteAppEntryLocalizationImpl.setRemoteAppEntryId(
			this.<Long>getColumnOriginalValue("remoteAppEntryId"));
		remoteAppEntryLocalizationImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		remoteAppEntryLocalizationImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		remoteAppEntryLocalizationImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return remoteAppEntryLocalizationImpl;
	}

	@Override
	public int compareTo(
		RemoteAppEntryLocalization remoteAppEntryLocalization) {

		long primaryKey = remoteAppEntryLocalization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RemoteAppEntryLocalization)) {
			return false;
		}

		RemoteAppEntryLocalization remoteAppEntryLocalization =
			(RemoteAppEntryLocalization)object;

		long primaryKey = remoteAppEntryLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RemoteAppEntryLocalization> toCacheModel() {
		RemoteAppEntryLocalizationCacheModel
			remoteAppEntryLocalizationCacheModel =
				new RemoteAppEntryLocalizationCacheModel();

		remoteAppEntryLocalizationCacheModel.mvccVersion = getMvccVersion();

		remoteAppEntryLocalizationCacheModel.remoteAppEntryLocalizationId =
			getRemoteAppEntryLocalizationId();

		remoteAppEntryLocalizationCacheModel.companyId = getCompanyId();

		remoteAppEntryLocalizationCacheModel.remoteAppEntryId =
			getRemoteAppEntryId();

		remoteAppEntryLocalizationCacheModel.languageId = getLanguageId();

		String languageId = remoteAppEntryLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			remoteAppEntryLocalizationCacheModel.languageId = null;
		}

		remoteAppEntryLocalizationCacheModel.description = getDescription();

		String description = remoteAppEntryLocalizationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			remoteAppEntryLocalizationCacheModel.description = null;
		}

		remoteAppEntryLocalizationCacheModel.name = getName();

		String name = remoteAppEntryLocalizationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			remoteAppEntryLocalizationCacheModel.name = null;
		}

		return remoteAppEntryLocalizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RemoteAppEntryLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RemoteAppEntryLocalization, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RemoteAppEntryLocalization, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RemoteAppEntryLocalization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RemoteAppEntryLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RemoteAppEntryLocalization, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RemoteAppEntryLocalization, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(RemoteAppEntryLocalization)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, RemoteAppEntryLocalization>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _remoteAppEntryLocalizationId;
	private long _companyId;
	private long _remoteAppEntryId;
	private String _languageId;
	private String _description;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<RemoteAppEntryLocalization, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RemoteAppEntryLocalization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"remoteAppEntryLocalizationId", _remoteAppEntryLocalizationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("remoteAppEntryId", _remoteAppEntryId);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("remoteAppEntryLocalizationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("remoteAppEntryId", 8L);

		columnBitmasks.put("languageId", 16L);

		columnBitmasks.put("description", 32L);

		columnBitmasks.put("name", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RemoteAppEntryLocalization _escapedModel;

}