/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.display.page.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.display.page.model.AssetDisplayPage;
import com.liferay.asset.display.page.model.AssetDisplayPageModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetDisplayPage service. Represents a row in the &quot;AssetDisplayPage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssetDisplayPageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetDisplayPageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetDisplayPageImpl
 * @see AssetDisplayPage
 * @see AssetDisplayPageModel
 * @generated
 */
@ProviderType
public class AssetDisplayPageModelImpl extends BaseModelImpl<AssetDisplayPage>
	implements AssetDisplayPageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset display page model instance should use the {@link AssetDisplayPage} interface instead.
	 */
	public static final String TABLE_NAME = "AssetDisplayPage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetDisplayPageId", Types.BIGINT },
			{ "assetEntryId", Types.BIGINT },
			{ "layoutId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("assetDisplayPageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("layoutId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssetDisplayPage (assetDisplayPageId LONG not null primary key,assetEntryId LONG,layoutId LONG)";
	public static final String TABLE_SQL_DROP = "drop table AssetDisplayPage";
	public static final String ORDER_BY_JPQL = " ORDER BY assetDisplayPage.assetDisplayPageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssetDisplayPage.assetDisplayPageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.display.page.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.asset.display.page.model.AssetDisplayPage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.display.page.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.asset.display.page.model.AssetDisplayPage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.asset.display.page.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.asset.display.page.model.AssetDisplayPage"),
			true);
	public static final long ASSETENTRYID_COLUMN_BITMASK = 1L;
	public static final long LAYOUTID_COLUMN_BITMASK = 2L;
	public static final long ASSETDISPLAYPAGEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.asset.display.page.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.asset.display.page.model.AssetDisplayPage"));

	public AssetDisplayPageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetDisplayPageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetDisplayPageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetDisplayPageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetDisplayPage.class;
	}

	@Override
	public String getModelClassName() {
		return AssetDisplayPage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetDisplayPageId", getAssetDisplayPageId());
		attributes.put("assetEntryId", getAssetEntryId());
		attributes.put("layoutId", getLayoutId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetDisplayPageId = (Long)attributes.get("assetDisplayPageId");

		if (assetDisplayPageId != null) {
			setAssetDisplayPageId(assetDisplayPageId);
		}

		Long assetEntryId = (Long)attributes.get("assetEntryId");

		if (assetEntryId != null) {
			setAssetEntryId(assetEntryId);
		}

		Long layoutId = (Long)attributes.get("layoutId");

		if (layoutId != null) {
			setLayoutId(layoutId);
		}
	}

	@Override
	public long getAssetDisplayPageId() {
		return _assetDisplayPageId;
	}

	@Override
	public void setAssetDisplayPageId(long assetDisplayPageId) {
		_assetDisplayPageId = assetDisplayPageId;
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAssetEntryId) {
			_setOriginalAssetEntryId = true;

			_originalAssetEntryId = _assetEntryId;
		}

		_assetEntryId = assetEntryId;
	}

	public long getOriginalAssetEntryId() {
		return _originalAssetEntryId;
	}

	@Override
	public long getLayoutId() {
		return _layoutId;
	}

	@Override
	public void setLayoutId(long layoutId) {
		_columnBitmask |= LAYOUTID_COLUMN_BITMASK;

		if (!_setOriginalLayoutId) {
			_setOriginalLayoutId = true;

			_originalLayoutId = _layoutId;
		}

		_layoutId = layoutId;
	}

	public long getOriginalLayoutId() {
		return _originalLayoutId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssetDisplayPage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetDisplayPage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetDisplayPage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetDisplayPageImpl assetDisplayPageImpl = new AssetDisplayPageImpl();

		assetDisplayPageImpl.setAssetDisplayPageId(getAssetDisplayPageId());
		assetDisplayPageImpl.setAssetEntryId(getAssetEntryId());
		assetDisplayPageImpl.setLayoutId(getLayoutId());

		assetDisplayPageImpl.resetOriginalValues();

		return assetDisplayPageImpl;
	}

	@Override
	public int compareTo(AssetDisplayPage assetDisplayPage) {
		long primaryKey = assetDisplayPage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetDisplayPage)) {
			return false;
		}

		AssetDisplayPage assetDisplayPage = (AssetDisplayPage)obj;

		long primaryKey = assetDisplayPage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssetDisplayPageModelImpl assetDisplayPageModelImpl = this;

		assetDisplayPageModelImpl._originalAssetEntryId = assetDisplayPageModelImpl._assetEntryId;

		assetDisplayPageModelImpl._setOriginalAssetEntryId = false;

		assetDisplayPageModelImpl._originalLayoutId = assetDisplayPageModelImpl._layoutId;

		assetDisplayPageModelImpl._setOriginalLayoutId = false;

		assetDisplayPageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetDisplayPage> toCacheModel() {
		AssetDisplayPageCacheModel assetDisplayPageCacheModel = new AssetDisplayPageCacheModel();

		assetDisplayPageCacheModel.assetDisplayPageId = getAssetDisplayPageId();

		assetDisplayPageCacheModel.assetEntryId = getAssetEntryId();

		assetDisplayPageCacheModel.layoutId = getLayoutId();

		return assetDisplayPageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{assetDisplayPageId=");
		sb.append(getAssetDisplayPageId());
		sb.append(", assetEntryId=");
		sb.append(getAssetEntryId());
		sb.append(", layoutId=");
		sb.append(getLayoutId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.asset.display.page.model.AssetDisplayPage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetDisplayPageId</column-name><column-value><![CDATA[");
		sb.append(getAssetDisplayPageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetEntryId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>layoutId</column-name><column-value><![CDATA[");
		sb.append(getLayoutId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssetDisplayPage.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetDisplayPage.class
		};
	private long _assetDisplayPageId;
	private long _assetEntryId;
	private long _originalAssetEntryId;
	private boolean _setOriginalAssetEntryId;
	private long _layoutId;
	private long _originalLayoutId;
	private boolean _setOriginalLayoutId;
	private long _columnBitmask;
	private AssetDisplayPage _escapedModel;
}