/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.meris.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.meris.model.MerisSegmentRel;
import com.liferay.meris.model.MerisSegmentRelModel;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MerisSegmentRel service. Represents a row in the &quot;MerisSegmentRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MerisSegmentRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MerisSegmentRelImpl}.
 * </p>
 *
 * @author Eduardo Garcia
 * @see MerisSegmentRelImpl
 * @see MerisSegmentRel
 * @see MerisSegmentRelModel
 * @generated
 */
@ProviderType
public class MerisSegmentRelModelImpl extends BaseModelImpl<MerisSegmentRel>
	implements MerisSegmentRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meris segment rel model instance should use the {@link MerisSegmentRel} interface instead.
	 */
	public static final String TABLE_NAME = "MerisSegmentRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "merisSegmentRelId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "merisSegmentId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("merisSegmentRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("merisSegmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table MerisSegmentRel (merisSegmentRelId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,merisSegmentId LONG,classNameId LONG,classPK LONG)";
	public static final String TABLE_SQL_DROP = "drop table MerisSegmentRel";
	public static final String ORDER_BY_JPQL = " ORDER BY merisSegmentRel.merisSegmentRelId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MerisSegmentRel.merisSegmentRelId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.meris.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.meris.model.MerisSegmentRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.meris.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.meris.model.MerisSegmentRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.meris.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.meris.model.MerisSegmentRel"),
			true);
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static final long CLASSPK_COLUMN_BITMASK = 2L;
	public static final long MERISSEGMENTID_COLUMN_BITMASK = 4L;
	public static final long MERISSEGMENTRELID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.meris.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.meris.model.MerisSegmentRel"));

	public MerisSegmentRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _merisSegmentRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMerisSegmentRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _merisSegmentRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MerisSegmentRel.class;
	}

	@Override
	public String getModelClassName() {
		return MerisSegmentRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("merisSegmentRelId", getMerisSegmentRelId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("merisSegmentId", getMerisSegmentId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long merisSegmentRelId = (Long)attributes.get("merisSegmentRelId");

		if (merisSegmentRelId != null) {
			setMerisSegmentRelId(merisSegmentRelId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long merisSegmentId = (Long)attributes.get("merisSegmentId");

		if (merisSegmentId != null) {
			setMerisSegmentId(merisSegmentId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}
	}

	@Override
	public long getMerisSegmentRelId() {
		return _merisSegmentRelId;
	}

	@Override
	public void setMerisSegmentRelId(long merisSegmentRelId) {
		_merisSegmentRelId = merisSegmentRelId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getMerisSegmentId() {
		return _merisSegmentId;
	}

	@Override
	public void setMerisSegmentId(long merisSegmentId) {
		_columnBitmask |= MERISSEGMENTID_COLUMN_BITMASK;

		if (!_setOriginalMerisSegmentId) {
			_setOriginalMerisSegmentId = true;

			_originalMerisSegmentId = _merisSegmentId;
		}

		_merisSegmentId = merisSegmentId;
	}

	public long getOriginalMerisSegmentId() {
		return _originalMerisSegmentId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MerisSegmentRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MerisSegmentRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MerisSegmentRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MerisSegmentRelImpl merisSegmentRelImpl = new MerisSegmentRelImpl();

		merisSegmentRelImpl.setMerisSegmentRelId(getMerisSegmentRelId());
		merisSegmentRelImpl.setGroupId(getGroupId());
		merisSegmentRelImpl.setCompanyId(getCompanyId());
		merisSegmentRelImpl.setUserId(getUserId());
		merisSegmentRelImpl.setUserName(getUserName());
		merisSegmentRelImpl.setCreateDate(getCreateDate());
		merisSegmentRelImpl.setModifiedDate(getModifiedDate());
		merisSegmentRelImpl.setMerisSegmentId(getMerisSegmentId());
		merisSegmentRelImpl.setClassNameId(getClassNameId());
		merisSegmentRelImpl.setClassPK(getClassPK());

		merisSegmentRelImpl.resetOriginalValues();

		return merisSegmentRelImpl;
	}

	@Override
	public int compareTo(MerisSegmentRel merisSegmentRel) {
		long primaryKey = merisSegmentRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MerisSegmentRel)) {
			return false;
		}

		MerisSegmentRel merisSegmentRel = (MerisSegmentRel)obj;

		long primaryKey = merisSegmentRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MerisSegmentRelModelImpl merisSegmentRelModelImpl = this;

		merisSegmentRelModelImpl._setModifiedDate = false;

		merisSegmentRelModelImpl._originalMerisSegmentId = merisSegmentRelModelImpl._merisSegmentId;

		merisSegmentRelModelImpl._setOriginalMerisSegmentId = false;

		merisSegmentRelModelImpl._originalClassNameId = merisSegmentRelModelImpl._classNameId;

		merisSegmentRelModelImpl._setOriginalClassNameId = false;

		merisSegmentRelModelImpl._originalClassPK = merisSegmentRelModelImpl._classPK;

		merisSegmentRelModelImpl._setOriginalClassPK = false;

		merisSegmentRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MerisSegmentRel> toCacheModel() {
		MerisSegmentRelCacheModel merisSegmentRelCacheModel = new MerisSegmentRelCacheModel();

		merisSegmentRelCacheModel.merisSegmentRelId = getMerisSegmentRelId();

		merisSegmentRelCacheModel.groupId = getGroupId();

		merisSegmentRelCacheModel.companyId = getCompanyId();

		merisSegmentRelCacheModel.userId = getUserId();

		merisSegmentRelCacheModel.userName = getUserName();

		String userName = merisSegmentRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			merisSegmentRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			merisSegmentRelCacheModel.createDate = createDate.getTime();
		}
		else {
			merisSegmentRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			merisSegmentRelCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			merisSegmentRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		merisSegmentRelCacheModel.merisSegmentId = getMerisSegmentId();

		merisSegmentRelCacheModel.classNameId = getClassNameId();

		merisSegmentRelCacheModel.classPK = getClassPK();

		return merisSegmentRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{merisSegmentRelId=");
		sb.append(getMerisSegmentRelId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", merisSegmentId=");
		sb.append(getMerisSegmentId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.meris.model.MerisSegmentRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>merisSegmentRelId</column-name><column-value><![CDATA[");
		sb.append(getMerisSegmentRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>merisSegmentId</column-name><column-value><![CDATA[");
		sb.append(getMerisSegmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MerisSegmentRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MerisSegmentRel.class, ModelWrapper.class
		};
	private long _merisSegmentRelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _merisSegmentId;
	private long _originalMerisSegmentId;
	private boolean _setOriginalMerisSegmentId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _columnBitmask;
	private MerisSegmentRel _escapedModel;
}