##
## ReleaseInfo.java
##

    release.info.build[dxp]=private static final String _BUILD = "7210";
    release.info.build[master]=private static final String _BUILD = "7\\d{3}";

    release.info.date[dxp]=private static final String _DATE = "June 4, 2019";
    release.info.date[master]=private static final String _DATE = "[\\s\\w,]+";

    release.info.name[dxp]=private static final String _NAME = "Liferay Digital Experience Platform";
    release.info.name[master]=private static final String _NAME = "Liferay Community Edition Portal";

    release.info.version[dxp]=private static final String _VERSION = "7.2.10";
    release.info.version[master]=private static final String _VERSION = "7\\.\\d+\\.\\d+";

    release.info.version.display.name[dxp]=private static final String _VERSION_DISPLAY_NAME = "7.2.10 GA1";
    release.info.version.display.name[master]=private static final String _VERSION_DISPLAY_NAME = "7\\.\\d+\\.\\d+ CE [A-Za-z]+ ?\\d+";

##
## build.properties
##

    snapshot.bundle.base.url[dxp]=https://files.liferay.com/private/ee/portal/
    snapshot.bundle.base.url[master]=https://releases.liferay.com/portal/

##
## release.properties
##

    lp.version[dxp]=7.2.10
    lp.version[master]=7.2.0

##
## sql.properties
##

    database.types[dxp]=db2,hypersonic,mariadb,mysql,oracle,postgresql,sqlserver,sybase
    database.types[master]=hypersonic,mariadb,mysql,postgresql

##
## test.properties
##

    test.run.environment[dxp]=EE
    test.run.environment[master]=CE

    testray.build.type[dxp]=EE Development (${liferay.portal.branch})
    testray.build.type[master]=CE Development (${liferay.portal.branch})