/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.oauth2.provider.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.oauth2.provider.model.OAuth2AccessToken;
import com.liferay.oauth2.provider.model.OAuth2AccessTokenModel;
import com.liferay.oauth2.provider.model.OAuth2AccessTokenSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OAuth2AccessToken service. Represents a row in the &quot;OAuth2AccessToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OAuth2AccessTokenModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OAuth2AccessTokenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OAuth2AccessTokenImpl
 * @see OAuth2AccessToken
 * @see OAuth2AccessTokenModel
 * @generated
 */
@ProviderType
public class OAuth2AccessTokenModelImpl extends BaseModelImpl<OAuth2AccessToken>
	implements OAuth2AccessTokenModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o auth2 access token model instance should use the {@link OAuth2AccessToken} interface instead.
	 */
	public static final String TABLE_NAME = "OAuth2AccessToken";
	public static final Object[][] TABLE_COLUMNS = {
			{ "OAuth2AccessTokenId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "expirationDate", Types.TIMESTAMP },
			{ "remoteIPInfo", Types.VARCHAR },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "oAuth2ApplicationId", Types.BIGINT },
			{ "oAuth2RefreshTokenId", Types.BIGINT },
			{ "OAuth2AccessTokenContent", Types.VARCHAR },
			{ "OAuth2AccessTokenType", Types.VARCHAR },
			{ "scopeAliases", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("OAuth2AccessTokenId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("remoteIPInfo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oAuth2ApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("oAuth2RefreshTokenId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("OAuth2AccessTokenContent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OAuth2AccessTokenType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scopeAliases", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OAuth2AccessToken (OAuth2AccessTokenId LONG not null primary key,companyId LONG,createDate DATE null,expirationDate DATE null,remoteIPInfo VARCHAR(75) null,userId LONG,userName VARCHAR(75) null,oAuth2ApplicationId LONG,oAuth2RefreshTokenId LONG,OAuth2AccessTokenContent VARCHAR(75) null,OAuth2AccessTokenType VARCHAR(75) null,scopeAliases VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OAuth2AccessToken";
	public static final String ORDER_BY_JPQL = " ORDER BY oAuth2AccessToken.OAuth2AccessTokenId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OAuth2AccessToken.OAuth2AccessTokenId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.oauth2.provider.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.oauth2.provider.model.OAuth2AccessToken"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.oauth2.provider.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.oauth2.provider.model.OAuth2AccessToken"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.oauth2.provider.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.oauth2.provider.model.OAuth2AccessToken"),
			true);
	public static final long OAUTH2ACCESSTOKENCONTENT_COLUMN_BITMASK = 1L;
	public static final long OAUTH2APPLICATIONID_COLUMN_BITMASK = 2L;
	public static final long OAUTH2REFRESHTOKENID_COLUMN_BITMASK = 4L;
	public static final long OAUTH2ACCESSTOKENID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OAuth2AccessToken toModel(OAuth2AccessTokenSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OAuth2AccessToken model = new OAuth2AccessTokenImpl();

		model.setOAuth2AccessTokenId(soapModel.getOAuth2AccessTokenId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setRemoteIPInfo(soapModel.getRemoteIPInfo());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setOAuth2ApplicationId(soapModel.getOAuth2ApplicationId());
		model.setOAuth2RefreshTokenId(soapModel.getOAuth2RefreshTokenId());
		model.setOAuth2AccessTokenContent(soapModel.getOAuth2AccessTokenContent());
		model.setOAuth2AccessTokenType(soapModel.getOAuth2AccessTokenType());
		model.setScopeAliases(soapModel.getScopeAliases());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OAuth2AccessToken> toModels(
		OAuth2AccessTokenSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OAuth2AccessToken> models = new ArrayList<OAuth2AccessToken>(soapModels.length);

		for (OAuth2AccessTokenSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.oauth2.provider.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.oauth2.provider.model.OAuth2AccessToken"));

	public OAuth2AccessTokenModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _OAuth2AccessTokenId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOAuth2AccessTokenId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _OAuth2AccessTokenId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OAuth2AccessToken.class;
	}

	@Override
	public String getModelClassName() {
		return OAuth2AccessToken.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("OAuth2AccessTokenId", getOAuth2AccessTokenId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("expirationDate", getExpirationDate());
		attributes.put("remoteIPInfo", getRemoteIPInfo());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("oAuth2ApplicationId", getOAuth2ApplicationId());
		attributes.put("oAuth2RefreshTokenId", getOAuth2RefreshTokenId());
		attributes.put("OAuth2AccessTokenContent", getOAuth2AccessTokenContent());
		attributes.put("OAuth2AccessTokenType", getOAuth2AccessTokenType());
		attributes.put("scopeAliases", getScopeAliases());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long OAuth2AccessTokenId = (Long)attributes.get("OAuth2AccessTokenId");

		if (OAuth2AccessTokenId != null) {
			setOAuth2AccessTokenId(OAuth2AccessTokenId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date expirationDate = (Date)attributes.get("expirationDate");

		if (expirationDate != null) {
			setExpirationDate(expirationDate);
		}

		String remoteIPInfo = (String)attributes.get("remoteIPInfo");

		if (remoteIPInfo != null) {
			setRemoteIPInfo(remoteIPInfo);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Long oAuth2ApplicationId = (Long)attributes.get("oAuth2ApplicationId");

		if (oAuth2ApplicationId != null) {
			setOAuth2ApplicationId(oAuth2ApplicationId);
		}

		Long oAuth2RefreshTokenId = (Long)attributes.get("oAuth2RefreshTokenId");

		if (oAuth2RefreshTokenId != null) {
			setOAuth2RefreshTokenId(oAuth2RefreshTokenId);
		}

		String OAuth2AccessTokenContent = (String)attributes.get(
				"OAuth2AccessTokenContent");

		if (OAuth2AccessTokenContent != null) {
			setOAuth2AccessTokenContent(OAuth2AccessTokenContent);
		}

		String OAuth2AccessTokenType = (String)attributes.get(
				"OAuth2AccessTokenType");

		if (OAuth2AccessTokenType != null) {
			setOAuth2AccessTokenType(OAuth2AccessTokenType);
		}

		String scopeAliases = (String)attributes.get("scopeAliases");

		if (scopeAliases != null) {
			setScopeAliases(scopeAliases);
		}
	}

	@Override
	public long getOAuth2AccessTokenId() {
		return _OAuth2AccessTokenId;
	}

	@Override
	public void setOAuth2AccessTokenId(long OAuth2AccessTokenId) {
		_OAuth2AccessTokenId = OAuth2AccessTokenId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@Override
	public String getRemoteIPInfo() {
		if (_remoteIPInfo == null) {
			return "";
		}
		else {
			return _remoteIPInfo;
		}
	}

	@Override
	public void setRemoteIPInfo(String remoteIPInfo) {
		_remoteIPInfo = remoteIPInfo;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getOAuth2ApplicationId() {
		return _oAuth2ApplicationId;
	}

	@Override
	public void setOAuth2ApplicationId(long oAuth2ApplicationId) {
		_columnBitmask |= OAUTH2APPLICATIONID_COLUMN_BITMASK;

		if (!_setOriginalOAuth2ApplicationId) {
			_setOriginalOAuth2ApplicationId = true;

			_originalOAuth2ApplicationId = _oAuth2ApplicationId;
		}

		_oAuth2ApplicationId = oAuth2ApplicationId;
	}

	public long getOriginalOAuth2ApplicationId() {
		return _originalOAuth2ApplicationId;
	}

	@Override
	public long getOAuth2RefreshTokenId() {
		return _oAuth2RefreshTokenId;
	}

	@Override
	public void setOAuth2RefreshTokenId(long oAuth2RefreshTokenId) {
		_columnBitmask |= OAUTH2REFRESHTOKENID_COLUMN_BITMASK;

		if (!_setOriginalOAuth2RefreshTokenId) {
			_setOriginalOAuth2RefreshTokenId = true;

			_originalOAuth2RefreshTokenId = _oAuth2RefreshTokenId;
		}

		_oAuth2RefreshTokenId = oAuth2RefreshTokenId;
	}

	public long getOriginalOAuth2RefreshTokenId() {
		return _originalOAuth2RefreshTokenId;
	}

	@Override
	public String getOAuth2AccessTokenContent() {
		if (_OAuth2AccessTokenContent == null) {
			return "";
		}
		else {
			return _OAuth2AccessTokenContent;
		}
	}

	@Override
	public void setOAuth2AccessTokenContent(String OAuth2AccessTokenContent) {
		_columnBitmask |= OAUTH2ACCESSTOKENCONTENT_COLUMN_BITMASK;

		if (_originalOAuth2AccessTokenContent == null) {
			_originalOAuth2AccessTokenContent = _OAuth2AccessTokenContent;
		}

		_OAuth2AccessTokenContent = OAuth2AccessTokenContent;
	}

	public String getOriginalOAuth2AccessTokenContent() {
		return GetterUtil.getString(_originalOAuth2AccessTokenContent);
	}

	@Override
	public String getOAuth2AccessTokenType() {
		if (_OAuth2AccessTokenType == null) {
			return "";
		}
		else {
			return _OAuth2AccessTokenType;
		}
	}

	@Override
	public void setOAuth2AccessTokenType(String OAuth2AccessTokenType) {
		_OAuth2AccessTokenType = OAuth2AccessTokenType;
	}

	@Override
	public String getScopeAliases() {
		if (_scopeAliases == null) {
			return "";
		}
		else {
			return _scopeAliases;
		}
	}

	@Override
	public void setScopeAliases(String scopeAliases) {
		_scopeAliases = scopeAliases;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			OAuth2AccessToken.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OAuth2AccessToken toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OAuth2AccessToken)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OAuth2AccessTokenImpl oAuth2AccessTokenImpl = new OAuth2AccessTokenImpl();

		oAuth2AccessTokenImpl.setOAuth2AccessTokenId(getOAuth2AccessTokenId());
		oAuth2AccessTokenImpl.setCompanyId(getCompanyId());
		oAuth2AccessTokenImpl.setCreateDate(getCreateDate());
		oAuth2AccessTokenImpl.setExpirationDate(getExpirationDate());
		oAuth2AccessTokenImpl.setRemoteIPInfo(getRemoteIPInfo());
		oAuth2AccessTokenImpl.setUserId(getUserId());
		oAuth2AccessTokenImpl.setUserName(getUserName());
		oAuth2AccessTokenImpl.setOAuth2ApplicationId(getOAuth2ApplicationId());
		oAuth2AccessTokenImpl.setOAuth2RefreshTokenId(getOAuth2RefreshTokenId());
		oAuth2AccessTokenImpl.setOAuth2AccessTokenContent(getOAuth2AccessTokenContent());
		oAuth2AccessTokenImpl.setOAuth2AccessTokenType(getOAuth2AccessTokenType());
		oAuth2AccessTokenImpl.setScopeAliases(getScopeAliases());

		oAuth2AccessTokenImpl.resetOriginalValues();

		return oAuth2AccessTokenImpl;
	}

	@Override
	public int compareTo(OAuth2AccessToken oAuth2AccessToken) {
		long primaryKey = oAuth2AccessToken.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OAuth2AccessToken)) {
			return false;
		}

		OAuth2AccessToken oAuth2AccessToken = (OAuth2AccessToken)obj;

		long primaryKey = oAuth2AccessToken.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		OAuth2AccessTokenModelImpl oAuth2AccessTokenModelImpl = this;

		oAuth2AccessTokenModelImpl._originalOAuth2ApplicationId = oAuth2AccessTokenModelImpl._oAuth2ApplicationId;

		oAuth2AccessTokenModelImpl._setOriginalOAuth2ApplicationId = false;

		oAuth2AccessTokenModelImpl._originalOAuth2RefreshTokenId = oAuth2AccessTokenModelImpl._oAuth2RefreshTokenId;

		oAuth2AccessTokenModelImpl._setOriginalOAuth2RefreshTokenId = false;

		oAuth2AccessTokenModelImpl._originalOAuth2AccessTokenContent = oAuth2AccessTokenModelImpl._OAuth2AccessTokenContent;

		oAuth2AccessTokenModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OAuth2AccessToken> toCacheModel() {
		OAuth2AccessTokenCacheModel oAuth2AccessTokenCacheModel = new OAuth2AccessTokenCacheModel();

		oAuth2AccessTokenCacheModel.OAuth2AccessTokenId = getOAuth2AccessTokenId();

		oAuth2AccessTokenCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			oAuth2AccessTokenCacheModel.createDate = createDate.getTime();
		}
		else {
			oAuth2AccessTokenCacheModel.createDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			oAuth2AccessTokenCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			oAuth2AccessTokenCacheModel.expirationDate = Long.MIN_VALUE;
		}

		oAuth2AccessTokenCacheModel.remoteIPInfo = getRemoteIPInfo();

		String remoteIPInfo = oAuth2AccessTokenCacheModel.remoteIPInfo;

		if ((remoteIPInfo != null) && (remoteIPInfo.length() == 0)) {
			oAuth2AccessTokenCacheModel.remoteIPInfo = null;
		}

		oAuth2AccessTokenCacheModel.userId = getUserId();

		oAuth2AccessTokenCacheModel.userName = getUserName();

		String userName = oAuth2AccessTokenCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			oAuth2AccessTokenCacheModel.userName = null;
		}

		oAuth2AccessTokenCacheModel.oAuth2ApplicationId = getOAuth2ApplicationId();

		oAuth2AccessTokenCacheModel.oAuth2RefreshTokenId = getOAuth2RefreshTokenId();

		oAuth2AccessTokenCacheModel.OAuth2AccessTokenContent = getOAuth2AccessTokenContent();

		String OAuth2AccessTokenContent = oAuth2AccessTokenCacheModel.OAuth2AccessTokenContent;

		if ((OAuth2AccessTokenContent != null) &&
				(OAuth2AccessTokenContent.length() == 0)) {
			oAuth2AccessTokenCacheModel.OAuth2AccessTokenContent = null;
		}

		oAuth2AccessTokenCacheModel.OAuth2AccessTokenType = getOAuth2AccessTokenType();

		String OAuth2AccessTokenType = oAuth2AccessTokenCacheModel.OAuth2AccessTokenType;

		if ((OAuth2AccessTokenType != null) &&
				(OAuth2AccessTokenType.length() == 0)) {
			oAuth2AccessTokenCacheModel.OAuth2AccessTokenType = null;
		}

		oAuth2AccessTokenCacheModel.scopeAliases = getScopeAliases();

		String scopeAliases = oAuth2AccessTokenCacheModel.scopeAliases;

		if ((scopeAliases != null) && (scopeAliases.length() == 0)) {
			oAuth2AccessTokenCacheModel.scopeAliases = null;
		}

		return oAuth2AccessTokenCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{OAuth2AccessTokenId=");
		sb.append(getOAuth2AccessTokenId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", expirationDate=");
		sb.append(getExpirationDate());
		sb.append(", remoteIPInfo=");
		sb.append(getRemoteIPInfo());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", oAuth2ApplicationId=");
		sb.append(getOAuth2ApplicationId());
		sb.append(", oAuth2RefreshTokenId=");
		sb.append(getOAuth2RefreshTokenId());
		sb.append(", OAuth2AccessTokenContent=");
		sb.append(getOAuth2AccessTokenContent());
		sb.append(", OAuth2AccessTokenType=");
		sb.append(getOAuth2AccessTokenType());
		sb.append(", scopeAliases=");
		sb.append(getScopeAliases());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.oauth2.provider.model.OAuth2AccessToken");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>OAuth2AccessTokenId</column-name><column-value><![CDATA[");
		sb.append(getOAuth2AccessTokenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expirationDate</column-name><column-value><![CDATA[");
		sb.append(getExpirationDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteIPInfo</column-name><column-value><![CDATA[");
		sb.append(getRemoteIPInfo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oAuth2ApplicationId</column-name><column-value><![CDATA[");
		sb.append(getOAuth2ApplicationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oAuth2RefreshTokenId</column-name><column-value><![CDATA[");
		sb.append(getOAuth2RefreshTokenId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OAuth2AccessTokenContent</column-name><column-value><![CDATA[");
		sb.append(getOAuth2AccessTokenContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>OAuth2AccessTokenType</column-name><column-value><![CDATA[");
		sb.append(getOAuth2AccessTokenType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scopeAliases</column-name><column-value><![CDATA[");
		sb.append(getScopeAliases());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OAuth2AccessToken.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OAuth2AccessToken.class
		};
	private long _OAuth2AccessTokenId;
	private long _companyId;
	private Date _createDate;
	private Date _expirationDate;
	private String _remoteIPInfo;
	private long _userId;
	private String _userName;
	private long _oAuth2ApplicationId;
	private long _originalOAuth2ApplicationId;
	private boolean _setOriginalOAuth2ApplicationId;
	private long _oAuth2RefreshTokenId;
	private long _originalOAuth2RefreshTokenId;
	private boolean _setOriginalOAuth2RefreshTokenId;
	private String _OAuth2AccessTokenContent;
	private String _originalOAuth2AccessTokenContent;
	private String _OAuth2AccessTokenType;
	private String _scopeAliases;
	private long _columnBitmask;
	private OAuth2AccessToken _escapedModel;
}