<action-definition>
	<action-command name="Click">
		<case key-equals="ADD_ENTRY">
			<execute function="Click#valueClickAtAndWait" value="Add Blogs Entry" />
		</case>
		<case key-equals="DELETE_ENTRY" key-contains="EDIT_ENTRY">
			<execute function="Click#valueClickAtAndWait" value="Delete" />
		</case>
	</action-command>
</action-definition>