##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    legacy.language.keys=\
        use-my-account-to-change-regular-account-settings,\
        you-have-to-be-signed-in-to-register-for-this-meetup