apiVersion: v1
kind: ConfigMap
metadata:
    annotations:
        workflows.argoproj.io/default-artifact-repository: artifact-repository
    name: {{ include "liferayAwsBackupRestore.configmap.artifactRepository.name" . }}
    namespace: {{ .Values.argoNamespace }}
data:
    artifact-repository: |-
        s3:
          endpoint: s3.amazonaws.com
          bucket: {{ .Values.artifactRepositoryBucketId }}