apiVersion: v2
appVersion: latest
description:
    This chart contains a cluster workflow template which enables a Liferay AWS backup restore.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-aws-backup-restore-workflow-template
type: application
version: 0.1.0