argoNamespace: argo
artifactRepositoryBucketId: ""
awsBackupServiceAssumedIamRoleArn: ""
awsBackupVaultName: "liferay-backup"
awsCliImage:
    repository: amazon/aws-cli
    tag: "2.27.63"
createClusterResources: true
enabled: true
fullnameOverride: ""
git:
    credentials:
        token: ""
        username: ""
    user:
        email: ""
        name: ""
kubectlImage:
    repository: registry.k8s.io/kubectl
    tag: v1.34.0
liferayWorkload:
    managedSecretName: managed-service-details
    name: liferay-default
nameOverride: ""
s3RestoreWaitTimeoutSeconds: 7200
serviceAccount:
    annotations: {}
terraformImage:
    repository: hashicorp/terraform
    tag: "1.12.2"
terraformRepo:
    branch: master
    dependenciesModuleRelativePath: dependencies
    httpsUrl: https://github.com/liferay/liferay-portal.git
    sparseCheckoutRelativePath: cloud/terraform/aws