/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.frontend.view.state.model.FrontendViewStateActiveEntry;
import com.liferay.frontend.view.state.model.FrontendViewStateActiveEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FrontendViewStateActiveEntry service. Represents a row in the &quot;FrontendViewStateActiveEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FrontendViewStateActiveEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FrontendViewStateActiveEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FrontendViewStateActiveEntryImpl
 * @generated
 */
public class FrontendViewStateActiveEntryModelImpl
	extends BaseModelImpl<FrontendViewStateActiveEntry>
	implements FrontendViewStateActiveEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a frontend view state active entry model instance should use the <code>FrontendViewStateActiveEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "FrontendViewStateActiveEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"frontendViewStateActiveEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"datasetDisplayId", Types.VARCHAR},
		{"frontendViewStateEntryId", Types.BIGINT}, {"plid", Types.BIGINT},
		{"portletId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("frontendViewStateActiveEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("datasetDisplayId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("frontendViewStateEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("portletId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FrontendViewStateActiveEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,frontendViewStateActiveEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,datasetDisplayId VARCHAR(75) null,frontendViewStateEntryId LONG,plid LONG,portletId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FrontendViewStateActiveEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY frontendViewStateActiveEntry.frontendViewStateActiveEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FrontendViewStateActiveEntry.frontendViewStateActiveEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATASETDISPLAYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PORTLETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRONTENDVIEWSTATEACTIVEENTRYID_COLUMN_BITMASK =
		64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FrontendViewStateActiveEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _frontendViewStateActiveEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFrontendViewStateActiveEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _frontendViewStateActiveEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FrontendViewStateActiveEntry.class;
	}

	@Override
	public String getModelClassName() {
		return FrontendViewStateActiveEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FrontendViewStateActiveEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FrontendViewStateActiveEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FrontendViewStateActiveEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(FrontendViewStateActiveEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FrontendViewStateActiveEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FrontendViewStateActiveEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FrontendViewStateActiveEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FrontendViewStateActiveEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FrontendViewStateActiveEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FrontendViewStateActiveEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FrontendViewStateActiveEntry.class.getClassLoader(),
			FrontendViewStateActiveEntry.class, ModelWrapper.class);

		try {
			Constructor<FrontendViewStateActiveEntry> constructor =
				(Constructor<FrontendViewStateActiveEntry>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<FrontendViewStateActiveEntry, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<FrontendViewStateActiveEntry, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<FrontendViewStateActiveEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FrontendViewStateActiveEntry, Object>>();
		Map<String, BiConsumer<FrontendViewStateActiveEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FrontendViewStateActiveEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FrontendViewStateActiveEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::setMvccVersion);
		attributeGetterFunctions.put(
			"uuid", FrontendViewStateActiveEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FrontendViewStateActiveEntry, String>)
				FrontendViewStateActiveEntry::setUuid);
		attributeGetterFunctions.put(
			"frontendViewStateActiveEntryId",
			FrontendViewStateActiveEntry::getFrontendViewStateActiveEntryId);
		attributeSetterBiConsumers.put(
			"frontendViewStateActiveEntryId",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::
					setFrontendViewStateActiveEntryId);
		attributeGetterFunctions.put(
			"companyId", FrontendViewStateActiveEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", FrontendViewStateActiveEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", FrontendViewStateActiveEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FrontendViewStateActiveEntry, String>)
				FrontendViewStateActiveEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", FrontendViewStateActiveEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FrontendViewStateActiveEntry, Date>)
				FrontendViewStateActiveEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FrontendViewStateActiveEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FrontendViewStateActiveEntry, Date>)
				FrontendViewStateActiveEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"datasetDisplayId",
			FrontendViewStateActiveEntry::getDatasetDisplayId);
		attributeSetterBiConsumers.put(
			"datasetDisplayId",
			(BiConsumer<FrontendViewStateActiveEntry, String>)
				FrontendViewStateActiveEntry::setDatasetDisplayId);
		attributeGetterFunctions.put(
			"frontendViewStateEntryId",
			FrontendViewStateActiveEntry::getFrontendViewStateEntryId);
		attributeSetterBiConsumers.put(
			"frontendViewStateEntryId",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::setFrontendViewStateEntryId);
		attributeGetterFunctions.put(
			"plid", FrontendViewStateActiveEntry::getPlid);
		attributeSetterBiConsumers.put(
			"plid",
			(BiConsumer<FrontendViewStateActiveEntry, Long>)
				FrontendViewStateActiveEntry::setPlid);
		attributeGetterFunctions.put(
			"portletId", FrontendViewStateActiveEntry::getPortletId);
		attributeSetterBiConsumers.put(
			"portletId",
			(BiConsumer<FrontendViewStateActiveEntry, String>)
				FrontendViewStateActiveEntry::setPortletId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getFrontendViewStateActiveEntryId() {
		return _frontendViewStateActiveEntryId;
	}

	@Override
	public void setFrontendViewStateActiveEntryId(
		long frontendViewStateActiveEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_frontendViewStateActiveEntryId = frontendViewStateActiveEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDatasetDisplayId() {
		if (_datasetDisplayId == null) {
			return "";
		}
		else {
			return _datasetDisplayId;
		}
	}

	@Override
	public void setDatasetDisplayId(String datasetDisplayId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_datasetDisplayId = datasetDisplayId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDatasetDisplayId() {
		return getColumnOriginalValue("datasetDisplayId");
	}

	@Override
	public long getFrontendViewStateEntryId() {
		return _frontendViewStateEntryId;
	}

	@Override
	public void setFrontendViewStateEntryId(long frontendViewStateEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_frontendViewStateEntryId = frontendViewStateEntryId;
	}

	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plid = plid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlid() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("plid"));
	}

	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return "";
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_portletId = portletId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPortletId() {
		return getColumnOriginalValue("portletId");
	}

	@Override
	public long getContainerModelId() {
		return getFrontendViewStateActiveEntryId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_frontendViewStateActiveEntryId = containerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getContainerModelId());
	}

	@Override
	public long getParentContainerModelId() {
		return 0;
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				FrontendViewStateActiveEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FrontendViewStateActiveEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FrontendViewStateActiveEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FrontendViewStateActiveEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FrontendViewStateActiveEntryImpl frontendViewStateActiveEntryImpl =
			new FrontendViewStateActiveEntryImpl();

		frontendViewStateActiveEntryImpl.setMvccVersion(getMvccVersion());
		frontendViewStateActiveEntryImpl.setUuid(getUuid());
		frontendViewStateActiveEntryImpl.setFrontendViewStateActiveEntryId(
			getFrontendViewStateActiveEntryId());
		frontendViewStateActiveEntryImpl.setCompanyId(getCompanyId());
		frontendViewStateActiveEntryImpl.setUserId(getUserId());
		frontendViewStateActiveEntryImpl.setUserName(getUserName());
		frontendViewStateActiveEntryImpl.setCreateDate(getCreateDate());
		frontendViewStateActiveEntryImpl.setModifiedDate(getModifiedDate());
		frontendViewStateActiveEntryImpl.setDatasetDisplayId(
			getDatasetDisplayId());
		frontendViewStateActiveEntryImpl.setFrontendViewStateEntryId(
			getFrontendViewStateEntryId());
		frontendViewStateActiveEntryImpl.setPlid(getPlid());
		frontendViewStateActiveEntryImpl.setPortletId(getPortletId());

		frontendViewStateActiveEntryImpl.resetOriginalValues();

		return frontendViewStateActiveEntryImpl;
	}

	@Override
	public int compareTo(
		FrontendViewStateActiveEntry frontendViewStateActiveEntry) {

		long primaryKey = frontendViewStateActiveEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FrontendViewStateActiveEntry)) {
			return false;
		}

		FrontendViewStateActiveEntry frontendViewStateActiveEntry =
			(FrontendViewStateActiveEntry)object;

		long primaryKey = frontendViewStateActiveEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FrontendViewStateActiveEntry> toCacheModel() {
		FrontendViewStateActiveEntryCacheModel
			frontendViewStateActiveEntryCacheModel =
				new FrontendViewStateActiveEntryCacheModel();

		frontendViewStateActiveEntryCacheModel.mvccVersion = getMvccVersion();

		frontendViewStateActiveEntryCacheModel.uuid = getUuid();

		String uuid = frontendViewStateActiveEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			frontendViewStateActiveEntryCacheModel.uuid = null;
		}

		frontendViewStateActiveEntryCacheModel.frontendViewStateActiveEntryId =
			getFrontendViewStateActiveEntryId();

		frontendViewStateActiveEntryCacheModel.companyId = getCompanyId();

		frontendViewStateActiveEntryCacheModel.userId = getUserId();

		frontendViewStateActiveEntryCacheModel.userName = getUserName();

		String userName = frontendViewStateActiveEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			frontendViewStateActiveEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			frontendViewStateActiveEntryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			frontendViewStateActiveEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			frontendViewStateActiveEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			frontendViewStateActiveEntryCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		frontendViewStateActiveEntryCacheModel.datasetDisplayId =
			getDatasetDisplayId();

		String datasetDisplayId =
			frontendViewStateActiveEntryCacheModel.datasetDisplayId;

		if ((datasetDisplayId != null) && (datasetDisplayId.length() == 0)) {
			frontendViewStateActiveEntryCacheModel.datasetDisplayId = null;
		}

		frontendViewStateActiveEntryCacheModel.frontendViewStateEntryId =
			getFrontendViewStateEntryId();

		frontendViewStateActiveEntryCacheModel.plid = getPlid();

		frontendViewStateActiveEntryCacheModel.portletId = getPortletId();

		String portletId = frontendViewStateActiveEntryCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			frontendViewStateActiveEntryCacheModel.portletId = null;
		}

		return frontendViewStateActiveEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FrontendViewStateActiveEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FrontendViewStateActiveEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FrontendViewStateActiveEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(FrontendViewStateActiveEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FrontendViewStateActiveEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FrontendViewStateActiveEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FrontendViewStateActiveEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(FrontendViewStateActiveEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FrontendViewStateActiveEntry>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private long _frontendViewStateActiveEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _datasetDisplayId;
	private long _frontendViewStateEntryId;
	private long _plid;
	private String _portletId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FrontendViewStateActiveEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FrontendViewStateActiveEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"frontendViewStateActiveEntryId", _frontendViewStateActiveEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("datasetDisplayId", _datasetDisplayId);
		_columnOriginalValues.put(
			"frontendViewStateEntryId", _frontendViewStateEntryId);
		_columnOriginalValues.put("plid", _plid);
		_columnOriginalValues.put("portletId", _portletId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("frontendViewStateActiveEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("datasetDisplayId", 256L);

		columnBitmasks.put("frontendViewStateEntryId", 512L);

		columnBitmasks.put("plid", 1024L);

		columnBitmasks.put("portletId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FrontendViewStateActiveEntry _escapedModel;

}