/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.page.template.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersion;
import com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersionModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LayoutPageTemplateEntryVersion service. Represents a row in the &quot;LayoutPageTemplateEntryVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LayoutPageTemplateEntryVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutPageTemplateEntryVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateEntryVersionImpl
 * @generated
 */
@ProviderType
public class LayoutPageTemplateEntryVersionModelImpl
	extends BaseModelImpl<LayoutPageTemplateEntryVersion>
	implements LayoutPageTemplateEntryVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout page template entry version model instance should use the <code>LayoutPageTemplateEntryVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutPageTemplateEntryVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"lPTEVersionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"layoutPageTemplateEntryId", Types.BIGINT}, {"plid", Types.BIGINT},
		{"version", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lPTEVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("layoutPageTemplateEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutPageTemplateEntryVersion (lPTEVersionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,layoutPageTemplateEntryId LONG,plid LONG,version DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table LayoutPageTemplateEntryVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutPageTemplateEntryVersion.layoutPageTemplateEntryVersionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutPageTemplateEntryVersion.lPTEVersionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersion"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersion"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersion"),
		true);

	public static final long LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK = 1L;

	public static final long LAYOUTPAGETEMPLATEENTRYVERSIONID_COLUMN_BITMASK =
		2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.layout.page.template.model.LayoutPageTemplateEntryVersion"));

	public LayoutPageTemplateEntryVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutPageTemplateEntryVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutPageTemplateEntryVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutPageTemplateEntryVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutPageTemplateEntryVersion.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutPageTemplateEntryVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutPageTemplateEntryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutPageTemplateEntryVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateEntryVersion, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(LayoutPageTemplateEntryVersion)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutPageTemplateEntryVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutPageTemplateEntryVersion, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutPageTemplateEntryVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutPageTemplateEntryVersion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutPageTemplateEntryVersion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<LayoutPageTemplateEntryVersion, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<LayoutPageTemplateEntryVersion, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<LayoutPageTemplateEntryVersion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<LayoutPageTemplateEntryVersion, Object>>();
		Map<String, BiConsumer<LayoutPageTemplateEntryVersion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LayoutPageTemplateEntryVersion, ?>>();

		attributeGetterFunctions.put(
			"layoutPageTemplateEntryVersionId",
			LayoutPageTemplateEntryVersion::
				getLayoutPageTemplateEntryVersionId);
		attributeSetterBiConsumers.put(
			"layoutPageTemplateEntryVersionId",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::
					setLayoutPageTemplateEntryVersionId);
		attributeGetterFunctions.put(
			"groupId", LayoutPageTemplateEntryVersion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LayoutPageTemplateEntryVersion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::setCompanyId);
		attributeGetterFunctions.put(
			"userId", LayoutPageTemplateEntryVersion::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::setUserId);
		attributeGetterFunctions.put(
			"userName", LayoutPageTemplateEntryVersion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LayoutPageTemplateEntryVersion, String>)
				LayoutPageTemplateEntryVersion::setUserName);
		attributeGetterFunctions.put(
			"createDate", LayoutPageTemplateEntryVersion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LayoutPageTemplateEntryVersion, Date>)
				LayoutPageTemplateEntryVersion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LayoutPageTemplateEntryVersion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LayoutPageTemplateEntryVersion, Date>)
				LayoutPageTemplateEntryVersion::setModifiedDate);
		attributeGetterFunctions.put(
			"layoutPageTemplateEntryId",
			LayoutPageTemplateEntryVersion::getLayoutPageTemplateEntryId);
		attributeSetterBiConsumers.put(
			"layoutPageTemplateEntryId",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::setLayoutPageTemplateEntryId);
		attributeGetterFunctions.put(
			"plid", LayoutPageTemplateEntryVersion::getPlid);
		attributeSetterBiConsumers.put(
			"plid",
			(BiConsumer<LayoutPageTemplateEntryVersion, Long>)
				LayoutPageTemplateEntryVersion::setPlid);
		attributeGetterFunctions.put(
			"version", LayoutPageTemplateEntryVersion::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<LayoutPageTemplateEntryVersion, Double>)
				LayoutPageTemplateEntryVersion::setVersion);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLayoutPageTemplateEntryVersionId() {
		return _layoutPageTemplateEntryVersionId;
	}

	@Override
	public void setLayoutPageTemplateEntryVersionId(
		long layoutPageTemplateEntryVersionId) {

		_layoutPageTemplateEntryVersionId = layoutPageTemplateEntryVersionId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getLayoutPageTemplateEntryId() {
		return _layoutPageTemplateEntryId;
	}

	@Override
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId) {
		_columnBitmask |= LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalLayoutPageTemplateEntryId) {
			_setOriginalLayoutPageTemplateEntryId = true;

			_originalLayoutPageTemplateEntryId = _layoutPageTemplateEntryId;
		}

		_layoutPageTemplateEntryId = layoutPageTemplateEntryId;
	}

	public long getOriginalLayoutPageTemplateEntryId() {
		return _originalLayoutPageTemplateEntryId;
	}

	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_plid = plid;
	}

	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		_version = version;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LayoutPageTemplateEntryVersion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LayoutPageTemplateEntryVersion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel =
				(LayoutPageTemplateEntryVersion)ProxyUtil.newProxyInstance(
					_classLoader, _escapedModelInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutPageTemplateEntryVersionImpl layoutPageTemplateEntryVersionImpl =
			new LayoutPageTemplateEntryVersionImpl();

		layoutPageTemplateEntryVersionImpl.setLayoutPageTemplateEntryVersionId(
			getLayoutPageTemplateEntryVersionId());
		layoutPageTemplateEntryVersionImpl.setGroupId(getGroupId());
		layoutPageTemplateEntryVersionImpl.setCompanyId(getCompanyId());
		layoutPageTemplateEntryVersionImpl.setUserId(getUserId());
		layoutPageTemplateEntryVersionImpl.setUserName(getUserName());
		layoutPageTemplateEntryVersionImpl.setCreateDate(getCreateDate());
		layoutPageTemplateEntryVersionImpl.setModifiedDate(getModifiedDate());
		layoutPageTemplateEntryVersionImpl.setLayoutPageTemplateEntryId(
			getLayoutPageTemplateEntryId());
		layoutPageTemplateEntryVersionImpl.setPlid(getPlid());
		layoutPageTemplateEntryVersionImpl.setVersion(getVersion());

		layoutPageTemplateEntryVersionImpl.resetOriginalValues();

		return layoutPageTemplateEntryVersionImpl;
	}

	@Override
	public int compareTo(
		LayoutPageTemplateEntryVersion layoutPageTemplateEntryVersion) {

		long primaryKey = layoutPageTemplateEntryVersion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutPageTemplateEntryVersion)) {
			return false;
		}

		LayoutPageTemplateEntryVersion layoutPageTemplateEntryVersion =
			(LayoutPageTemplateEntryVersion)obj;

		long primaryKey = layoutPageTemplateEntryVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LayoutPageTemplateEntryVersionModelImpl
			layoutPageTemplateEntryVersionModelImpl = this;

		layoutPageTemplateEntryVersionModelImpl._setModifiedDate = false;

		layoutPageTemplateEntryVersionModelImpl.
			_originalLayoutPageTemplateEntryId =
				layoutPageTemplateEntryVersionModelImpl.
					_layoutPageTemplateEntryId;

		layoutPageTemplateEntryVersionModelImpl.
			_setOriginalLayoutPageTemplateEntryId = false;

		layoutPageTemplateEntryVersionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutPageTemplateEntryVersion> toCacheModel() {
		LayoutPageTemplateEntryVersionCacheModel
			layoutPageTemplateEntryVersionCacheModel =
				new LayoutPageTemplateEntryVersionCacheModel();

		layoutPageTemplateEntryVersionCacheModel.
			layoutPageTemplateEntryVersionId =
				getLayoutPageTemplateEntryVersionId();

		layoutPageTemplateEntryVersionCacheModel.groupId = getGroupId();

		layoutPageTemplateEntryVersionCacheModel.companyId = getCompanyId();

		layoutPageTemplateEntryVersionCacheModel.userId = getUserId();

		layoutPageTemplateEntryVersionCacheModel.userName = getUserName();

		String userName = layoutPageTemplateEntryVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutPageTemplateEntryVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutPageTemplateEntryVersionCacheModel.createDate =
				createDate.getTime();
		}
		else {
			layoutPageTemplateEntryVersionCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutPageTemplateEntryVersionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			layoutPageTemplateEntryVersionCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		layoutPageTemplateEntryVersionCacheModel.layoutPageTemplateEntryId =
			getLayoutPageTemplateEntryId();

		layoutPageTemplateEntryVersionCacheModel.plid = getPlid();

		layoutPageTemplateEntryVersionCacheModel.version = getVersion();

		return layoutPageTemplateEntryVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutPageTemplateEntryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutPageTemplateEntryVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateEntryVersion, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(LayoutPageTemplateEntryVersion)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LayoutPageTemplateEntryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LayoutPageTemplateEntryVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateEntryVersion, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(LayoutPageTemplateEntryVersion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		LayoutPageTemplateEntryVersion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		LayoutPageTemplateEntryVersion.class, ModelWrapper.class
	};

	private long _layoutPageTemplateEntryVersionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _layoutPageTemplateEntryId;
	private long _originalLayoutPageTemplateEntryId;
	private boolean _setOriginalLayoutPageTemplateEntryId;
	private long _plid;
	private double _version;
	private long _columnBitmask;
	private LayoutPageTemplateEntryVersion _escapedModel;

}