{
 "title": "Backups",
 "tags": [
  "Liferay",
  "Backups"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_namespace_labels{label_liferay_com_observable=\"true\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 }, "options": { "content": "${HEADER_HTML}" } },
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by (name) (avg_over_time({\"__name__\"=\"kube_customresource_liferay_backup_start_time_seconds\", \"exported_namespace\"=\"$environment\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (name) (avg_over_time({\"__name__\"=\"kube_customresource_liferay_backup_completion_time_seconds\", \"exported_namespace\"=\"$environment\"}[$__range])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  avg by (name, reason) (\n    avg_over_time(kube_customresource_liferay_backup_status_condition{reason!=\"initiated\", exported_namespace=\"$environment\"}[$__range])\n  )\n)\nOR\n(\n  (\n    avg by (name, reason) (\n      avg_over_time(kube_customresource_liferay_backup_status_condition{reason=\"initiated\", exported_namespace=\"$environment\"}[$__range])\n    )\n    unless on(name)\n    avg by (name) (\n      avg_over_time(kube_customresource_liferay_backup_status_condition{reason!=\"initiated\", exported_namespace=\"$environment\"}[$__range])\n    )\n  ) + 0.5\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESS RUNS #",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  max by (name) (\r\n    max_over_time(\r\n      kube_customresource_liferay_backup_status_condition{reason=\"succeeded\", exported_namespace=\"$environment\"}[$__range]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED RUNS #",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  max by (name) (\r\n    max_over_time(\r\n      kube_customresource_liferay_backup_status_condition{reason!~\"succeeded|initiated\", exported_namespace=\"$environment\"}[$__range]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL RUNS #",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  max by (name) (\r\n    max_over_time(\r\n      kube_customresource_liferay_backup_status_condition{reason!=\"initiated\", exported_namespace=\"$environment\"}[$__range]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  max by (name) (\r\n    max_over_time(\r\n      kube_customresource_liferay_backup_status_condition{reason!~\"succeeded|initiated\", exported_namespace=\"$environment\"}[$__range]\r\n    )\r\n  )\r\n)\r\n/\r\ncount(\r\n  max by (name) (\r\n    max_over_time(\r\n      kube_customresource_liferay_backup_status_condition{reason!=\"initiated\", exported_namespace=\"$environment\"}[$__range]\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}