{
 "title": "Databases",
 "tags": [
  "Liferay",
  "Databases"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_namespace_labels{label_liferay_com_observable=\"true\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 }, "options": { "content": "${HEADER_HTML}" } },
  {
   "title": "Database Status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by (database_id, data_plane, state) (\n  last_over_time(\n    liferay:db_instance_state{environment_id=\"$environment\"}[${__interval}]\n  ) > 0\n)",
     "legendFormat": "{{db_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    liferay:db_disk_total_bytes{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "Capacity"
    },
    {
     "expr": "avg by (database_id, data_plane) (\n  avg_over_time(\n    liferay:db_disk_used_bytes{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    liferay:db_memory_total_bytes{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "Capacity"
    },
    {
     "expr": "avg by (database_id, data_plane) (\n  avg_over_time(\n    liferay:db_memory_used_bytes{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    liferay:db_cpu_reserved_cores{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "Capacity"
    },
    {
     "expr": "avg by (database_id, data_plane) (\n  avg_over_time(\n    liferay:db_cpu_used_cores{environment_id=\"$environment\"}[${__interval}]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}