##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/apps/twitter/twitter-service/src/main/java/com/liferay/twitter/internal/upgrade/TwitterUpgradeServiceModuleRelease.java