/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.changeset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Changeset service. Represents a row in the &quot;Changeset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.changeset.model.impl.ChangesetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.changeset.model.impl.ChangesetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Changeset
 * @see com.liferay.changeset.model.impl.ChangesetImpl
 * @see com.liferay.changeset.model.impl.ChangesetModelImpl
 * @generated
 */
@ProviderType
public interface ChangesetModel extends BaseModel<Changeset>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a changeset model instance should use the {@link Changeset} interface instead.
	 */

	/**
	 * Returns the primary key of this changeset.
	 *
	 * @return the primary key of this changeset
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this changeset.
	 *
	 * @param primaryKey the primary key of this changeset
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the changeset ID of this changeset.
	 *
	 * @return the changeset ID of this changeset
	 */
	public long getChangesetId();

	/**
	 * Sets the changeset ID of this changeset.
	 *
	 * @param changesetId the changeset ID of this changeset
	 */
	public void setChangesetId(long changesetId);

	/**
	 * Returns the group ID of this changeset.
	 *
	 * @return the group ID of this changeset
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this changeset.
	 *
	 * @param groupId the group ID of this changeset
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this changeset.
	 *
	 * @return the company ID of this changeset
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this changeset.
	 *
	 * @param companyId the company ID of this changeset
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this changeset.
	 *
	 * @return the user ID of this changeset
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this changeset.
	 *
	 * @param userId the user ID of this changeset
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this changeset.
	 *
	 * @return the user uuid of this changeset
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this changeset.
	 *
	 * @param userUuid the user uuid of this changeset
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this changeset.
	 *
	 * @return the user name of this changeset
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this changeset.
	 *
	 * @param userName the user name of this changeset
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this changeset.
	 *
	 * @return the create date of this changeset
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this changeset.
	 *
	 * @param createDate the create date of this changeset
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this changeset.
	 *
	 * @return the modified date of this changeset
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this changeset.
	 *
	 * @param modifiedDate the modified date of this changeset
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this changeset.
	 *
	 * @return the name of this changeset
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this changeset.
	 *
	 * @param name the name of this changeset
	 */
	public void setName(String name);

	/**
	 * Returns the description of this changeset.
	 *
	 * @return the description of this changeset
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this changeset.
	 *
	 * @param description the description of this changeset
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Changeset changeset);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Changeset> toCacheModel();

	@Override
	public Changeset toEscapedModel();

	@Override
	public Changeset toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}