/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.site.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.site.model.XMLSitemapRegenerationEntry;
import com.liferay.site.model.XMLSitemapRegenerationEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the XMLSitemapRegenerationEntry service. Represents a row in the &quot;XMLSitemapRegenerationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>XMLSitemapRegenerationEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link XMLSitemapRegenerationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see XMLSitemapRegenerationEntryImpl
 * @generated
 */
public class XMLSitemapRegenerationEntryModelImpl
	extends BaseModelImpl<XMLSitemapRegenerationEntry>
	implements XMLSitemapRegenerationEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a xml sitemap regeneration entry model instance should use the <code>XMLSitemapRegenerationEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "XMLSitemapRegenerationEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"xmlSitemapRegenerationEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"assetTypeKey", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("xmlSitemapRegenerationEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetTypeKey", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table XMLSitemapRegenerationEntry (mvccVersion LONG default 0 not null,xmlSitemapRegenerationEntryId LONG not null primary key,groupId LONG,companyId LONG,assetTypeKey VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table XMLSitemapRegenerationEntry";

	public static final String ENTITY_ALIAS = "xmlSitemapRegenerationEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY xmlSitemapRegenerationEntry.xmlSitemapRegenerationEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY XMLSitemapRegenerationEntry.xmlSitemapRegenerationEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETTYPEKEY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long XMLSITEMAPREGENERATIONENTRYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public XMLSitemapRegenerationEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _xmlSitemapRegenerationEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setXmlSitemapRegenerationEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _xmlSitemapRegenerationEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return XMLSitemapRegenerationEntry.class;
	}

	@Override
	public String getModelClassName() {
		return XMLSitemapRegenerationEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<XMLSitemapRegenerationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<XMLSitemapRegenerationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<XMLSitemapRegenerationEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(XMLSitemapRegenerationEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<XMLSitemapRegenerationEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<XMLSitemapRegenerationEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(XMLSitemapRegenerationEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<XMLSitemapRegenerationEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<XMLSitemapRegenerationEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<XMLSitemapRegenerationEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<XMLSitemapRegenerationEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<XMLSitemapRegenerationEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", XMLSitemapRegenerationEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"xmlSitemapRegenerationEntryId",
				XMLSitemapRegenerationEntry::getXmlSitemapRegenerationEntryId);
			attributeGetterFunctions.put(
				"groupId", XMLSitemapRegenerationEntry::getGroupId);
			attributeGetterFunctions.put(
				"companyId", XMLSitemapRegenerationEntry::getCompanyId);
			attributeGetterFunctions.put(
				"assetTypeKey", XMLSitemapRegenerationEntry::getAssetTypeKey);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<XMLSitemapRegenerationEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<XMLSitemapRegenerationEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<XMLSitemapRegenerationEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<XMLSitemapRegenerationEntry, Long>)
					XMLSitemapRegenerationEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"xmlSitemapRegenerationEntryId",
				(BiConsumer<XMLSitemapRegenerationEntry, Long>)
					XMLSitemapRegenerationEntry::
						setXmlSitemapRegenerationEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<XMLSitemapRegenerationEntry, Long>)
					XMLSitemapRegenerationEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<XMLSitemapRegenerationEntry, Long>)
					XMLSitemapRegenerationEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"assetTypeKey",
				(BiConsumer<XMLSitemapRegenerationEntry, String>)
					XMLSitemapRegenerationEntry::setAssetTypeKey);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getXmlSitemapRegenerationEntryId() {
		return _xmlSitemapRegenerationEntryId;
	}

	@Override
	public void setXmlSitemapRegenerationEntryId(
		long xmlSitemapRegenerationEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_xmlSitemapRegenerationEntryId = xmlSitemapRegenerationEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getAssetTypeKey() {
		if (_assetTypeKey == null) {
			return "";
		}
		else {
			return _assetTypeKey;
		}
	}

	@Override
	public void setAssetTypeKey(String assetTypeKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetTypeKey = assetTypeKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAssetTypeKey() {
		return getColumnOriginalValue("assetTypeKey");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), XMLSitemapRegenerationEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public XMLSitemapRegenerationEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, XMLSitemapRegenerationEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		XMLSitemapRegenerationEntryImpl xmlSitemapRegenerationEntryImpl =
			new XMLSitemapRegenerationEntryImpl();

		xmlSitemapRegenerationEntryImpl.setMvccVersion(getMvccVersion());
		xmlSitemapRegenerationEntryImpl.setXmlSitemapRegenerationEntryId(
			getXmlSitemapRegenerationEntryId());
		xmlSitemapRegenerationEntryImpl.setGroupId(getGroupId());
		xmlSitemapRegenerationEntryImpl.setCompanyId(getCompanyId());
		xmlSitemapRegenerationEntryImpl.setAssetTypeKey(getAssetTypeKey());

		xmlSitemapRegenerationEntryImpl.resetOriginalValues();

		return xmlSitemapRegenerationEntryImpl;
	}

	@Override
	public XMLSitemapRegenerationEntry cloneWithOriginalValues() {
		XMLSitemapRegenerationEntryImpl xmlSitemapRegenerationEntryImpl =
			new XMLSitemapRegenerationEntryImpl();

		xmlSitemapRegenerationEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		xmlSitemapRegenerationEntryImpl.setXmlSitemapRegenerationEntryId(
			this.<Long>getColumnOriginalValue("xmlSitemapRegenerationEntryId"));
		xmlSitemapRegenerationEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		xmlSitemapRegenerationEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		xmlSitemapRegenerationEntryImpl.setAssetTypeKey(
			this.<String>getColumnOriginalValue("assetTypeKey"));

		return xmlSitemapRegenerationEntryImpl;
	}

	@Override
	public int compareTo(
		XMLSitemapRegenerationEntry xmlSitemapRegenerationEntry) {

		long primaryKey = xmlSitemapRegenerationEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof XMLSitemapRegenerationEntry)) {
			return false;
		}

		XMLSitemapRegenerationEntry xmlSitemapRegenerationEntry =
			(XMLSitemapRegenerationEntry)object;

		long primaryKey = xmlSitemapRegenerationEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<XMLSitemapRegenerationEntry> toCacheModel() {
		XMLSitemapRegenerationEntryCacheModel
			xmlSitemapRegenerationEntryCacheModel =
				new XMLSitemapRegenerationEntryCacheModel();

		xmlSitemapRegenerationEntryCacheModel.mvccVersion = getMvccVersion();

		xmlSitemapRegenerationEntryCacheModel.xmlSitemapRegenerationEntryId =
			getXmlSitemapRegenerationEntryId();

		xmlSitemapRegenerationEntryCacheModel.groupId = getGroupId();

		xmlSitemapRegenerationEntryCacheModel.companyId = getCompanyId();

		xmlSitemapRegenerationEntryCacheModel.assetTypeKey = getAssetTypeKey();

		String assetTypeKey =
			xmlSitemapRegenerationEntryCacheModel.assetTypeKey;

		if ((assetTypeKey != null) && (assetTypeKey.length() == 0)) {
			xmlSitemapRegenerationEntryCacheModel.assetTypeKey = null;
		}

		return xmlSitemapRegenerationEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<XMLSitemapRegenerationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<XMLSitemapRegenerationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<XMLSitemapRegenerationEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(XMLSitemapRegenerationEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, XMLSitemapRegenerationEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						XMLSitemapRegenerationEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _xmlSitemapRegenerationEntryId;
	private long _groupId;
	private long _companyId;
	private String _assetTypeKey;

	public <T> T getColumnValue(String columnName) {
		Function<XMLSitemapRegenerationEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((XMLSitemapRegenerationEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"xmlSitemapRegenerationEntryId", _xmlSitemapRegenerationEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("assetTypeKey", _assetTypeKey);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("xmlSitemapRegenerationEntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("assetTypeKey", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private XMLSitemapRegenerationEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-119085131