/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.site.model.impl;

import com.liferay.site.model.XMLSitemapRegenerationEntry;
import com.liferay.site.service.XMLSitemapRegenerationEntryLocalServiceUtil;

/**
 * The extended model base implementation for the XMLSitemapRegenerationEntry service. Represents a row in the &quot;XMLSitemapRegenerationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link XMLSitemapRegenerationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see XMLSitemapRegenerationEntryImpl
 * @see XMLSitemapRegenerationEntry
 * @generated
 */
public abstract class XMLSitemapRegenerationEntryBaseImpl
	extends XMLSitemapRegenerationEntryModelImpl
	implements XMLSitemapRegenerationEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a xml sitemap regeneration entry model instance should use the <code>XMLSitemapRegenerationEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			XMLSitemapRegenerationEntryLocalServiceUtil.
				addXMLSitemapRegenerationEntry(this);
		}
		else {
			XMLSitemapRegenerationEntryLocalServiceUtil.
				updateXMLSitemapRegenerationEntry(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1766146474