/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portal.search.tuning.rankings.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ranking service. Represents a row in the &quot;Ranking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.search.tuning.rankings.model.impl.RankingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.search.tuning.rankings.model.impl.RankingImpl</code>.
 * </p>
 *
 * @author Bryan Engler
 * @see Ranking
 * @generated
 */
@ProviderType
public interface RankingModel
	extends BaseModel<Ranking>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ranking model instance should use the {@link Ranking} interface instead.
	 */

	/**
	 * Returns the primary key of this ranking.
	 *
	 * @return the primary key of this ranking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ranking.
	 *
	 * @param primaryKey the primary key of this ranking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ranking.
	 *
	 * @return the mvcc version of this ranking
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ranking.
	 *
	 * @param mvccVersion the mvcc version of this ranking
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ranking ID of this ranking.
	 *
	 * @return the ranking ID of this ranking
	 */
	public long getRankingId();

	/**
	 * Sets the ranking ID of this ranking.
	 *
	 * @param rankingId the ranking ID of this ranking
	 */
	public void setRankingId(long rankingId);

	/**
	 * Returns the company ID of this ranking.
	 *
	 * @return the company ID of this ranking
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ranking.
	 *
	 * @param companyId the company ID of this ranking
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the json of this ranking.
	 *
	 * @return the json of this ranking
	 */
	@AutoEscape
	public String getJson();

	/**
	 * Sets the json of this ranking.
	 *
	 * @param json the json of this ranking
	 */
	public void setJson(String json);

}