/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.repository.service.base;

import com.liferay.content.repository.model.ContentRepositoryEntry;
import com.liferay.content.repository.service.ContentRepositoryEntryLocalService;
import com.liferay.content.repository.service.persistence.ContentRepositoryEntryPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the content repository entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.content.repository.service.impl.ContentRepositoryEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.content.repository.service.impl.ContentRepositoryEntryLocalServiceImpl
 * @generated
 */
public abstract class ContentRepositoryEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ContentRepositoryEntryLocalService,
			   IdentifiableOSGiService {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ContentRepositoryEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.content.repository.service.ContentRepositoryEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the content repository entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param contentRepositoryEntry the content repository entry
	 * @return the content repository entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ContentRepositoryEntry addContentRepositoryEntry(
		ContentRepositoryEntry contentRepositoryEntry) {

		contentRepositoryEntry.setNew(true);

		return contentRepositoryEntryPersistence.update(contentRepositoryEntry);
	}

	/**
	 * Creates a new content repository entry with the primary key. Does not add the content repository entry to the database.
	 *
	 * @param contentRepositoryEntryId the primary key for the new content repository entry
	 * @return the new content repository entry
	 */
	@Override
	@Transactional(enabled = false)
	public ContentRepositoryEntry createContentRepositoryEntry(
		long contentRepositoryEntryId) {

		return contentRepositoryEntryPersistence.create(
			contentRepositoryEntryId);
	}

	/**
	 * Deletes the content repository entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param contentRepositoryEntryId the primary key of the content repository entry
	 * @return the content repository entry that was removed
	 * @throws PortalException if a content repository entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ContentRepositoryEntry deleteContentRepositoryEntry(
			long contentRepositoryEntryId)
		throws PortalException {

		return contentRepositoryEntryPersistence.remove(
			contentRepositoryEntryId);
	}

	/**
	 * Deletes the content repository entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param contentRepositoryEntry the content repository entry
	 * @return the content repository entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ContentRepositoryEntry deleteContentRepositoryEntry(
		ContentRepositoryEntry contentRepositoryEntry) {

		return contentRepositoryEntryPersistence.remove(contentRepositoryEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ContentRepositoryEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return contentRepositoryEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.content.repository.model.impl.ContentRepositoryEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return contentRepositoryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.content.repository.model.impl.ContentRepositoryEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return contentRepositoryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return contentRepositoryEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return contentRepositoryEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ContentRepositoryEntry fetchContentRepositoryEntry(
		long contentRepositoryEntryId) {

		return contentRepositoryEntryPersistence.fetchByPrimaryKey(
			contentRepositoryEntryId);
	}

	/**
	 * Returns the content repository entry matching the UUID and group.
	 *
	 * @param uuid the content repository entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching content repository entry, or <code>null</code> if a matching content repository entry could not be found
	 */
	@Override
	public ContentRepositoryEntry fetchContentRepositoryEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return contentRepositoryEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the content repository entry with the primary key.
	 *
	 * @param contentRepositoryEntryId the primary key of the content repository entry
	 * @return the content repository entry
	 * @throws PortalException if a content repository entry with the primary key could not be found
	 */
	@Override
	public ContentRepositoryEntry getContentRepositoryEntry(
			long contentRepositoryEntryId)
		throws PortalException {

		return contentRepositoryEntryPersistence.findByPrimaryKey(
			contentRepositoryEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			contentRepositoryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ContentRepositoryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"contentRepositoryEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			contentRepositoryEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			ContentRepositoryEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"contentRepositoryEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			contentRepositoryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ContentRepositoryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"contentRepositoryEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<ContentRepositoryEntry>() {

				@Override
				public void performAction(
						ContentRepositoryEntry contentRepositoryEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, contentRepositoryEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					ContentRepositoryEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return contentRepositoryEntryLocalService.deleteContentRepositoryEntry(
			(ContentRepositoryEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return contentRepositoryEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the content repository entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the content repository entries
	 * @param companyId the primary key of the company
	 * @return the matching content repository entries, or an empty list if no matches were found
	 */
	@Override
	public List<ContentRepositoryEntry>
		getContentRepositoryEntriesByUuidAndCompanyId(
			String uuid, long companyId) {

		return contentRepositoryEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of content repository entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the content repository entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of content repository entries
	 * @param end the upper bound of the range of content repository entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching content repository entries, or an empty list if no matches were found
	 */
	@Override
	public List<ContentRepositoryEntry>
		getContentRepositoryEntriesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<ContentRepositoryEntry> orderByComparator) {

		return contentRepositoryEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the content repository entry matching the UUID and group.
	 *
	 * @param uuid the content repository entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching content repository entry
	 * @throws PortalException if a matching content repository entry could not be found
	 */
	@Override
	public ContentRepositoryEntry getContentRepositoryEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return contentRepositoryEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the content repository entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.content.repository.model.impl.ContentRepositoryEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of content repository entries
	 * @param end the upper bound of the range of content repository entries (not inclusive)
	 * @return the range of content repository entries
	 */
	@Override
	public List<ContentRepositoryEntry> getContentRepositoryEntries(
		int start, int end) {

		return contentRepositoryEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of content repository entries.
	 *
	 * @return the number of content repository entries
	 */
	@Override
	public int getContentRepositoryEntriesCount() {
		return contentRepositoryEntryPersistence.countAll();
	}

	/**
	 * Updates the content repository entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param contentRepositoryEntry the content repository entry
	 * @return the content repository entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ContentRepositoryEntry updateContentRepositoryEntry(
		ContentRepositoryEntry contentRepositoryEntry) {

		return contentRepositoryEntryPersistence.update(contentRepositoryEntry);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ContentRepositoryEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		contentRepositoryEntryLocalService =
			(ContentRepositoryEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ContentRepositoryEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ContentRepositoryEntry.class;
	}

	protected String getModelClassName() {
		return ContentRepositoryEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				contentRepositoryEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	protected ContentRepositoryEntryLocalService
		contentRepositoryEntryLocalService;

	@Reference
	protected ContentRepositoryEntryPersistence
		contentRepositoryEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}