/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.seo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.seo.model.LayoutSEOCanonicalURL;
import com.liferay.layout.seo.model.LayoutSEOCanonicalURLModel;
import com.liferay.layout.seo.model.LayoutSEOCanonicalURLSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the LayoutSEOCanonicalURL service. Represents a row in the &quot;LayoutSEOCanonicalURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LayoutSEOCanonicalURLModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutSEOCanonicalURLImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutSEOCanonicalURLImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LayoutSEOCanonicalURLModelImpl
	extends BaseModelImpl<LayoutSEOCanonicalURL>
	implements LayoutSEOCanonicalURLModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout seo canonical url model instance should use the <code>LayoutSEOCanonicalURL</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutSEOCanonicalURL";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"layoutSEOCanonicalURLId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"canonicalURL", Types.VARCHAR}, {"enabled", Types.BOOLEAN},
		{"privateLayout", Types.BOOLEAN}, {"lastPublishDate", Types.TIMESTAMP},
		{"layoutId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layoutSEOCanonicalURLId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("canonicalURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("enabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("privateLayout", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("layoutId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutSEOCanonicalURL (uuid_ VARCHAR(75) null,layoutSEOCanonicalURLId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,canonicalURL STRING null,enabled BOOLEAN,privateLayout BOOLEAN,lastPublishDate DATE null,layoutId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table LayoutSEOCanonicalURL";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutSEOCanonicalURL.layoutSEOCanonicalURLId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutSEOCanonicalURL.layoutSEOCanonicalURLId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long LAYOUTID_COLUMN_BITMASK = 4L;

	public static final long PRIVATELAYOUT_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long LAYOUTSEOCANONICALURLID_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LayoutSEOCanonicalURL toModel(
		LayoutSEOCanonicalURLSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		LayoutSEOCanonicalURL model = new LayoutSEOCanonicalURLImpl();

		model.setUuid(soapModel.getUuid());
		model.setLayoutSEOCanonicalURLId(
			soapModel.getLayoutSEOCanonicalURLId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCanonicalURL(soapModel.getCanonicalURL());
		model.setEnabled(soapModel.isEnabled());
		model.setPrivateLayout(soapModel.isPrivateLayout());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setLayoutId(soapModel.getLayoutId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LayoutSEOCanonicalURL> toModels(
		LayoutSEOCanonicalURLSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<LayoutSEOCanonicalURL> models =
			new ArrayList<LayoutSEOCanonicalURL>(soapModels.length);

		for (LayoutSEOCanonicalURLSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LayoutSEOCanonicalURLModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutSEOCanonicalURLId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutSEOCanonicalURLId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutSEOCanonicalURLId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutSEOCanonicalURL.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutSEOCanonicalURL.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutSEOCanonicalURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutSEOCanonicalURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOCanonicalURL, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LayoutSEOCanonicalURL)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutSEOCanonicalURL, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutSEOCanonicalURL, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutSEOCanonicalURL)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutSEOCanonicalURL, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutSEOCanonicalURL, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LayoutSEOCanonicalURL>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LayoutSEOCanonicalURL.class.getClassLoader(),
			LayoutSEOCanonicalURL.class, ModelWrapper.class);

		try {
			Constructor<LayoutSEOCanonicalURL> constructor =
				(Constructor<LayoutSEOCanonicalURL>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<LayoutSEOCanonicalURL, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LayoutSEOCanonicalURL, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LayoutSEOCanonicalURL, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LayoutSEOCanonicalURL, Object>>();
		Map<String, BiConsumer<LayoutSEOCanonicalURL, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LayoutSEOCanonicalURL, ?>>();

		attributeGetterFunctions.put("uuid", LayoutSEOCanonicalURL::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LayoutSEOCanonicalURL, String>)
				LayoutSEOCanonicalURL::setUuid);
		attributeGetterFunctions.put(
			"layoutSEOCanonicalURLId",
			LayoutSEOCanonicalURL::getLayoutSEOCanonicalURLId);
		attributeSetterBiConsumers.put(
			"layoutSEOCanonicalURLId",
			(BiConsumer<LayoutSEOCanonicalURL, Long>)
				LayoutSEOCanonicalURL::setLayoutSEOCanonicalURLId);
		attributeGetterFunctions.put(
			"groupId", LayoutSEOCanonicalURL::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LayoutSEOCanonicalURL, Long>)
				LayoutSEOCanonicalURL::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LayoutSEOCanonicalURL::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LayoutSEOCanonicalURL, Long>)
				LayoutSEOCanonicalURL::setCompanyId);
		attributeGetterFunctions.put(
			"userId", LayoutSEOCanonicalURL::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LayoutSEOCanonicalURL, Long>)
				LayoutSEOCanonicalURL::setUserId);
		attributeGetterFunctions.put(
			"userName", LayoutSEOCanonicalURL::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LayoutSEOCanonicalURL, String>)
				LayoutSEOCanonicalURL::setUserName);
		attributeGetterFunctions.put(
			"createDate", LayoutSEOCanonicalURL::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LayoutSEOCanonicalURL, Date>)
				LayoutSEOCanonicalURL::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LayoutSEOCanonicalURL::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LayoutSEOCanonicalURL, Date>)
				LayoutSEOCanonicalURL::setModifiedDate);
		attributeGetterFunctions.put(
			"canonicalURL", LayoutSEOCanonicalURL::getCanonicalURL);
		attributeSetterBiConsumers.put(
			"canonicalURL",
			(BiConsumer<LayoutSEOCanonicalURL, String>)
				LayoutSEOCanonicalURL::setCanonicalURL);
		attributeGetterFunctions.put(
			"enabled", LayoutSEOCanonicalURL::getEnabled);
		attributeSetterBiConsumers.put(
			"enabled",
			(BiConsumer<LayoutSEOCanonicalURL, Boolean>)
				LayoutSEOCanonicalURL::setEnabled);
		attributeGetterFunctions.put(
			"privateLayout", LayoutSEOCanonicalURL::getPrivateLayout);
		attributeSetterBiConsumers.put(
			"privateLayout",
			(BiConsumer<LayoutSEOCanonicalURL, Boolean>)
				LayoutSEOCanonicalURL::setPrivateLayout);
		attributeGetterFunctions.put(
			"lastPublishDate", LayoutSEOCanonicalURL::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<LayoutSEOCanonicalURL, Date>)
				LayoutSEOCanonicalURL::setLastPublishDate);
		attributeGetterFunctions.put(
			"layoutId", LayoutSEOCanonicalURL::getLayoutId);
		attributeSetterBiConsumers.put(
			"layoutId",
			(BiConsumer<LayoutSEOCanonicalURL, Long>)
				LayoutSEOCanonicalURL::setLayoutId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLayoutSEOCanonicalURLId() {
		return _layoutSEOCanonicalURLId;
	}

	@Override
	public void setLayoutSEOCanonicalURLId(long layoutSEOCanonicalURLId) {
		_layoutSEOCanonicalURLId = layoutSEOCanonicalURLId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCanonicalURL() {
		if (_canonicalURL == null) {
			return "";
		}
		else {
			return _canonicalURL;
		}
	}

	@Override
	public String getCanonicalURL(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCanonicalURL(languageId);
	}

	@Override
	public String getCanonicalURL(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCanonicalURL(languageId, useDefault);
	}

	@Override
	public String getCanonicalURL(String languageId) {
		return LocalizationUtil.getLocalization(getCanonicalURL(), languageId);
	}

	@Override
	public String getCanonicalURL(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getCanonicalURL(), languageId, useDefault);
	}

	@Override
	public String getCanonicalURLCurrentLanguageId() {
		return _canonicalURLCurrentLanguageId;
	}

	@JSON
	@Override
	public String getCanonicalURLCurrentValue() {
		Locale locale = getLocale(_canonicalURLCurrentLanguageId);

		return getCanonicalURL(locale);
	}

	@Override
	public Map<Locale, String> getCanonicalURLMap() {
		return LocalizationUtil.getLocalizationMap(getCanonicalURL());
	}

	@Override
	public void setCanonicalURL(String canonicalURL) {
		_canonicalURL = canonicalURL;
	}

	@Override
	public void setCanonicalURL(String canonicalURL, Locale locale) {
		setCanonicalURL(canonicalURL, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCanonicalURL(
		String canonicalURL, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(canonicalURL)) {
			setCanonicalURL(
				LocalizationUtil.updateLocalization(
					getCanonicalURL(), "CanonicalURL", canonicalURL, languageId,
					defaultLanguageId));
		}
		else {
			setCanonicalURL(
				LocalizationUtil.removeLocalization(
					getCanonicalURL(), "CanonicalURL", languageId));
		}
	}

	@Override
	public void setCanonicalURLCurrentLanguageId(String languageId) {
		_canonicalURLCurrentLanguageId = languageId;
	}

	@Override
	public void setCanonicalURLMap(Map<Locale, String> canonicalURLMap) {
		setCanonicalURLMap(canonicalURLMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCanonicalURLMap(
		Map<Locale, String> canonicalURLMap, Locale defaultLocale) {

		if (canonicalURLMap == null) {
			return;
		}

		setCanonicalURL(
			LocalizationUtil.updateLocalization(
				canonicalURLMap, getCanonicalURL(), "CanonicalURL",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public boolean getEnabled() {
		return _enabled;
	}

	@JSON
	@Override
	public boolean isEnabled() {
		return _enabled;
	}

	@Override
	public void setEnabled(boolean enabled) {
		_enabled = enabled;
	}

	@JSON
	@Override
	public boolean getPrivateLayout() {
		return _privateLayout;
	}

	@JSON
	@Override
	public boolean isPrivateLayout() {
		return _privateLayout;
	}

	@Override
	public void setPrivateLayout(boolean privateLayout) {
		_columnBitmask |= PRIVATELAYOUT_COLUMN_BITMASK;

		if (!_setOriginalPrivateLayout) {
			_setOriginalPrivateLayout = true;

			_originalPrivateLayout = _privateLayout;
		}

		_privateLayout = privateLayout;
	}

	public boolean getOriginalPrivateLayout() {
		return _originalPrivateLayout;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public long getLayoutId() {
		return _layoutId;
	}

	@Override
	public void setLayoutId(long layoutId) {
		_columnBitmask |= LAYOUTID_COLUMN_BITMASK;

		if (!_setOriginalLayoutId) {
			_setOriginalLayoutId = true;

			_originalLayoutId = _layoutId;
		}

		_layoutId = layoutId;
	}

	public long getOriginalLayoutId() {
		return _originalLayoutId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LayoutSEOCanonicalURL.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LayoutSEOCanonicalURL.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> canonicalURLMap = getCanonicalURLMap();

		for (Map.Entry<Locale, String> entry : canonicalURLMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getCanonicalURL();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LayoutSEOCanonicalURL.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String canonicalURL = getCanonicalURL(defaultLocale);

		if (Validator.isNull(canonicalURL)) {
			setCanonicalURL(
				getCanonicalURL(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setCanonicalURL(
				getCanonicalURL(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public LayoutSEOCanonicalURL toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LayoutSEOCanonicalURL>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutSEOCanonicalURLImpl layoutSEOCanonicalURLImpl =
			new LayoutSEOCanonicalURLImpl();

		layoutSEOCanonicalURLImpl.setUuid(getUuid());
		layoutSEOCanonicalURLImpl.setLayoutSEOCanonicalURLId(
			getLayoutSEOCanonicalURLId());
		layoutSEOCanonicalURLImpl.setGroupId(getGroupId());
		layoutSEOCanonicalURLImpl.setCompanyId(getCompanyId());
		layoutSEOCanonicalURLImpl.setUserId(getUserId());
		layoutSEOCanonicalURLImpl.setUserName(getUserName());
		layoutSEOCanonicalURLImpl.setCreateDate(getCreateDate());
		layoutSEOCanonicalURLImpl.setModifiedDate(getModifiedDate());
		layoutSEOCanonicalURLImpl.setCanonicalURL(getCanonicalURL());
		layoutSEOCanonicalURLImpl.setEnabled(isEnabled());
		layoutSEOCanonicalURLImpl.setPrivateLayout(isPrivateLayout());
		layoutSEOCanonicalURLImpl.setLastPublishDate(getLastPublishDate());
		layoutSEOCanonicalURLImpl.setLayoutId(getLayoutId());

		layoutSEOCanonicalURLImpl.resetOriginalValues();

		return layoutSEOCanonicalURLImpl;
	}

	@Override
	public int compareTo(LayoutSEOCanonicalURL layoutSEOCanonicalURL) {
		long primaryKey = layoutSEOCanonicalURL.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutSEOCanonicalURL)) {
			return false;
		}

		LayoutSEOCanonicalURL layoutSEOCanonicalURL =
			(LayoutSEOCanonicalURL)obj;

		long primaryKey = layoutSEOCanonicalURL.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LayoutSEOCanonicalURLModelImpl layoutSEOCanonicalURLModelImpl = this;

		layoutSEOCanonicalURLModelImpl._originalUuid =
			layoutSEOCanonicalURLModelImpl._uuid;

		layoutSEOCanonicalURLModelImpl._originalGroupId =
			layoutSEOCanonicalURLModelImpl._groupId;

		layoutSEOCanonicalURLModelImpl._setOriginalGroupId = false;

		layoutSEOCanonicalURLModelImpl._originalCompanyId =
			layoutSEOCanonicalURLModelImpl._companyId;

		layoutSEOCanonicalURLModelImpl._setOriginalCompanyId = false;

		layoutSEOCanonicalURLModelImpl._setModifiedDate = false;

		layoutSEOCanonicalURLModelImpl._originalPrivateLayout =
			layoutSEOCanonicalURLModelImpl._privateLayout;

		layoutSEOCanonicalURLModelImpl._setOriginalPrivateLayout = false;

		layoutSEOCanonicalURLModelImpl._originalLayoutId =
			layoutSEOCanonicalURLModelImpl._layoutId;

		layoutSEOCanonicalURLModelImpl._setOriginalLayoutId = false;

		layoutSEOCanonicalURLModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutSEOCanonicalURL> toCacheModel() {
		LayoutSEOCanonicalURLCacheModel layoutSEOCanonicalURLCacheModel =
			new LayoutSEOCanonicalURLCacheModel();

		layoutSEOCanonicalURLCacheModel.uuid = getUuid();

		String uuid = layoutSEOCanonicalURLCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			layoutSEOCanonicalURLCacheModel.uuid = null;
		}

		layoutSEOCanonicalURLCacheModel.layoutSEOCanonicalURLId =
			getLayoutSEOCanonicalURLId();

		layoutSEOCanonicalURLCacheModel.groupId = getGroupId();

		layoutSEOCanonicalURLCacheModel.companyId = getCompanyId();

		layoutSEOCanonicalURLCacheModel.userId = getUserId();

		layoutSEOCanonicalURLCacheModel.userName = getUserName();

		String userName = layoutSEOCanonicalURLCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutSEOCanonicalURLCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutSEOCanonicalURLCacheModel.createDate = createDate.getTime();
		}
		else {
			layoutSEOCanonicalURLCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutSEOCanonicalURLCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			layoutSEOCanonicalURLCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		layoutSEOCanonicalURLCacheModel.canonicalURL = getCanonicalURL();

		String canonicalURL = layoutSEOCanonicalURLCacheModel.canonicalURL;

		if ((canonicalURL != null) && (canonicalURL.length() == 0)) {
			layoutSEOCanonicalURLCacheModel.canonicalURL = null;
		}

		layoutSEOCanonicalURLCacheModel.enabled = isEnabled();

		layoutSEOCanonicalURLCacheModel.privateLayout = isPrivateLayout();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			layoutSEOCanonicalURLCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			layoutSEOCanonicalURLCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		layoutSEOCanonicalURLCacheModel.layoutId = getLayoutId();

		return layoutSEOCanonicalURLCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutSEOCanonicalURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutSEOCanonicalURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOCanonicalURL, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((LayoutSEOCanonicalURL)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LayoutSEOCanonicalURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LayoutSEOCanonicalURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOCanonicalURL, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((LayoutSEOCanonicalURL)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LayoutSEOCanonicalURL>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _layoutSEOCanonicalURLId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _canonicalURL;
	private String _canonicalURLCurrentLanguageId;
	private boolean _enabled;
	private boolean _privateLayout;
	private boolean _originalPrivateLayout;
	private boolean _setOriginalPrivateLayout;
	private Date _lastPublishDate;
	private long _layoutId;
	private long _originalLayoutId;
	private boolean _setOriginalLayoutId;
	private long _columnBitmask;
	private LayoutSEOCanonicalURL _escapedModel;

}