/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.seo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.seo.model.LayoutSEOSiteEntry;
import com.liferay.layout.seo.model.LayoutSEOSiteEntryModel;
import com.liferay.layout.seo.model.LayoutSEOSiteEntrySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LayoutSEOSiteEntry service. Represents a row in the &quot;LayoutSEOSiteEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LayoutSEOSiteEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutSEOSiteEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutSEOSiteEntryImpl
 * @generated
 */
@JSON(strict = true)
public class LayoutSEOSiteEntryModelImpl
	extends BaseModelImpl<LayoutSEOSiteEntry>
	implements LayoutSEOSiteEntryModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout seo site entry model instance should use the <code>LayoutSEOSiteEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutSEOSiteEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"layoutSEOSiteEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"openGraphEnabled", Types.BOOLEAN},
		{"openGraphImageFileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layoutSEOSiteEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("openGraphEnabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("openGraphImageFileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutSEOSiteEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,layoutSEOSiteEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,openGraphEnabled BOOLEAN,openGraphImageFileEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LayoutSEOSiteEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutSEOSiteEntry.layoutSEOSiteEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutSEOSiteEntry.layoutSEOSiteEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long LAYOUTSEOSITEENTRYID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LayoutSEOSiteEntry toModel(LayoutSEOSiteEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LayoutSEOSiteEntry model = new LayoutSEOSiteEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setLayoutSEOSiteEntryId(soapModel.getLayoutSEOSiteEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOpenGraphEnabled(soapModel.isOpenGraphEnabled());
		model.setOpenGraphImageFileEntryId(
			soapModel.getOpenGraphImageFileEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LayoutSEOSiteEntry> toModels(
		LayoutSEOSiteEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<LayoutSEOSiteEntry> models = new ArrayList<LayoutSEOSiteEntry>(
			soapModels.length);

		for (LayoutSEOSiteEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LayoutSEOSiteEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutSEOSiteEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutSEOSiteEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutSEOSiteEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutSEOSiteEntry.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutSEOSiteEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutSEOSiteEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutSEOSiteEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOSiteEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LayoutSEOSiteEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutSEOSiteEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutSEOSiteEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutSEOSiteEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutSEOSiteEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutSEOSiteEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LayoutSEOSiteEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LayoutSEOSiteEntry.class.getClassLoader(), LayoutSEOSiteEntry.class,
			ModelWrapper.class);

		try {
			Constructor<LayoutSEOSiteEntry> constructor =
				(Constructor<LayoutSEOSiteEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<LayoutSEOSiteEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LayoutSEOSiteEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LayoutSEOSiteEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LayoutSEOSiteEntry, Object>>();
		Map<String, BiConsumer<LayoutSEOSiteEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<LayoutSEOSiteEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", LayoutSEOSiteEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", LayoutSEOSiteEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LayoutSEOSiteEntry, String>)
				LayoutSEOSiteEntry::setUuid);
		attributeGetterFunctions.put(
			"layoutSEOSiteEntryId",
			LayoutSEOSiteEntry::getLayoutSEOSiteEntryId);
		attributeSetterBiConsumers.put(
			"layoutSEOSiteEntryId",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setLayoutSEOSiteEntryId);
		attributeGetterFunctions.put("groupId", LayoutSEOSiteEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LayoutSEOSiteEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setCompanyId);
		attributeGetterFunctions.put("userId", LayoutSEOSiteEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", LayoutSEOSiteEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LayoutSEOSiteEntry, String>)
				LayoutSEOSiteEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", LayoutSEOSiteEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LayoutSEOSiteEntry, Date>)
				LayoutSEOSiteEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LayoutSEOSiteEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LayoutSEOSiteEntry, Date>)
				LayoutSEOSiteEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"openGraphEnabled", LayoutSEOSiteEntry::getOpenGraphEnabled);
		attributeSetterBiConsumers.put(
			"openGraphEnabled",
			(BiConsumer<LayoutSEOSiteEntry, Boolean>)
				LayoutSEOSiteEntry::setOpenGraphEnabled);
		attributeGetterFunctions.put(
			"openGraphImageFileEntryId",
			LayoutSEOSiteEntry::getOpenGraphImageFileEntryId);
		attributeSetterBiConsumers.put(
			"openGraphImageFileEntryId",
			(BiConsumer<LayoutSEOSiteEntry, Long>)
				LayoutSEOSiteEntry::setOpenGraphImageFileEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLayoutSEOSiteEntryId() {
		return _layoutSEOSiteEntryId;
	}

	@Override
	public void setLayoutSEOSiteEntryId(long layoutSEOSiteEntryId) {
		_layoutSEOSiteEntryId = layoutSEOSiteEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getOpenGraphEnabled() {
		return _openGraphEnabled;
	}

	@JSON
	@Override
	public boolean isOpenGraphEnabled() {
		return _openGraphEnabled;
	}

	@Override
	public void setOpenGraphEnabled(boolean openGraphEnabled) {
		_openGraphEnabled = openGraphEnabled;
	}

	@JSON
	@Override
	public long getOpenGraphImageFileEntryId() {
		return _openGraphImageFileEntryId;
	}

	@Override
	public void setOpenGraphImageFileEntryId(long openGraphImageFileEntryId) {
		_openGraphImageFileEntryId = openGraphImageFileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LayoutSEOSiteEntry.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LayoutSEOSiteEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LayoutSEOSiteEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LayoutSEOSiteEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutSEOSiteEntryImpl layoutSEOSiteEntryImpl =
			new LayoutSEOSiteEntryImpl();

		layoutSEOSiteEntryImpl.setMvccVersion(getMvccVersion());
		layoutSEOSiteEntryImpl.setUuid(getUuid());
		layoutSEOSiteEntryImpl.setLayoutSEOSiteEntryId(
			getLayoutSEOSiteEntryId());
		layoutSEOSiteEntryImpl.setGroupId(getGroupId());
		layoutSEOSiteEntryImpl.setCompanyId(getCompanyId());
		layoutSEOSiteEntryImpl.setUserId(getUserId());
		layoutSEOSiteEntryImpl.setUserName(getUserName());
		layoutSEOSiteEntryImpl.setCreateDate(getCreateDate());
		layoutSEOSiteEntryImpl.setModifiedDate(getModifiedDate());
		layoutSEOSiteEntryImpl.setOpenGraphEnabled(isOpenGraphEnabled());
		layoutSEOSiteEntryImpl.setOpenGraphImageFileEntryId(
			getOpenGraphImageFileEntryId());

		layoutSEOSiteEntryImpl.resetOriginalValues();

		return layoutSEOSiteEntryImpl;
	}

	@Override
	public int compareTo(LayoutSEOSiteEntry layoutSEOSiteEntry) {
		long primaryKey = layoutSEOSiteEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutSEOSiteEntry)) {
			return false;
		}

		LayoutSEOSiteEntry layoutSEOSiteEntry = (LayoutSEOSiteEntry)obj;

		long primaryKey = layoutSEOSiteEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LayoutSEOSiteEntryModelImpl layoutSEOSiteEntryModelImpl = this;

		layoutSEOSiteEntryModelImpl._originalUuid =
			layoutSEOSiteEntryModelImpl._uuid;

		layoutSEOSiteEntryModelImpl._originalGroupId =
			layoutSEOSiteEntryModelImpl._groupId;

		layoutSEOSiteEntryModelImpl._setOriginalGroupId = false;

		layoutSEOSiteEntryModelImpl._originalCompanyId =
			layoutSEOSiteEntryModelImpl._companyId;

		layoutSEOSiteEntryModelImpl._setOriginalCompanyId = false;

		layoutSEOSiteEntryModelImpl._setModifiedDate = false;

		layoutSEOSiteEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutSEOSiteEntry> toCacheModel() {
		LayoutSEOSiteEntryCacheModel layoutSEOSiteEntryCacheModel =
			new LayoutSEOSiteEntryCacheModel();

		layoutSEOSiteEntryCacheModel.mvccVersion = getMvccVersion();

		layoutSEOSiteEntryCacheModel.uuid = getUuid();

		String uuid = layoutSEOSiteEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			layoutSEOSiteEntryCacheModel.uuid = null;
		}

		layoutSEOSiteEntryCacheModel.layoutSEOSiteEntryId =
			getLayoutSEOSiteEntryId();

		layoutSEOSiteEntryCacheModel.groupId = getGroupId();

		layoutSEOSiteEntryCacheModel.companyId = getCompanyId();

		layoutSEOSiteEntryCacheModel.userId = getUserId();

		layoutSEOSiteEntryCacheModel.userName = getUserName();

		String userName = layoutSEOSiteEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutSEOSiteEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutSEOSiteEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			layoutSEOSiteEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutSEOSiteEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			layoutSEOSiteEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		layoutSEOSiteEntryCacheModel.openGraphEnabled = isOpenGraphEnabled();

		layoutSEOSiteEntryCacheModel.openGraphImageFileEntryId =
			getOpenGraphImageFileEntryId();

		return layoutSEOSiteEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutSEOSiteEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutSEOSiteEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOSiteEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LayoutSEOSiteEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LayoutSEOSiteEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LayoutSEOSiteEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutSEOSiteEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LayoutSEOSiteEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LayoutSEOSiteEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _layoutSEOSiteEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _openGraphEnabled;
	private long _openGraphImageFileEntryId;
	private long _columnBitmask;
	private LayoutSEOSiteEntry _escapedModel;

}