/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.seo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.seo.model.SiteSEOEntry;
import com.liferay.layout.seo.model.SiteSEOEntryModel;
import com.liferay.layout.seo.model.SiteSEOEntrySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SiteSEOEntry service. Represents a row in the &quot;SiteSEOEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>SiteSEOEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SiteSEOEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteSEOEntryImpl
 * @generated
 */
@JSON(strict = true)
public class SiteSEOEntryModelImpl
	extends BaseModelImpl<SiteSEOEntry> implements SiteSEOEntryModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a site seo entry model instance should use the <code>SiteSEOEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "SiteSEOEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"siteSEOEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"openGraphEnabled", Types.BOOLEAN},
		{"openGraphImageFileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("siteSEOEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("openGraphEnabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("openGraphImageFileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SiteSEOEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,siteSEOEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,openGraphEnabled BOOLEAN,openGraphImageFileEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table SiteSEOEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY siteSEOEntry.siteSEOEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SiteSEOEntry.siteSEOEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long SITESEOENTRYID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SiteSEOEntry toModel(SiteSEOEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SiteSEOEntry model = new SiteSEOEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setSiteSEOEntryId(soapModel.getSiteSEOEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOpenGraphEnabled(soapModel.isOpenGraphEnabled());
		model.setOpenGraphImageFileEntryId(
			soapModel.getOpenGraphImageFileEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SiteSEOEntry> toModels(SiteSEOEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SiteSEOEntry> models = new ArrayList<SiteSEOEntry>(
			soapModels.length);

		for (SiteSEOEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SiteSEOEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _siteSEOEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSiteSEOEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _siteSEOEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SiteSEOEntry.class;
	}

	@Override
	public String getModelClassName() {
		return SiteSEOEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SiteSEOEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SiteSEOEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SiteSEOEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SiteSEOEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SiteSEOEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SiteSEOEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SiteSEOEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SiteSEOEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SiteSEOEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SiteSEOEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SiteSEOEntry.class.getClassLoader(), SiteSEOEntry.class,
			ModelWrapper.class);

		try {
			Constructor<SiteSEOEntry> constructor =
				(Constructor<SiteSEOEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<SiteSEOEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SiteSEOEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SiteSEOEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SiteSEOEntry, Object>>();
		Map<String, BiConsumer<SiteSEOEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SiteSEOEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", SiteSEOEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<SiteSEOEntry, Long>)SiteSEOEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", SiteSEOEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<SiteSEOEntry, String>)SiteSEOEntry::setUuid);
		attributeGetterFunctions.put(
			"siteSEOEntryId", SiteSEOEntry::getSiteSEOEntryId);
		attributeSetterBiConsumers.put(
			"siteSEOEntryId",
			(BiConsumer<SiteSEOEntry, Long>)SiteSEOEntry::setSiteSEOEntryId);
		attributeGetterFunctions.put("groupId", SiteSEOEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SiteSEOEntry, Long>)SiteSEOEntry::setGroupId);
		attributeGetterFunctions.put("companyId", SiteSEOEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SiteSEOEntry, Long>)SiteSEOEntry::setCompanyId);
		attributeGetterFunctions.put("userId", SiteSEOEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<SiteSEOEntry, Long>)SiteSEOEntry::setUserId);
		attributeGetterFunctions.put("userName", SiteSEOEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SiteSEOEntry, String>)SiteSEOEntry::setUserName);
		attributeGetterFunctions.put("createDate", SiteSEOEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SiteSEOEntry, Date>)SiteSEOEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SiteSEOEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SiteSEOEntry, Date>)SiteSEOEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"openGraphEnabled", SiteSEOEntry::getOpenGraphEnabled);
		attributeSetterBiConsumers.put(
			"openGraphEnabled",
			(BiConsumer<SiteSEOEntry, Boolean>)
				SiteSEOEntry::setOpenGraphEnabled);
		attributeGetterFunctions.put(
			"openGraphImageFileEntryId",
			SiteSEOEntry::getOpenGraphImageFileEntryId);
		attributeSetterBiConsumers.put(
			"openGraphImageFileEntryId",
			(BiConsumer<SiteSEOEntry, Long>)
				SiteSEOEntry::setOpenGraphImageFileEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSiteSEOEntryId() {
		return _siteSEOEntryId;
	}

	@Override
	public void setSiteSEOEntryId(long siteSEOEntryId) {
		_siteSEOEntryId = siteSEOEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getOpenGraphEnabled() {
		return _openGraphEnabled;
	}

	@JSON
	@Override
	public boolean isOpenGraphEnabled() {
		return _openGraphEnabled;
	}

	@Override
	public void setOpenGraphEnabled(boolean openGraphEnabled) {
		_openGraphEnabled = openGraphEnabled;
	}

	@JSON
	@Override
	public long getOpenGraphImageFileEntryId() {
		return _openGraphImageFileEntryId;
	}

	@Override
	public void setOpenGraphImageFileEntryId(long openGraphImageFileEntryId) {
		_openGraphImageFileEntryId = openGraphImageFileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SiteSEOEntry.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SiteSEOEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SiteSEOEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SiteSEOEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SiteSEOEntryImpl siteSEOEntryImpl = new SiteSEOEntryImpl();

		siteSEOEntryImpl.setMvccVersion(getMvccVersion());
		siteSEOEntryImpl.setUuid(getUuid());
		siteSEOEntryImpl.setSiteSEOEntryId(getSiteSEOEntryId());
		siteSEOEntryImpl.setGroupId(getGroupId());
		siteSEOEntryImpl.setCompanyId(getCompanyId());
		siteSEOEntryImpl.setUserId(getUserId());
		siteSEOEntryImpl.setUserName(getUserName());
		siteSEOEntryImpl.setCreateDate(getCreateDate());
		siteSEOEntryImpl.setModifiedDate(getModifiedDate());
		siteSEOEntryImpl.setOpenGraphEnabled(isOpenGraphEnabled());
		siteSEOEntryImpl.setOpenGraphImageFileEntryId(
			getOpenGraphImageFileEntryId());

		siteSEOEntryImpl.resetOriginalValues();

		return siteSEOEntryImpl;
	}

	@Override
	public int compareTo(SiteSEOEntry siteSEOEntry) {
		long primaryKey = siteSEOEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SiteSEOEntry)) {
			return false;
		}

		SiteSEOEntry siteSEOEntry = (SiteSEOEntry)obj;

		long primaryKey = siteSEOEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		SiteSEOEntryModelImpl siteSEOEntryModelImpl = this;

		siteSEOEntryModelImpl._originalUuid = siteSEOEntryModelImpl._uuid;

		siteSEOEntryModelImpl._originalGroupId = siteSEOEntryModelImpl._groupId;

		siteSEOEntryModelImpl._setOriginalGroupId = false;

		siteSEOEntryModelImpl._originalCompanyId =
			siteSEOEntryModelImpl._companyId;

		siteSEOEntryModelImpl._setOriginalCompanyId = false;

		siteSEOEntryModelImpl._setModifiedDate = false;

		siteSEOEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SiteSEOEntry> toCacheModel() {
		SiteSEOEntryCacheModel siteSEOEntryCacheModel =
			new SiteSEOEntryCacheModel();

		siteSEOEntryCacheModel.mvccVersion = getMvccVersion();

		siteSEOEntryCacheModel.uuid = getUuid();

		String uuid = siteSEOEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			siteSEOEntryCacheModel.uuid = null;
		}

		siteSEOEntryCacheModel.siteSEOEntryId = getSiteSEOEntryId();

		siteSEOEntryCacheModel.groupId = getGroupId();

		siteSEOEntryCacheModel.companyId = getCompanyId();

		siteSEOEntryCacheModel.userId = getUserId();

		siteSEOEntryCacheModel.userName = getUserName();

		String userName = siteSEOEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			siteSEOEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			siteSEOEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			siteSEOEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			siteSEOEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			siteSEOEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		siteSEOEntryCacheModel.openGraphEnabled = isOpenGraphEnabled();

		siteSEOEntryCacheModel.openGraphImageFileEntryId =
			getOpenGraphImageFileEntryId();

		return siteSEOEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SiteSEOEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SiteSEOEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SiteSEOEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((SiteSEOEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SiteSEOEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SiteSEOEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SiteSEOEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SiteSEOEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SiteSEOEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _siteSEOEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _openGraphEnabled;
	private long _openGraphImageFileEntryId;
	private long _columnBitmask;
	private SiteSEOEntry _escapedModel;

}