##
## Test Batch
##

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        util/portal-tools-theme-builder/**/*Test.java

##
## Testray
##

    testray.main.component.name=Dev Tools