/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.ResourceBlockRoleAction;
import com.liferay.portal.model.ResourceBlockRoleActionModel;
import com.liferay.portal.service.persistence.ResourceBlockRoleActionPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the ResourceBlockRoleAction service. Represents a row in the &quot;ResourceBlockRoleAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portal.model.ResourceBlockRoleActionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceBlockRoleActionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceBlockRoleActionImpl
 * @see com.liferay.portal.model.ResourceBlockRoleAction
 * @see com.liferay.portal.model.ResourceBlockRoleActionModel
 * @generated
 */
public class ResourceBlockRoleActionModelImpl extends BaseModelImpl<ResourceBlockRoleAction>
	implements ResourceBlockRoleActionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource block role action model instance should use the {@link com.liferay.portal.model.ResourceBlockRoleAction} interface instead.
	 */
	public static final String TABLE_NAME = "ResourceBlockRoleAction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "actionIds", Types.BIGINT },
			{ "resourceBlockId", Types.BIGINT },
			{ "roleId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ResourceBlockRoleAction (actionIds LONG not null,resourceBlockId LONG not null,roleId LONG not null,primary key (actionIds, resourceBlockId, roleId))";
	public static final String TABLE_SQL_DROP = "drop table ResourceBlockRoleAction";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.model.ResourceBlockRoleAction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.model.ResourceBlockRoleAction"),
			true);

	public Class<?> getModelClass() {
		return ResourceBlockRoleAction.class;
	}

	public String getModelClassName() {
		return ResourceBlockRoleAction.class.getName();
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.model.ResourceBlockRoleAction"));

	public ResourceBlockRoleActionModelImpl() {
	}

	public ResourceBlockRoleActionPK getPrimaryKey() {
		return new ResourceBlockRoleActionPK(_actionIds, _resourceBlockId,
			_roleId);
	}

	public void setPrimaryKey(ResourceBlockRoleActionPK primaryKey) {
		setActionIds(primaryKey.actionIds);
		setResourceBlockId(primaryKey.resourceBlockId);
		setRoleId(primaryKey.roleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new ResourceBlockRoleActionPK(_actionIds, _resourceBlockId,
			_roleId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ResourceBlockRoleActionPK)primaryKeyObj);
	}

	public long getActionIds() {
		return _actionIds;
	}

	public void setActionIds(long actionIds) {
		_actionIds = actionIds;
	}

	public long getResourceBlockId() {
		return _resourceBlockId;
	}

	public void setResourceBlockId(long resourceBlockId) {
		_resourceBlockId = resourceBlockId;
	}

	public long getRoleId() {
		return _roleId;
	}

	public void setRoleId(long roleId) {
		_roleId = roleId;
	}

	@Override
	public ResourceBlockRoleAction toEscapedModel() {
		if (isEscapedModel()) {
			return (ResourceBlockRoleAction)this;
		}
		else {
			if (_escapedModelProxy == null) {
				_escapedModelProxy = (ResourceBlockRoleAction)Proxy.newProxyInstance(_classLoader,
						_escapedModelProxyInterfaces,
						new AutoEscapeBeanHandler(this));
			}

			return _escapedModelProxy;
		}
	}

	@Override
	public Object clone() {
		ResourceBlockRoleActionImpl resourceBlockRoleActionImpl = new ResourceBlockRoleActionImpl();

		resourceBlockRoleActionImpl.setActionIds(getActionIds());
		resourceBlockRoleActionImpl.setResourceBlockId(getResourceBlockId());
		resourceBlockRoleActionImpl.setRoleId(getRoleId());

		resourceBlockRoleActionImpl.resetOriginalValues();

		return resourceBlockRoleActionImpl;
	}

	public int compareTo(ResourceBlockRoleAction resourceBlockRoleAction) {
		ResourceBlockRoleActionPK primaryKey = resourceBlockRoleAction.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ResourceBlockRoleAction resourceBlockRoleAction = null;

		try {
			resourceBlockRoleAction = (ResourceBlockRoleAction)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		ResourceBlockRoleActionPK primaryKey = resourceBlockRoleAction.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{actionIds=");
		sb.append(getActionIds());
		sb.append(", resourceBlockId=");
		sb.append(getResourceBlockId());
		sb.append(", roleId=");
		sb.append(getRoleId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.model.ResourceBlockRoleAction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>actionIds</column-name><column-value><![CDATA[");
		sb.append(getActionIds());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourceBlockId</column-name><column-value><![CDATA[");
		sb.append(getResourceBlockId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>roleId</column-name><column-value><![CDATA[");
		sb.append(getRoleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ResourceBlockRoleAction.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ResourceBlockRoleAction.class
		};
	private long _actionIds;
	private long _resourceBlockId;
	private long _roleId;
	private ResourceBlockRoleAction _escapedModelProxy;
}