##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    upgrade.data.access.connection.excludes=\
        src/main/java/com/liferay/journal/wysiwyg/upgrade/JournalWysiwygUpgradeHelper.java