/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.upgrade.recorder;

import com.liferay.portal.kernel.dao.jdbc.util.ConnectionWrapper;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.util.PropsValues;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Objects;

/**
 * @author István András Dézsi
 */
public class UpgradeLogProgressTracker {

	public static Connection getConnectionWrapper(Connection connection) {
		if (!_enabled) {
			return connection;
		}

		return new ConnectionWrapper(connection) {

			@Override
			public Statement createStatement() throws SQLException {
				return _wrap(super.createStatement(), this);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return _wrap(
					super.createStatement(resultSetType, resultSetConcurrency),
					this);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return _wrap(
					super.createStatement(
						resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this);
			}

			@Override
			public CallableStatement prepareCall(String sql)
				throws SQLException {

				return (CallableStatement)_wrap(super.prepareCall(sql), this);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(sql, resultSetType, resultSetConcurrency),
					this);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this);
			}

			@Override
			public PreparedStatement prepareStatement(String sql)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql), this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int autoGeneratedKeys)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, autoGeneratedKeys), this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency),
					this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int[] columnIndexes)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnIndexes), this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, String[] columnNames)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnNames), this);
			}

		};
	}

	public static void start() {
		if (!PropsValues.UPGRADE_LOG_PROGRESS_ENABLED) {
			return;
		}

		_enabled = true;

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Granular progress logging for upgrades is enabled. This may " +
					"decrease performance.");
		}
	}

	public static void stop() {
		_enabled = false;
	}

	private static ResultSet _wrap(
		ResultSet resultSet, Statement statementProxy) {

		if (resultSet == null) {
			return null;
		}

		return (ResultSet)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(),
			new Class<?>[] {ResultSet.class},
			new ResultSetInvocationHandler(resultSet, statementProxy));
	}

	private static Statement _wrap(
		Statement statement, Connection wrapperConnection) {

		if (statement == null) {
			return null;
		}

		Class<?>[] interfaces = null;

		if (statement instanceof CallableStatement) {
			interfaces = new Class<?>[] {CallableStatement.class};
		}
		else if (statement instanceof PreparedStatement) {
			interfaces = new Class<?>[] {PreparedStatement.class};
		}
		else {
			interfaces = new Class<?>[] {Statement.class};
		}

		return (Statement)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(), interfaces,
			new StatementInvocationHandler(statement, wrapperConnection));
	}

	private static final Log _log = LogFactoryUtil.getLog(
		UpgradeLogProgressTracker.class);

	private static volatile boolean _enabled;

	private static class ResultSetInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			if (Objects.equals(method.getName(), "getStatement")) {
				return _statementProxy;
			}

			Object result = null;

			try {
				result = method.invoke(_resultSet, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}

			return result;
		}

		private ResultSetInvocationHandler(
			ResultSet resultSet, Statement statementProxy) {

			_resultSet = resultSet;
			_statementProxy = statementProxy;
		}

		private final ResultSet _resultSet;
		private final Statement _statementProxy;

	}

	private static class StatementInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			if (Objects.equals(method.getName(), "getConnection")) {
				return _wrapperConnection;
			}

			Object result = null;

			try {
				result = method.invoke(_statement, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}

			if (result instanceof ResultSet) {
				return _wrap((ResultSet)result, (Statement)proxy);
			}

			return result;
		}

		private StatementInvocationHandler(
			Statement statement, Connection wrapperConnection) {

			_statement = statement;
			_wrapperConnection = wrapperConnection;
		}

		private final Statement _statement;
		private final Connection _wrapperConnection;

	}

}