/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.upgrade.recorder;

import com.liferay.petra.lang.SafeCloseable;
import com.liferay.petra.string.CharPool;
import com.liferay.petra.string.StringBundler;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.db.DBType;
import com.liferay.portal.kernel.dao.jdbc.DataAccess;
import com.liferay.portal.kernel.dao.jdbc.util.ConnectionWrapper;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.security.auth.CompanyThreadLocal;
import com.liferay.portal.kernel.util.ArrayUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PropsValues;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.InputStream;
import java.io.Reader;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Statement;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Queue;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Supplier;

/**
 * @author István András Dézsi
 */
public class UpgradeLogProgressTracker {

	public static Map<String, Long> getLastKnownProgresses() {
		return Collections.unmodifiableMap(_lastKnownProgresses);
	}

	public static Map<String, Long> getLastKnownTotalCounts() {
		return Collections.unmodifiableMap(_lastKnownTotalCounts);
	}

	public static void start() {
		_lastKnownProgresses.clear();
		_lastKnownTotalCounts.clear();

		if (!PropsValues.UPGRADE_LOG_PROGRESS_ENABLED) {
			return;
		}

		_enabled = true;

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Granular progress logging for upgrades is enabled. This may " +
					"decrease performance.");
		}
	}

	public static void stop() {
		_enabled = false;
	}

	public static Connection wrap(
		Connection connection, String upgradeProcessClassName) {

		if (!_enabled) {
			return connection;
		}

		return new ConnectionWrapper(connection) {

			@Override
			public Statement createStatement() throws SQLException {
				return _wrap(
					null, super.createStatement(), connection,
					upgradeProcessClassName, this);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return _wrap(
					null,
					super.createStatement(resultSetType, resultSetConcurrency),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return _wrap(
					null,
					super.createStatement(
						resultSetType, resultSetConcurrency,
						resultSetHoldability),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public CallableStatement prepareCall(String sql)
				throws SQLException {

				return (CallableStatement)_wrap(
					null, super.prepareCall(sql), connection,
					upgradeProcessClassName, this);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (CallableStatement)_wrap(
					null,
					super.prepareCall(sql, resultSetType, resultSetConcurrency),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (CallableStatement)_wrap(
					null,
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(String sql)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(sql), connection,
					upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int autoGeneratedKeys)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(sql, autoGeneratedKeys), connection,
					upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					connection, upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int[] columnIndexes)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(sql, columnIndexes), connection,
					upgradeProcessClassName, this);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, String[] columnNames)
				throws SQLException {

				return (PreparedStatement)_wrap(
					_prepareCountStatement(connection, sql),
					super.prepareStatement(sql, columnNames), connection,
					upgradeProcessClassName, this);
			}

		};
	}

	private static String _buildCountSQL(String sql) {
		if (Validator.isNull(sql)) {
			return null;
		}

		String lowerSQL = StringUtil.toLowerCase(sql);

		if (!_isSelect(lowerSQL)) {
			return null;
		}

		String stripped = StringUtil.trimTrailing(_stripOrderBy(lowerSQL, sql));

		if (stripped.endsWith(StringPool.SEMICOLON)) {
			stripped = StringUtil.trimTrailing(
				stripped.substring(0, stripped.length() - 1));
		}

		return StringBundler.concat(
			"select count(1) from (", stripped, ") tempCountTable_");
	}

	private static boolean _isSelect(String lowerSQL) {
		String trimmed = lowerSQL.stripLeading();

		if (!trimmed.startsWith("select") ||
			(trimmed.length() == "select".length())) {

			return false;
		}

		char nextChar = trimmed.charAt("select".length());

		if (Character.isWhitespace(nextChar) ||
			(nextChar == CharPool.OPEN_PARENTHESIS)) {

			return true;
		}

		return false;
	}

	private static boolean _isUnsafeSetter(String methodName, Object[] args) {
		if (_unsafeSetters.contains(methodName)) {
			return true;
		}

		if (!Objects.equals(methodName, "setObject") ||
			ArrayUtil.isEmpty(args) || (args.length < 2)) {

			return false;
		}

		Object value = args[1];

		if (value instanceof Blob || value instanceof Clob ||
			value instanceof InputStream || value instanceof NClob ||
			value instanceof Reader || value instanceof SQLXML) {

			return true;
		}

		return false;
	}

	private static PreparedStatement _prepareCountStatement(
		Connection connection, String sql) {

		String countSQL = _buildCountSQL(sql);

		if (countSQL == null) {
			return null;
		}

		try {
			return connection.prepareStatement(countSQL);
		}
		catch (Throwable throwable) {
			if (_log.isDebugEnabled()) {
				_log.debug("Skipping count query for SQL: " + sql, throwable);
			}

			return null;
		}
	}

	private static Long _runCount(PreparedStatement countPreparedStatement) {
		try (SafeCloseable safeCloseable =
				UpgradeSQLRecorder.suppressRecording()) {

			countPreparedStatement.setQueryTimeout(
				_COUNT_QUERY_TIMEOUT_SECONDS);

			_setCancelQueryTimeoutIfSupported(countPreparedStatement);

			try (ResultSet resultSet = countPreparedStatement.executeQuery()) {
				if (resultSet.next()) {
					return resultSet.getLong(1);
				}
			}
		}
		catch (Throwable throwable) {
			if (_log.isDebugEnabled()) {
				_log.debug("Skipping count query", throwable);
			}
		}

		return null;
	}

	private static void _setCancelQueryTimeoutIfSupported(
		PreparedStatement preparedStatement) {

		try {
			if (DBManagerUtil.getDBType() != DBType.SQLSERVER) {
				return;
			}

			Method method = preparedStatement.getClass(
			).getMethod(
				"setCancelQueryTimeout", int.class
			);

			method.invoke(
				preparedStatement, _COUNT_CANCEL_QUERY_TIMEOUT_SECONDS);
		}
		catch (Exception exception) {
			if (_log.isDebugEnabled()) {
				_log.debug("Unable to set cancel query timeout", exception);
			}
		}
	}

	private static String _stripOrderBy(String lowerSQL, String sql) {
		try {
			if (DBManagerUtil.getDBType() != DBType.SQLSERVER) {
				return sql;
			}
		}
		catch (Exception exception) {
			if (_log.isDebugEnabled()) {
				_log.debug("Unable to determine DB type", exception);
			}

			return sql;
		}

		int index = lowerSQL.lastIndexOf(" order by ");

		if (index < 0) {
			return sql;
		}

		return sql.substring(0, index);
	}

	private static Statement _wrap(
		PreparedStatement countPreparedStatement, Statement statement,
		Connection underlyingConnection, String upgradeProcessClassName,
		Connection wrapperConnection) {

		if (statement == null) {
			return null;
		}

		Class<?>[] classes = null;

		if (statement instanceof CallableStatement) {
			classes = new Class<?>[] {CallableStatement.class};
		}
		else if (statement instanceof PreparedStatement) {
			classes = new Class<?>[] {PreparedStatement.class};
		}
		else {
			classes = new Class<?>[] {Statement.class};
		}

		return (Statement)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(), classes,
			new StatementInvocationHandler(
				countPreparedStatement, statement, underlyingConnection,
				upgradeProcessClassName, wrapperConnection));
	}

	private static ResultSet _wrap(
		ResultSet resultSet,
		Queue<ResultSetInvocationHandler> resultSetInvocationHandlers,
		Statement statementProxy, Supplier<Long> totalRowCountSupplier,
		String upgradeProcessClassName) {

		if (resultSet == null) {
			return null;
		}

		return (ResultSet)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(),
			new Class<?>[] {ResultSet.class},
			new ResultSetInvocationHandler(
				resultSet, resultSetInvocationHandlers, statementProxy,
				totalRowCountSupplier, upgradeProcessClassName));
	}

	private static final int _COUNT_CANCEL_QUERY_TIMEOUT_SECONDS = 5;

	private static final int _COUNT_QUERY_TIMEOUT_SECONDS = 10;

	private static final Log _log = LogFactoryUtil.getLog(
		UpgradeLogProgressTracker.class);

	private static volatile boolean _enabled;
	private static final AtomicLong _handlerCounter = new AtomicLong();
	private static final Map<String, Long> _lastKnownProgresses =
		new ConcurrentHashMap<>();
	private static final Map<String, Long> _lastKnownTotalCounts =
		new ConcurrentHashMap<>();
	private static final Set<String> _unsafeSetters = new HashSet<>(
		Arrays.asList(
			"setAsciiStream", "setBinaryStream", "setBlob",
			"setCharacterStream", "setClob", "setNCharacterStream", "setNClob",
			"setSQLXML", "setUnicodeStream"));

	private static class ResultSetInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			String methodName = method.getName();

			if (Objects.equals(methodName, "getStatement")) {
				return _statementProxy;
			}

			Object result = null;

			try {
				result = method.invoke(_resultSet, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}

			if (Objects.equals(methodName, "next") &&
				Objects.equals(result, Boolean.TRUE)) {

				_rowCount++;

				long now = System.currentTimeMillis();

				if ((now - _lastLogTime) >
						PropsValues.UPGRADE_LOG_PROGRESS_INTERVAL) {

					if (!_totalRowCountComputed &&
						(_totalRowCountSupplier != null)) {

						_totalRowCount = GetterUtil.getLong(
							_totalRowCountSupplier.get());
						_totalRowCountComputed = true;
					}

					if ((_totalRowCount > 0) && (_rowCount > _totalRowCount)) {
						_totalRowCount = 0;
						_lastKnownTotalCounts.remove(_registryKey);
					}

					_lastKnownProgresses.put(_registryKey, _rowCount);

					if (_totalRowCount > 0) {
						_lastKnownTotalCounts.put(_registryKey, _totalRowCount);
					}

					if (_log.isInfoEnabled()) {
						if (_totalRowCount > 0) {
							long percentage =
								(_rowCount * 100L) / _totalRowCount;

							_log.info(
								StringBundler.concat(
									_registryKey,
									" is still executing. Processed ",
									_rowCount, " of ", _totalRowCount,
									" rows. (", percentage, "%)"));
						}
						else {
							_log.info(
								StringBundler.concat(
									_registryKey,
									" is still executing. Processed ",
									_rowCount, " rows."));
						}
					}

					_lastLogTime = now;
				}
			}
			else if (Objects.equals(methodName, "close")) {
				_cleanUpRegistry();

				_resultSetInvocationHandlers.remove(this);
			}

			return result;
		}

		private ResultSetInvocationHandler(
			ResultSet resultSet,
			Queue<ResultSetInvocationHandler> resultSetInvocationHandlers,
			Statement statementProxy, Supplier<Long> totalRowCountSupplier,
			String upgradeProcessClassName) {

			_resultSet = resultSet;
			_resultSetInvocationHandlers = resultSetInvocationHandlers;
			_statementProxy = statementProxy;
			_totalRowCountSupplier = totalRowCountSupplier;

			long handlerId = _handlerCounter.incrementAndGet();

			if (PropsValues.DATABASE_PARTITION_ENABLED) {
				_registryKey = StringBundler.concat(
					upgradeProcessClassName, " {companyId=",
					CompanyThreadLocal.getCompanyId(), ", handlerId=",
					handlerId, "}");
			}
			else {
				_registryKey = StringBundler.concat(
					upgradeProcessClassName, " {handlerId=", handlerId, "}");
			}

			_lastLogTime = System.currentTimeMillis();
		}

		private void _cleanUpRegistry() {
			if (_lastKnownProgresses.remove(_registryKey) != null) {
				_lastKnownTotalCounts.remove(_registryKey);

				if (_log.isInfoEnabled()) {
					_log.info(_registryKey + " is finished.");
				}
			}
		}

		private long _lastLogTime;
		private final String _registryKey;
		private final ResultSet _resultSet;
		private final Queue<ResultSetInvocationHandler>
			_resultSetInvocationHandlers;
		private long _rowCount;
		private final Statement _statementProxy;
		private long _totalRowCount;
		private boolean _totalRowCountComputed;
		private final Supplier<Long> _totalRowCountSupplier;

	}

	private static class StatementInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			String methodName = method.getName();

			if (Objects.equals(methodName, "getConnection")) {
				return _wrapperConnection;
			}

			if (PreparedStatement.class.equals(method.getDeclaringClass())) {
				if (Objects.equals(methodName, "clearParameters")) {
					Object result = _delegate(method, args);

					if (_countPreparedStatement != null) {
						try {
							method.invoke(_countPreparedStatement, args);
						}
						catch (Throwable throwable) {
							_cleanUpCountStatement(throwable);
						}
					}

					_hasUnsafeBinding = false;

					return result;
				}

				if (methodName.startsWith("set")) {
					Object result = _delegate(method, args);

					if (_countPreparedStatement == null) {
						return result;
					}

					if (_isUnsafeSetter(methodName, args)) {
						_hasUnsafeBinding = true;
					}
					else {
						try {
							method.invoke(_countPreparedStatement, args);
						}
						catch (Throwable throwable) {
							_cleanUpCountStatement(throwable);
						}
					}

					return result;
				}
			}

			if (Objects.equals(methodName, "executeQuery")) {
				if (ArrayUtil.isEmpty(args)) {
					Supplier<Long> totalRowCountSupplier = null;

					if ((_countPreparedStatement != null) &&
						!_hasUnsafeBinding) {

						PreparedStatement countPreparedStatement =
							_countPreparedStatement;

						totalRowCountSupplier = () -> _runCount(
							countPreparedStatement);
					}

					return _delegateAndWrap(
						proxy, method, args, totalRowCountSupplier);
				}

				if ((args.length == 1) && (args[0] instanceof String)) {
					String sql = (String)args[0];

					Supplier<Long> totalRowCountSupplier =
						() -> _runCountForSQL(sql);

					return _delegateAndWrap(
						proxy, method, args, totalRowCountSupplier);
				}
			}

			if (Objects.equals(methodName, "close")) {
				DataAccess.cleanUp(_countPreparedStatement);

				_countPreparedStatement = null;

				for (ResultSetInvocationHandler resultSetInvocationHandler :
						_resultSetInvocationHandlers) {

					resultSetInvocationHandler._cleanUpRegistry();
				}

				_resultSetInvocationHandlers.clear();

				return _delegate(method, args);
			}

			return _delegateAndWrap(proxy, method, args, null);
		}

		private StatementInvocationHandler(
			PreparedStatement countPreparedStatement, Statement statement,
			Connection underlyingConnection, String upgradeProcessClassName,
			Connection wrapperConnection) {

			_countPreparedStatement = countPreparedStatement;
			_statement = statement;
			_underlyingConnection = underlyingConnection;
			_upgradeProcessClassName = upgradeProcessClassName;
			_wrapperConnection = wrapperConnection;
		}

		private void _cleanUpCountStatement(Throwable throwable) {
			if (_log.isDebugEnabled()) {
				_log.debug(
					"Disabling count query after mirror failure", throwable);
			}

			DataAccess.cleanUp(_countPreparedStatement);

			_countPreparedStatement = null;
		}

		private Object _delegate(Method method, Object[] args)
			throws Throwable {

			try {
				return method.invoke(_statement, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}
		}

		private Object _delegateAndWrap(
				Object proxy, Method method, Object[] args,
				Supplier<Long> totalRowCountSupplier)
			throws Throwable {

			Object result = _delegate(method, args);

			if (result instanceof ResultSet) {
				ResultSet wrappedResultSet = _wrap(
					(ResultSet)result, _resultSetInvocationHandlers,
					(Statement)proxy, totalRowCountSupplier,
					_upgradeProcessClassName);

				_resultSetInvocationHandlers.add(
					(ResultSetInvocationHandler)ProxyUtil.getInvocationHandler(
						wrappedResultSet));

				return wrappedResultSet;
			}

			return result;
		}

		private Long _runCountForSQL(String sql) {
			Long totalRowCount = null;

			try (PreparedStatement countPreparedStatement =
					_prepareCountStatement(_underlyingConnection, sql)) {

				if (countPreparedStatement != null) {
					totalRowCount = _runCount(countPreparedStatement);
				}
			}
			catch (SQLException sqlException) {
				if (_log.isDebugEnabled()) {
					_log.debug("Failed to close count statement", sqlException);
				}
			}

			return totalRowCount;
		}

		private PreparedStatement _countPreparedStatement;
		private boolean _hasUnsafeBinding;
		private final Queue<ResultSetInvocationHandler>
			_resultSetInvocationHandlers = new ConcurrentLinkedQueue<>();
		private final Statement _statement;
		private final Connection _underlyingConnection;
		private final String _upgradeProcessClassName;
		private final Connection _wrapperConnection;

	}

}