create index IX_E2B60C14 on FragmentCollection (groupId, ctCollectionId);
create unique index IX_7FA4CEC9 on FragmentCollection (groupId, fragmentCollectionKey[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_4F415D53 on FragmentCollection (groupId, name[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_B34B88C6 on FragmentCollection (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_F197401E on FragmentCollection (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_3244548 on FragmentCollection (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);

create index IX_A86D5F3B on FragmentComposition (fragmentCollectionId, ctCollectionId);
create index IX_6588F8A8 on FragmentComposition (groupId, ctCollectionId);
create index IX_5F3FEBA5 on FragmentComposition (groupId, fragmentCollectionId, ctCollectionId);
create index IX_50F8C24 on FragmentComposition (groupId, fragmentCollectionId, name[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_1918190A on FragmentComposition (groupId, fragmentCollectionId, name[$COLUMN_LENGTH:75$], status, ctCollectionId);
create index IX_5EF5678B on FragmentComposition (groupId, fragmentCollectionId, status, ctCollectionId);
create unique index IX_3F7591A1 on FragmentComposition (groupId, fragmentCompositionKey[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_2B7782B2 on FragmentComposition (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_C3A441B2 on FragmentComposition (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_B39DCA34 on FragmentComposition (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);

create index IX_18964A03 on FragmentEntry (fragmentCollectionId, ctCollectionId);
create index IX_DDB6278B on FragmentEntry (fragmentCollectionId, status);
create index IX_C25228E0 on FragmentEntry (groupId, ctCollectionId);
create index IX_96DEA1DD on FragmentEntry (groupId, fragmentCollectionId, ctCollectionId);
create index IX_CEAAB85C on FragmentEntry (groupId, fragmentCollectionId, name[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_49BF8D42 on FragmentEntry (groupId, fragmentCollectionId, name[$COLUMN_LENGTH:75$], status, ctCollectionId);
create index IX_2E7665C3 on FragmentEntry (groupId, fragmentCollectionId, status, ctCollectionId);
create index IX_2A7A0DD4 on FragmentEntry (groupId, fragmentCollectionId, type_, ctCollectionId);
create index IX_9F7DEABA on FragmentEntry (groupId, fragmentCollectionId, type_, status, ctCollectionId);
create unique index IX_67941F11 on FragmentEntry (groupId, fragmentEntryKey[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_5615117A on FragmentEntry (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_D2EC1FEA on FragmentEntry (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_4606AFC on FragmentEntry (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);

create index IX_6AFFBB89 on FragmentEntryLink (fragmentEntryId, ctCollectionId);
create index IX_932B7FDB on FragmentEntryLink (groupId, classNameId, classPK, ctCollectionId);
create index IX_7AB5A586 on FragmentEntryLink (groupId, ctCollectionId);
create index IX_B7BFD778 on FragmentEntryLink (groupId, fragmentEntryId, classNameId, classPK, ctCollectionId);
create index IX_4C1EB947 on FragmentEntryLink (groupId, fragmentEntryId, classNameId, ctCollectionId);
create index IX_25790E3 on FragmentEntryLink (groupId, fragmentEntryId, ctCollectionId);
create index IX_28F091A8 on FragmentEntryLink (rendererKey[$COLUMN_LENGTH:200$], ctCollectionId);
create index IX_577C6F94 on FragmentEntryLink (uuid_[$COLUMN_LENGTH:75$], companyId, ctCollectionId);
create index IX_83328E10 on FragmentEntryLink (uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create unique index IX_145C8796 on FragmentEntryLink (uuid_[$COLUMN_LENGTH:75$], groupId, ctCollectionId);