spring.cache.type=simple

liferay.oauth.urls.excludes=/ready,/server

liferay.oauth.application.external.reference.codes=\
    liferay-stream-hub-etc-spring-boot-oauth-application-user-agent,\
    liferay-stream-hub-etc-spring-boot-oauth-application-server

main.liferay.agent.oauth.application=liferay-stream-hub-etc-spring-boot-oauth-application-user-agent
main.liferay.server.oauth.application liferay-stream-hub-etc-spring-boot-oauth-application-server

# Liferay LXC DXP Configuration
com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.main.domain=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

# OAuth2 Server Configuration
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.authorization.uri=/o/oauth2/authorize
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.headless.server.audience=http://localhost:3000
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.headless.server.client.id=id-8af16499-1156-4d42-ed4e-35a39158016
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.headless.server.client.secret=secret-c1f29b75-b3ed-9323-c6dc-374f5f8be4db

liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.headless.server.scopes=\
    Liferay.Headless.Admin.User.everything.read,\
    Liferay.Object.Admin.REST.everything,\
    c_message.everything,\
    c_chatbot.everything,\
    liferay-json-web-services.everything

liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.introspection.uri=/o/oauth2/introspect
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.jwks.uri=/o/oauth2/jwks
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.redirect.uris=/o/oauth2/redirect
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.token.uri=/o/oauth2/token
liferay-stream-hub-etc-spring-boot-oauth-application-server.oauth2.home.page.uri=http://localhost:3000

# OAuth2 User Agent Configuration
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.authorization.uri=/o/oauth2/authorize
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.introspection.uri=/o/oauth2/introspect
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.jwks.uri=/o/oauth2/jwks
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.redirect.uris=/o/oauth2/redirect
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.token.uri=/o/oauth2/token
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.user.agent.audience=http://localhost:3000
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.user.agent.client.id=id-f69cfe27-e73f-b259-a432-6721f544ede
liferay-stream-hub-etc-spring-boot-oauth-application-user-agent.oauth2.home.page.uri=http://localhost:3000
#
# Spring Boot
#
server.port=3000
socket.path=/server