##
## Test Suites
##

    modified.files.includes[relevant][object-entry-folder-rest-test-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    modified.files.includes[relevant][object-entry-folder-rest-test-playwright-rule]=**
    relevant.rule.names=object-entry-folder-rest-test-java-rule

    test.batch.names[relevant][object-entry-folder-rest-test-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][object-entry-folder-rest-test-java-rule]=\
        **/object/object-rest-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][object-entry-folder-rest-test-java-rule]=\
        **/object/object-rest-test/**/src/test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Object Entries REST APIs