/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.CompanyScopedEntry;
import com.liferay.portal.tools.service.builder.test.service.CompanyScopedEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.persistence.CompanyScopedEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the company scoped entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.CompanyScopedEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.CompanyScopedEntryLocalServiceImpl
 * @generated
 */
public abstract class CompanyScopedEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements CompanyScopedEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CompanyScopedEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.CompanyScopedEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the company scoped entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CompanyScopedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param companyScopedEntry the company scoped entry
	 * @return the company scoped entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CompanyScopedEntry addCompanyScopedEntry(
		CompanyScopedEntry companyScopedEntry) {

		companyScopedEntry.setNew(true);

		return companyScopedEntryPersistence.update(companyScopedEntry);
	}

	/**
	 * Creates a new company scoped entry with the primary key. Does not add the company scoped entry to the database.
	 *
	 * @param CompanyScopedEntryId the primary key for the new company scoped entry
	 * @return the new company scoped entry
	 */
	@Override
	@Transactional(enabled = false)
	public CompanyScopedEntry createCompanyScopedEntry(
		long CompanyScopedEntryId) {

		return companyScopedEntryPersistence.create(CompanyScopedEntryId);
	}

	/**
	 * Deletes the company scoped entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CompanyScopedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param CompanyScopedEntryId the primary key of the company scoped entry
	 * @return the company scoped entry that was removed
	 * @throws PortalException if a company scoped entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CompanyScopedEntry deleteCompanyScopedEntry(
			long CompanyScopedEntryId)
		throws PortalException {

		return companyScopedEntryPersistence.remove(CompanyScopedEntryId);
	}

	/**
	 * Deletes the company scoped entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CompanyScopedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param companyScopedEntry the company scoped entry
	 * @return the company scoped entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CompanyScopedEntry deleteCompanyScopedEntry(
		CompanyScopedEntry companyScopedEntry) {

		return companyScopedEntryPersistence.remove(companyScopedEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return companyScopedEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CompanyScopedEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return companyScopedEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CompanyScopedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return companyScopedEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CompanyScopedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return companyScopedEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return companyScopedEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return companyScopedEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CompanyScopedEntry fetchCompanyScopedEntry(
		long CompanyScopedEntryId) {

		return companyScopedEntryPersistence.fetchByPrimaryKey(
			CompanyScopedEntryId);
	}

	/**
	 * Returns the company scoped entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the company scoped entry's external reference code
	 * @return the matching company scoped entry, or <code>null</code> if a matching company scoped entry could not be found
	 */
	@Override
	public CompanyScopedEntry fetchCompanyScopedEntryByReferenceCode(
		long companyId, String externalReferenceCode) {

		return companyScopedEntryPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the company scoped entry with the primary key.
	 *
	 * @param CompanyScopedEntryId the primary key of the company scoped entry
	 * @return the company scoped entry
	 * @throws PortalException if a company scoped entry with the primary key could not be found
	 */
	@Override
	public CompanyScopedEntry getCompanyScopedEntry(long CompanyScopedEntryId)
		throws PortalException {

		return companyScopedEntryPersistence.findByPrimaryKey(
			CompanyScopedEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			companyScopedEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CompanyScopedEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CompanyScopedEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			companyScopedEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CompanyScopedEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"CompanyScopedEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			companyScopedEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CompanyScopedEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CompanyScopedEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return companyScopedEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return companyScopedEntryLocalService.deleteCompanyScopedEntry(
			(CompanyScopedEntry)persistedModel);
	}

	@Override
	public BasePersistence<CompanyScopedEntry> getBasePersistence() {
		return companyScopedEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return companyScopedEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the company scoped entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.CompanyScopedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of company scoped entries
	 * @param end the upper bound of the range of company scoped entries (not inclusive)
	 * @return the range of company scoped entries
	 */
	@Override
	public List<CompanyScopedEntry> getCompanyScopedEntries(
		int start, int end) {

		return companyScopedEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of company scoped entries.
	 *
	 * @return the number of company scoped entries
	 */
	@Override
	public int getCompanyScopedEntriesCount() {
		return companyScopedEntryPersistence.countAll();
	}

	/**
	 * Updates the company scoped entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CompanyScopedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param companyScopedEntry the company scoped entry
	 * @return the company scoped entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CompanyScopedEntry updateCompanyScopedEntry(
		CompanyScopedEntry companyScopedEntry) {

		return companyScopedEntryPersistence.update(companyScopedEntry);
	}

	/**
	 * Returns the company scoped entry local service.
	 *
	 * @return the company scoped entry local service
	 */
	public CompanyScopedEntryLocalService getCompanyScopedEntryLocalService() {
		return companyScopedEntryLocalService;
	}

	/**
	 * Sets the company scoped entry local service.
	 *
	 * @param companyScopedEntryLocalService the company scoped entry local service
	 */
	public void setCompanyScopedEntryLocalService(
		CompanyScopedEntryLocalService companyScopedEntryLocalService) {

		this.companyScopedEntryLocalService = companyScopedEntryLocalService;
	}

	/**
	 * Returns the company scoped entry persistence.
	 *
	 * @return the company scoped entry persistence
	 */
	public CompanyScopedEntryPersistence getCompanyScopedEntryPersistence() {
		return companyScopedEntryPersistence;
	}

	/**
	 * Sets the company scoped entry persistence.
	 *
	 * @param companyScopedEntryPersistence the company scoped entry persistence
	 */
	public void setCompanyScopedEntryPersistence(
		CompanyScopedEntryPersistence companyScopedEntryPersistence) {

		this.companyScopedEntryPersistence = companyScopedEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.CompanyScopedEntry",
			companyScopedEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.CompanyScopedEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CompanyScopedEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CompanyScopedEntry.class;
	}

	protected String getModelClassName() {
		return CompanyScopedEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				companyScopedEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = CompanyScopedEntryLocalService.class)
	protected CompanyScopedEntryLocalService companyScopedEntryLocalService;

	@BeanReference(type = CompanyScopedEntryPersistence.class)
	protected CompanyScopedEntryPersistence companyScopedEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}