/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.CompanyScopedEntry;
import com.liferay.portal.tools.service.builder.test.service.CompanyScopedEntryService;
import com.liferay.portal.tools.service.builder.test.service.persistence.CompanyScopedEntryPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the company scoped entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.CompanyScopedEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.CompanyScopedEntryServiceImpl
 * @generated
 */
public abstract class CompanyScopedEntryServiceBaseImpl
	extends BaseServiceImpl
	implements CompanyScopedEntryService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CompanyScopedEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.CompanyScopedEntryServiceUtil</code>.
	 */

	/**
	 * Returns the company scoped entry local service.
	 *
	 * @return the company scoped entry local service
	 */
	public com.liferay.portal.tools.service.builder.test.service.
		CompanyScopedEntryLocalService getCompanyScopedEntryLocalService() {

		return companyScopedEntryLocalService;
	}

	/**
	 * Sets the company scoped entry local service.
	 *
	 * @param companyScopedEntryLocalService the company scoped entry local service
	 */
	public void setCompanyScopedEntryLocalService(
		com.liferay.portal.tools.service.builder.test.service.
			CompanyScopedEntryLocalService companyScopedEntryLocalService) {

		this.companyScopedEntryLocalService = companyScopedEntryLocalService;
	}

	/**
	 * Returns the company scoped entry remote service.
	 *
	 * @return the company scoped entry remote service
	 */
	public CompanyScopedEntryService getCompanyScopedEntryService() {
		return companyScopedEntryService;
	}

	/**
	 * Sets the company scoped entry remote service.
	 *
	 * @param companyScopedEntryService the company scoped entry remote service
	 */
	public void setCompanyScopedEntryService(
		CompanyScopedEntryService companyScopedEntryService) {

		this.companyScopedEntryService = companyScopedEntryService;
	}

	/**
	 * Returns the company scoped entry persistence.
	 *
	 * @return the company scoped entry persistence
	 */
	public CompanyScopedEntryPersistence getCompanyScopedEntryPersistence() {
		return companyScopedEntryPersistence;
	}

	/**
	 * Sets the company scoped entry persistence.
	 *
	 * @param companyScopedEntryPersistence the company scoped entry persistence
	 */
	public void setCompanyScopedEntryPersistence(
		CompanyScopedEntryPersistence companyScopedEntryPersistence) {

		this.companyScopedEntryPersistence = companyScopedEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CompanyScopedEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CompanyScopedEntry.class;
	}

	protected String getModelClassName() {
		return CompanyScopedEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				companyScopedEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.portal.tools.service.builder.test.service.CompanyScopedEntryLocalService.class
	)
	protected com.liferay.portal.tools.service.builder.test.service.
		CompanyScopedEntryLocalService companyScopedEntryLocalService;

	@BeanReference(type = CompanyScopedEntryService.class)
	protected CompanyScopedEntryService companyScopedEntryService;

	@BeanReference(type = CompanyScopedEntryPersistence.class)
	protected CompanyScopedEntryPersistence companyScopedEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}