/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.DefaultScopedEntry;
import com.liferay.portal.tools.service.builder.test.service.DefaultScopedEntryService;
import com.liferay.portal.tools.service.builder.test.service.persistence.DefaultScopedEntryPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the default scoped entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.DefaultScopedEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.DefaultScopedEntryServiceImpl
 * @generated
 */
public abstract class DefaultScopedEntryServiceBaseImpl
	extends BaseServiceImpl
	implements DefaultScopedEntryService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DefaultScopedEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.DefaultScopedEntryServiceUtil</code>.
	 */

	/**
	 * Returns the default scoped entry local service.
	 *
	 * @return the default scoped entry local service
	 */
	public com.liferay.portal.tools.service.builder.test.service.
		DefaultScopedEntryLocalService getDefaultScopedEntryLocalService() {

		return defaultScopedEntryLocalService;
	}

	/**
	 * Sets the default scoped entry local service.
	 *
	 * @param defaultScopedEntryLocalService the default scoped entry local service
	 */
	public void setDefaultScopedEntryLocalService(
		com.liferay.portal.tools.service.builder.test.service.
			DefaultScopedEntryLocalService defaultScopedEntryLocalService) {

		this.defaultScopedEntryLocalService = defaultScopedEntryLocalService;
	}

	/**
	 * Returns the default scoped entry remote service.
	 *
	 * @return the default scoped entry remote service
	 */
	public DefaultScopedEntryService getDefaultScopedEntryService() {
		return defaultScopedEntryService;
	}

	/**
	 * Sets the default scoped entry remote service.
	 *
	 * @param defaultScopedEntryService the default scoped entry remote service
	 */
	public void setDefaultScopedEntryService(
		DefaultScopedEntryService defaultScopedEntryService) {

		this.defaultScopedEntryService = defaultScopedEntryService;
	}

	/**
	 * Returns the default scoped entry persistence.
	 *
	 * @return the default scoped entry persistence
	 */
	public DefaultScopedEntryPersistence getDefaultScopedEntryPersistence() {
		return defaultScopedEntryPersistence;
	}

	/**
	 * Sets the default scoped entry persistence.
	 *
	 * @param defaultScopedEntryPersistence the default scoped entry persistence
	 */
	public void setDefaultScopedEntryPersistence(
		DefaultScopedEntryPersistence defaultScopedEntryPersistence) {

		this.defaultScopedEntryPersistence = defaultScopedEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DefaultScopedEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DefaultScopedEntry.class;
	}

	protected String getModelClassName() {
		return DefaultScopedEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				defaultScopedEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.portal.tools.service.builder.test.service.DefaultScopedEntryLocalService.class
	)
	protected com.liferay.portal.tools.service.builder.test.service.
		DefaultScopedEntryLocalService defaultScopedEntryLocalService;

	@BeanReference(type = DefaultScopedEntryService.class)
	protected DefaultScopedEntryService defaultScopedEntryService;

	@BeanReference(type = DefaultScopedEntryPersistence.class)
	protected DefaultScopedEntryPersistence defaultScopedEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}