/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity;
import com.liferay.portal.tools.service.builder.test.service.ManyColumnsEntityLocalService;
import com.liferay.portal.tools.service.builder.test.service.persistence.ManyColumnsEntityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the many columns entity local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.ManyColumnsEntityLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.ManyColumnsEntityLocalServiceImpl
 * @generated
 */
public abstract class ManyColumnsEntityLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, ManyColumnsEntityLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ManyColumnsEntityLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.ManyColumnsEntityLocalServiceUtil</code>.
	 */

	/**
	 * Adds the many columns entity to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManyColumnsEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param manyColumnsEntity the many columns entity
	 * @return the many columns entity that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ManyColumnsEntity addManyColumnsEntity(
		ManyColumnsEntity manyColumnsEntity) {

		manyColumnsEntity.setNew(true);

		return manyColumnsEntityPersistence.update(manyColumnsEntity);
	}

	/**
	 * Creates a new many columns entity with the primary key. Does not add the many columns entity to the database.
	 *
	 * @param manyColumnsEntityId the primary key for the new many columns entity
	 * @return the new many columns entity
	 */
	@Override
	@Transactional(enabled = false)
	public ManyColumnsEntity createManyColumnsEntity(long manyColumnsEntityId) {
		return manyColumnsEntityPersistence.create(manyColumnsEntityId);
	}

	/**
	 * Deletes the many columns entity with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManyColumnsEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param manyColumnsEntityId the primary key of the many columns entity
	 * @return the many columns entity that was removed
	 * @throws PortalException if a many columns entity with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ManyColumnsEntity deleteManyColumnsEntity(long manyColumnsEntityId)
		throws PortalException {

		return manyColumnsEntityPersistence.remove(manyColumnsEntityId);
	}

	/**
	 * Deletes the many columns entity from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManyColumnsEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param manyColumnsEntity the many columns entity
	 * @return the many columns entity that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ManyColumnsEntity deleteManyColumnsEntity(
		ManyColumnsEntity manyColumnsEntity) {

		return manyColumnsEntityPersistence.remove(manyColumnsEntity);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return manyColumnsEntityPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ManyColumnsEntity.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return manyColumnsEntityPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ManyColumnsEntityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return manyColumnsEntityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ManyColumnsEntityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return manyColumnsEntityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return manyColumnsEntityPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return manyColumnsEntityPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ManyColumnsEntity fetchManyColumnsEntity(long manyColumnsEntityId) {
		return manyColumnsEntityPersistence.fetchByPrimaryKey(
			manyColumnsEntityId);
	}

	/**
	 * Returns the many columns entity with the primary key.
	 *
	 * @param manyColumnsEntityId the primary key of the many columns entity
	 * @return the many columns entity
	 * @throws PortalException if a many columns entity with the primary key could not be found
	 */
	@Override
	public ManyColumnsEntity getManyColumnsEntity(long manyColumnsEntityId)
		throws PortalException {

		return manyColumnsEntityPersistence.findByPrimaryKey(
			manyColumnsEntityId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			manyColumnsEntityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ManyColumnsEntity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("manyColumnsEntityId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			manyColumnsEntityLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ManyColumnsEntity.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"manyColumnsEntityId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			manyColumnsEntityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ManyColumnsEntity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("manyColumnsEntityId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return manyColumnsEntityPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return manyColumnsEntityLocalService.deleteManyColumnsEntity(
			(ManyColumnsEntity)persistedModel);
	}

	public BasePersistence<ManyColumnsEntity> getBasePersistence() {
		return manyColumnsEntityPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return manyColumnsEntityPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the many columns entities.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ManyColumnsEntityModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of many columns entities
	 * @param end the upper bound of the range of many columns entities (not inclusive)
	 * @return the range of many columns entities
	 */
	@Override
	public List<ManyColumnsEntity> getManyColumnsEntities(int start, int end) {
		return manyColumnsEntityPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of many columns entities.
	 *
	 * @return the number of many columns entities
	 */
	@Override
	public int getManyColumnsEntitiesCount() {
		return manyColumnsEntityPersistence.countAll();
	}

	/**
	 * Updates the many columns entity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManyColumnsEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param manyColumnsEntity the many columns entity
	 * @return the many columns entity that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ManyColumnsEntity updateManyColumnsEntity(
		ManyColumnsEntity manyColumnsEntity) {

		return manyColumnsEntityPersistence.update(manyColumnsEntity);
	}

	/**
	 * Returns the many columns entity local service.
	 *
	 * @return the many columns entity local service
	 */
	public ManyColumnsEntityLocalService getManyColumnsEntityLocalService() {
		return manyColumnsEntityLocalService;
	}

	/**
	 * Sets the many columns entity local service.
	 *
	 * @param manyColumnsEntityLocalService the many columns entity local service
	 */
	public void setManyColumnsEntityLocalService(
		ManyColumnsEntityLocalService manyColumnsEntityLocalService) {

		this.manyColumnsEntityLocalService = manyColumnsEntityLocalService;
	}

	/**
	 * Returns the many columns entity persistence.
	 *
	 * @return the many columns entity persistence
	 */
	public ManyColumnsEntityPersistence getManyColumnsEntityPersistence() {
		return manyColumnsEntityPersistence;
	}

	/**
	 * Sets the many columns entity persistence.
	 *
	 * @param manyColumnsEntityPersistence the many columns entity persistence
	 */
	public void setManyColumnsEntityPersistence(
		ManyColumnsEntityPersistence manyColumnsEntityPersistence) {

		this.manyColumnsEntityPersistence = manyColumnsEntityPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity",
			manyColumnsEntityLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ManyColumnsEntityLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ManyColumnsEntity.class;
	}

	protected String getModelClassName() {
		return ManyColumnsEntity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				manyColumnsEntityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = ManyColumnsEntityLocalService.class)
	protected ManyColumnsEntityLocalService manyColumnsEntityLocalService;

	@BeanReference(type = ManyColumnsEntityPersistence.class)
	protected ManyColumnsEntityPersistence manyColumnsEntityPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}