/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity;
import com.liferay.portal.tools.service.builder.test.service.ManyColumnsEntityService;
import com.liferay.portal.tools.service.builder.test.service.persistence.ManyColumnsEntityPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the many columns entity remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.ManyColumnsEntityServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.ManyColumnsEntityServiceImpl
 * @generated
 */
public abstract class ManyColumnsEntityServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, ManyColumnsEntityService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ManyColumnsEntityService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.ManyColumnsEntityServiceUtil</code>.
	 */

	/**
	 * Returns the many columns entity local service.
	 *
	 * @return the many columns entity local service
	 */
	public com.liferay.portal.tools.service.builder.test.service.
		ManyColumnsEntityLocalService getManyColumnsEntityLocalService() {

		return manyColumnsEntityLocalService;
	}

	/**
	 * Sets the many columns entity local service.
	 *
	 * @param manyColumnsEntityLocalService the many columns entity local service
	 */
	public void setManyColumnsEntityLocalService(
		com.liferay.portal.tools.service.builder.test.service.
			ManyColumnsEntityLocalService manyColumnsEntityLocalService) {

		this.manyColumnsEntityLocalService = manyColumnsEntityLocalService;
	}

	/**
	 * Returns the many columns entity remote service.
	 *
	 * @return the many columns entity remote service
	 */
	public ManyColumnsEntityService getManyColumnsEntityService() {
		return manyColumnsEntityService;
	}

	/**
	 * Sets the many columns entity remote service.
	 *
	 * @param manyColumnsEntityService the many columns entity remote service
	 */
	public void setManyColumnsEntityService(
		ManyColumnsEntityService manyColumnsEntityService) {

		this.manyColumnsEntityService = manyColumnsEntityService;
	}

	/**
	 * Returns the many columns entity persistence.
	 *
	 * @return the many columns entity persistence
	 */
	public ManyColumnsEntityPersistence getManyColumnsEntityPersistence() {
		return manyColumnsEntityPersistence;
	}

	/**
	 * Sets the many columns entity persistence.
	 *
	 * @param manyColumnsEntityPersistence the many columns entity persistence
	 */
	public void setManyColumnsEntityPersistence(
		ManyColumnsEntityPersistence manyColumnsEntityPersistence) {

		this.manyColumnsEntityPersistence = manyColumnsEntityPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ManyColumnsEntityService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ManyColumnsEntity.class;
	}

	protected String getModelClassName() {
		return ManyColumnsEntity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				manyColumnsEntityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.portal.tools.service.builder.test.service.ManyColumnsEntityLocalService.class
	)
	protected com.liferay.portal.tools.service.builder.test.service.
		ManyColumnsEntityLocalService manyColumnsEntityLocalService;

	@BeanReference(type = ManyColumnsEntityService.class)
	protected ManyColumnsEntityService manyColumnsEntityService;

	@BeanReference(type = ManyColumnsEntityPersistence.class)
	protected ManyColumnsEntityPersistence manyColumnsEntityPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}