logging.level.com.easy.service=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
oauth.application.externalReferenceCode=easy-oauth-application-user-agent
oauth.application.uri=http://localhost:8080/o/oauth2/application
oauth.jwks.uri=http://localhost:8080/o/oauth2/jwks
server.port=58081