/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the EagerBlobEntity service. Represents a row in the &quot;EagerBlobEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerBlobEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerBlobEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerBlobEntity
 * @generated
 */
@ProviderType
public interface EagerBlobEntityModel
	extends BaseModel<EagerBlobEntity>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eager blob entity model instance should use the {@link EagerBlobEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this eager blob entity.
	 *
	 * @return the primary key of this eager blob entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eager blob entity.
	 *
	 * @param primaryKey the primary key of this eager blob entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this eager blob entity.
	 *
	 * @return the uuid of this eager blob entity
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this eager blob entity.
	 *
	 * @param uuid the uuid of this eager blob entity
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the eager blob entity ID of this eager blob entity.
	 *
	 * @return the eager blob entity ID of this eager blob entity
	 */
	public long getEagerBlobEntityId();

	/**
	 * Sets the eager blob entity ID of this eager blob entity.
	 *
	 * @param eagerBlobEntityId the eager blob entity ID of this eager blob entity
	 */
	public void setEagerBlobEntityId(long eagerBlobEntityId);

	/**
	 * Returns the group ID of this eager blob entity.
	 *
	 * @return the group ID of this eager blob entity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this eager blob entity.
	 *
	 * @param groupId the group ID of this eager blob entity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this eager blob entity.
	 *
	 * @return the company ID of this eager blob entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this eager blob entity.
	 *
	 * @param companyId the company ID of this eager blob entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this eager blob entity.
	 *
	 * @return the user ID of this eager blob entity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this eager blob entity.
	 *
	 * @param userId the user ID of this eager blob entity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this eager blob entity.
	 *
	 * @return the user uuid of this eager blob entity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this eager blob entity.
	 *
	 * @param userUuid the user uuid of this eager blob entity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this eager blob entity.
	 *
	 * @return the user name of this eager blob entity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this eager blob entity.
	 *
	 * @param userName the user name of this eager blob entity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this eager blob entity.
	 *
	 * @return the create date of this eager blob entity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this eager blob entity.
	 *
	 * @param createDate the create date of this eager blob entity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this eager blob entity.
	 *
	 * @return the modified date of this eager blob entity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this eager blob entity.
	 *
	 * @param modifiedDate the modified date of this eager blob entity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this eager blob entity.
	 *
	 * @return the field1 of this eager blob entity
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this eager blob entity.
	 *
	 * @param field1 the field1 of this eager blob entity
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this eager blob entity.
	 *
	 * @return the field2 of this eager blob entity
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this eager blob entity is field2.
	 *
	 * @return <code>true</code> if this eager blob entity is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this eager blob entity is field2.
	 *
	 * @param field2 the field2 of this eager blob entity
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this eager blob entity.
	 *
	 * @return the field3 of this eager blob entity
	 */
	public int getField3();

	/**
	 * Sets the field3 of this eager blob entity.
	 *
	 * @param field3 the field3 of this eager blob entity
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this eager blob entity.
	 *
	 * @return the field4 of this eager blob entity
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this eager blob entity.
	 *
	 * @param field4 the field4 of this eager blob entity
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this eager blob entity.
	 *
	 * @return the field5 of this eager blob entity
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this eager blob entity.
	 *
	 * @param field5 the field5 of this eager blob entity
	 */
	public void setField5(String field5);

	/**
	 * Returns the field blob of this eager blob entity.
	 *
	 * @return the field blob of this eager blob entity
	 */
	public Blob getFieldBlob();

	/**
	 * Sets the field blob of this eager blob entity.
	 *
	 * @param fieldBlob the field blob of this eager blob entity
	 */
	public void setFieldBlob(Blob fieldBlob);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EagerBlobEntity eagerBlobEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EagerBlobEntity> toCacheModel();

	@Override
	public EagerBlobEntity toEscapedModel();

	@Override
	public EagerBlobEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}