/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GroupScopedEntry service. Represents a row in the &quot;GroupScopedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.GroupScopedEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.GroupScopedEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GroupScopedEntry
 * @generated
 */
@ProviderType
public interface GroupScopedEntryModel
	extends BaseModel<GroupScopedEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a group scoped entry model instance should use the {@link GroupScopedEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this group scoped entry.
	 *
	 * @return the primary key of this group scoped entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this group scoped entry.
	 *
	 * @param primaryKey the primary key of this group scoped entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the external reference code of this group scoped entry.
	 *
	 * @return the external reference code of this group scoped entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this group scoped entry.
	 *
	 * @param externalReferenceCode the external reference code of this group scoped entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the group scoped entry ID of this group scoped entry.
	 *
	 * @return the group scoped entry ID of this group scoped entry
	 */
	public long getGroupScopedEntryId();

	/**
	 * Sets the group scoped entry ID of this group scoped entry.
	 *
	 * @param GroupScopedEntryId the group scoped entry ID of this group scoped entry
	 */
	public void setGroupScopedEntryId(long GroupScopedEntryId);

	/**
	 * Returns the company ID of this group scoped entry.
	 *
	 * @return the company ID of this group scoped entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this group scoped entry.
	 *
	 * @param companyId the company ID of this group scoped entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this group scoped entry.
	 *
	 * @return the group ID of this group scoped entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this group scoped entry.
	 *
	 * @param groupId the group ID of this group scoped entry
	 */
	public void setGroupId(long groupId);

}