/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ldap.exportimport.configuration;

import aQute.bnd.annotation.metatype.Meta;

/**
 * @author Michael C. Han
 */
@Meta.OCD(
	id = "com.liferay.portal.ldap.import",
	localization = "content.Language-LDAPImportConfiguration"
)
public interface LDAPImportConfiguration {

	@Meta.AD(
		deflt = "false", id = "ldap.import.create.role.per.group",
		required = false)
	public boolean ldapImportCreateRolePerGroup();

	@Meta.AD(deflt = "false", id = "ldap.import.enabled", required = false)
	public boolean ldapImportEnabled();

	@Meta.AD(
		deflt = "true", id = "ldap.import.group.cache.enabled",
		required = false)
	public boolean ldapImportGroupCacheEnabled();

	@Meta.AD(
		deflt = "true", id = "ldap.import.group.search.filter.enabled",
		required = false)
	public boolean ldapImportGroupSearchFilterEnabled();

	@Meta.AD(deflt = "10", id = "ldap.import.interval", required = false)
	public int ldapImportInterval();

	@Meta.AD(
		deflt = "86400000", id = "ldap.import.lock.expiration.time",
		required = false)
	public long ldapImportLockExpirationTime();

	@Meta.AD(
		deflt = "user", id = "ldap.import.method",
		optionValues = {"group", "user"}, required = false
	)
	public String ldapImportMethod();

	@Meta.AD(deflt = "false", id = "ldap.import.on.startup", required = false)
	public boolean ldapImportOnStartup();

	@Meta.AD(
		deflt = "false",id = "ldap.import.user.password.autogenerated",
		required = false)
	public boolean ldapImportUserPasswordAutogenerated();

	@Meta.AD(
		deflt = "test", id = "ldap.import.user.password.default",
		required = false)
	public String ldapImportUserPasswordDefault();

	@Meta.AD(
		deflt = "true", id = "ldap.import.user.password.enabled",
		required = false)
	public boolean ldapImportUserPasswordEnabled();

	@Meta.AD(id = "ldap.user.ignore.attributes", required = false)
	public String[] ldapUserIgnoreAttributes();

}