/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ldap.exportimport.configuration;

import aQute.bnd.annotation.metatype.Meta;

/**
 * @author Michael C. Han
 */
@Meta.OCD(
	id = "com.liferay.portal.ldap.import", localization = "content.Language"
)
public interface LDAPImportConfiguration {

	@Meta.AD(deflt = "10", id = "ldap.import.interval")
	public int getLDAPImportInterval();

	@Meta.AD(deflt = "86400000", id = "ldap.import.lock.expiration.time")
	public long getLDAPImportLockExpirationTime();

	@Meta.AD(
		deflt = "user", id = "ldap.import.method",
		optionValues = {"group", "user"}
	)
	public String getLDAPImportMethod();

	@Meta.AD(deflt = "test", id = "ldap.import.user.password.default")
	public String getLDAPImportUserPasswordDefault();

	@Meta.AD(id = "ldap.user.ignore.attributes")
	public String[] getLDAPUserIgnoreAttributes();

	@Meta.AD(deflt = "false", id = "ldap.import.create.role.per.group")
	public boolean isLDAPImportCreateRolePerGroup();

	@Meta.AD(deflt = "false", id = "ldap.import.enabled")
	public boolean isLDAPImportEnabled();

	@Meta.AD(deflt = "true", id = "ldap.import.group.cache.enabled")
	public boolean isLDAPImportGroupCacheEnabled();

	@Meta.AD(deflt = "true", id = "ldap.import.group.search.filter.enabled")
	public boolean isLDAPImportGroupSearchFilterEnabled();

	@Meta.AD(deflt = "false", id = "ldap.import.on.startup")
	public boolean isLDAPImportOnStartup();

	@Meta.AD(deflt = "false",id = "ldap.import.user.password.autogenerated")
	public boolean isLDAPImportUserPasswordAutogenerated();

	@Meta.AD(deflt = "true", id = "ldap.import.user.password.enabled")
	public boolean isLDAPImportUserPasswordEnabled();

}