/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.service.base;

import com.liferay.notification.model.NotificationQueueEntryRecipientSetting;
import com.liferay.notification.service.NotificationQueueEntryRecipientSettingLocalService;
import com.liferay.notification.service.NotificationQueueEntryRecipientSettingLocalServiceUtil;
import com.liferay.notification.service.persistence.NotificationQueueEntryRecipientSettingPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the notification queue entry recipient setting local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.notification.service.impl.NotificationQueueEntryRecipientSettingLocalServiceImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see com.liferay.notification.service.impl.NotificationQueueEntryRecipientSettingLocalServiceImpl
 * @generated
 */
public abstract class NotificationQueueEntryRecipientSettingLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   NotificationQueueEntryRecipientSettingLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NotificationQueueEntryRecipientSettingLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>NotificationQueueEntryRecipientSettingLocalServiceUtil</code>.
	 */

	/**
	 * Adds the notification queue entry recipient setting to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationQueueEntryRecipientSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationQueueEntryRecipientSetting the notification queue entry recipient setting
	 * @return the notification queue entry recipient setting that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NotificationQueueEntryRecipientSetting
		addNotificationQueueEntryRecipientSetting(
			NotificationQueueEntryRecipientSetting
				notificationQueueEntryRecipientSetting) {

		notificationQueueEntryRecipientSetting.setNew(true);

		return notificationQueueEntryRecipientSettingPersistence.update(
			notificationQueueEntryRecipientSetting);
	}

	/**
	 * Creates a new notification queue entry recipient setting with the primary key. Does not add the notification queue entry recipient setting to the database.
	 *
	 * @param notificationQueueEntryRecipientSettingId the primary key for the new notification queue entry recipient setting
	 * @return the new notification queue entry recipient setting
	 */
	@Override
	@Transactional(enabled = false)
	public NotificationQueueEntryRecipientSetting
		createNotificationQueueEntryRecipientSetting(
			long notificationQueueEntryRecipientSettingId) {

		return notificationQueueEntryRecipientSettingPersistence.create(
			notificationQueueEntryRecipientSettingId);
	}

	/**
	 * Deletes the notification queue entry recipient setting with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationQueueEntryRecipientSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationQueueEntryRecipientSettingId the primary key of the notification queue entry recipient setting
	 * @return the notification queue entry recipient setting that was removed
	 * @throws PortalException if a notification queue entry recipient setting with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NotificationQueueEntryRecipientSetting
			deleteNotificationQueueEntryRecipientSetting(
				long notificationQueueEntryRecipientSettingId)
		throws PortalException {

		return notificationQueueEntryRecipientSettingPersistence.remove(
			notificationQueueEntryRecipientSettingId);
	}

	/**
	 * Deletes the notification queue entry recipient setting from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationQueueEntryRecipientSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationQueueEntryRecipientSetting the notification queue entry recipient setting
	 * @return the notification queue entry recipient setting that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NotificationQueueEntryRecipientSetting
		deleteNotificationQueueEntryRecipientSetting(
			NotificationQueueEntryRecipientSetting
				notificationQueueEntryRecipientSetting) {

		return notificationQueueEntryRecipientSettingPersistence.remove(
			notificationQueueEntryRecipientSetting);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return notificationQueueEntryRecipientSettingPersistence.dslQuery(
			dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			NotificationQueueEntryRecipientSetting.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return notificationQueueEntryRecipientSettingPersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.model.impl.NotificationQueueEntryRecipientSettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return notificationQueueEntryRecipientSettingPersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.model.impl.NotificationQueueEntryRecipientSettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return notificationQueueEntryRecipientSettingPersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return notificationQueueEntryRecipientSettingPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return notificationQueueEntryRecipientSettingPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public NotificationQueueEntryRecipientSetting
		fetchNotificationQueueEntryRecipientSetting(
			long notificationQueueEntryRecipientSettingId) {

		return notificationQueueEntryRecipientSettingPersistence.
			fetchByPrimaryKey(notificationQueueEntryRecipientSettingId);
	}

	/**
	 * Returns the notification queue entry recipient setting with the primary key.
	 *
	 * @param notificationQueueEntryRecipientSettingId the primary key of the notification queue entry recipient setting
	 * @return the notification queue entry recipient setting
	 * @throws PortalException if a notification queue entry recipient setting with the primary key could not be found
	 */
	@Override
	public NotificationQueueEntryRecipientSetting
			getNotificationQueueEntryRecipientSetting(
				long notificationQueueEntryRecipientSettingId)
		throws PortalException {

		return notificationQueueEntryRecipientSettingPersistence.
			findByPrimaryKey(notificationQueueEntryRecipientSettingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			notificationQueueEntryRecipientSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			NotificationQueueEntryRecipientSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationQueueEntryRecipientSettingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			notificationQueueEntryRecipientSettingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			NotificationQueueEntryRecipientSetting.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationQueueEntryRecipientSettingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			notificationQueueEntryRecipientSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			NotificationQueueEntryRecipientSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationQueueEntryRecipientSettingId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return notificationQueueEntryRecipientSettingPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement NotificationQueueEntryRecipientSettingLocalServiceImpl#deleteNotificationQueueEntryRecipientSetting(NotificationQueueEntryRecipientSetting) to avoid orphaned data");
		}

		return notificationQueueEntryRecipientSettingLocalService.
			deleteNotificationQueueEntryRecipientSetting(
				(NotificationQueueEntryRecipientSetting)persistedModel);
	}

	@Override
	public BasePersistence<NotificationQueueEntryRecipientSetting>
		getBasePersistence() {

		return notificationQueueEntryRecipientSettingPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return notificationQueueEntryRecipientSettingPersistence.
			findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the notification queue entry recipient settings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.model.impl.NotificationQueueEntryRecipientSettingModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of notification queue entry recipient settings
	 * @param end the upper bound of the range of notification queue entry recipient settings (not inclusive)
	 * @return the range of notification queue entry recipient settings
	 */
	@Override
	public List<NotificationQueueEntryRecipientSetting>
		getNotificationQueueEntryRecipientSettings(int start, int end) {

		return notificationQueueEntryRecipientSettingPersistence.findAll(
			start, end);
	}

	/**
	 * Returns the number of notification queue entry recipient settings.
	 *
	 * @return the number of notification queue entry recipient settings
	 */
	@Override
	public int getNotificationQueueEntryRecipientSettingsCount() {
		return notificationQueueEntryRecipientSettingPersistence.countAll();
	}

	/**
	 * Updates the notification queue entry recipient setting in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationQueueEntryRecipientSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationQueueEntryRecipientSetting the notification queue entry recipient setting
	 * @return the notification queue entry recipient setting that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NotificationQueueEntryRecipientSetting
		updateNotificationQueueEntryRecipientSetting(
			NotificationQueueEntryRecipientSetting
				notificationQueueEntryRecipientSetting) {

		return notificationQueueEntryRecipientSettingPersistence.update(
			notificationQueueEntryRecipientSetting);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			NotificationQueueEntryRecipientSettingLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		notificationQueueEntryRecipientSettingLocalService =
			(NotificationQueueEntryRecipientSettingLocalService)aopProxy;

		_setLocalServiceUtilService(
			notificationQueueEntryRecipientSettingLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NotificationQueueEntryRecipientSettingLocalService.class.
			getName();
	}

	protected Class<?> getModelClass() {
		return NotificationQueueEntryRecipientSetting.class;
	}

	protected String getModelClassName() {
		return NotificationQueueEntryRecipientSetting.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				notificationQueueEntryRecipientSettingPersistence.
					getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		NotificationQueueEntryRecipientSettingLocalService
			notificationQueueEntryRecipientSettingLocalService) {

		try {
			Field field =
				NotificationQueueEntryRecipientSettingLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, notificationQueueEntryRecipientSettingLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected NotificationQueueEntryRecipientSettingLocalService
		notificationQueueEntryRecipientSettingLocalService;

	@Reference
	protected NotificationQueueEntryRecipientSettingPersistence
		notificationQueueEntryRecipientSettingPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		NotificationQueueEntryRecipientSettingLocalServiceBaseImpl.class);

}