#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-seostudio-pagespeed-oahs.oauth2.headless.server.client.secret=${LIFERAY_SEOSTUDIO_PAGESPEED_OAHS_CLIENT_SECRET}

liferay.oauth.application.external.reference.codes=\
    liferay-seostudio-pagespeed-oahs,\
    liferay-seostudio-pagespeed-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081