/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.meris.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.meris.model.MerisSegmentRel;
import com.liferay.meris.service.MerisSegmentRelLocalService;
import com.liferay.meris.service.persistence.MerisSegmentPersistence;
import com.liferay.meris.service.persistence.MerisSegmentRelPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the meris segment rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.meris.service.impl.MerisSegmentRelLocalServiceImpl}.
 * </p>
 *
 * @author Eduardo Garcia
 * @see com.liferay.meris.service.impl.MerisSegmentRelLocalServiceImpl
 * @see com.liferay.meris.service.MerisSegmentRelLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MerisSegmentRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MerisSegmentRelLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.meris.service.MerisSegmentRelLocalServiceUtil} to access the meris segment rel local service.
	 */

	/**
	 * Adds the meris segment rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param merisSegmentRel the meris segment rel
	 * @return the meris segment rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MerisSegmentRel addMerisSegmentRel(MerisSegmentRel merisSegmentRel) {
		merisSegmentRel.setNew(true);

		return merisSegmentRelPersistence.update(merisSegmentRel);
	}

	/**
	 * Creates a new meris segment rel with the primary key. Does not add the meris segment rel to the database.
	 *
	 * @param merisSegmentRelId the primary key for the new meris segment rel
	 * @return the new meris segment rel
	 */
	@Override
	@Transactional(enabled = false)
	public MerisSegmentRel createMerisSegmentRel(long merisSegmentRelId) {
		return merisSegmentRelPersistence.create(merisSegmentRelId);
	}

	/**
	 * Deletes the meris segment rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param merisSegmentRelId the primary key of the meris segment rel
	 * @return the meris segment rel that was removed
	 * @throws PortalException if a meris segment rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MerisSegmentRel deleteMerisSegmentRel(long merisSegmentRelId)
		throws PortalException {
		return merisSegmentRelPersistence.remove(merisSegmentRelId);
	}

	/**
	 * Deletes the meris segment rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param merisSegmentRel the meris segment rel
	 * @return the meris segment rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MerisSegmentRel deleteMerisSegmentRel(
		MerisSegmentRel merisSegmentRel) {
		return merisSegmentRelPersistence.remove(merisSegmentRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MerisSegmentRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return merisSegmentRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.meris.model.impl.MerisSegmentRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return merisSegmentRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.meris.model.impl.MerisSegmentRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return merisSegmentRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return merisSegmentRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return merisSegmentRelPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MerisSegmentRel fetchMerisSegmentRel(long merisSegmentRelId) {
		return merisSegmentRelPersistence.fetchByPrimaryKey(merisSegmentRelId);
	}

	/**
	 * Returns the meris segment rel with the primary key.
	 *
	 * @param merisSegmentRelId the primary key of the meris segment rel
	 * @return the meris segment rel
	 * @throws PortalException if a meris segment rel with the primary key could not be found
	 */
	@Override
	public MerisSegmentRel getMerisSegmentRel(long merisSegmentRelId)
		throws PortalException {
		return merisSegmentRelPersistence.findByPrimaryKey(merisSegmentRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(merisSegmentRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MerisSegmentRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("merisSegmentRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(merisSegmentRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MerisSegmentRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"merisSegmentRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(merisSegmentRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MerisSegmentRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("merisSegmentRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return merisSegmentRelLocalService.deleteMerisSegmentRel((MerisSegmentRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return merisSegmentRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the meris segment rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.meris.model.impl.MerisSegmentRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of meris segment rels
	 * @param end the upper bound of the range of meris segment rels (not inclusive)
	 * @return the range of meris segment rels
	 */
	@Override
	public List<MerisSegmentRel> getMerisSegmentRels(int start, int end) {
		return merisSegmentRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of meris segment rels.
	 *
	 * @return the number of meris segment rels
	 */
	@Override
	public int getMerisSegmentRelsCount() {
		return merisSegmentRelPersistence.countAll();
	}

	/**
	 * Updates the meris segment rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param merisSegmentRel the meris segment rel
	 * @return the meris segment rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MerisSegmentRel updateMerisSegmentRel(
		MerisSegmentRel merisSegmentRel) {
		return merisSegmentRelPersistence.update(merisSegmentRel);
	}

	/**
	 * Returns the meris segment local service.
	 *
	 * @return the meris segment local service
	 */
	public com.liferay.meris.service.MerisSegmentLocalService getMerisSegmentLocalService() {
		return merisSegmentLocalService;
	}

	/**
	 * Sets the meris segment local service.
	 *
	 * @param merisSegmentLocalService the meris segment local service
	 */
	public void setMerisSegmentLocalService(
		com.liferay.meris.service.MerisSegmentLocalService merisSegmentLocalService) {
		this.merisSegmentLocalService = merisSegmentLocalService;
	}

	/**
	 * Returns the meris segment persistence.
	 *
	 * @return the meris segment persistence
	 */
	public MerisSegmentPersistence getMerisSegmentPersistence() {
		return merisSegmentPersistence;
	}

	/**
	 * Sets the meris segment persistence.
	 *
	 * @param merisSegmentPersistence the meris segment persistence
	 */
	public void setMerisSegmentPersistence(
		MerisSegmentPersistence merisSegmentPersistence) {
		this.merisSegmentPersistence = merisSegmentPersistence;
	}

	/**
	 * Returns the meris segment rel local service.
	 *
	 * @return the meris segment rel local service
	 */
	public MerisSegmentRelLocalService getMerisSegmentRelLocalService() {
		return merisSegmentRelLocalService;
	}

	/**
	 * Sets the meris segment rel local service.
	 *
	 * @param merisSegmentRelLocalService the meris segment rel local service
	 */
	public void setMerisSegmentRelLocalService(
		MerisSegmentRelLocalService merisSegmentRelLocalService) {
		this.merisSegmentRelLocalService = merisSegmentRelLocalService;
	}

	/**
	 * Returns the meris segment rel persistence.
	 *
	 * @return the meris segment rel persistence
	 */
	public MerisSegmentRelPersistence getMerisSegmentRelPersistence() {
		return merisSegmentRelPersistence;
	}

	/**
	 * Sets the meris segment rel persistence.
	 *
	 * @param merisSegmentRelPersistence the meris segment rel persistence
	 */
	public void setMerisSegmentRelPersistence(
		MerisSegmentRelPersistence merisSegmentRelPersistence) {
		this.merisSegmentRelPersistence = merisSegmentRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.meris.model.MerisSegmentRel",
			merisSegmentRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.meris.model.MerisSegmentRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MerisSegmentRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MerisSegmentRel.class;
	}

	protected String getModelClassName() {
		return MerisSegmentRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = merisSegmentRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.meris.service.MerisSegmentLocalService.class)
	protected com.liferay.meris.service.MerisSegmentLocalService merisSegmentLocalService;
	@BeanReference(type = MerisSegmentPersistence.class)
	protected MerisSegmentPersistence merisSegmentPersistence;
	@BeanReference(type = MerisSegmentRelLocalService.class)
	protected MerisSegmentRelLocalService merisSegmentRelLocalService;
	@BeanReference(type = MerisSegmentRelPersistence.class)
	protected MerisSegmentRelPersistence merisSegmentRelPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}