apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-100"
        eks.amazonaws.com/role-arn: {{ .Values.deploymentContext.crossplaneDataRoleArn | quote }}
    name: crossplane-data
    namespace: {{ .Values.crossplaneNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-100"
        eks.amazonaws.com/role-arn: {{ .Values.deploymentContext.crossplaneIamRoleArn | quote }}
    name: crossplane-iam
    namespace: {{ .Values.crossplaneNamespace }}