##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    legacy.language.keys=\
        get-url,\
        get-url-or-webdav-url,\
        uploaded-by-x-x,\
        webdav-help,\
        webdav-windows-help