/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.social.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.social.model.SocialActivityStatsEntry;
import com.liferay.portlet.social.model.SocialActivityStatsEntryModel;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the SocialActivityStatsEntry service. Represents a row in the &quot;SocialActivityStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portlet.social.model.SocialActivityStatsEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialActivityStatsEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialActivityStatsEntryImpl
 * @see com.liferay.portlet.social.model.SocialActivityStatsEntry
 * @see com.liferay.portlet.social.model.SocialActivityStatsEntryModel
 * @generated
 */
public class SocialActivityStatsEntryModelImpl extends BaseModelImpl<SocialActivityStatsEntry>
	implements SocialActivityStatsEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social activity stats entry model instance should use the {@link com.liferay.portlet.social.model.SocialActivityStatsEntry} interface instead.
	 */
	public static final String TABLE_NAME = "SocialActivityStats";
	public static final Object[][] TABLE_COLUMNS = {
			{ "activityStatsEntryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "classType", Types.INTEGER },
			{ "statName", Types.VARCHAR },
			{ "currentValue", Types.INTEGER },
			{ "overallValue", Types.INTEGER },
			{ "graceValue", Types.INTEGER },
			{ "statPeriodStart", Types.INTEGER },
			{ "statPeriodEnd", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table SocialActivityStats (activityStatsEntryId LONG not null primary key,groupId LONG,companyId LONG,classNameId LONG,classPK LONG,classType INTEGER,statName VARCHAR(75) null,currentValue INTEGER,overallValue INTEGER,graceValue INTEGER,statPeriodStart INTEGER,statPeriodEnd INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table SocialActivityStats";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portlet.social.model.SocialActivityStatsEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portlet.social.model.SocialActivityStatsEntry"),
			true);

	public Class<?> getModelClass() {
		return SocialActivityStatsEntry.class;
	}

	public String getModelClassName() {
		return SocialActivityStatsEntry.class.getName();
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portlet.social.model.SocialActivityStatsEntry"));

	public SocialActivityStatsEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _activityStatsEntryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setActivityStatsEntryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_activityStatsEntryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public long getActivityStatsEntryId() {
		return _activityStatsEntryId;
	}

	public void setActivityStatsEntryId(long activityStatsEntryId) {
		_activityStatsEntryId = activityStatsEntryId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public String getClassName() {
		if (getClassNameId() <= 0) {
			return StringPool.BLANK;
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	public long getClassNameId() {
		return _classNameId;
	}

	public void setClassNameId(long classNameId) {
		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	public long getClassPK() {
		return _classPK;
	}

	public void setClassPK(long classPK) {
		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public int getClassType() {
		return _classType;
	}

	public void setClassType(int classType) {
		if (!_setOriginalClassType) {
			_setOriginalClassType = true;

			_originalClassType = _classType;
		}

		_classType = classType;
	}

	public int getOriginalClassType() {
		return _originalClassType;
	}

	public String getStatName() {
		if (_statName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statName;
		}
	}

	public void setStatName(String statName) {
		if (_originalStatName == null) {
			_originalStatName = _statName;
		}

		_statName = statName;
	}

	public String getOriginalStatName() {
		return GetterUtil.getString(_originalStatName);
	}

	public int getCurrentValue() {
		return _currentValue;
	}

	public void setCurrentValue(int currentValue) {
		_currentValue = currentValue;
	}

	public int getOverallValue() {
		return _overallValue;
	}

	public void setOverallValue(int overallValue) {
		_overallValue = overallValue;
	}

	public int getGraceValue() {
		return _graceValue;
	}

	public void setGraceValue(int graceValue) {
		_graceValue = graceValue;
	}

	public int getStatPeriodStart() {
		return _statPeriodStart;
	}

	public void setStatPeriodStart(int statPeriodStart) {
		if (!_setOriginalStatPeriodStart) {
			_setOriginalStatPeriodStart = true;

			_originalStatPeriodStart = _statPeriodStart;
		}

		_statPeriodStart = statPeriodStart;
	}

	public int getOriginalStatPeriodStart() {
		return _originalStatPeriodStart;
	}

	public int getStatPeriodEnd() {
		return _statPeriodEnd;
	}

	public void setStatPeriodEnd(int statPeriodEnd) {
		if (!_setOriginalStatPeriodEnd) {
			_setOriginalStatPeriodEnd = true;

			_originalStatPeriodEnd = _statPeriodEnd;
		}

		_statPeriodEnd = statPeriodEnd;
	}

	public int getOriginalStatPeriodEnd() {
		return _originalStatPeriodEnd;
	}

	@Override
	public SocialActivityStatsEntry toEscapedModel() {
		if (isEscapedModel()) {
			return (SocialActivityStatsEntry)this;
		}
		else {
			if (_escapedModelProxy == null) {
				_escapedModelProxy = (SocialActivityStatsEntry)ProxyUtil.newProxyInstance(_classLoader,
						_escapedModelProxyInterfaces,
						new AutoEscapeBeanHandler(this));
			}

			return _escapedModelProxy;
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					SocialActivityStatsEntry.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		SocialActivityStatsEntryImpl socialActivityStatsEntryImpl = new SocialActivityStatsEntryImpl();

		socialActivityStatsEntryImpl.setActivityStatsEntryId(getActivityStatsEntryId());
		socialActivityStatsEntryImpl.setGroupId(getGroupId());
		socialActivityStatsEntryImpl.setCompanyId(getCompanyId());
		socialActivityStatsEntryImpl.setClassNameId(getClassNameId());
		socialActivityStatsEntryImpl.setClassPK(getClassPK());
		socialActivityStatsEntryImpl.setClassType(getClassType());
		socialActivityStatsEntryImpl.setStatName(getStatName());
		socialActivityStatsEntryImpl.setCurrentValue(getCurrentValue());
		socialActivityStatsEntryImpl.setOverallValue(getOverallValue());
		socialActivityStatsEntryImpl.setGraceValue(getGraceValue());
		socialActivityStatsEntryImpl.setStatPeriodStart(getStatPeriodStart());
		socialActivityStatsEntryImpl.setStatPeriodEnd(getStatPeriodEnd());

		socialActivityStatsEntryImpl.resetOriginalValues();

		return socialActivityStatsEntryImpl;
	}

	public int compareTo(SocialActivityStatsEntry socialActivityStatsEntry) {
		long primaryKey = socialActivityStatsEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SocialActivityStatsEntry socialActivityStatsEntry = null;

		try {
			socialActivityStatsEntry = (SocialActivityStatsEntry)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = socialActivityStatsEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SocialActivityStatsEntryModelImpl socialActivityStatsEntryModelImpl = this;

		socialActivityStatsEntryModelImpl._originalGroupId = socialActivityStatsEntryModelImpl._groupId;

		socialActivityStatsEntryModelImpl._setOriginalGroupId = false;

		socialActivityStatsEntryModelImpl._originalClassNameId = socialActivityStatsEntryModelImpl._classNameId;

		socialActivityStatsEntryModelImpl._setOriginalClassNameId = false;

		socialActivityStatsEntryModelImpl._originalClassPK = socialActivityStatsEntryModelImpl._classPK;

		socialActivityStatsEntryModelImpl._setOriginalClassPK = false;

		socialActivityStatsEntryModelImpl._originalClassType = socialActivityStatsEntryModelImpl._classType;

		socialActivityStatsEntryModelImpl._setOriginalClassType = false;

		socialActivityStatsEntryModelImpl._originalStatName = socialActivityStatsEntryModelImpl._statName;

		socialActivityStatsEntryModelImpl._originalStatPeriodStart = socialActivityStatsEntryModelImpl._statPeriodStart;

		socialActivityStatsEntryModelImpl._setOriginalStatPeriodStart = false;

		socialActivityStatsEntryModelImpl._originalStatPeriodEnd = socialActivityStatsEntryModelImpl._statPeriodEnd;

		socialActivityStatsEntryModelImpl._setOriginalStatPeriodEnd = false;
	}

	@Override
	public CacheModel<SocialActivityStatsEntry> toCacheModel() {
		SocialActivityStatsEntryCacheModel socialActivityStatsEntryCacheModel = new SocialActivityStatsEntryCacheModel();

		socialActivityStatsEntryCacheModel.activityStatsEntryId = getActivityStatsEntryId();

		socialActivityStatsEntryCacheModel.groupId = getGroupId();

		socialActivityStatsEntryCacheModel.companyId = getCompanyId();

		socialActivityStatsEntryCacheModel.classNameId = getClassNameId();

		socialActivityStatsEntryCacheModel.classPK = getClassPK();

		socialActivityStatsEntryCacheModel.classType = getClassType();

		socialActivityStatsEntryCacheModel.statName = getStatName();

		String statName = socialActivityStatsEntryCacheModel.statName;

		if ((statName != null) && (statName.length() == 0)) {
			socialActivityStatsEntryCacheModel.statName = null;
		}

		socialActivityStatsEntryCacheModel.currentValue = getCurrentValue();

		socialActivityStatsEntryCacheModel.overallValue = getOverallValue();

		socialActivityStatsEntryCacheModel.graceValue = getGraceValue();

		socialActivityStatsEntryCacheModel.statPeriodStart = getStatPeriodStart();

		socialActivityStatsEntryCacheModel.statPeriodEnd = getStatPeriodEnd();

		return socialActivityStatsEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{activityStatsEntryId=");
		sb.append(getActivityStatsEntryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", classType=");
		sb.append(getClassType());
		sb.append(", statName=");
		sb.append(getStatName());
		sb.append(", currentValue=");
		sb.append(getCurrentValue());
		sb.append(", overallValue=");
		sb.append(getOverallValue());
		sb.append(", graceValue=");
		sb.append(getGraceValue());
		sb.append(", statPeriodStart=");
		sb.append(getStatPeriodStart());
		sb.append(", statPeriodEnd=");
		sb.append(getStatPeriodEnd());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portlet.social.model.SocialActivityStatsEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>activityStatsEntryId</column-name><column-value><![CDATA[");
		sb.append(getActivityStatsEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classType</column-name><column-value><![CDATA[");
		sb.append(getClassType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statName</column-name><column-value><![CDATA[");
		sb.append(getStatName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currentValue</column-name><column-value><![CDATA[");
		sb.append(getCurrentValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>overallValue</column-name><column-value><![CDATA[");
		sb.append(getOverallValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>graceValue</column-name><column-value><![CDATA[");
		sb.append(getGraceValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statPeriodStart</column-name><column-value><![CDATA[");
		sb.append(getStatPeriodStart());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statPeriodEnd</column-name><column-value><![CDATA[");
		sb.append(getStatPeriodEnd());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SocialActivityStatsEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SocialActivityStatsEntry.class
		};
	private long _activityStatsEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private int _classType;
	private int _originalClassType;
	private boolean _setOriginalClassType;
	private String _statName;
	private String _originalStatName;
	private int _currentValue;
	private int _overallValue;
	private int _graceValue;
	private int _statPeriodStart;
	private int _originalStatPeriodStart;
	private boolean _setOriginalStatPeriodStart;
	private int _statPeriodEnd;
	private int _originalStatPeriodEnd;
	private boolean _setOriginalStatPeriodEnd;
	private transient ExpandoBridge _expandoBridge;
	private SocialActivityStatsEntry _escapedModelProxy;
}