com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http
liferay.oauth.application.external.reference.code=liferay-sample-oauth-application-headless-server
# TODO add 

			"${${liferay.oauth.application.external.reference.code}.oauth2.token.uri}"
		)
		String tokenUri,
		@Value(
			"${${liferay.oauth.application.external.reference.code}.oauth2.headless.server.client.id}"
		)
		String clientId,
		@Value(
			"${${liferay.oauth.application.external.reference.code}.oauth2.headless.server.client.secret}"
		)
		String clientSecret,
		@Value(
			"${${liferay.oauth.application.external.reference.code}.oauth2.headless.server.scopes}"
		)