/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.object.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.object.model.ObjectActionEntry;
import com.liferay.object.model.ObjectActionEntryModel;
import com.liferay.object.model.ObjectActionEntrySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ObjectActionEntry service. Represents a row in the &quot;ObjectActionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ObjectActionEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectActionEntryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ObjectActionEntryImpl
 * @generated
 */
@JSON(strict = true)
public class ObjectActionEntryModelImpl
	extends BaseModelImpl<ObjectActionEntry> implements ObjectActionEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a object action entry model instance should use the <code>ObjectActionEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ObjectActionEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"objectActionEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"objectDefinitionId", Types.BIGINT}, {"active_", Types.BOOLEAN},
		{"triggerName", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"settings_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("objectActionEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("objectDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("triggerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("settings_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ObjectActionEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,objectActionEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,objectDefinitionId LONG,active_ BOOLEAN,triggerName VARCHAR(75) null,name VARCHAR(75) null,settings_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ObjectActionEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY objectActionEntry.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ObjectActionEntry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OBJECTDEFINITIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRIGGERNAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ObjectActionEntry toModel(ObjectActionEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ObjectActionEntry model = new ObjectActionEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setObjectActionEntryId(soapModel.getObjectActionEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setObjectDefinitionId(soapModel.getObjectDefinitionId());
		model.setActive(soapModel.isActive());
		model.setTriggerName(soapModel.getTriggerName());
		model.setName(soapModel.getName());
		model.setSettings(soapModel.getSettings());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ObjectActionEntry> toModels(
		ObjectActionEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ObjectActionEntry> models = new ArrayList<ObjectActionEntry>(
			soapModels.length);

		for (ObjectActionEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ObjectActionEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _objectActionEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setObjectActionEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _objectActionEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ObjectActionEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ObjectActionEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ObjectActionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ObjectActionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectActionEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ObjectActionEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ObjectActionEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ObjectActionEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ObjectActionEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ObjectActionEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ObjectActionEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ObjectActionEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ObjectActionEntry.class.getClassLoader(), ObjectActionEntry.class,
			ModelWrapper.class);

		try {
			Constructor<ObjectActionEntry> constructor =
				(Constructor<ObjectActionEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ObjectActionEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ObjectActionEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ObjectActionEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ObjectActionEntry, Object>>();
		Map<String, BiConsumer<ObjectActionEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ObjectActionEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", ObjectActionEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ObjectActionEntry, Long>)
				ObjectActionEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", ObjectActionEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ObjectActionEntry, String>)ObjectActionEntry::setUuid);
		attributeGetterFunctions.put(
			"objectActionEntryId", ObjectActionEntry::getObjectActionEntryId);
		attributeSetterBiConsumers.put(
			"objectActionEntryId",
			(BiConsumer<ObjectActionEntry, Long>)
				ObjectActionEntry::setObjectActionEntryId);
		attributeGetterFunctions.put(
			"companyId", ObjectActionEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ObjectActionEntry, Long>)
				ObjectActionEntry::setCompanyId);
		attributeGetterFunctions.put("userId", ObjectActionEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ObjectActionEntry, Long>)ObjectActionEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", ObjectActionEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ObjectActionEntry, String>)
				ObjectActionEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", ObjectActionEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ObjectActionEntry, Date>)
				ObjectActionEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ObjectActionEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ObjectActionEntry, Date>)
				ObjectActionEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"objectDefinitionId", ObjectActionEntry::getObjectDefinitionId);
		attributeSetterBiConsumers.put(
			"objectDefinitionId",
			(BiConsumer<ObjectActionEntry, Long>)
				ObjectActionEntry::setObjectDefinitionId);
		attributeGetterFunctions.put("active", ObjectActionEntry::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<ObjectActionEntry, Boolean>)
				ObjectActionEntry::setActive);
		attributeGetterFunctions.put(
			"triggerName", ObjectActionEntry::getTriggerName);
		attributeSetterBiConsumers.put(
			"triggerName",
			(BiConsumer<ObjectActionEntry, String>)
				ObjectActionEntry::setTriggerName);
		attributeGetterFunctions.put("name", ObjectActionEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<ObjectActionEntry, String>)ObjectActionEntry::setName);
		attributeGetterFunctions.put(
			"settings", ObjectActionEntry::getSettings);
		attributeSetterBiConsumers.put(
			"settings",
			(BiConsumer<ObjectActionEntry, String>)
				ObjectActionEntry::setSettings);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getObjectActionEntryId() {
		return _objectActionEntryId;
	}

	@Override
	public void setObjectActionEntryId(long objectActionEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_objectActionEntryId = objectActionEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getObjectDefinitionId() {
		return _objectDefinitionId;
	}

	@Override
	public void setObjectDefinitionId(long objectDefinitionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_objectDefinitionId = objectDefinitionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalObjectDefinitionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("objectDefinitionId"));
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalActive() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("active_"));
	}

	@JSON
	@Override
	public String getTriggerName() {
		if (_triggerName == null) {
			return "";
		}
		else {
			return _triggerName;
		}
	}

	@Override
	public void setTriggerName(String triggerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_triggerName = triggerName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTriggerName() {
		return getColumnOriginalValue("triggerName");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getSettings() {
		if (_settings == null) {
			return "";
		}
		else {
			return _settings;
		}
	}

	@Override
	public void setSettings(String settings) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_settings = settings;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ObjectActionEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ObjectActionEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ObjectActionEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ObjectActionEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ObjectActionEntryImpl objectActionEntryImpl =
			new ObjectActionEntryImpl();

		objectActionEntryImpl.setMvccVersion(getMvccVersion());
		objectActionEntryImpl.setUuid(getUuid());
		objectActionEntryImpl.setObjectActionEntryId(getObjectActionEntryId());
		objectActionEntryImpl.setCompanyId(getCompanyId());
		objectActionEntryImpl.setUserId(getUserId());
		objectActionEntryImpl.setUserName(getUserName());
		objectActionEntryImpl.setCreateDate(getCreateDate());
		objectActionEntryImpl.setModifiedDate(getModifiedDate());
		objectActionEntryImpl.setObjectDefinitionId(getObjectDefinitionId());
		objectActionEntryImpl.setActive(isActive());
		objectActionEntryImpl.setTriggerName(getTriggerName());
		objectActionEntryImpl.setName(getName());
		objectActionEntryImpl.setSettings(getSettings());

		objectActionEntryImpl.resetOriginalValues();

		return objectActionEntryImpl;
	}

	@Override
	public ObjectActionEntry cloneWithOriginalValues() {
		ObjectActionEntryImpl objectActionEntryImpl =
			new ObjectActionEntryImpl();

		objectActionEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		objectActionEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		objectActionEntryImpl.setObjectActionEntryId(
			this.<Long>getColumnOriginalValue("objectActionEntryId"));
		objectActionEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		objectActionEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		objectActionEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		objectActionEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		objectActionEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		objectActionEntryImpl.setObjectDefinitionId(
			this.<Long>getColumnOriginalValue("objectDefinitionId"));
		objectActionEntryImpl.setActive(
			this.<Boolean>getColumnOriginalValue("active_"));
		objectActionEntryImpl.setTriggerName(
			this.<String>getColumnOriginalValue("triggerName"));
		objectActionEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		objectActionEntryImpl.setSettings(
			this.<String>getColumnOriginalValue("settings_"));

		return objectActionEntryImpl;
	}

	@Override
	public int compareTo(ObjectActionEntry objectActionEntry) {
		int value = 0;

		value = getName().compareTo(objectActionEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ObjectActionEntry)) {
			return false;
		}

		ObjectActionEntry objectActionEntry = (ObjectActionEntry)object;

		long primaryKey = objectActionEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ObjectActionEntry> toCacheModel() {
		ObjectActionEntryCacheModel objectActionEntryCacheModel =
			new ObjectActionEntryCacheModel();

		objectActionEntryCacheModel.mvccVersion = getMvccVersion();

		objectActionEntryCacheModel.uuid = getUuid();

		String uuid = objectActionEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			objectActionEntryCacheModel.uuid = null;
		}

		objectActionEntryCacheModel.objectActionEntryId =
			getObjectActionEntryId();

		objectActionEntryCacheModel.companyId = getCompanyId();

		objectActionEntryCacheModel.userId = getUserId();

		objectActionEntryCacheModel.userName = getUserName();

		String userName = objectActionEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			objectActionEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			objectActionEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			objectActionEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			objectActionEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			objectActionEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		objectActionEntryCacheModel.objectDefinitionId =
			getObjectDefinitionId();

		objectActionEntryCacheModel.active = isActive();

		objectActionEntryCacheModel.triggerName = getTriggerName();

		String triggerName = objectActionEntryCacheModel.triggerName;

		if ((triggerName != null) && (triggerName.length() == 0)) {
			objectActionEntryCacheModel.triggerName = null;
		}

		objectActionEntryCacheModel.name = getName();

		String name = objectActionEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			objectActionEntryCacheModel.name = null;
		}

		objectActionEntryCacheModel.settings = getSettings();

		String settings = objectActionEntryCacheModel.settings;

		if ((settings != null) && (settings.length() == 0)) {
			objectActionEntryCacheModel.settings = null;
		}

		return objectActionEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ObjectActionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ObjectActionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectActionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ObjectActionEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ObjectActionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ObjectActionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ObjectActionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ObjectActionEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ObjectActionEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private long _objectActionEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _objectDefinitionId;
	private boolean _active;
	private String _triggerName;
	private String _name;
	private String _settings;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ObjectActionEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ObjectActionEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("objectActionEntryId", _objectActionEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("objectDefinitionId", _objectDefinitionId);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("triggerName", _triggerName);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("settings_", _settings);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("active_", "active");
		attributeNames.put("settings_", "settings");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("objectActionEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("objectDefinitionId", 256L);

		columnBitmasks.put("active_", 512L);

		columnBitmasks.put("triggerName", 1024L);

		columnBitmasks.put("name", 2048L);

		columnBitmasks.put("settings_", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ObjectActionEntry _escapedModel;

}