/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.list.type.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ListTypeEntry service. Represents a row in the &quot;ListTypeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.list.type.model.impl.ListTypeEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.list.type.model.impl.ListTypeEntryImpl</code>.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see ListTypeEntry
 * @generated
 */
@ProviderType
public interface ListTypeEntryModel
	extends BaseModel<ListTypeEntry>, LocalizedModel, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a list type entry model instance should use the {@link ListTypeEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this list type entry.
	 *
	 * @return the primary key of this list type entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this list type entry.
	 *
	 * @param primaryKey the primary key of this list type entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this list type entry.
	 *
	 * @return the mvcc version of this list type entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this list type entry.
	 *
	 * @param mvccVersion the mvcc version of this list type entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this list type entry.
	 *
	 * @return the uuid of this list type entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this list type entry.
	 *
	 * @param uuid the uuid of this list type entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the list type entry ID of this list type entry.
	 *
	 * @return the list type entry ID of this list type entry
	 */
	public long getListTypeEntryId();

	/**
	 * Sets the list type entry ID of this list type entry.
	 *
	 * @param listTypeEntryId the list type entry ID of this list type entry
	 */
	public void setListTypeEntryId(long listTypeEntryId);

	/**
	 * Returns the company ID of this list type entry.
	 *
	 * @return the company ID of this list type entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this list type entry.
	 *
	 * @param companyId the company ID of this list type entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the list type definition ID of this list type entry.
	 *
	 * @return the list type definition ID of this list type entry
	 */
	public long getListTypeDefinitionId();

	/**
	 * Sets the list type definition ID of this list type entry.
	 *
	 * @param listTypeDefinitionId the list type definition ID of this list type entry
	 */
	public void setListTypeDefinitionId(long listTypeDefinitionId);

	/**
	 * Returns the label of this list type entry.
	 *
	 * @return the label of this list type entry
	 */
	public String getLabel();

	/**
	 * Returns the localized label of this list type entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized label of this list type entry
	 */
	@AutoEscape
	public String getLabel(Locale locale);

	/**
	 * Returns the localized label of this list type entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this list type entry. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLabel(Locale locale, boolean useDefault);

	/**
	 * Returns the localized label of this list type entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized label of this list type entry
	 */
	@AutoEscape
	public String getLabel(String languageId);

	/**
	 * Returns the localized label of this list type entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this list type entry
	 */
	@AutoEscape
	public String getLabel(String languageId, boolean useDefault);

	@AutoEscape
	public String getLabelCurrentLanguageId();

	@AutoEscape
	public String getLabelCurrentValue();

	/**
	 * Returns a map of the locales and localized labels of this list type entry.
	 *
	 * @return the locales and localized labels of this list type entry
	 */
	public Map<Locale, String> getLabelMap();

	/**
	 * Sets the label of this list type entry.
	 *
	 * @param label the label of this list type entry
	 */
	public void setLabel(String label);

	/**
	 * Sets the localized label of this list type entry in the language.
	 *
	 * @param label the localized label of this list type entry
	 * @param locale the locale of the language
	 */
	public void setLabel(String label, Locale locale);

	/**
	 * Sets the localized label of this list type entry in the language, and sets the default locale.
	 *
	 * @param label the localized label of this list type entry
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLabel(String label, Locale locale, Locale defaultLocale);

	public void setLabelCurrentLanguageId(String languageId);

	/**
	 * Sets the localized labels of this list type entry from the map of locales and localized labels.
	 *
	 * @param labelMap the locales and localized labels of this list type entry
	 */
	public void setLabelMap(Map<Locale, String> labelMap);

	/**
	 * Sets the localized labels of this list type entry from the map of locales and localized labels, and sets the default locale.
	 *
	 * @param labelMap the locales and localized labels of this list type entry
	 * @param defaultLocale the default locale
	 */
	public void setLabelMap(Map<Locale, String> labelMap, Locale defaultLocale);

	/**
	 * Returns the name of this list type entry.
	 *
	 * @return the name of this list type entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this list type entry.
	 *
	 * @param name the name of this list type entry
	 */
	public void setName(String name);

	/**
	 * Returns the type of this list type entry.
	 *
	 * @return the type of this list type entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this list type entry.
	 *
	 * @param type the type of this list type entry
	 */
	public void setType(String type);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}