/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.json.store.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.json.store.model.JSONStoreEntry;
import com.liferay.json.store.model.JSONStoreEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JSONStoreEntry service. Represents a row in the &quot;JSONStoreEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JSONStoreEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JSONStoreEntryImpl}.
 * </p>
 *
 * @author Preston Crary
 * @see JSONStoreEntryImpl
 * @generated
 */
public class JSONStoreEntryModelImpl
	extends BaseModelImpl<JSONStoreEntry> implements JSONStoreEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a json store entry model instance should use the <code>JSONStoreEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "JSONStoreEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"jsonStoreEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"parentJSONStoreEntryId", Types.BIGINT}, {"index_", Types.INTEGER},
		{"key_", Types.VARCHAR}, {"type_", Types.INTEGER},
		{"valueLong", Types.BIGINT}, {"valueString", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("jsonStoreEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentJSONStoreEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("index_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("valueLong", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("valueString", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JSONStoreEntry (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,jsonStoreEntryId LONG not null,companyId LONG,classNameId LONG,classPK LONG,parentJSONStoreEntryId LONG,index_ INTEGER,key_ VARCHAR(75) null,type_ INTEGER,valueLong LONG,valueString VARCHAR(75) null,primary key (jsonStoreEntryId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table JSONStoreEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY jsonStoreEntry.index ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JSONStoreEntry.index_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INDEX_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KEY_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTJSONSTOREENTRYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VALUELONG_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public JSONStoreEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jsonStoreEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJsonStoreEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jsonStoreEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JSONStoreEntry.class;
	}

	@Override
	public String getModelClassName() {
		return JSONStoreEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JSONStoreEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<JSONStoreEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JSONStoreEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((JSONStoreEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JSONStoreEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JSONStoreEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JSONStoreEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<JSONStoreEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<JSONStoreEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, JSONStoreEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			JSONStoreEntry.class.getClassLoader(), JSONStoreEntry.class,
			ModelWrapper.class);

		try {
			Constructor<JSONStoreEntry> constructor =
				(Constructor<JSONStoreEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<JSONStoreEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<JSONStoreEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<JSONStoreEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<JSONStoreEntry, Object>>();
		Map<String, BiConsumer<JSONStoreEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<JSONStoreEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", JSONStoreEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<JSONStoreEntry, Long>)JSONStoreEntry::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", JSONStoreEntry::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<JSONStoreEntry, Long>)
				JSONStoreEntry::setCtCollectionId);
		attributeGetterFunctions.put(
			"jsonStoreEntryId", JSONStoreEntry::getJsonStoreEntryId);
		attributeSetterBiConsumers.put(
			"jsonStoreEntryId",
			(BiConsumer<JSONStoreEntry, Long>)
				JSONStoreEntry::setJsonStoreEntryId);
		attributeGetterFunctions.put("companyId", JSONStoreEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<JSONStoreEntry, Long>)JSONStoreEntry::setCompanyId);
		attributeGetterFunctions.put(
			"classNameId", JSONStoreEntry::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<JSONStoreEntry, Long>)JSONStoreEntry::setClassNameId);
		attributeGetterFunctions.put("classPK", JSONStoreEntry::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<JSONStoreEntry, Long>)JSONStoreEntry::setClassPK);
		attributeGetterFunctions.put(
			"parentJSONStoreEntryId",
			JSONStoreEntry::getParentJSONStoreEntryId);
		attributeSetterBiConsumers.put(
			"parentJSONStoreEntryId",
			(BiConsumer<JSONStoreEntry, Long>)
				JSONStoreEntry::setParentJSONStoreEntryId);
		attributeGetterFunctions.put("index", JSONStoreEntry::getIndex);
		attributeSetterBiConsumers.put(
			"index",
			(BiConsumer<JSONStoreEntry, Integer>)JSONStoreEntry::setIndex);
		attributeGetterFunctions.put("key", JSONStoreEntry::getKey);
		attributeSetterBiConsumers.put(
			"key", (BiConsumer<JSONStoreEntry, String>)JSONStoreEntry::setKey);
		attributeGetterFunctions.put("type", JSONStoreEntry::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<JSONStoreEntry, Integer>)JSONStoreEntry::setType);
		attributeGetterFunctions.put("valueLong", JSONStoreEntry::getValueLong);
		attributeSetterBiConsumers.put(
			"valueLong",
			(BiConsumer<JSONStoreEntry, Long>)JSONStoreEntry::setValueLong);
		attributeGetterFunctions.put(
			"valueString", JSONStoreEntry::getValueString);
		attributeSetterBiConsumers.put(
			"valueString",
			(BiConsumer<JSONStoreEntry, String>)JSONStoreEntry::setValueString);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getJsonStoreEntryId() {
		return _jsonStoreEntryId;
	}

	@Override
	public void setJsonStoreEntryId(long jsonStoreEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jsonStoreEntryId = jsonStoreEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@Override
	public long getParentJSONStoreEntryId() {
		return _parentJSONStoreEntryId;
	}

	@Override
	public void setParentJSONStoreEntryId(long parentJSONStoreEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentJSONStoreEntryId = parentJSONStoreEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentJSONStoreEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentJSONStoreEntryId"));
	}

	@Override
	public int getIndex() {
		return _index;
	}

	@Override
	public void setIndex(int index) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_index = index;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalIndex() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("index_"));
	}

	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_key = key;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalKey() {
		return getColumnOriginalValue("key_");
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalType() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("type_"));
	}

	@Override
	public long getValueLong() {
		return _valueLong;
	}

	@Override
	public void setValueLong(long valueLong) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valueLong = valueLong;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalValueLong() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("valueLong"));
	}

	@Override
	public String getValueString() {
		if (_valueString == null) {
			return "";
		}
		else {
			return _valueString;
		}
	}

	@Override
	public void setValueString(String valueString) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valueString = valueString;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), JSONStoreEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JSONStoreEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JSONStoreEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JSONStoreEntryImpl jsonStoreEntryImpl = new JSONStoreEntryImpl();

		jsonStoreEntryImpl.setMvccVersion(getMvccVersion());
		jsonStoreEntryImpl.setCtCollectionId(getCtCollectionId());
		jsonStoreEntryImpl.setJsonStoreEntryId(getJsonStoreEntryId());
		jsonStoreEntryImpl.setCompanyId(getCompanyId());
		jsonStoreEntryImpl.setClassNameId(getClassNameId());
		jsonStoreEntryImpl.setClassPK(getClassPK());
		jsonStoreEntryImpl.setParentJSONStoreEntryId(
			getParentJSONStoreEntryId());
		jsonStoreEntryImpl.setIndex(getIndex());
		jsonStoreEntryImpl.setKey(getKey());
		jsonStoreEntryImpl.setType(getType());
		jsonStoreEntryImpl.setValueLong(getValueLong());
		jsonStoreEntryImpl.setValueString(getValueString());

		jsonStoreEntryImpl.resetOriginalValues();

		return jsonStoreEntryImpl;
	}

	@Override
	public int compareTo(JSONStoreEntry jsonStoreEntry) {
		int value = 0;

		if (getIndex() < jsonStoreEntry.getIndex()) {
			value = -1;
		}
		else if (getIndex() > jsonStoreEntry.getIndex()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof JSONStoreEntry)) {
			return false;
		}

		JSONStoreEntry jsonStoreEntry = (JSONStoreEntry)object;

		long primaryKey = jsonStoreEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<JSONStoreEntry> toCacheModel() {
		JSONStoreEntryCacheModel jsonStoreEntryCacheModel =
			new JSONStoreEntryCacheModel();

		jsonStoreEntryCacheModel.mvccVersion = getMvccVersion();

		jsonStoreEntryCacheModel.ctCollectionId = getCtCollectionId();

		jsonStoreEntryCacheModel.jsonStoreEntryId = getJsonStoreEntryId();

		jsonStoreEntryCacheModel.companyId = getCompanyId();

		jsonStoreEntryCacheModel.classNameId = getClassNameId();

		jsonStoreEntryCacheModel.classPK = getClassPK();

		jsonStoreEntryCacheModel.parentJSONStoreEntryId =
			getParentJSONStoreEntryId();

		jsonStoreEntryCacheModel.index = getIndex();

		jsonStoreEntryCacheModel.key = getKey();

		String key = jsonStoreEntryCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			jsonStoreEntryCacheModel.key = null;
		}

		jsonStoreEntryCacheModel.type = getType();

		jsonStoreEntryCacheModel.valueLong = getValueLong();

		jsonStoreEntryCacheModel.valueString = getValueString();

		String valueString = jsonStoreEntryCacheModel.valueString;

		if ((valueString != null) && (valueString.length() == 0)) {
			jsonStoreEntryCacheModel.valueString = null;
		}

		return jsonStoreEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JSONStoreEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<JSONStoreEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JSONStoreEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((JSONStoreEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<JSONStoreEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<JSONStoreEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JSONStoreEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((JSONStoreEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, JSONStoreEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _jsonStoreEntryId;
	private long _companyId;
	private long _classNameId;
	private long _classPK;
	private long _parentJSONStoreEntryId;
	private int _index;
	private String _key;
	private int _type;
	private long _valueLong;
	private String _valueString;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<JSONStoreEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((JSONStoreEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("jsonStoreEntryId", _jsonStoreEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put(
			"parentJSONStoreEntryId", _parentJSONStoreEntryId);
		_columnOriginalValues.put("index_", _index);
		_columnOriginalValues.put("key_", _key);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("valueLong", _valueLong);
		_columnOriginalValues.put("valueString", _valueString);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("index_", "index");
		attributeNames.put("key_", "key");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("jsonStoreEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("classNameId", 16L);

		columnBitmasks.put("classPK", 32L);

		columnBitmasks.put("parentJSONStoreEntryId", 64L);

		columnBitmasks.put("index_", 128L);

		columnBitmasks.put("key_", 256L);

		columnBitmasks.put("type_", 512L);

		columnBitmasks.put("valueLong", 1024L);

		columnBitmasks.put("valueString", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private JSONStoreEntry _escapedModel;

}