modified.files.includes[relevant][customer-solutions-rule]=**

playwright.test.project[relevant][customer-solutions-rule][playwright-js-tomcat90-mysql57-jdk8]=customer

relevant.rule.names=customer-solutions-rule

test.batch.names[relevant][customer-solutions-rule]=playwright-js-tomcat90-mysql57-jdk8