##
## Test Batch
##

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        util/portal-tools-db-partition-migration-validator-test/**/*Test.java