/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.site.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.site.model.XMLSitemapRegenerationEntry;
import com.liferay.site.service.XMLSitemapRegenerationEntryLocalService;
import com.liferay.site.service.persistence.XMLSitemapRegenerationEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the xml sitemap regeneration entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.site.service.impl.XMLSitemapRegenerationEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.site.service.impl.XMLSitemapRegenerationEntryLocalServiceImpl
 * @generated
 */
public abstract class XMLSitemapRegenerationEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   XMLSitemapRegenerationEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>XMLSitemapRegenerationEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.site.service.XMLSitemapRegenerationEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the xml sitemap regeneration entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect XMLSitemapRegenerationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param xmlSitemapRegenerationEntry the xml sitemap regeneration entry
	 * @return the xml sitemap regeneration entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public XMLSitemapRegenerationEntry addXMLSitemapRegenerationEntry(
		XMLSitemapRegenerationEntry xmlSitemapRegenerationEntry) {

		xmlSitemapRegenerationEntry.setNew(true);

		return xmlSitemapRegenerationEntryPersistence.update(
			xmlSitemapRegenerationEntry);
	}

	/**
	 * Creates a new xml sitemap regeneration entry with the primary key. Does not add the xml sitemap regeneration entry to the database.
	 *
	 * @param xmlSitemapRegenerationEntryId the primary key for the new xml sitemap regeneration entry
	 * @return the new xml sitemap regeneration entry
	 */
	@Override
	@Transactional(enabled = false)
	public XMLSitemapRegenerationEntry createXMLSitemapRegenerationEntry(
		long xmlSitemapRegenerationEntryId) {

		return xmlSitemapRegenerationEntryPersistence.create(
			xmlSitemapRegenerationEntryId);
	}

	/**
	 * Deletes the xml sitemap regeneration entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect XMLSitemapRegenerationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param xmlSitemapRegenerationEntryId the primary key of the xml sitemap regeneration entry
	 * @return the xml sitemap regeneration entry that was removed
	 * @throws PortalException if a xml sitemap regeneration entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public XMLSitemapRegenerationEntry deleteXMLSitemapRegenerationEntry(
			long xmlSitemapRegenerationEntryId)
		throws PortalException {

		return xmlSitemapRegenerationEntryPersistence.remove(
			xmlSitemapRegenerationEntryId);
	}

	/**
	 * Deletes the xml sitemap regeneration entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect XMLSitemapRegenerationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param xmlSitemapRegenerationEntry the xml sitemap regeneration entry
	 * @return the xml sitemap regeneration entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public XMLSitemapRegenerationEntry deleteXMLSitemapRegenerationEntry(
		XMLSitemapRegenerationEntry xmlSitemapRegenerationEntry) {

		return xmlSitemapRegenerationEntryPersistence.remove(
			xmlSitemapRegenerationEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return xmlSitemapRegenerationEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			XMLSitemapRegenerationEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return xmlSitemapRegenerationEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.site.model.impl.XMLSitemapRegenerationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return xmlSitemapRegenerationEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.site.model.impl.XMLSitemapRegenerationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return xmlSitemapRegenerationEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return xmlSitemapRegenerationEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return xmlSitemapRegenerationEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public XMLSitemapRegenerationEntry fetchXMLSitemapRegenerationEntry(
		long xmlSitemapRegenerationEntryId) {

		return xmlSitemapRegenerationEntryPersistence.fetchByPrimaryKey(
			xmlSitemapRegenerationEntryId);
	}

	/**
	 * Returns the xml sitemap regeneration entry with the primary key.
	 *
	 * @param xmlSitemapRegenerationEntryId the primary key of the xml sitemap regeneration entry
	 * @return the xml sitemap regeneration entry
	 * @throws PortalException if a xml sitemap regeneration entry with the primary key could not be found
	 */
	@Override
	public XMLSitemapRegenerationEntry getXMLSitemapRegenerationEntry(
			long xmlSitemapRegenerationEntryId)
		throws PortalException {

		return xmlSitemapRegenerationEntryPersistence.findByPrimaryKey(
			xmlSitemapRegenerationEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			xmlSitemapRegenerationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(XMLSitemapRegenerationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"xmlSitemapRegenerationEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			xmlSitemapRegenerationEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			XMLSitemapRegenerationEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"xmlSitemapRegenerationEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			xmlSitemapRegenerationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(XMLSitemapRegenerationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"xmlSitemapRegenerationEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return xmlSitemapRegenerationEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement XMLSitemapRegenerationEntryLocalServiceImpl#deleteXMLSitemapRegenerationEntry(XMLSitemapRegenerationEntry) to avoid orphaned data");
		}

		return xmlSitemapRegenerationEntryLocalService.
			deleteXMLSitemapRegenerationEntry(
				(XMLSitemapRegenerationEntry)persistedModel);
	}

	@Override
	public BasePersistence<XMLSitemapRegenerationEntry> getBasePersistence() {
		return xmlSitemapRegenerationEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return xmlSitemapRegenerationEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the xml sitemap regeneration entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.site.model.impl.XMLSitemapRegenerationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of xml sitemap regeneration entries
	 * @param end the upper bound of the range of xml sitemap regeneration entries (not inclusive)
	 * @return the range of xml sitemap regeneration entries
	 */
	@Override
	public List<XMLSitemapRegenerationEntry> getXMLSitemapRegenerationEntries(
		int start, int end) {

		return xmlSitemapRegenerationEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of xml sitemap regeneration entries.
	 *
	 * @return the number of xml sitemap regeneration entries
	 */
	@Override
	public int getXMLSitemapRegenerationEntriesCount() {
		return xmlSitemapRegenerationEntryPersistence.countAll();
	}

	/**
	 * Updates the xml sitemap regeneration entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect XMLSitemapRegenerationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param xmlSitemapRegenerationEntry the xml sitemap regeneration entry
	 * @return the xml sitemap regeneration entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public XMLSitemapRegenerationEntry updateXMLSitemapRegenerationEntry(
		XMLSitemapRegenerationEntry xmlSitemapRegenerationEntry) {

		return xmlSitemapRegenerationEntryPersistence.update(
			xmlSitemapRegenerationEntry);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			XMLSitemapRegenerationEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		xmlSitemapRegenerationEntryLocalService =
			(XMLSitemapRegenerationEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return XMLSitemapRegenerationEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return XMLSitemapRegenerationEntry.class;
	}

	protected String getModelClassName() {
		return XMLSitemapRegenerationEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			xmlSitemapRegenerationEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected XMLSitemapRegenerationEntryLocalService
		xmlSitemapRegenerationEntryLocalService;

	@Reference
	protected XMLSitemapRegenerationEntryPersistence
		xmlSitemapRegenerationEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		XMLSitemapRegenerationEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:835562849