##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    legacy.language.keys=\
        you-can-also-forcibly-disable-remote-staging