/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.seo.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.seo.model.LayoutSEOOpenGraphEntry;
import com.liferay.layout.seo.service.LayoutSEOOpenGraphEntryLocalService;
import com.liferay.layout.seo.service.persistence.LayoutSEOOpenGraphEntryPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout seo open graph entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.seo.service.impl.LayoutSEOOpenGraphEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.seo.service.impl.LayoutSEOOpenGraphEntryLocalServiceImpl
 * @generated
 */
public abstract class LayoutSEOOpenGraphEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   LayoutSEOOpenGraphEntryLocalService {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LayoutSEOOpenGraphEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.layout.seo.service.LayoutSEOOpenGraphEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the layout seo open graph entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutSEOOpenGraphEntry the layout seo open graph entry
	 * @return the layout seo open graph entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutSEOOpenGraphEntry addLayoutSEOOpenGraphEntry(
		LayoutSEOOpenGraphEntry layoutSEOOpenGraphEntry) {

		layoutSEOOpenGraphEntry.setNew(true);

		return layoutSEOOpenGraphEntryPersistence.update(
			layoutSEOOpenGraphEntry);
	}

	/**
	 * Creates a new layout seo open graph entry with the primary key. Does not add the layout seo open graph entry to the database.
	 *
	 * @param layoutSEOEntryId the primary key for the new layout seo open graph entry
	 * @return the new layout seo open graph entry
	 */
	@Override
	@Transactional(enabled = false)
	public LayoutSEOOpenGraphEntry createLayoutSEOOpenGraphEntry(
		long layoutSEOEntryId) {

		return layoutSEOOpenGraphEntryPersistence.create(layoutSEOEntryId);
	}

	/**
	 * Deletes the layout seo open graph entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutSEOEntryId the primary key of the layout seo open graph entry
	 * @return the layout seo open graph entry that was removed
	 * @throws PortalException if a layout seo open graph entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutSEOOpenGraphEntry deleteLayoutSEOOpenGraphEntry(
			long layoutSEOEntryId)
		throws PortalException {

		return layoutSEOOpenGraphEntryPersistence.remove(layoutSEOEntryId);
	}

	/**
	 * Deletes the layout seo open graph entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param layoutSEOOpenGraphEntry the layout seo open graph entry
	 * @return the layout seo open graph entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutSEOOpenGraphEntry deleteLayoutSEOOpenGraphEntry(
		LayoutSEOOpenGraphEntry layoutSEOOpenGraphEntry) {

		return layoutSEOOpenGraphEntryPersistence.remove(
			layoutSEOOpenGraphEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LayoutSEOOpenGraphEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return layoutSEOOpenGraphEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOOpenGraphEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return layoutSEOOpenGraphEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOOpenGraphEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return layoutSEOOpenGraphEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return layoutSEOOpenGraphEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return layoutSEOOpenGraphEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LayoutSEOOpenGraphEntry fetchLayoutSEOOpenGraphEntry(
		long layoutSEOEntryId) {

		return layoutSEOOpenGraphEntryPersistence.fetchByPrimaryKey(
			layoutSEOEntryId);
	}

	/**
	 * Returns the layout seo open graph entry matching the UUID and group.
	 *
	 * @param uuid the layout seo open graph entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout seo open graph entry, or <code>null</code> if a matching layout seo open graph entry could not be found
	 */
	@Override
	public LayoutSEOOpenGraphEntry fetchLayoutSEOOpenGraphEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return layoutSEOOpenGraphEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the layout seo open graph entry with the primary key.
	 *
	 * @param layoutSEOEntryId the primary key of the layout seo open graph entry
	 * @return the layout seo open graph entry
	 * @throws PortalException if a layout seo open graph entry with the primary key could not be found
	 */
	@Override
	public LayoutSEOOpenGraphEntry getLayoutSEOOpenGraphEntry(
			long layoutSEOEntryId)
		throws PortalException {

		return layoutSEOOpenGraphEntryPersistence.findByPrimaryKey(
			layoutSEOEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			layoutSEOOpenGraphEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutSEOOpenGraphEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("layoutSEOEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			layoutSEOOpenGraphEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LayoutSEOOpenGraphEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutSEOEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			layoutSEOOpenGraphEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutSEOOpenGraphEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("layoutSEOEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setGroupId(
			portletDataContext.getScopeGroupId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<LayoutSEOOpenGraphEntry>() {

				@Override
				public void performAction(
						LayoutSEOOpenGraphEntry layoutSEOOpenGraphEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, layoutSEOOpenGraphEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					LayoutSEOOpenGraphEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return layoutSEOOpenGraphEntryLocalService.
			deleteLayoutSEOOpenGraphEntry(
				(LayoutSEOOpenGraphEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutSEOOpenGraphEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the layout seo open graph entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout seo open graph entries
	 * @param companyId the primary key of the company
	 * @return the matching layout seo open graph entries, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutSEOOpenGraphEntry>
		getLayoutSEOOpenGraphEntriesByUuidAndCompanyId(
			String uuid, long companyId) {

		return layoutSEOOpenGraphEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of layout seo open graph entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout seo open graph entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of layout seo open graph entries
	 * @param end the upper bound of the range of layout seo open graph entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching layout seo open graph entries, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutSEOOpenGraphEntry>
		getLayoutSEOOpenGraphEntriesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<LayoutSEOOpenGraphEntry> orderByComparator) {

		return layoutSEOOpenGraphEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the layout seo open graph entry matching the UUID and group.
	 *
	 * @param uuid the layout seo open graph entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout seo open graph entry
	 * @throws PortalException if a matching layout seo open graph entry could not be found
	 */
	@Override
	public LayoutSEOOpenGraphEntry getLayoutSEOOpenGraphEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return layoutSEOOpenGraphEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the layout seo open graph entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOOpenGraphEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of layout seo open graph entries
	 * @param end the upper bound of the range of layout seo open graph entries (not inclusive)
	 * @return the range of layout seo open graph entries
	 */
	@Override
	public List<LayoutSEOOpenGraphEntry> getLayoutSEOOpenGraphEntries(
		int start, int end) {

		return layoutSEOOpenGraphEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of layout seo open graph entries.
	 *
	 * @return the number of layout seo open graph entries
	 */
	@Override
	public int getLayoutSEOOpenGraphEntriesCount() {
		return layoutSEOOpenGraphEntryPersistence.countAll();
	}

	/**
	 * Updates the layout seo open graph entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param layoutSEOOpenGraphEntry the layout seo open graph entry
	 * @return the layout seo open graph entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutSEOOpenGraphEntry updateLayoutSEOOpenGraphEntry(
		LayoutSEOOpenGraphEntry layoutSEOOpenGraphEntry) {

		return layoutSEOOpenGraphEntryPersistence.update(
			layoutSEOOpenGraphEntry);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LayoutSEOOpenGraphEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		layoutSEOOpenGraphEntryLocalService =
			(LayoutSEOOpenGraphEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutSEOOpenGraphEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LayoutSEOOpenGraphEntry.class;
	}

	protected String getModelClassName() {
		return LayoutSEOOpenGraphEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				layoutSEOOpenGraphEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	protected LayoutSEOOpenGraphEntryLocalService
		layoutSEOOpenGraphEntryLocalService;

	@Reference
	protected LayoutSEOOpenGraphEntryPersistence
		layoutSEOOpenGraphEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.GroupLocalService
		groupLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.LayoutLocalService
		layoutLocalService;

}