/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.repository.model.impl;

import com.liferay.content.repository.model.ContentRepositoryEntry;
import com.liferay.content.repository.service.ContentRepositoryEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ContentRepositoryEntry service. Represents a row in the &quot;ContentRepositoryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentRepositoryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentRepositoryEntryImpl
 * @see ContentRepositoryEntry
 * @generated
 */
public abstract class ContentRepositoryEntryBaseImpl
	extends ContentRepositoryEntryModelImpl implements ContentRepositoryEntry {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a content repository entry model instance should use the <code>ContentRepositoryEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContentRepositoryEntryLocalServiceUtil.addContentRepositoryEntry(
				this);
		}
		else {
			ContentRepositoryEntryLocalServiceUtil.updateContentRepositoryEntry(
				this);
		}
	}

}