/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.repository.model.impl;

import com.liferay.content.repository.model.ContentRepositoryEntry;
import com.liferay.content.repository.model.ContentRepositoryEntryModel;
import com.liferay.content.repository.model.ContentRepositoryEntrySoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ContentRepositoryEntry service. Represents a row in the &quot;ContentRepositoryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ContentRepositoryEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentRepositoryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentRepositoryEntryImpl
 * @generated
 */
@JSON(strict = true)
public class ContentRepositoryEntryModelImpl
	extends BaseModelImpl<ContentRepositoryEntry>
	implements ContentRepositoryEntryModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a content repository entry model instance should use the <code>ContentRepositoryEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ContentRepositoryEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"contentRepositoryEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contentRepositoryEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ContentRepositoryEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,contentRepositoryEntryId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,groupId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ContentRepositoryEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contentRepositoryEntry.contentRepositoryEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ContentRepositoryEntry.contentRepositoryEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long CONTENTREPOSITORYENTRYID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContentRepositoryEntry toModel(
		ContentRepositoryEntrySoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		ContentRepositoryEntry model = new ContentRepositoryEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setContentRepositoryEntryId(
			soapModel.getContentRepositoryEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContentRepositoryEntry> toModels(
		ContentRepositoryEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ContentRepositoryEntry> models =
			new ArrayList<ContentRepositoryEntry>(soapModels.length);

		for (ContentRepositoryEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ContentRepositoryEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contentRepositoryEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContentRepositoryEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contentRepositoryEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContentRepositoryEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ContentRepositoryEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContentRepositoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContentRepositoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContentRepositoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContentRepositoryEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContentRepositoryEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContentRepositoryEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContentRepositoryEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContentRepositoryEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContentRepositoryEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ContentRepositoryEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ContentRepositoryEntry.class.getClassLoader(),
			ContentRepositoryEntry.class, ModelWrapper.class);

		try {
			Constructor<ContentRepositoryEntry> constructor =
				(Constructor<ContentRepositoryEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ContentRepositoryEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ContentRepositoryEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ContentRepositoryEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ContentRepositoryEntry, Object>>();
		Map<String, BiConsumer<ContentRepositoryEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ContentRepositoryEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", ContentRepositoryEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ContentRepositoryEntry, Long>)
				ContentRepositoryEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", ContentRepositoryEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ContentRepositoryEntry, String>)
				ContentRepositoryEntry::setUuid);
		attributeGetterFunctions.put(
			"contentRepositoryEntryId",
			ContentRepositoryEntry::getContentRepositoryEntryId);
		attributeSetterBiConsumers.put(
			"contentRepositoryEntryId",
			(BiConsumer<ContentRepositoryEntry, Long>)
				ContentRepositoryEntry::setContentRepositoryEntryId);
		attributeGetterFunctions.put(
			"companyId", ContentRepositoryEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ContentRepositoryEntry, Long>)
				ContentRepositoryEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", ContentRepositoryEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ContentRepositoryEntry, Long>)
				ContentRepositoryEntry::setUserId);
		attributeGetterFunctions.put(
			"createDate", ContentRepositoryEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ContentRepositoryEntry, Date>)
				ContentRepositoryEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ContentRepositoryEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ContentRepositoryEntry, Date>)
				ContentRepositoryEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"groupId", ContentRepositoryEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ContentRepositoryEntry, Long>)
				ContentRepositoryEntry::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getContentRepositoryEntryId() {
		return _contentRepositoryEntryId;
	}

	@Override
	public void setContentRepositoryEntryId(long contentRepositoryEntryId) {
		_contentRepositoryEntryId = contentRepositoryEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ContentRepositoryEntry.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ContentRepositoryEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContentRepositoryEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContentRepositoryEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContentRepositoryEntryImpl contentRepositoryEntryImpl =
			new ContentRepositoryEntryImpl();

		contentRepositoryEntryImpl.setMvccVersion(getMvccVersion());
		contentRepositoryEntryImpl.setUuid(getUuid());
		contentRepositoryEntryImpl.setContentRepositoryEntryId(
			getContentRepositoryEntryId());
		contentRepositoryEntryImpl.setCompanyId(getCompanyId());
		contentRepositoryEntryImpl.setUserId(getUserId());
		contentRepositoryEntryImpl.setCreateDate(getCreateDate());
		contentRepositoryEntryImpl.setModifiedDate(getModifiedDate());
		contentRepositoryEntryImpl.setGroupId(getGroupId());

		contentRepositoryEntryImpl.resetOriginalValues();

		return contentRepositoryEntryImpl;
	}

	@Override
	public int compareTo(ContentRepositoryEntry contentRepositoryEntry) {
		long primaryKey = contentRepositoryEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ContentRepositoryEntry)) {
			return false;
		}

		ContentRepositoryEntry contentRepositoryEntry =
			(ContentRepositoryEntry)obj;

		long primaryKey = contentRepositoryEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ContentRepositoryEntryModelImpl contentRepositoryEntryModelImpl = this;

		contentRepositoryEntryModelImpl._originalUuid =
			contentRepositoryEntryModelImpl._uuid;

		contentRepositoryEntryModelImpl._originalCompanyId =
			contentRepositoryEntryModelImpl._companyId;

		contentRepositoryEntryModelImpl._setOriginalCompanyId = false;

		contentRepositoryEntryModelImpl._setModifiedDate = false;

		contentRepositoryEntryModelImpl._originalGroupId =
			contentRepositoryEntryModelImpl._groupId;

		contentRepositoryEntryModelImpl._setOriginalGroupId = false;

		contentRepositoryEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContentRepositoryEntry> toCacheModel() {
		ContentRepositoryEntryCacheModel contentRepositoryEntryCacheModel =
			new ContentRepositoryEntryCacheModel();

		contentRepositoryEntryCacheModel.mvccVersion = getMvccVersion();

		contentRepositoryEntryCacheModel.uuid = getUuid();

		String uuid = contentRepositoryEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contentRepositoryEntryCacheModel.uuid = null;
		}

		contentRepositoryEntryCacheModel.contentRepositoryEntryId =
			getContentRepositoryEntryId();

		contentRepositoryEntryCacheModel.companyId = getCompanyId();

		contentRepositoryEntryCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			contentRepositoryEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			contentRepositoryEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contentRepositoryEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			contentRepositoryEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contentRepositoryEntryCacheModel.groupId = getGroupId();

		return contentRepositoryEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContentRepositoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContentRepositoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContentRepositoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((ContentRepositoryEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ContentRepositoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ContentRepositoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContentRepositoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((ContentRepositoryEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContentRepositoryEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _contentRepositoryEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private ContentRepositoryEntry _escapedModel;

}