#
# Files that are using PwdGenerator correctly.
#
portal-impl/src/com/liferay/portal/security/auth/OpenSSOAutoLogin.java@58=true
portal-impl/src/com/liferay/portal/security/auth/SessionAuthToken.java@141=true
portal-impl/src/com/liferay/portal/security/pwd/PasswordPolicyToolkit.java@224=true
portal-impl/src/com/liferay/portal/security/pwd/PasswordPolicyToolkit.java@229=true
portal-impl/src/com/liferay/portal/security/pwd/RegExpToolkit.java@41=true
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java@3330=true
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java@3507=true
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java@4061=true
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java@5641=true
portal-impl/src/com/liferay/portal/util/FileImpl.java@235=true
portal-impl/src/com/liferay/portlet/login/action/CreateAccountAction.java@423=true
portal-impl/src/com/liferay/portlet/login/action/OpenIdAction.java@349=true
portal-impl/src/com/liferay/portlet/shopping/service/impl/ShoppingCouponLocalServiceImpl.java@242=true
portal-impl/src/com/liferay/portlet/shopping/service/impl/ShoppingItemLocalServiceImpl.java@668=true
portal-impl/src/com/liferay/portlet/shopping/service/impl/ShoppingItemLocalServiceImpl.java@690=true
portal-impl/src/com/liferay/portlet/shopping/service/impl/ShoppingItemLocalServiceImpl.java@712=true
portal-impl/src/com/liferay/portlet/shopping/service/impl/ShoppingOrderLocalServiceImpl.java@664=true
util-java/test/unit/com/liferay/util/PwdGeneratorTest.java@33=true