{{- $cloud := include "observability.cloudProvider" . -}}
{{- $rw := .Values.alloy.remoteWrite -}}
{{- if and .Values.alloy.enabled (ne $cloud "aws") (ne $cloud "gcp") (or $rw.basicAuth.password $rw.bearerToken) -}}
apiVersion: v1
kind: Secret
metadata:
    labels:
        {{- include "observability.labels" . | nindent 8 }}
    name: liferay-alloy-remote-write
    namespace: {{ include "observability.namespace" . | quote }}
stringData:
    {{- with $rw.basicAuth.password }}
    password: {{ . | quote }}
    {{- end }}
    {{- with $rw.bearerToken }}
    bearer-token: {{ . | quote }}
    {{- end }}
type: Opaque
{{- end -}}