/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.notification.model.NotificationQueueEntryRecipient;
import com.liferay.notification.model.NotificationQueueEntryRecipientModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotificationQueueEntryRecipient service. Represents a row in the &quot;NQueueEntryRecipient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationQueueEntryRecipientModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationQueueEntryRecipientImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationQueueEntryRecipientImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationQueueEntryRecipientModelImpl
	extends BaseModelImpl<NotificationQueueEntryRecipient>
	implements NotificationQueueEntryRecipientModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification queue entry recipient model instance should use the <code>NotificationQueueEntryRecipient</code> interface instead.
	 */
	public static final String TABLE_NAME = "NQueueEntryRecipient";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"NQueueEntryRecipientId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"notificationQueueEntryId", Types.BIGINT}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NQueueEntryRecipientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("notificationQueueEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NQueueEntryRecipient (mvccVersion LONG default 0 not null,NQueueEntryRecipientId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,notificationQueueEntryId LONG,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table NQueueEntryRecipient";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationQueueEntryRecipient.notificationQueueEntryRecipientId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NQueueEntryRecipient.NQueueEntryRecipientId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOTIFICATIONQUEUEENTRYRECIPIENTID_COLUMN_BITMASK =
		1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NotificationQueueEntryRecipientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationQueueEntryRecipientId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationQueueEntryRecipientId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationQueueEntryRecipientId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationQueueEntryRecipient.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationQueueEntryRecipient.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationQueueEntryRecipient, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String, Function<NotificationQueueEntryRecipient, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationQueueEntryRecipient, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(NotificationQueueEntryRecipient)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationQueueEntryRecipient, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationQueueEntryRecipient, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationQueueEntryRecipient)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationQueueEntryRecipient, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotificationQueueEntryRecipient, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<NotificationQueueEntryRecipient, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<NotificationQueueEntryRecipient, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationQueueEntryRecipient, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<NotificationQueueEntryRecipient, Object>>();
		Map<String, BiConsumer<NotificationQueueEntryRecipient, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<NotificationQueueEntryRecipient, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", NotificationQueueEntryRecipient::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<NotificationQueueEntryRecipient, Long>)
				NotificationQueueEntryRecipient::setMvccVersion);
		attributeGetterFunctions.put(
			"notificationQueueEntryRecipientId",
			NotificationQueueEntryRecipient::
				getNotificationQueueEntryRecipientId);
		attributeSetterBiConsumers.put(
			"notificationQueueEntryRecipientId",
			(BiConsumer<NotificationQueueEntryRecipient, Long>)
				NotificationQueueEntryRecipient::
					setNotificationQueueEntryRecipientId);
		attributeGetterFunctions.put(
			"companyId", NotificationQueueEntryRecipient::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationQueueEntryRecipient, Long>)
				NotificationQueueEntryRecipient::setCompanyId);
		attributeGetterFunctions.put(
			"userId", NotificationQueueEntryRecipient::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationQueueEntryRecipient, Long>)
				NotificationQueueEntryRecipient::setUserId);
		attributeGetterFunctions.put(
			"userName", NotificationQueueEntryRecipient::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationQueueEntryRecipient, String>)
				NotificationQueueEntryRecipient::setUserName);
		attributeGetterFunctions.put(
			"createDate", NotificationQueueEntryRecipient::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationQueueEntryRecipient, Date>)
				NotificationQueueEntryRecipient::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NotificationQueueEntryRecipient::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationQueueEntryRecipient, Date>)
				NotificationQueueEntryRecipient::setModifiedDate);
		attributeGetterFunctions.put(
			"notificationQueueEntryId",
			NotificationQueueEntryRecipient::getNotificationQueueEntryId);
		attributeSetterBiConsumers.put(
			"notificationQueueEntryId",
			(BiConsumer<NotificationQueueEntryRecipient, Long>)
				NotificationQueueEntryRecipient::setNotificationQueueEntryId);
		attributeGetterFunctions.put(
			"type", NotificationQueueEntryRecipient::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<NotificationQueueEntryRecipient, String>)
				NotificationQueueEntryRecipient::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getNotificationQueueEntryRecipientId() {
		return _notificationQueueEntryRecipientId;
	}

	@Override
	public void setNotificationQueueEntryRecipientId(
		long notificationQueueEntryRecipientId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationQueueEntryRecipientId = notificationQueueEntryRecipientId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNotificationQueueEntryId() {
		return _notificationQueueEntryId;
	}

	@Override
	public void setNotificationQueueEntryId(long notificationQueueEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationQueueEntryId = notificationQueueEntryId;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NotificationQueueEntryRecipient.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationQueueEntryRecipient toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationQueueEntryRecipient>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationQueueEntryRecipientImpl
			notificationQueueEntryRecipientImpl =
				new NotificationQueueEntryRecipientImpl();

		notificationQueueEntryRecipientImpl.setMvccVersion(getMvccVersion());
		notificationQueueEntryRecipientImpl.
			setNotificationQueueEntryRecipientId(
				getNotificationQueueEntryRecipientId());
		notificationQueueEntryRecipientImpl.setCompanyId(getCompanyId());
		notificationQueueEntryRecipientImpl.setUserId(getUserId());
		notificationQueueEntryRecipientImpl.setUserName(getUserName());
		notificationQueueEntryRecipientImpl.setCreateDate(getCreateDate());
		notificationQueueEntryRecipientImpl.setModifiedDate(getModifiedDate());
		notificationQueueEntryRecipientImpl.setNotificationQueueEntryId(
			getNotificationQueueEntryId());
		notificationQueueEntryRecipientImpl.setType(getType());

		notificationQueueEntryRecipientImpl.resetOriginalValues();

		return notificationQueueEntryRecipientImpl;
	}

	@Override
	public NotificationQueueEntryRecipient cloneWithOriginalValues() {
		NotificationQueueEntryRecipientImpl
			notificationQueueEntryRecipientImpl =
				new NotificationQueueEntryRecipientImpl();

		notificationQueueEntryRecipientImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		notificationQueueEntryRecipientImpl.
			setNotificationQueueEntryRecipientId(
				this.<Long>getColumnOriginalValue("NQueueEntryRecipientId"));
		notificationQueueEntryRecipientImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		notificationQueueEntryRecipientImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		notificationQueueEntryRecipientImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		notificationQueueEntryRecipientImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		notificationQueueEntryRecipientImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		notificationQueueEntryRecipientImpl.setNotificationQueueEntryId(
			this.<Long>getColumnOriginalValue("notificationQueueEntryId"));
		notificationQueueEntryRecipientImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return notificationQueueEntryRecipientImpl;
	}

	@Override
	public int compareTo(
		NotificationQueueEntryRecipient notificationQueueEntryRecipient) {

		long primaryKey = notificationQueueEntryRecipient.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationQueueEntryRecipient)) {
			return false;
		}

		NotificationQueueEntryRecipient notificationQueueEntryRecipient =
			(NotificationQueueEntryRecipient)object;

		long primaryKey = notificationQueueEntryRecipient.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationQueueEntryRecipient> toCacheModel() {
		NotificationQueueEntryRecipientCacheModel
			notificationQueueEntryRecipientCacheModel =
				new NotificationQueueEntryRecipientCacheModel();

		notificationQueueEntryRecipientCacheModel.mvccVersion =
			getMvccVersion();

		notificationQueueEntryRecipientCacheModel.
			notificationQueueEntryRecipientId =
				getNotificationQueueEntryRecipientId();

		notificationQueueEntryRecipientCacheModel.companyId = getCompanyId();

		notificationQueueEntryRecipientCacheModel.userId = getUserId();

		notificationQueueEntryRecipientCacheModel.userName = getUserName();

		String userName = notificationQueueEntryRecipientCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationQueueEntryRecipientCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationQueueEntryRecipientCacheModel.createDate =
				createDate.getTime();
		}
		else {
			notificationQueueEntryRecipientCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationQueueEntryRecipientCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			notificationQueueEntryRecipientCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		notificationQueueEntryRecipientCacheModel.notificationQueueEntryId =
			getNotificationQueueEntryId();

		notificationQueueEntryRecipientCacheModel.type = getType();

		String type = notificationQueueEntryRecipientCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			notificationQueueEntryRecipientCacheModel.type = null;
		}

		return notificationQueueEntryRecipientCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationQueueEntryRecipient, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String, Function<NotificationQueueEntryRecipient, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationQueueEntryRecipient, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NotificationQueueEntryRecipient)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, NotificationQueueEntryRecipient>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						NotificationQueueEntryRecipient.class,
						ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _notificationQueueEntryRecipientId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _notificationQueueEntryId;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationQueueEntryRecipient, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationQueueEntryRecipient)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"NQueueEntryRecipientId", _notificationQueueEntryRecipientId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"notificationQueueEntryId", _notificationQueueEntryId);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put(
			"NQueueEntryRecipientId", "notificationQueueEntryRecipientId");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("NQueueEntryRecipientId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("notificationQueueEntryId", 128L);

		columnBitmasks.put("type_", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationQueueEntryRecipient _escapedModel;

}