/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.notification.model.NotificationQueueEntryRecipientSetting;
import com.liferay.notification.model.NotificationQueueEntryRecipientSettingModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotificationQueueEntryRecipientSetting service. Represents a row in the &quot;NQueueEntryRecipientSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationQueueEntryRecipientSettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationQueueEntryRecipientSettingImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationQueueEntryRecipientSettingImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationQueueEntryRecipientSettingModelImpl
	extends BaseModelImpl<NotificationQueueEntryRecipientSetting>
	implements NotificationQueueEntryRecipientSettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification queue entry recipient setting model instance should use the <code>NotificationQueueEntryRecipientSetting</code> interface instead.
	 */
	public static final String TABLE_NAME = "NQueueEntryRecipientSetting";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"NQueueEntryRecipientSettingId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"NQueueEntryRecipientId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NQueueEntryRecipientSettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("NQueueEntryRecipientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NQueueEntryRecipientSetting (mvccVersion LONG default 0 not null,NQueueEntryRecipientSettingId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,NQueueEntryRecipientId LONG,name VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table NQueueEntryRecipientSetting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationQueueEntryRecipientSetting.notificationQueueEntryRecipientSettingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NQueueEntryRecipientSetting.NQueueEntryRecipientSettingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long
		NOTIFICATIONQUEUEENTRYRECIPIENTSETTINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NotificationQueueEntryRecipientSettingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationQueueEntryRecipientSettingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationQueueEntryRecipientSettingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationQueueEntryRecipientSettingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationQueueEntryRecipientSetting.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationQueueEntryRecipientSetting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationQueueEntryRecipientSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String,
				 Function<NotificationQueueEntryRecipientSetting, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationQueueEntryRecipientSetting, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(NotificationQueueEntryRecipientSetting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationQueueEntryRecipientSetting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationQueueEntryRecipientSetting, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationQueueEntryRecipientSetting)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationQueueEntryRecipientSetting, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map
		<String, BiConsumer<NotificationQueueEntryRecipientSetting, Object>>
			getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<NotificationQueueEntryRecipientSetting, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<NotificationQueueEntryRecipientSetting, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationQueueEntryRecipientSetting, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function
						 <NotificationQueueEntryRecipientSetting, Object>>();
		Map<String, BiConsumer<NotificationQueueEntryRecipientSetting, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<NotificationQueueEntryRecipientSetting, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion",
			NotificationQueueEntryRecipientSetting::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Long>)
				NotificationQueueEntryRecipientSetting::setMvccVersion);
		attributeGetterFunctions.put(
			"notificationQueueEntryRecipientSettingId",
			NotificationQueueEntryRecipientSetting::
				getNotificationQueueEntryRecipientSettingId);
		attributeSetterBiConsumers.put(
			"notificationQueueEntryRecipientSettingId",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Long>)
				NotificationQueueEntryRecipientSetting::
					setNotificationQueueEntryRecipientSettingId);
		attributeGetterFunctions.put(
			"companyId", NotificationQueueEntryRecipientSetting::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Long>)
				NotificationQueueEntryRecipientSetting::setCompanyId);
		attributeGetterFunctions.put(
			"userId", NotificationQueueEntryRecipientSetting::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Long>)
				NotificationQueueEntryRecipientSetting::setUserId);
		attributeGetterFunctions.put(
			"userName", NotificationQueueEntryRecipientSetting::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationQueueEntryRecipientSetting, String>)
				NotificationQueueEntryRecipientSetting::setUserName);
		attributeGetterFunctions.put(
			"createDate",
			NotificationQueueEntryRecipientSetting::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Date>)
				NotificationQueueEntryRecipientSetting::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate",
			NotificationQueueEntryRecipientSetting::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Date>)
				NotificationQueueEntryRecipientSetting::setModifiedDate);
		attributeGetterFunctions.put(
			"notificationQueueEntryRecipientId",
			NotificationQueueEntryRecipientSetting::
				getNotificationQueueEntryRecipientId);
		attributeSetterBiConsumers.put(
			"notificationQueueEntryRecipientId",
			(BiConsumer<NotificationQueueEntryRecipientSetting, Long>)
				NotificationQueueEntryRecipientSetting::
					setNotificationQueueEntryRecipientId);
		attributeGetterFunctions.put(
			"name", NotificationQueueEntryRecipientSetting::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<NotificationQueueEntryRecipientSetting, String>)
				NotificationQueueEntryRecipientSetting::setName);
		attributeGetterFunctions.put(
			"value", NotificationQueueEntryRecipientSetting::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<NotificationQueueEntryRecipientSetting, String>)
				NotificationQueueEntryRecipientSetting::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getNotificationQueueEntryRecipientSettingId() {
		return _notificationQueueEntryRecipientSettingId;
	}

	@Override
	public void setNotificationQueueEntryRecipientSettingId(
		long notificationQueueEntryRecipientSettingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationQueueEntryRecipientSettingId =
			notificationQueueEntryRecipientSettingId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNotificationQueueEntryRecipientId() {
		return _notificationQueueEntryRecipientId;
	}

	@Override
	public void setNotificationQueueEntryRecipientId(
		long notificationQueueEntryRecipientId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationQueueEntryRecipientId = notificationQueueEntryRecipientId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			NotificationQueueEntryRecipientSetting.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationQueueEntryRecipientSetting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationQueueEntryRecipientSetting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationQueueEntryRecipientSettingImpl
			notificationQueueEntryRecipientSettingImpl =
				new NotificationQueueEntryRecipientSettingImpl();

		notificationQueueEntryRecipientSettingImpl.setMvccVersion(
			getMvccVersion());
		notificationQueueEntryRecipientSettingImpl.
			setNotificationQueueEntryRecipientSettingId(
				getNotificationQueueEntryRecipientSettingId());
		notificationQueueEntryRecipientSettingImpl.setCompanyId(getCompanyId());
		notificationQueueEntryRecipientSettingImpl.setUserId(getUserId());
		notificationQueueEntryRecipientSettingImpl.setUserName(getUserName());
		notificationQueueEntryRecipientSettingImpl.setCreateDate(
			getCreateDate());
		notificationQueueEntryRecipientSettingImpl.setModifiedDate(
			getModifiedDate());
		notificationQueueEntryRecipientSettingImpl.
			setNotificationQueueEntryRecipientId(
				getNotificationQueueEntryRecipientId());
		notificationQueueEntryRecipientSettingImpl.setName(getName());
		notificationQueueEntryRecipientSettingImpl.setValue(getValue());

		notificationQueueEntryRecipientSettingImpl.resetOriginalValues();

		return notificationQueueEntryRecipientSettingImpl;
	}

	@Override
	public NotificationQueueEntryRecipientSetting cloneWithOriginalValues() {
		NotificationQueueEntryRecipientSettingImpl
			notificationQueueEntryRecipientSettingImpl =
				new NotificationQueueEntryRecipientSettingImpl();

		notificationQueueEntryRecipientSettingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		notificationQueueEntryRecipientSettingImpl.
			setNotificationQueueEntryRecipientSettingId(
				this.<Long>getColumnOriginalValue(
					"NQueueEntryRecipientSettingId"));
		notificationQueueEntryRecipientSettingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		notificationQueueEntryRecipientSettingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		notificationQueueEntryRecipientSettingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		notificationQueueEntryRecipientSettingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		notificationQueueEntryRecipientSettingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		notificationQueueEntryRecipientSettingImpl.
			setNotificationQueueEntryRecipientId(
				this.<Long>getColumnOriginalValue("NQueueEntryRecipientId"));
		notificationQueueEntryRecipientSettingImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		notificationQueueEntryRecipientSettingImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return notificationQueueEntryRecipientSettingImpl;
	}

	@Override
	public int compareTo(
		NotificationQueueEntryRecipientSetting
			notificationQueueEntryRecipientSetting) {

		long primaryKey =
			notificationQueueEntryRecipientSetting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationQueueEntryRecipientSetting)) {
			return false;
		}

		NotificationQueueEntryRecipientSetting
			notificationQueueEntryRecipientSetting =
				(NotificationQueueEntryRecipientSetting)object;

		long primaryKey =
			notificationQueueEntryRecipientSetting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationQueueEntryRecipientSetting> toCacheModel() {
		NotificationQueueEntryRecipientSettingCacheModel
			notificationQueueEntryRecipientSettingCacheModel =
				new NotificationQueueEntryRecipientSettingCacheModel();

		notificationQueueEntryRecipientSettingCacheModel.mvccVersion =
			getMvccVersion();

		notificationQueueEntryRecipientSettingCacheModel.
			notificationQueueEntryRecipientSettingId =
				getNotificationQueueEntryRecipientSettingId();

		notificationQueueEntryRecipientSettingCacheModel.companyId =
			getCompanyId();

		notificationQueueEntryRecipientSettingCacheModel.userId = getUserId();

		notificationQueueEntryRecipientSettingCacheModel.userName =
			getUserName();

		String userName =
			notificationQueueEntryRecipientSettingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationQueueEntryRecipientSettingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationQueueEntryRecipientSettingCacheModel.createDate =
				createDate.getTime();
		}
		else {
			notificationQueueEntryRecipientSettingCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationQueueEntryRecipientSettingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			notificationQueueEntryRecipientSettingCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		notificationQueueEntryRecipientSettingCacheModel.
			notificationQueueEntryRecipientId =
				getNotificationQueueEntryRecipientId();

		notificationQueueEntryRecipientSettingCacheModel.name = getName();

		String name = notificationQueueEntryRecipientSettingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			notificationQueueEntryRecipientSettingCacheModel.name = null;
		}

		notificationQueueEntryRecipientSettingCacheModel.value = getValue();

		String value = notificationQueueEntryRecipientSettingCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			notificationQueueEntryRecipientSettingCacheModel.value = null;
		}

		return notificationQueueEntryRecipientSettingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationQueueEntryRecipientSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String,
				 Function<NotificationQueueEntryRecipientSetting, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationQueueEntryRecipientSetting, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NotificationQueueEntryRecipientSetting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, NotificationQueueEntryRecipientSetting>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						NotificationQueueEntryRecipientSetting.class,
						ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _notificationQueueEntryRecipientSettingId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _notificationQueueEntryRecipientId;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationQueueEntryRecipientSetting, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationQueueEntryRecipientSetting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"NQueueEntryRecipientSettingId",
			_notificationQueueEntryRecipientSettingId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"NQueueEntryRecipientId", _notificationQueueEntryRecipientId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put(
			"NQueueEntryRecipientSettingId",
			"notificationQueueEntryRecipientSettingId");
		attributeNames.put(
			"NQueueEntryRecipientId", "notificationQueueEntryRecipientId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("NQueueEntryRecipientSettingId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("NQueueEntryRecipientId", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("value", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationQueueEntryRecipientSetting _escapedModel;

}