/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.notification.model.NotificationTemplateRecipient;
import com.liferay.notification.model.NotificationTemplateRecipientModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotificationTemplateRecipient service. Represents a row in the &quot;NTemplateRecipient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationTemplateRecipientModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationTemplateRecipientImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationTemplateRecipientImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationTemplateRecipientModelImpl
	extends BaseModelImpl<NotificationTemplateRecipient>
	implements NotificationTemplateRecipientModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification template recipient model instance should use the <code>NotificationTemplateRecipient</code> interface instead.
	 */
	public static final String TABLE_NAME = "NTemplateRecipient";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"NTemplateRecipientId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"notificationTemplateId", Types.BIGINT}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NTemplateRecipientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("notificationTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NTemplateRecipient (mvccVersion LONG default 0 not null,NTemplateRecipientId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,notificationTemplateId LONG,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table NTemplateRecipient";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationTemplateRecipient.notificationTemplateRecipientId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NTemplateRecipient.NTemplateRecipientId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOTIFICATIONTEMPLATEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOTIFICATIONTEMPLATERECIPIENTID_COLUMN_BITMASK =
		2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NotificationTemplateRecipientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationTemplateRecipientId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationTemplateRecipientId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationTemplateRecipientId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationTemplateRecipient.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationTemplateRecipient.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationTemplateRecipient, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NotificationTemplateRecipient, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationTemplateRecipient, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(NotificationTemplateRecipient)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationTemplateRecipient, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationTemplateRecipient, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationTemplateRecipient)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationTemplateRecipient, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotificationTemplateRecipient, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<NotificationTemplateRecipient, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<NotificationTemplateRecipient, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationTemplateRecipient, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<NotificationTemplateRecipient, Object>>();
		Map<String, BiConsumer<NotificationTemplateRecipient, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<NotificationTemplateRecipient, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", NotificationTemplateRecipient::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<NotificationTemplateRecipient, Long>)
				NotificationTemplateRecipient::setMvccVersion);
		attributeGetterFunctions.put(
			"notificationTemplateRecipientId",
			NotificationTemplateRecipient::getNotificationTemplateRecipientId);
		attributeSetterBiConsumers.put(
			"notificationTemplateRecipientId",
			(BiConsumer<NotificationTemplateRecipient, Long>)
				NotificationTemplateRecipient::
					setNotificationTemplateRecipientId);
		attributeGetterFunctions.put(
			"companyId", NotificationTemplateRecipient::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationTemplateRecipient, Long>)
				NotificationTemplateRecipient::setCompanyId);
		attributeGetterFunctions.put(
			"userId", NotificationTemplateRecipient::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationTemplateRecipient, Long>)
				NotificationTemplateRecipient::setUserId);
		attributeGetterFunctions.put(
			"userName", NotificationTemplateRecipient::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationTemplateRecipient, String>)
				NotificationTemplateRecipient::setUserName);
		attributeGetterFunctions.put(
			"createDate", NotificationTemplateRecipient::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationTemplateRecipient, Date>)
				NotificationTemplateRecipient::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NotificationTemplateRecipient::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationTemplateRecipient, Date>)
				NotificationTemplateRecipient::setModifiedDate);
		attributeGetterFunctions.put(
			"notificationTemplateId",
			NotificationTemplateRecipient::getNotificationTemplateId);
		attributeSetterBiConsumers.put(
			"notificationTemplateId",
			(BiConsumer<NotificationTemplateRecipient, Long>)
				NotificationTemplateRecipient::setNotificationTemplateId);
		attributeGetterFunctions.put(
			"type", NotificationTemplateRecipient::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<NotificationTemplateRecipient, String>)
				NotificationTemplateRecipient::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getNotificationTemplateRecipientId() {
		return _notificationTemplateRecipientId;
	}

	@Override
	public void setNotificationTemplateRecipientId(
		long notificationTemplateRecipientId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationTemplateRecipientId = notificationTemplateRecipientId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNotificationTemplateId() {
		return _notificationTemplateId;
	}

	@Override
	public void setNotificationTemplateId(long notificationTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationTemplateId = notificationTemplateId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNotificationTemplateId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("notificationTemplateId"));
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NotificationTemplateRecipient.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationTemplateRecipient toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationTemplateRecipient>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationTemplateRecipientImpl notificationTemplateRecipientImpl =
			new NotificationTemplateRecipientImpl();

		notificationTemplateRecipientImpl.setMvccVersion(getMvccVersion());
		notificationTemplateRecipientImpl.setNotificationTemplateRecipientId(
			getNotificationTemplateRecipientId());
		notificationTemplateRecipientImpl.setCompanyId(getCompanyId());
		notificationTemplateRecipientImpl.setUserId(getUserId());
		notificationTemplateRecipientImpl.setUserName(getUserName());
		notificationTemplateRecipientImpl.setCreateDate(getCreateDate());
		notificationTemplateRecipientImpl.setModifiedDate(getModifiedDate());
		notificationTemplateRecipientImpl.setNotificationTemplateId(
			getNotificationTemplateId());
		notificationTemplateRecipientImpl.setType(getType());

		notificationTemplateRecipientImpl.resetOriginalValues();

		return notificationTemplateRecipientImpl;
	}

	@Override
	public NotificationTemplateRecipient cloneWithOriginalValues() {
		NotificationTemplateRecipientImpl notificationTemplateRecipientImpl =
			new NotificationTemplateRecipientImpl();

		notificationTemplateRecipientImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		notificationTemplateRecipientImpl.setNotificationTemplateRecipientId(
			this.<Long>getColumnOriginalValue("NTemplateRecipientId"));
		notificationTemplateRecipientImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		notificationTemplateRecipientImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		notificationTemplateRecipientImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		notificationTemplateRecipientImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		notificationTemplateRecipientImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		notificationTemplateRecipientImpl.setNotificationTemplateId(
			this.<Long>getColumnOriginalValue("notificationTemplateId"));
		notificationTemplateRecipientImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return notificationTemplateRecipientImpl;
	}

	@Override
	public int compareTo(
		NotificationTemplateRecipient notificationTemplateRecipient) {

		long primaryKey = notificationTemplateRecipient.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationTemplateRecipient)) {
			return false;
		}

		NotificationTemplateRecipient notificationTemplateRecipient =
			(NotificationTemplateRecipient)object;

		long primaryKey = notificationTemplateRecipient.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationTemplateRecipient> toCacheModel() {
		NotificationTemplateRecipientCacheModel
			notificationTemplateRecipientCacheModel =
				new NotificationTemplateRecipientCacheModel();

		notificationTemplateRecipientCacheModel.mvccVersion = getMvccVersion();

		notificationTemplateRecipientCacheModel.
			notificationTemplateRecipientId =
				getNotificationTemplateRecipientId();

		notificationTemplateRecipientCacheModel.companyId = getCompanyId();

		notificationTemplateRecipientCacheModel.userId = getUserId();

		notificationTemplateRecipientCacheModel.userName = getUserName();

		String userName = notificationTemplateRecipientCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationTemplateRecipientCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationTemplateRecipientCacheModel.createDate =
				createDate.getTime();
		}
		else {
			notificationTemplateRecipientCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationTemplateRecipientCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			notificationTemplateRecipientCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		notificationTemplateRecipientCacheModel.notificationTemplateId =
			getNotificationTemplateId();

		notificationTemplateRecipientCacheModel.type = getType();

		String type = notificationTemplateRecipientCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			notificationTemplateRecipientCacheModel.type = null;
		}

		return notificationTemplateRecipientCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationTemplateRecipient, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NotificationTemplateRecipient, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationTemplateRecipient, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NotificationTemplateRecipient)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, NotificationTemplateRecipient>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						NotificationTemplateRecipient.class,
						ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _notificationTemplateRecipientId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _notificationTemplateId;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationTemplateRecipient, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationTemplateRecipient)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"NTemplateRecipientId", _notificationTemplateRecipientId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"notificationTemplateId", _notificationTemplateId);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put(
			"NTemplateRecipientId", "notificationTemplateRecipientId");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("NTemplateRecipientId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("notificationTemplateId", 128L);

		columnBitmasks.put("type_", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationTemplateRecipient _escapedModel;

}