/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.notification.model.NotificationTemplateRecipientSetting;
import com.liferay.notification.model.NotificationTemplateRecipientSettingModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotificationTemplateRecipientSetting service. Represents a row in the &quot;NTemplateRecipientSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationTemplateRecipientSettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationTemplateRecipientSettingImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationTemplateRecipientSettingImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationTemplateRecipientSettingModelImpl
	extends BaseModelImpl<NotificationTemplateRecipientSetting>
	implements NotificationTemplateRecipientSettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification template recipient setting model instance should use the <code>NotificationTemplateRecipientSetting</code> interface instead.
	 */
	public static final String TABLE_NAME = "NTemplateRecipientSetting";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"NTemplateRecipientSettingId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"NTemplateRecipientId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NTemplateRecipientSettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("NTemplateRecipientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NTemplateRecipientSetting (mvccVersion LONG default 0 not null,NTemplateRecipientSettingId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,NTemplateRecipientId LONG,name VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table NTemplateRecipientSetting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationTemplateRecipientSetting.notificationTemplateRecipientSettingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NTemplateRecipientSetting.NTemplateRecipientSettingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long
		NOTIFICATIONTEMPLATERECIPIENTSETTINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NotificationTemplateRecipientSettingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationTemplateRecipientSettingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationTemplateRecipientSettingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationTemplateRecipientSettingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationTemplateRecipientSetting.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationTemplateRecipientSetting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationTemplateRecipientSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String, Function<NotificationTemplateRecipientSetting, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationTemplateRecipientSetting, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(NotificationTemplateRecipientSetting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationTemplateRecipientSetting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationTemplateRecipientSetting, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationTemplateRecipientSetting)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationTemplateRecipientSetting, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotificationTemplateRecipientSetting, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<NotificationTemplateRecipientSetting, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<NotificationTemplateRecipientSetting, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationTemplateRecipientSetting, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<NotificationTemplateRecipientSetting, Object>>();
		Map<String, BiConsumer<NotificationTemplateRecipientSetting, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<NotificationTemplateRecipientSetting, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion",
			NotificationTemplateRecipientSetting::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<NotificationTemplateRecipientSetting, Long>)
				NotificationTemplateRecipientSetting::setMvccVersion);
		attributeGetterFunctions.put(
			"notificationTemplateRecipientSettingId",
			NotificationTemplateRecipientSetting::
				getNotificationTemplateRecipientSettingId);
		attributeSetterBiConsumers.put(
			"notificationTemplateRecipientSettingId",
			(BiConsumer<NotificationTemplateRecipientSetting, Long>)
				NotificationTemplateRecipientSetting::
					setNotificationTemplateRecipientSettingId);
		attributeGetterFunctions.put(
			"companyId", NotificationTemplateRecipientSetting::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationTemplateRecipientSetting, Long>)
				NotificationTemplateRecipientSetting::setCompanyId);
		attributeGetterFunctions.put(
			"userId", NotificationTemplateRecipientSetting::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationTemplateRecipientSetting, Long>)
				NotificationTemplateRecipientSetting::setUserId);
		attributeGetterFunctions.put(
			"userName", NotificationTemplateRecipientSetting::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationTemplateRecipientSetting, String>)
				NotificationTemplateRecipientSetting::setUserName);
		attributeGetterFunctions.put(
			"createDate", NotificationTemplateRecipientSetting::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationTemplateRecipientSetting, Date>)
				NotificationTemplateRecipientSetting::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate",
			NotificationTemplateRecipientSetting::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationTemplateRecipientSetting, Date>)
				NotificationTemplateRecipientSetting::setModifiedDate);
		attributeGetterFunctions.put(
			"notificationTemplateRecipientId",
			NotificationTemplateRecipientSetting::
				getNotificationTemplateRecipientId);
		attributeSetterBiConsumers.put(
			"notificationTemplateRecipientId",
			(BiConsumer<NotificationTemplateRecipientSetting, Long>)
				NotificationTemplateRecipientSetting::
					setNotificationTemplateRecipientId);
		attributeGetterFunctions.put(
			"name", NotificationTemplateRecipientSetting::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<NotificationTemplateRecipientSetting, String>)
				NotificationTemplateRecipientSetting::setName);
		attributeGetterFunctions.put(
			"value", NotificationTemplateRecipientSetting::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<NotificationTemplateRecipientSetting, String>)
				NotificationTemplateRecipientSetting::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getNotificationTemplateRecipientSettingId() {
		return _notificationTemplateRecipientSettingId;
	}

	@Override
	public void setNotificationTemplateRecipientSettingId(
		long notificationTemplateRecipientSettingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationTemplateRecipientSettingId =
			notificationTemplateRecipientSettingId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNotificationTemplateRecipientId() {
		return _notificationTemplateRecipientId;
	}

	@Override
	public void setNotificationTemplateRecipientId(
		long notificationTemplateRecipientId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationTemplateRecipientId = notificationTemplateRecipientId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			NotificationTemplateRecipientSetting.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationTemplateRecipientSetting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationTemplateRecipientSetting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationTemplateRecipientSettingImpl
			notificationTemplateRecipientSettingImpl =
				new NotificationTemplateRecipientSettingImpl();

		notificationTemplateRecipientSettingImpl.setMvccVersion(
			getMvccVersion());
		notificationTemplateRecipientSettingImpl.
			setNotificationTemplateRecipientSettingId(
				getNotificationTemplateRecipientSettingId());
		notificationTemplateRecipientSettingImpl.setCompanyId(getCompanyId());
		notificationTemplateRecipientSettingImpl.setUserId(getUserId());
		notificationTemplateRecipientSettingImpl.setUserName(getUserName());
		notificationTemplateRecipientSettingImpl.setCreateDate(getCreateDate());
		notificationTemplateRecipientSettingImpl.setModifiedDate(
			getModifiedDate());
		notificationTemplateRecipientSettingImpl.
			setNotificationTemplateRecipientId(
				getNotificationTemplateRecipientId());
		notificationTemplateRecipientSettingImpl.setName(getName());
		notificationTemplateRecipientSettingImpl.setValue(getValue());

		notificationTemplateRecipientSettingImpl.resetOriginalValues();

		return notificationTemplateRecipientSettingImpl;
	}

	@Override
	public NotificationTemplateRecipientSetting cloneWithOriginalValues() {
		NotificationTemplateRecipientSettingImpl
			notificationTemplateRecipientSettingImpl =
				new NotificationTemplateRecipientSettingImpl();

		notificationTemplateRecipientSettingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		notificationTemplateRecipientSettingImpl.
			setNotificationTemplateRecipientSettingId(
				this.<Long>getColumnOriginalValue(
					"NTemplateRecipientSettingId"));
		notificationTemplateRecipientSettingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		notificationTemplateRecipientSettingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		notificationTemplateRecipientSettingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		notificationTemplateRecipientSettingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		notificationTemplateRecipientSettingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		notificationTemplateRecipientSettingImpl.
			setNotificationTemplateRecipientId(
				this.<Long>getColumnOriginalValue("NTemplateRecipientId"));
		notificationTemplateRecipientSettingImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		notificationTemplateRecipientSettingImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return notificationTemplateRecipientSettingImpl;
	}

	@Override
	public int compareTo(
		NotificationTemplateRecipientSetting
			notificationTemplateRecipientSetting) {

		long primaryKey = notificationTemplateRecipientSetting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationTemplateRecipientSetting)) {
			return false;
		}

		NotificationTemplateRecipientSetting
			notificationTemplateRecipientSetting =
				(NotificationTemplateRecipientSetting)object;

		long primaryKey = notificationTemplateRecipientSetting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationTemplateRecipientSetting> toCacheModel() {
		NotificationTemplateRecipientSettingCacheModel
			notificationTemplateRecipientSettingCacheModel =
				new NotificationTemplateRecipientSettingCacheModel();

		notificationTemplateRecipientSettingCacheModel.mvccVersion =
			getMvccVersion();

		notificationTemplateRecipientSettingCacheModel.
			notificationTemplateRecipientSettingId =
				getNotificationTemplateRecipientSettingId();

		notificationTemplateRecipientSettingCacheModel.companyId =
			getCompanyId();

		notificationTemplateRecipientSettingCacheModel.userId = getUserId();

		notificationTemplateRecipientSettingCacheModel.userName = getUserName();

		String userName =
			notificationTemplateRecipientSettingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationTemplateRecipientSettingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationTemplateRecipientSettingCacheModel.createDate =
				createDate.getTime();
		}
		else {
			notificationTemplateRecipientSettingCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationTemplateRecipientSettingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			notificationTemplateRecipientSettingCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		notificationTemplateRecipientSettingCacheModel.
			notificationTemplateRecipientId =
				getNotificationTemplateRecipientId();

		notificationTemplateRecipientSettingCacheModel.name = getName();

		String name = notificationTemplateRecipientSettingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			notificationTemplateRecipientSettingCacheModel.name = null;
		}

		notificationTemplateRecipientSettingCacheModel.value = getValue();

		String value = notificationTemplateRecipientSettingCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			notificationTemplateRecipientSettingCacheModel.value = null;
		}

		return notificationTemplateRecipientSettingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationTemplateRecipientSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String, Function<NotificationTemplateRecipientSetting, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationTemplateRecipientSetting, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NotificationTemplateRecipientSetting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, NotificationTemplateRecipientSetting>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						NotificationTemplateRecipientSetting.class,
						ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _notificationTemplateRecipientSettingId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _notificationTemplateRecipientId;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationTemplateRecipientSetting, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationTemplateRecipientSetting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"NTemplateRecipientSettingId",
			_notificationTemplateRecipientSettingId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"NTemplateRecipientId", _notificationTemplateRecipientId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put(
			"NTemplateRecipientSettingId",
			"notificationTemplateRecipientSettingId");
		attributeNames.put(
			"NTemplateRecipientId", "notificationTemplateRecipientId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("NTemplateRecipientSettingId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("NTemplateRecipientId", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("value", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationTemplateRecipientSetting _escapedModel;

}