form.Advanced.displayName=Advanced
form.Advanced.title=Advanced
form.Main.displayName=Main
form.Main.title=Main
form.Reference.displayName=Connection Reference
form.Reference.title=Connection Reference
form.Wizard.displayName=Liferay Connection Settings
form.Wizard.subtitle=Complete these fields in order to connect to your Liferay installation.
form.Wizard.title=Liferay Connection Settings

property.anonymousLoginProperty.displayName=Anonymous
property.connectTimeoutProperty.displayName=REST Connection Timeout (s)
property.endpointProperty.displayName=Liferay URL
property.followRedirectsProperty.displayName=Follow Redirects (Max 3)
property.forceHttpsProperty.displayName=Force HTTPS Scheme
property.itemsPerPageProperty.displayName=Max Items per Request
property.loginTypeProperty.displayName=Connection Type
property.passwordProperty.displayName=Password
property.readTimeoutProperty.displayName=REST Read Timeout (s)
property.repositoryNameProperty.displayName=Name
property.userIdProperty.displayName=User