/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.list.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.list.model.AssetEntryAssetListEntryRel;
import com.liferay.asset.list.service.AssetEntryAssetListEntryRelLocalService;
import com.liferay.asset.list.service.persistence.AssetEntryAssetListEntryRelPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry asset list entry rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.list.service.impl.AssetEntryAssetListEntryRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.list.service.impl.AssetEntryAssetListEntryRelLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class AssetEntryAssetListEntryRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AssetEntryAssetListEntryRelLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetEntryAssetListEntryRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.asset.list.service.AssetEntryAssetListEntryRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asset entry asset list entry rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetListEntryRel the asset entry asset list entry rel
	 * @return the asset entry asset list entry rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetListEntryRel addAssetEntryAssetListEntryRel(
		AssetEntryAssetListEntryRel assetEntryAssetListEntryRel) {

		assetEntryAssetListEntryRel.setNew(true);

		return assetEntryAssetListEntryRelPersistence.update(
			assetEntryAssetListEntryRel);
	}

	/**
	 * Creates a new asset entry asset list entry rel with the primary key. Does not add the asset entry asset list entry rel to the database.
	 *
	 * @param assetEntryAssetListEntryRelId the primary key for the new asset entry asset list entry rel
	 * @return the new asset entry asset list entry rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetEntryAssetListEntryRel createAssetEntryAssetListEntryRel(
		long assetEntryAssetListEntryRelId) {

		return assetEntryAssetListEntryRelPersistence.create(
			assetEntryAssetListEntryRelId);
	}

	/**
	 * Deletes the asset entry asset list entry rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetListEntryRelId the primary key of the asset entry asset list entry rel
	 * @return the asset entry asset list entry rel that was removed
	 * @throws PortalException if a asset entry asset list entry rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetListEntryRel deleteAssetEntryAssetListEntryRel(
			long assetEntryAssetListEntryRelId)
		throws PortalException {

		return assetEntryAssetListEntryRelPersistence.remove(
			assetEntryAssetListEntryRelId);
	}

	/**
	 * Deletes the asset entry asset list entry rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetListEntryRel the asset entry asset list entry rel
	 * @return the asset entry asset list entry rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetListEntryRel deleteAssetEntryAssetListEntryRel(
		AssetEntryAssetListEntryRel assetEntryAssetListEntryRel) {

		return assetEntryAssetListEntryRelPersistence.remove(
			assetEntryAssetListEntryRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssetEntryAssetListEntryRel.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntryAssetListEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.asset.list.model.impl.AssetEntryAssetListEntryRelModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assetEntryAssetListEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.asset.list.model.impl.AssetEntryAssetListEntryRelModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assetEntryAssetListEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntryAssetListEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assetEntryAssetListEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssetEntryAssetListEntryRel fetchAssetEntryAssetListEntryRel(
		long assetEntryAssetListEntryRelId) {

		return assetEntryAssetListEntryRelPersistence.fetchByPrimaryKey(
			assetEntryAssetListEntryRelId);
	}

	/**
	 * Returns the asset entry asset list entry rel matching the UUID and group.
	 *
	 * @param uuid the asset entry asset list entry rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset entry asset list entry rel, or <code>null</code> if a matching asset entry asset list entry rel could not be found
	 */
	@Override
	public AssetEntryAssetListEntryRel
		fetchAssetEntryAssetListEntryRelByUuidAndGroupId(
			String uuid, long groupId) {

		return assetEntryAssetListEntryRelPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the asset entry asset list entry rel with the primary key.
	 *
	 * @param assetEntryAssetListEntryRelId the primary key of the asset entry asset list entry rel
	 * @return the asset entry asset list entry rel
	 * @throws PortalException if a asset entry asset list entry rel with the primary key could not be found
	 */
	@Override
	public AssetEntryAssetListEntryRel getAssetEntryAssetListEntryRel(
			long assetEntryAssetListEntryRelId)
		throws PortalException {

		return assetEntryAssetListEntryRelPersistence.findByPrimaryKey(
			assetEntryAssetListEntryRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assetEntryAssetListEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetListEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetListEntryRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assetEntryAssetListEntryRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AssetEntryAssetListEntryRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetListEntryRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assetEntryAssetListEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetListEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetListEntryRelId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setGroupId(
			portletDataContext.getScopeGroupId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<AssetEntryAssetListEntryRel>() {

				@Override
				public void performAction(
						AssetEntryAssetListEntryRel assetEntryAssetListEntryRel)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, assetEntryAssetListEntryRel);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					AssetEntryAssetListEntryRel.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return assetEntryAssetListEntryRelLocalService.
			deleteAssetEntryAssetListEntryRel(
				(AssetEntryAssetListEntryRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetEntryAssetListEntryRelPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the asset entry asset list entry rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset entry asset list entry rels
	 * @param companyId the primary key of the company
	 * @return the matching asset entry asset list entry rels, or an empty list if no matches were found
	 */
	@Override
	public List<AssetEntryAssetListEntryRel>
		getAssetEntryAssetListEntryRelsByUuidAndCompanyId(
			String uuid, long companyId) {

		return assetEntryAssetListEntryRelPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of asset entry asset list entry rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset entry asset list entry rels
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of asset entry asset list entry rels
	 * @param end the upper bound of the range of asset entry asset list entry rels (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching asset entry asset list entry rels, or an empty list if no matches were found
	 */
	@Override
	public List<AssetEntryAssetListEntryRel>
		getAssetEntryAssetListEntryRelsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<AssetEntryAssetListEntryRel> orderByComparator) {

		return assetEntryAssetListEntryRelPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the asset entry asset list entry rel matching the UUID and group.
	 *
	 * @param uuid the asset entry asset list entry rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset entry asset list entry rel
	 * @throws PortalException if a matching asset entry asset list entry rel could not be found
	 */
	@Override
	public AssetEntryAssetListEntryRel
			getAssetEntryAssetListEntryRelByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return assetEntryAssetListEntryRelPersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the asset entry asset list entry rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.asset.list.model.impl.AssetEntryAssetListEntryRelModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry asset list entry rels
	 * @param end the upper bound of the range of asset entry asset list entry rels (not inclusive)
	 * @return the range of asset entry asset list entry rels
	 */
	@Override
	public List<AssetEntryAssetListEntryRel> getAssetEntryAssetListEntryRels(
		int start, int end) {

		return assetEntryAssetListEntryRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry asset list entry rels.
	 *
	 * @return the number of asset entry asset list entry rels
	 */
	@Override
	public int getAssetEntryAssetListEntryRelsCount() {
		return assetEntryAssetListEntryRelPersistence.countAll();
	}

	/**
	 * Updates the asset entry asset list entry rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetListEntryRel the asset entry asset list entry rel
	 * @return the asset entry asset list entry rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetListEntryRel updateAssetEntryAssetListEntryRel(
		AssetEntryAssetListEntryRel assetEntryAssetListEntryRel) {

		return assetEntryAssetListEntryRelPersistence.update(
			assetEntryAssetListEntryRel);
	}

	/**
	 * Returns the asset entry asset list entry rel local service.
	 *
	 * @return the asset entry asset list entry rel local service
	 */
	public AssetEntryAssetListEntryRelLocalService
		getAssetEntryAssetListEntryRelLocalService() {

		return assetEntryAssetListEntryRelLocalService;
	}

	/**
	 * Sets the asset entry asset list entry rel local service.
	 *
	 * @param assetEntryAssetListEntryRelLocalService the asset entry asset list entry rel local service
	 */
	public void setAssetEntryAssetListEntryRelLocalService(
		AssetEntryAssetListEntryRelLocalService
			assetEntryAssetListEntryRelLocalService) {

		this.assetEntryAssetListEntryRelLocalService =
			assetEntryAssetListEntryRelLocalService;
	}

	/**
	 * Returns the asset entry asset list entry rel persistence.
	 *
	 * @return the asset entry asset list entry rel persistence
	 */
	public AssetEntryAssetListEntryRelPersistence
		getAssetEntryAssetListEntryRelPersistence() {

		return assetEntryAssetListEntryRelPersistence;
	}

	/**
	 * Sets the asset entry asset list entry rel persistence.
	 *
	 * @param assetEntryAssetListEntryRelPersistence the asset entry asset list entry rel persistence
	 */
	public void setAssetEntryAssetListEntryRelPersistence(
		AssetEntryAssetListEntryRelPersistence
			assetEntryAssetListEntryRelPersistence) {

		this.assetEntryAssetListEntryRelPersistence =
			assetEntryAssetListEntryRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.asset.list.model.AssetEntryAssetListEntryRel",
			assetEntryAssetListEntryRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.asset.list.model.AssetEntryAssetListEntryRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntryAssetListEntryRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntryAssetListEntryRel.class;
	}

	protected String getModelClassName() {
		return AssetEntryAssetListEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				assetEntryAssetListEntryRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetEntryAssetListEntryRelLocalService.class)
	protected AssetEntryAssetListEntryRelLocalService
		assetEntryAssetListEntryRelLocalService;

	@BeanReference(type = AssetEntryAssetListEntryRelPersistence.class)
	protected AssetEntryAssetListEntryRelPersistence
		assetEntryAssetListEntryRelPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}