/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel;
import com.liferay.asset.entry.rel.service.AssetEntryDisplayPageRelLocalServiceUtil;

/**
 * The extended model base implementation for the AssetEntryDisplayPageRel service. Represents a row in the &quot;AssetEntryDisplayPageRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntryDisplayPageRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryDisplayPageRelImpl
 * @see AssetEntryDisplayPageRel
 * @generated
 */
@ProviderType
public abstract class AssetEntryDisplayPageRelBaseImpl
	extends AssetEntryDisplayPageRelModelImpl
	implements AssetEntryDisplayPageRel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry display page rel model instance should use the {@link AssetEntryDisplayPageRel} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AssetEntryDisplayPageRelLocalServiceUtil.addAssetEntryDisplayPageRel(this);
		}
		else {
			AssetEntryDisplayPageRelLocalServiceUtil.updateAssetEntryDisplayPageRel(this);
		}
	}
}