/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel;
import com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRelModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetEntryDisplayPageRel service. Represents a row in the &quot;AssetEntryDisplayPageRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssetEntryDisplayPageRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntryDisplayPageRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryDisplayPageRelImpl
 * @see AssetEntryDisplayPageRel
 * @see AssetEntryDisplayPageRelModel
 * @generated
 */
@ProviderType
public class AssetEntryDisplayPageRelModelImpl extends BaseModelImpl<AssetEntryDisplayPageRel>
	implements AssetEntryDisplayPageRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry display page rel model instance should use the {@link AssetEntryDisplayPageRel} interface instead.
	 */
	public static final String TABLE_NAME = "AssetEntryDisplayPageRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetEntryDisplayPageRelId", Types.BIGINT },
			{ "assetEntryId", Types.BIGINT },
			{ "displayPageId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("assetEntryDisplayPageRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("displayPageId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssetEntryDisplayPageRel (assetEntryDisplayPageRelId LONG not null primary key,assetEntryId LONG,displayPageId LONG)";
	public static final String TABLE_SQL_DROP = "drop table AssetEntryDisplayPageRel";
	public static final String ORDER_BY_JPQL = " ORDER BY assetEntryDisplayPageRel.assetEntryDisplayPageRelId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssetEntryDisplayPageRel.assetEntryDisplayPageRelId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel"),
			true);
	public static final long ASSETENTRYID_COLUMN_BITMASK = 1L;
	public static final long DISPLAYPAGEID_COLUMN_BITMASK = 2L;
	public static final long ASSETENTRYDISPLAYPAGERELID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel"));

	public AssetEntryDisplayPageRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetEntryDisplayPageRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetEntryDisplayPageRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetEntryDisplayPageRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetEntryDisplayPageRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetEntryDisplayPageRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetEntryDisplayPageRelId",
			getAssetEntryDisplayPageRelId());
		attributes.put("assetEntryId", getAssetEntryId());
		attributes.put("displayPageId", getDisplayPageId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetEntryDisplayPageRelId = (Long)attributes.get(
				"assetEntryDisplayPageRelId");

		if (assetEntryDisplayPageRelId != null) {
			setAssetEntryDisplayPageRelId(assetEntryDisplayPageRelId);
		}

		Long assetEntryId = (Long)attributes.get("assetEntryId");

		if (assetEntryId != null) {
			setAssetEntryId(assetEntryId);
		}

		Long displayPageId = (Long)attributes.get("displayPageId");

		if (displayPageId != null) {
			setDisplayPageId(displayPageId);
		}
	}

	@Override
	public long getAssetEntryDisplayPageRelId() {
		return _assetEntryDisplayPageRelId;
	}

	@Override
	public void setAssetEntryDisplayPageRelId(long assetEntryDisplayPageRelId) {
		_assetEntryDisplayPageRelId = assetEntryDisplayPageRelId;
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAssetEntryId) {
			_setOriginalAssetEntryId = true;

			_originalAssetEntryId = _assetEntryId;
		}

		_assetEntryId = assetEntryId;
	}

	public long getOriginalAssetEntryId() {
		return _originalAssetEntryId;
	}

	@Override
	public long getDisplayPageId() {
		return _displayPageId;
	}

	@Override
	public void setDisplayPageId(long displayPageId) {
		_columnBitmask |= DISPLAYPAGEID_COLUMN_BITMASK;

		if (!_setOriginalDisplayPageId) {
			_setOriginalDisplayPageId = true;

			_originalDisplayPageId = _displayPageId;
		}

		_displayPageId = displayPageId;
	}

	public long getOriginalDisplayPageId() {
		return _originalDisplayPageId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssetEntryDisplayPageRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetEntryDisplayPageRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetEntryDisplayPageRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetEntryDisplayPageRelImpl assetEntryDisplayPageRelImpl = new AssetEntryDisplayPageRelImpl();

		assetEntryDisplayPageRelImpl.setAssetEntryDisplayPageRelId(getAssetEntryDisplayPageRelId());
		assetEntryDisplayPageRelImpl.setAssetEntryId(getAssetEntryId());
		assetEntryDisplayPageRelImpl.setDisplayPageId(getDisplayPageId());

		assetEntryDisplayPageRelImpl.resetOriginalValues();

		return assetEntryDisplayPageRelImpl;
	}

	@Override
	public int compareTo(AssetEntryDisplayPageRel assetEntryDisplayPageRel) {
		long primaryKey = assetEntryDisplayPageRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetEntryDisplayPageRel)) {
			return false;
		}

		AssetEntryDisplayPageRel assetEntryDisplayPageRel = (AssetEntryDisplayPageRel)obj;

		long primaryKey = assetEntryDisplayPageRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssetEntryDisplayPageRelModelImpl assetEntryDisplayPageRelModelImpl = this;

		assetEntryDisplayPageRelModelImpl._originalAssetEntryId = assetEntryDisplayPageRelModelImpl._assetEntryId;

		assetEntryDisplayPageRelModelImpl._setOriginalAssetEntryId = false;

		assetEntryDisplayPageRelModelImpl._originalDisplayPageId = assetEntryDisplayPageRelModelImpl._displayPageId;

		assetEntryDisplayPageRelModelImpl._setOriginalDisplayPageId = false;

		assetEntryDisplayPageRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetEntryDisplayPageRel> toCacheModel() {
		AssetEntryDisplayPageRelCacheModel assetEntryDisplayPageRelCacheModel = new AssetEntryDisplayPageRelCacheModel();

		assetEntryDisplayPageRelCacheModel.assetEntryDisplayPageRelId = getAssetEntryDisplayPageRelId();

		assetEntryDisplayPageRelCacheModel.assetEntryId = getAssetEntryId();

		assetEntryDisplayPageRelCacheModel.displayPageId = getDisplayPageId();

		return assetEntryDisplayPageRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{assetEntryDisplayPageRelId=");
		sb.append(getAssetEntryDisplayPageRelId());
		sb.append(", assetEntryId=");
		sb.append(getAssetEntryId());
		sb.append(", displayPageId=");
		sb.append(getDisplayPageId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.asset.entry.rel.model.AssetEntryDisplayPageRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetEntryDisplayPageRelId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryDisplayPageRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetEntryId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayPageId</column-name><column-value><![CDATA[");
		sb.append(getDisplayPageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssetEntryDisplayPageRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetEntryDisplayPageRel.class
		};
	private long _assetEntryDisplayPageRelId;
	private long _assetEntryId;
	private long _originalAssetEntryId;
	private boolean _setOriginalAssetEntryId;
	private long _displayPageId;
	private long _originalDisplayPageId;
	private boolean _setOriginalDisplayPageId;
	private long _columnBitmask;
	private AssetEntryDisplayPageRel _escapedModel;
}