/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel;
import com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRelModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetEntryAssetDisplayPageRel service. Represents a row in the &quot;AssetEntryAssetDisplayPageRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssetEntryAssetDisplayPageRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntryAssetDisplayPageRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryAssetDisplayPageRelImpl
 * @see AssetEntryAssetDisplayPageRel
 * @see AssetEntryAssetDisplayPageRelModel
 * @generated
 */
@ProviderType
public class AssetEntryAssetDisplayPageRelModelImpl extends BaseModelImpl<AssetEntryAssetDisplayPageRel>
	implements AssetEntryAssetDisplayPageRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry asset display page rel model instance should use the {@link AssetEntryAssetDisplayPageRel} interface instead.
	 */
	public static final String TABLE_NAME = "AssetEntryAssetDisplayPageRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetEntryAssetDisplayPageId", Types.BIGINT },
			{ "assetEntryId", Types.BIGINT },
			{ "assetDisplayPageId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("assetEntryAssetDisplayPageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetDisplayPageId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssetEntryAssetDisplayPageRel (assetEntryAssetDisplayPageId LONG not null primary key,assetEntryId LONG,assetDisplayPageId LONG)";
	public static final String TABLE_SQL_DROP = "drop table AssetEntryAssetDisplayPageRel";
	public static final String ORDER_BY_JPQL = " ORDER BY assetEntryAssetDisplayPageRel.assetEntryAssetDisplayPageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssetEntryAssetDisplayPageRel.assetEntryAssetDisplayPageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel"),
			true);
	public static final long ASSETDISPLAYPAGEID_COLUMN_BITMASK = 1L;
	public static final long ASSETENTRYID_COLUMN_BITMASK = 2L;
	public static final long ASSETENTRYASSETDISPLAYPAGEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.asset.entry.rel.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel"));

	public AssetEntryAssetDisplayPageRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetEntryAssetDisplayPageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetEntryAssetDisplayPageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetEntryAssetDisplayPageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetEntryAssetDisplayPageRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetEntryAssetDisplayPageRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetEntryAssetDisplayPageId",
			getAssetEntryAssetDisplayPageId());
		attributes.put("assetEntryId", getAssetEntryId());
		attributes.put("assetDisplayPageId", getAssetDisplayPageId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetEntryAssetDisplayPageId = (Long)attributes.get(
				"assetEntryAssetDisplayPageId");

		if (assetEntryAssetDisplayPageId != null) {
			setAssetEntryAssetDisplayPageId(assetEntryAssetDisplayPageId);
		}

		Long assetEntryId = (Long)attributes.get("assetEntryId");

		if (assetEntryId != null) {
			setAssetEntryId(assetEntryId);
		}

		Long assetDisplayPageId = (Long)attributes.get("assetDisplayPageId");

		if (assetDisplayPageId != null) {
			setAssetDisplayPageId(assetDisplayPageId);
		}
	}

	@Override
	public long getAssetEntryAssetDisplayPageId() {
		return _assetEntryAssetDisplayPageId;
	}

	@Override
	public void setAssetEntryAssetDisplayPageId(
		long assetEntryAssetDisplayPageId) {
		_assetEntryAssetDisplayPageId = assetEntryAssetDisplayPageId;
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAssetEntryId) {
			_setOriginalAssetEntryId = true;

			_originalAssetEntryId = _assetEntryId;
		}

		_assetEntryId = assetEntryId;
	}

	public long getOriginalAssetEntryId() {
		return _originalAssetEntryId;
	}

	@Override
	public long getAssetDisplayPageId() {
		return _assetDisplayPageId;
	}

	@Override
	public void setAssetDisplayPageId(long assetDisplayPageId) {
		_columnBitmask |= ASSETDISPLAYPAGEID_COLUMN_BITMASK;

		if (!_setOriginalAssetDisplayPageId) {
			_setOriginalAssetDisplayPageId = true;

			_originalAssetDisplayPageId = _assetDisplayPageId;
		}

		_assetDisplayPageId = assetDisplayPageId;
	}

	public long getOriginalAssetDisplayPageId() {
		return _originalAssetDisplayPageId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssetEntryAssetDisplayPageRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetEntryAssetDisplayPageRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetEntryAssetDisplayPageRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetEntryAssetDisplayPageRelImpl assetEntryAssetDisplayPageRelImpl = new AssetEntryAssetDisplayPageRelImpl();

		assetEntryAssetDisplayPageRelImpl.setAssetEntryAssetDisplayPageId(getAssetEntryAssetDisplayPageId());
		assetEntryAssetDisplayPageRelImpl.setAssetEntryId(getAssetEntryId());
		assetEntryAssetDisplayPageRelImpl.setAssetDisplayPageId(getAssetDisplayPageId());

		assetEntryAssetDisplayPageRelImpl.resetOriginalValues();

		return assetEntryAssetDisplayPageRelImpl;
	}

	@Override
	public int compareTo(
		AssetEntryAssetDisplayPageRel assetEntryAssetDisplayPageRel) {
		long primaryKey = assetEntryAssetDisplayPageRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetEntryAssetDisplayPageRel)) {
			return false;
		}

		AssetEntryAssetDisplayPageRel assetEntryAssetDisplayPageRel = (AssetEntryAssetDisplayPageRel)obj;

		long primaryKey = assetEntryAssetDisplayPageRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssetEntryAssetDisplayPageRelModelImpl assetEntryAssetDisplayPageRelModelImpl =
			this;

		assetEntryAssetDisplayPageRelModelImpl._originalAssetEntryId = assetEntryAssetDisplayPageRelModelImpl._assetEntryId;

		assetEntryAssetDisplayPageRelModelImpl._setOriginalAssetEntryId = false;

		assetEntryAssetDisplayPageRelModelImpl._originalAssetDisplayPageId = assetEntryAssetDisplayPageRelModelImpl._assetDisplayPageId;

		assetEntryAssetDisplayPageRelModelImpl._setOriginalAssetDisplayPageId = false;

		assetEntryAssetDisplayPageRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetEntryAssetDisplayPageRel> toCacheModel() {
		AssetEntryAssetDisplayPageRelCacheModel assetEntryAssetDisplayPageRelCacheModel =
			new AssetEntryAssetDisplayPageRelCacheModel();

		assetEntryAssetDisplayPageRelCacheModel.assetEntryAssetDisplayPageId = getAssetEntryAssetDisplayPageId();

		assetEntryAssetDisplayPageRelCacheModel.assetEntryId = getAssetEntryId();

		assetEntryAssetDisplayPageRelCacheModel.assetDisplayPageId = getAssetDisplayPageId();

		return assetEntryAssetDisplayPageRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{assetEntryAssetDisplayPageId=");
		sb.append(getAssetEntryAssetDisplayPageId());
		sb.append(", assetEntryId=");
		sb.append(getAssetEntryId());
		sb.append(", assetDisplayPageId=");
		sb.append(getAssetDisplayPageId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetEntryAssetDisplayPageId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryAssetDisplayPageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetEntryId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetDisplayPageId</column-name><column-value><![CDATA[");
		sb.append(getAssetDisplayPageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssetEntryAssetDisplayPageRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetEntryAssetDisplayPageRel.class
		};
	private long _assetEntryAssetDisplayPageId;
	private long _assetEntryId;
	private long _originalAssetEntryId;
	private boolean _setOriginalAssetEntryId;
	private long _assetDisplayPageId;
	private long _originalAssetDisplayPageId;
	private boolean _setOriginalAssetDisplayPageId;
	private long _columnBitmask;
	private AssetEntryAssetDisplayPageRel _escapedModel;
}