/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.social.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SocialActivityStatsEntry service. Represents a row in the &quot;SocialActivityStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.social.model.impl.SocialActivityStatsEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.social.model.impl.SocialActivityStatsEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialActivityStatsEntry
 * @see com.liferay.portlet.social.model.impl.SocialActivityStatsEntryImpl
 * @see com.liferay.portlet.social.model.impl.SocialActivityStatsEntryModelImpl
 * @generated
 */
public interface SocialActivityStatsEntryModel extends AttachedModel,
	BaseModel<SocialActivityStatsEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a social activity stats entry model instance should use the {@link SocialActivityStatsEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this social activity stats entry.
	 *
	 * @return the primary key of this social activity stats entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this social activity stats entry.
	 *
	 * @param primaryKey the primary key of this social activity stats entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the activity stats entry ID of this social activity stats entry.
	 *
	 * @return the activity stats entry ID of this social activity stats entry
	 */
	public long getActivityStatsEntryId();

	/**
	 * Sets the activity stats entry ID of this social activity stats entry.
	 *
	 * @param activityStatsEntryId the activity stats entry ID of this social activity stats entry
	 */
	public void setActivityStatsEntryId(long activityStatsEntryId);

	/**
	 * Returns the group ID of this social activity stats entry.
	 *
	 * @return the group ID of this social activity stats entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this social activity stats entry.
	 *
	 * @param groupId the group ID of this social activity stats entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this social activity stats entry.
	 *
	 * @return the company ID of this social activity stats entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this social activity stats entry.
	 *
	 * @param companyId the company ID of this social activity stats entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the fully qualified class name of this social activity stats entry.
	 *
	 * @return the fully qualified class name of this social activity stats entry
	 */
	public String getClassName();

	/**
	 * Returns the class name ID of this social activity stats entry.
	 *
	 * @return the class name ID of this social activity stats entry
	 */
	public long getClassNameId();

	/**
	 * Sets the class name ID of this social activity stats entry.
	 *
	 * @param classNameId the class name ID of this social activity stats entry
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this social activity stats entry.
	 *
	 * @return the class p k of this social activity stats entry
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this social activity stats entry.
	 *
	 * @param classPK the class p k of this social activity stats entry
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the class type of this social activity stats entry.
	 *
	 * @return the class type of this social activity stats entry
	 */
	public int getClassType();

	/**
	 * Sets the class type of this social activity stats entry.
	 *
	 * @param classType the class type of this social activity stats entry
	 */
	public void setClassType(int classType);

	/**
	 * Returns the stat name of this social activity stats entry.
	 *
	 * @return the stat name of this social activity stats entry
	 */
	@AutoEscape
	public String getStatName();

	/**
	 * Sets the stat name of this social activity stats entry.
	 *
	 * @param statName the stat name of this social activity stats entry
	 */
	public void setStatName(String statName);

	/**
	 * Returns the current value of this social activity stats entry.
	 *
	 * @return the current value of this social activity stats entry
	 */
	public int getCurrentValue();

	/**
	 * Sets the current value of this social activity stats entry.
	 *
	 * @param currentValue the current value of this social activity stats entry
	 */
	public void setCurrentValue(int currentValue);

	/**
	 * Returns the overall value of this social activity stats entry.
	 *
	 * @return the overall value of this social activity stats entry
	 */
	public int getOverallValue();

	/**
	 * Sets the overall value of this social activity stats entry.
	 *
	 * @param overallValue the overall value of this social activity stats entry
	 */
	public void setOverallValue(int overallValue);

	/**
	 * Returns the grace value of this social activity stats entry.
	 *
	 * @return the grace value of this social activity stats entry
	 */
	public int getGraceValue();

	/**
	 * Sets the grace value of this social activity stats entry.
	 *
	 * @param graceValue the grace value of this social activity stats entry
	 */
	public void setGraceValue(int graceValue);

	/**
	 * Returns the stat period start of this social activity stats entry.
	 *
	 * @return the stat period start of this social activity stats entry
	 */
	public int getStatPeriodStart();

	/**
	 * Sets the stat period start of this social activity stats entry.
	 *
	 * @param statPeriodStart the stat period start of this social activity stats entry
	 */
	public void setStatPeriodStart(int statPeriodStart);

	/**
	 * Returns the stat period end of this social activity stats entry.
	 *
	 * @return the stat period end of this social activity stats entry
	 */
	public int getStatPeriodEnd();

	/**
	 * Sets the stat period end of this social activity stats entry.
	 *
	 * @param statPeriodEnd the stat period end of this social activity stats entry
	 */
	public void setStatPeriodEnd(int statPeriodEnd);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SocialActivityStatsEntry socialActivityStatsEntry);

	public int hashCode();

	public CacheModel<SocialActivityStatsEntry> toCacheModel();

	public SocialActivityStatsEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}