/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.seo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SiteSEOEntry service. Represents a row in the &quot;SiteSEOEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.layout.seo.model.impl.SiteSEOEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.layout.seo.model.impl.SiteSEOEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteSEOEntry
 * @generated
 */
@ProviderType
public interface SiteSEOEntryModel
	extends BaseModel<SiteSEOEntry>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site seo entry model instance should use the {@link SiteSEOEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this site seo entry.
	 *
	 * @return the primary key of this site seo entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site seo entry.
	 *
	 * @param primaryKey the primary key of this site seo entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this site seo entry.
	 *
	 * @return the mvcc version of this site seo entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this site seo entry.
	 *
	 * @param mvccVersion the mvcc version of this site seo entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this site seo entry.
	 *
	 * @return the uuid of this site seo entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this site seo entry.
	 *
	 * @param uuid the uuid of this site seo entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the site seo entry ID of this site seo entry.
	 *
	 * @return the site seo entry ID of this site seo entry
	 */
	public long getSiteSEOEntryId();

	/**
	 * Sets the site seo entry ID of this site seo entry.
	 *
	 * @param siteSEOEntryId the site seo entry ID of this site seo entry
	 */
	public void setSiteSEOEntryId(long siteSEOEntryId);

	/**
	 * Returns the group ID of this site seo entry.
	 *
	 * @return the group ID of this site seo entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this site seo entry.
	 *
	 * @param groupId the group ID of this site seo entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this site seo entry.
	 *
	 * @return the company ID of this site seo entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this site seo entry.
	 *
	 * @param companyId the company ID of this site seo entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this site seo entry.
	 *
	 * @return the user ID of this site seo entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this site seo entry.
	 *
	 * @param userId the user ID of this site seo entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this site seo entry.
	 *
	 * @return the user uuid of this site seo entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this site seo entry.
	 *
	 * @param userUuid the user uuid of this site seo entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this site seo entry.
	 *
	 * @return the user name of this site seo entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this site seo entry.
	 *
	 * @param userName the user name of this site seo entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this site seo entry.
	 *
	 * @return the create date of this site seo entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this site seo entry.
	 *
	 * @param createDate the create date of this site seo entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this site seo entry.
	 *
	 * @return the modified date of this site seo entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this site seo entry.
	 *
	 * @param modifiedDate the modified date of this site seo entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the open graph enabled of this site seo entry.
	 *
	 * @return the open graph enabled of this site seo entry
	 */
	public boolean getOpenGraphEnabled();

	/**
	 * Returns <code>true</code> if this site seo entry is open graph enabled.
	 *
	 * @return <code>true</code> if this site seo entry is open graph enabled; <code>false</code> otherwise
	 */
	public boolean isOpenGraphEnabled();

	/**
	 * Sets whether this site seo entry is open graph enabled.
	 *
	 * @param openGraphEnabled the open graph enabled of this site seo entry
	 */
	public void setOpenGraphEnabled(boolean openGraphEnabled);

	/**
	 * Returns the open graph image file entry ID of this site seo entry.
	 *
	 * @return the open graph image file entry ID of this site seo entry
	 */
	public long getOpenGraphImageFileEntryId();

	/**
	 * Sets the open graph image file entry ID of this site seo entry.
	 *
	 * @param openGraphImageFileEntryId the open graph image file entry ID of this site seo entry
	 */
	public void setOpenGraphImageFileEntryId(long openGraphImageFileEntryId);

}