/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.change.tracking.engine.model.ChangeEntry;
import com.liferay.change.tracking.engine.model.ChangeEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ChangeEntry service. Represents a row in the &quot;ChangeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ChangeEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChangeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChangeEntryImpl
 * @see ChangeEntry
 * @see ChangeEntryModel
 * @generated
 */
@ProviderType
public class ChangeEntryModelImpl extends BaseModelImpl<ChangeEntry>
	implements ChangeEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a change entry model instance should use the {@link ChangeEntry} interface instead.
	 */
	public static final String TABLE_NAME = "ChangeEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "changeEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "resourcePrimKey", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("changeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourcePrimKey", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table ChangeEntry (changeEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,resourcePrimKey LONG)";
	public static final String TABLE_SQL_DROP = "drop table ChangeEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY changeEntry.changeEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ChangeEntry.changeEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.change.tracking.engine.model.ChangeEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.change.tracking.engine.model.ChangeEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.change.tracking.engine.model.ChangeEntry"),
			true);
	public static final long RESOURCEPRIMKEY_COLUMN_BITMASK = 1L;
	public static final long CHANGEENTRYID_COLUMN_BITMASK = 2L;
	public static final String MAPPING_TABLE_COLLECTIONS_ENTRIES_NAME = "Collections_Entries";
	public static final Object[][] MAPPING_TABLE_COLLECTIONS_ENTRIES_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "changeCollectionId", Types.BIGINT },
			{ "changeEntryId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_COLLECTIONS_ENTRIES_SQL_CREATE = "create table Collections_Entries (companyId LONG not null,changeCollectionId LONG not null,changeEntryId LONG not null,primary key (changeCollectionId, changeEntryId))";
	public static final boolean FINDER_CACHE_ENABLED_COLLECTIONS_ENTRIES = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.Collections_Entries"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.change.tracking.engine.model.ChangeEntry"));

	public ChangeEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _changeEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChangeEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _changeEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChangeEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ChangeEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("changeEntryId", getChangeEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("resourcePrimKey", getResourcePrimKey());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long changeEntryId = (Long)attributes.get("changeEntryId");

		if (changeEntryId != null) {
			setChangeEntryId(changeEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Long resourcePrimKey = (Long)attributes.get("resourcePrimKey");

		if (resourcePrimKey != null) {
			setResourcePrimKey(resourcePrimKey);
		}
	}

	@Override
	public long getChangeEntryId() {
		return _changeEntryId;
	}

	@Override
	public void setChangeEntryId(long changeEntryId) {
		_changeEntryId = changeEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public long getResourcePrimKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setResourcePrimKey(long resourcePrimKey) {
		_columnBitmask |= RESOURCEPRIMKEY_COLUMN_BITMASK;

		if (!_setOriginalResourcePrimKey) {
			_setOriginalResourcePrimKey = true;

			_originalResourcePrimKey = _resourcePrimKey;
		}

		_resourcePrimKey = resourcePrimKey;
	}

	@Override
	public boolean isResourceMain() {
		return true;
	}

	public long getOriginalResourcePrimKey() {
		return _originalResourcePrimKey;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ChangeEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChangeEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChangeEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChangeEntryImpl changeEntryImpl = new ChangeEntryImpl();

		changeEntryImpl.setChangeEntryId(getChangeEntryId());
		changeEntryImpl.setCompanyId(getCompanyId());
		changeEntryImpl.setUserId(getUserId());
		changeEntryImpl.setUserName(getUserName());
		changeEntryImpl.setCreateDate(getCreateDate());
		changeEntryImpl.setModifiedDate(getModifiedDate());
		changeEntryImpl.setClassNameId(getClassNameId());
		changeEntryImpl.setClassPK(getClassPK());
		changeEntryImpl.setResourcePrimKey(getResourcePrimKey());

		changeEntryImpl.resetOriginalValues();

		return changeEntryImpl;
	}

	@Override
	public int compareTo(ChangeEntry changeEntry) {
		long primaryKey = changeEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChangeEntry)) {
			return false;
		}

		ChangeEntry changeEntry = (ChangeEntry)obj;

		long primaryKey = changeEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ChangeEntryModelImpl changeEntryModelImpl = this;

		changeEntryModelImpl._setModifiedDate = false;

		changeEntryModelImpl._originalResourcePrimKey = changeEntryModelImpl._resourcePrimKey;

		changeEntryModelImpl._setOriginalResourcePrimKey = false;

		changeEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChangeEntry> toCacheModel() {
		ChangeEntryCacheModel changeEntryCacheModel = new ChangeEntryCacheModel();

		changeEntryCacheModel.changeEntryId = getChangeEntryId();

		changeEntryCacheModel.companyId = getCompanyId();

		changeEntryCacheModel.userId = getUserId();

		changeEntryCacheModel.userName = getUserName();

		String userName = changeEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			changeEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			changeEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			changeEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			changeEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			changeEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		changeEntryCacheModel.classNameId = getClassNameId();

		changeEntryCacheModel.classPK = getClassPK();

		changeEntryCacheModel.resourcePrimKey = getResourcePrimKey();

		return changeEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{changeEntryId=");
		sb.append(getChangeEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", resourcePrimKey=");
		sb.append(getResourcePrimKey());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.change.tracking.engine.model.ChangeEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>changeEntryId</column-name><column-value><![CDATA[");
		sb.append(getChangeEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourcePrimKey</column-name><column-value><![CDATA[");
		sb.append(getResourcePrimKey());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ChangeEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ChangeEntry.class, ModelWrapper.class
		};
	private long _changeEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _resourcePrimKey;
	private long _originalResourcePrimKey;
	private boolean _setOriginalResourcePrimKey;
	private long _columnBitmask;
	private ChangeEntry _escapedModel;
}