/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RemoteAppEntryLocalization service. Represents a row in the &quot;RemoteAppEntryLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.remote.app.model.impl.RemoteAppEntryLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.remote.app.model.impl.RemoteAppEntryLocalizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RemoteAppEntryLocalization
 * @generated
 */
@ProviderType
public interface RemoteAppEntryLocalizationModel
	extends BaseModel<RemoteAppEntryLocalization>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a remote app entry localization model instance should use the {@link RemoteAppEntryLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this remote app entry localization.
	 *
	 * @return the primary key of this remote app entry localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this remote app entry localization.
	 *
	 * @param primaryKey the primary key of this remote app entry localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this remote app entry localization.
	 *
	 * @return the mvcc version of this remote app entry localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this remote app entry localization.
	 *
	 * @param mvccVersion the mvcc version of this remote app entry localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the remote app entry localization ID of this remote app entry localization.
	 *
	 * @return the remote app entry localization ID of this remote app entry localization
	 */
	public long getRemoteAppEntryLocalizationId();

	/**
	 * Sets the remote app entry localization ID of this remote app entry localization.
	 *
	 * @param remoteAppEntryLocalizationId the remote app entry localization ID of this remote app entry localization
	 */
	public void setRemoteAppEntryLocalizationId(
		long remoteAppEntryLocalizationId);

	/**
	 * Returns the company ID of this remote app entry localization.
	 *
	 * @return the company ID of this remote app entry localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this remote app entry localization.
	 *
	 * @param companyId the company ID of this remote app entry localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the remote app entry ID of this remote app entry localization.
	 *
	 * @return the remote app entry ID of this remote app entry localization
	 */
	public long getRemoteAppEntryId();

	/**
	 * Sets the remote app entry ID of this remote app entry localization.
	 *
	 * @param remoteAppEntryId the remote app entry ID of this remote app entry localization
	 */
	public void setRemoteAppEntryId(long remoteAppEntryId);

	/**
	 * Returns the language ID of this remote app entry localization.
	 *
	 * @return the language ID of this remote app entry localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this remote app entry localization.
	 *
	 * @param languageId the language ID of this remote app entry localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the description of this remote app entry localization.
	 *
	 * @return the description of this remote app entry localization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this remote app entry localization.
	 *
	 * @param description the description of this remote app entry localization
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this remote app entry localization.
	 *
	 * @return the name of this remote app entry localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this remote app entry localization.
	 *
	 * @param name the name of this remote app entry localization
	 */
	public void setName(String name);

	@Override
	public RemoteAppEntryLocalization cloneWithOriginalValues();

}