/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.repository.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContentRepositoryEntry service. Represents a row in the &quot;ContentRepositoryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.content.repository.model.impl.ContentRepositoryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.content.repository.model.impl.ContentRepositoryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentRepositoryEntry
 * @generated
 */
@ProviderType
public interface ContentRepositoryEntryModel
	extends BaseModel<ContentRepositoryEntry>, MVCCModel, ShardedModel,
			StagedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content repository entry model instance should use the {@link ContentRepositoryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this content repository entry.
	 *
	 * @return the primary key of this content repository entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content repository entry.
	 *
	 * @param primaryKey the primary key of this content repository entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this content repository entry.
	 *
	 * @return the mvcc version of this content repository entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this content repository entry.
	 *
	 * @param mvccVersion the mvcc version of this content repository entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this content repository entry.
	 *
	 * @return the uuid of this content repository entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this content repository entry.
	 *
	 * @param uuid the uuid of this content repository entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the content repository entry ID of this content repository entry.
	 *
	 * @return the content repository entry ID of this content repository entry
	 */
	public long getContentRepositoryEntryId();

	/**
	 * Sets the content repository entry ID of this content repository entry.
	 *
	 * @param contentRepositoryEntryId the content repository entry ID of this content repository entry
	 */
	public void setContentRepositoryEntryId(long contentRepositoryEntryId);

	/**
	 * Returns the company ID of this content repository entry.
	 *
	 * @return the company ID of this content repository entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this content repository entry.
	 *
	 * @param companyId the company ID of this content repository entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this content repository entry.
	 *
	 * @return the user ID of this content repository entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this content repository entry.
	 *
	 * @param userId the user ID of this content repository entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this content repository entry.
	 *
	 * @return the user uuid of this content repository entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this content repository entry.
	 *
	 * @param userUuid the user uuid of this content repository entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this content repository entry.
	 *
	 * @return the create date of this content repository entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this content repository entry.
	 *
	 * @param createDate the create date of this content repository entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this content repository entry.
	 *
	 * @return the modified date of this content repository entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this content repository entry.
	 *
	 * @param modifiedDate the modified date of this content repository entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this content repository entry.
	 *
	 * @return the group ID of this content repository entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this content repository entry.
	 *
	 * @param groupId the group ID of this content repository entry
	 */
	public void setGroupId(long groupId);

}