/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.change.tracking.engine.model.ChangeEntry;
import com.liferay.change.tracking.engine.service.ChangeEntryLocalService;
import com.liferay.change.tracking.engine.service.persistence.ChangeCollectionPersistence;
import com.liferay.change.tracking.engine.service.persistence.ChangeEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the change entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.change.tracking.engine.service.impl.ChangeEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.change.tracking.engine.service.impl.ChangeEntryLocalServiceImpl
 * @see com.liferay.change.tracking.engine.service.ChangeEntryLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ChangeEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ChangeEntryLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.change.tracking.engine.service.ChangeEntryLocalServiceUtil} to access the change entry local service.
	 */

	/**
	 * Adds the change entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeEntry the change entry
	 * @return the change entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChangeEntry addChangeEntry(ChangeEntry changeEntry) {
		changeEntry.setNew(true);

		return changeEntryPersistence.update(changeEntry);
	}

	/**
	 * Creates a new change entry with the primary key. Does not add the change entry to the database.
	 *
	 * @param changeEntryId the primary key for the new change entry
	 * @return the new change entry
	 */
	@Override
	@Transactional(enabled = false)
	public ChangeEntry createChangeEntry(long changeEntryId) {
		return changeEntryPersistence.create(changeEntryId);
	}

	/**
	 * Deletes the change entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeEntryId the primary key of the change entry
	 * @return the change entry that was removed
	 * @throws PortalException if a change entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChangeEntry deleteChangeEntry(long changeEntryId)
		throws PortalException {
		return changeEntryPersistence.remove(changeEntryId);
	}

	/**
	 * Deletes the change entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeEntry the change entry
	 * @return the change entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChangeEntry deleteChangeEntry(ChangeEntry changeEntry) {
		return changeEntryPersistence.remove(changeEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ChangeEntry.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return changeEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return changeEntryPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return changeEntryPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return changeEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return changeEntryPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ChangeEntry fetchChangeEntry(long changeEntryId) {
		return changeEntryPersistence.fetchByPrimaryKey(changeEntryId);
	}

	/**
	 * Returns the change entry with the primary key.
	 *
	 * @param changeEntryId the primary key of the change entry
	 * @return the change entry
	 * @throws PortalException if a change entry with the primary key could not be found
	 */
	@Override
	public ChangeEntry getChangeEntry(long changeEntryId)
		throws PortalException {
		return changeEntryPersistence.findByPrimaryKey(changeEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(changeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChangeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("changeEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(changeEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ChangeEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"changeEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(changeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChangeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("changeEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return changeEntryLocalService.deleteChangeEntry((ChangeEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return changeEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	@Override
	public List<?extends PersistedModel> getPersistedModel(long resourcePrimKey)
		throws PortalException {
		return changeEntryPersistence.findByResourcePrimKey(resourcePrimKey);
	}

	/**
	 * Returns a range of all the change entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of change entries
	 * @param end the upper bound of the range of change entries (not inclusive)
	 * @return the range of change entries
	 */
	@Override
	public List<ChangeEntry> getChangeEntries(int start, int end) {
		return changeEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of change entries.
	 *
	 * @return the number of change entries
	 */
	@Override
	public int getChangeEntriesCount() {
		return changeEntryPersistence.countAll();
	}

	/**
	 * Updates the change entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param changeEntry the change entry
	 * @return the change entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChangeEntry updateChangeEntry(ChangeEntry changeEntry) {
		return changeEntryPersistence.update(changeEntry);
	}

	/**
	 */
	@Override
	public void addChangeCollectionChangeEntry(long changeCollectionId,
		long changeEntryId) {
		changeCollectionPersistence.addChangeEntry(changeCollectionId,
			changeEntryId);
	}

	/**
	 */
	@Override
	public void addChangeCollectionChangeEntry(long changeCollectionId,
		ChangeEntry changeEntry) {
		changeCollectionPersistence.addChangeEntry(changeCollectionId,
			changeEntry);
	}

	/**
	 */
	@Override
	public void addChangeCollectionChangeEntries(long changeCollectionId,
		long[] changeEntryIds) {
		changeCollectionPersistence.addChangeEntries(changeCollectionId,
			changeEntryIds);
	}

	/**
	 */
	@Override
	public void addChangeCollectionChangeEntries(long changeCollectionId,
		List<ChangeEntry> changeEntries) {
		changeCollectionPersistence.addChangeEntries(changeCollectionId,
			changeEntries);
	}

	/**
	 */
	@Override
	public void clearChangeCollectionChangeEntries(long changeCollectionId) {
		changeCollectionPersistence.clearChangeEntries(changeCollectionId);
	}

	/**
	 */
	@Override
	public void deleteChangeCollectionChangeEntry(long changeCollectionId,
		long changeEntryId) {
		changeCollectionPersistence.removeChangeEntry(changeCollectionId,
			changeEntryId);
	}

	/**
	 */
	@Override
	public void deleteChangeCollectionChangeEntry(long changeCollectionId,
		ChangeEntry changeEntry) {
		changeCollectionPersistence.removeChangeEntry(changeCollectionId,
			changeEntry);
	}

	/**
	 */
	@Override
	public void deleteChangeCollectionChangeEntries(long changeCollectionId,
		long[] changeEntryIds) {
		changeCollectionPersistence.removeChangeEntries(changeCollectionId,
			changeEntryIds);
	}

	/**
	 */
	@Override
	public void deleteChangeCollectionChangeEntries(long changeCollectionId,
		List<ChangeEntry> changeEntries) {
		changeCollectionPersistence.removeChangeEntries(changeCollectionId,
			changeEntries);
	}

	/**
	 * Returns the changeCollectionIds of the change collections associated with the change entry.
	 *
	 * @param changeEntryId the changeEntryId of the change entry
	 * @return long[] the changeCollectionIds of change collections associated with the change entry
	 */
	@Override
	public long[] getChangeCollectionPrimaryKeys(long changeEntryId) {
		return changeEntryPersistence.getChangeCollectionPrimaryKeys(changeEntryId);
	}

	/**
	 */
	@Override
	public List<ChangeEntry> getChangeCollectionChangeEntries(
		long changeCollectionId) {
		return changeCollectionPersistence.getChangeEntries(changeCollectionId);
	}

	/**
	 */
	@Override
	public List<ChangeEntry> getChangeCollectionChangeEntries(
		long changeCollectionId, int start, int end) {
		return changeCollectionPersistence.getChangeEntries(changeCollectionId,
			start, end);
	}

	/**
	 */
	@Override
	public List<ChangeEntry> getChangeCollectionChangeEntries(
		long changeCollectionId, int start, int end,
		OrderByComparator<ChangeEntry> orderByComparator) {
		return changeCollectionPersistence.getChangeEntries(changeCollectionId,
			start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getChangeCollectionChangeEntriesCount(long changeCollectionId) {
		return changeCollectionPersistence.getChangeEntriesSize(changeCollectionId);
	}

	/**
	 */
	@Override
	public boolean hasChangeCollectionChangeEntry(long changeCollectionId,
		long changeEntryId) {
		return changeCollectionPersistence.containsChangeEntry(changeCollectionId,
			changeEntryId);
	}

	/**
	 */
	@Override
	public boolean hasChangeCollectionChangeEntries(long changeCollectionId) {
		return changeCollectionPersistence.containsChangeEntries(changeCollectionId);
	}

	/**
	 */
	@Override
	public void setChangeCollectionChangeEntries(long changeCollectionId,
		long[] changeEntryIds) {
		changeCollectionPersistence.setChangeEntries(changeCollectionId,
			changeEntryIds);
	}

	/**
	 * Returns the change collection local service.
	 *
	 * @return the change collection local service
	 */
	public com.liferay.change.tracking.engine.service.ChangeCollectionLocalService getChangeCollectionLocalService() {
		return changeCollectionLocalService;
	}

	/**
	 * Sets the change collection local service.
	 *
	 * @param changeCollectionLocalService the change collection local service
	 */
	public void setChangeCollectionLocalService(
		com.liferay.change.tracking.engine.service.ChangeCollectionLocalService changeCollectionLocalService) {
		this.changeCollectionLocalService = changeCollectionLocalService;
	}

	/**
	 * Returns the change collection persistence.
	 *
	 * @return the change collection persistence
	 */
	public ChangeCollectionPersistence getChangeCollectionPersistence() {
		return changeCollectionPersistence;
	}

	/**
	 * Sets the change collection persistence.
	 *
	 * @param changeCollectionPersistence the change collection persistence
	 */
	public void setChangeCollectionPersistence(
		ChangeCollectionPersistence changeCollectionPersistence) {
		this.changeCollectionPersistence = changeCollectionPersistence;
	}

	/**
	 * Returns the change entry local service.
	 *
	 * @return the change entry local service
	 */
	public ChangeEntryLocalService getChangeEntryLocalService() {
		return changeEntryLocalService;
	}

	/**
	 * Sets the change entry local service.
	 *
	 * @param changeEntryLocalService the change entry local service
	 */
	public void setChangeEntryLocalService(
		ChangeEntryLocalService changeEntryLocalService) {
		this.changeEntryLocalService = changeEntryLocalService;
	}

	/**
	 * Returns the change entry persistence.
	 *
	 * @return the change entry persistence
	 */
	public ChangeEntryPersistence getChangeEntryPersistence() {
		return changeEntryPersistence;
	}

	/**
	 * Sets the change entry persistence.
	 *
	 * @param changeEntryPersistence the change entry persistence
	 */
	public void setChangeEntryPersistence(
		ChangeEntryPersistence changeEntryPersistence) {
		this.changeEntryPersistence = changeEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.change.tracking.engine.model.ChangeEntry",
			changeEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.change.tracking.engine.model.ChangeEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChangeEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChangeEntry.class;
	}

	protected String getModelClassName() {
		return ChangeEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = changeEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.change.tracking.engine.service.ChangeCollectionLocalService.class)
	protected com.liferay.change.tracking.engine.service.ChangeCollectionLocalService changeCollectionLocalService;
	@BeanReference(type = ChangeCollectionPersistence.class)
	protected ChangeCollectionPersistence changeCollectionPersistence;
	@BeanReference(type = ChangeEntryLocalService.class)
	protected ChangeEntryLocalService changeEntryLocalService;
	@BeanReference(type = ChangeEntryPersistence.class)
	protected ChangeEntryPersistence changeEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}