/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.change.tracking.engine.model.ChangeCollection;
import com.liferay.change.tracking.engine.service.ChangeCollectionLocalService;
import com.liferay.change.tracking.engine.service.persistence.ChangeCollectionPersistence;
import com.liferay.change.tracking.engine.service.persistence.ChangeEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the change collection local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.change.tracking.engine.service.impl.ChangeCollectionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.change.tracking.engine.service.impl.ChangeCollectionLocalServiceImpl
 * @see com.liferay.change.tracking.engine.service.ChangeCollectionLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ChangeCollectionLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ChangeCollectionLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.change.tracking.engine.service.ChangeCollectionLocalServiceUtil} to access the change collection local service.
	 */

	/**
	 * Adds the change collection to the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeCollection the change collection
	 * @return the change collection that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChangeCollection addChangeCollection(
		ChangeCollection changeCollection) {
		changeCollection.setNew(true);

		return changeCollectionPersistence.update(changeCollection);
	}

	/**
	 * Creates a new change collection with the primary key. Does not add the change collection to the database.
	 *
	 * @param changeCollectionId the primary key for the new change collection
	 * @return the new change collection
	 */
	@Override
	@Transactional(enabled = false)
	public ChangeCollection createChangeCollection(long changeCollectionId) {
		return changeCollectionPersistence.create(changeCollectionId);
	}

	/**
	 * Deletes the change collection with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeCollectionId the primary key of the change collection
	 * @return the change collection that was removed
	 * @throws PortalException if a change collection with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChangeCollection deleteChangeCollection(long changeCollectionId)
		throws PortalException {
		return changeCollectionPersistence.remove(changeCollectionId);
	}

	/**
	 * Deletes the change collection from the database. Also notifies the appropriate model listeners.
	 *
	 * @param changeCollection the change collection
	 * @return the change collection that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChangeCollection deleteChangeCollection(
		ChangeCollection changeCollection) {
		return changeCollectionPersistence.remove(changeCollection);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ChangeCollection.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return changeCollectionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeCollectionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return changeCollectionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeCollectionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return changeCollectionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return changeCollectionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return changeCollectionPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ChangeCollection fetchChangeCollection(long changeCollectionId) {
		return changeCollectionPersistence.fetchByPrimaryKey(changeCollectionId);
	}

	/**
	 * Returns the change collection with the primary key.
	 *
	 * @param changeCollectionId the primary key of the change collection
	 * @return the change collection
	 * @throws PortalException if a change collection with the primary key could not be found
	 */
	@Override
	public ChangeCollection getChangeCollection(long changeCollectionId)
		throws PortalException {
		return changeCollectionPersistence.findByPrimaryKey(changeCollectionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(changeCollectionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChangeCollection.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("changeCollectionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(changeCollectionLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ChangeCollection.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"changeCollectionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(changeCollectionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChangeCollection.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("changeCollectionId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return changeCollectionLocalService.deleteChangeCollection((ChangeCollection)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return changeCollectionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the change collections.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.change.tracking.engine.model.impl.ChangeCollectionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of change collections
	 * @param end the upper bound of the range of change collections (not inclusive)
	 * @return the range of change collections
	 */
	@Override
	public List<ChangeCollection> getChangeCollections(int start, int end) {
		return changeCollectionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of change collections.
	 *
	 * @return the number of change collections
	 */
	@Override
	public int getChangeCollectionsCount() {
		return changeCollectionPersistence.countAll();
	}

	/**
	 * Updates the change collection in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param changeCollection the change collection
	 * @return the change collection that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChangeCollection updateChangeCollection(
		ChangeCollection changeCollection) {
		return changeCollectionPersistence.update(changeCollection);
	}

	/**
	 */
	@Override
	public void addChangeEntryChangeCollection(long changeEntryId,
		long changeCollectionId) {
		changeEntryPersistence.addChangeCollection(changeEntryId,
			changeCollectionId);
	}

	/**
	 */
	@Override
	public void addChangeEntryChangeCollection(long changeEntryId,
		ChangeCollection changeCollection) {
		changeEntryPersistence.addChangeCollection(changeEntryId,
			changeCollection);
	}

	/**
	 */
	@Override
	public void addChangeEntryChangeCollections(long changeEntryId,
		long[] changeCollectionIds) {
		changeEntryPersistence.addChangeCollections(changeEntryId,
			changeCollectionIds);
	}

	/**
	 */
	@Override
	public void addChangeEntryChangeCollections(long changeEntryId,
		List<ChangeCollection> changeCollections) {
		changeEntryPersistence.addChangeCollections(changeEntryId,
			changeCollections);
	}

	/**
	 */
	@Override
	public void clearChangeEntryChangeCollections(long changeEntryId) {
		changeEntryPersistence.clearChangeCollections(changeEntryId);
	}

	/**
	 */
	@Override
	public void deleteChangeEntryChangeCollection(long changeEntryId,
		long changeCollectionId) {
		changeEntryPersistence.removeChangeCollection(changeEntryId,
			changeCollectionId);
	}

	/**
	 */
	@Override
	public void deleteChangeEntryChangeCollection(long changeEntryId,
		ChangeCollection changeCollection) {
		changeEntryPersistence.removeChangeCollection(changeEntryId,
			changeCollection);
	}

	/**
	 */
	@Override
	public void deleteChangeEntryChangeCollections(long changeEntryId,
		long[] changeCollectionIds) {
		changeEntryPersistence.removeChangeCollections(changeEntryId,
			changeCollectionIds);
	}

	/**
	 */
	@Override
	public void deleteChangeEntryChangeCollections(long changeEntryId,
		List<ChangeCollection> changeCollections) {
		changeEntryPersistence.removeChangeCollections(changeEntryId,
			changeCollections);
	}

	/**
	 * Returns the changeEntryIds of the change entries associated with the change collection.
	 *
	 * @param changeCollectionId the changeCollectionId of the change collection
	 * @return long[] the changeEntryIds of change entries associated with the change collection
	 */
	@Override
	public long[] getChangeEntryPrimaryKeys(long changeCollectionId) {
		return changeCollectionPersistence.getChangeEntryPrimaryKeys(changeCollectionId);
	}

	/**
	 */
	@Override
	public List<ChangeCollection> getChangeEntryChangeCollections(
		long changeEntryId) {
		return changeEntryPersistence.getChangeCollections(changeEntryId);
	}

	/**
	 */
	@Override
	public List<ChangeCollection> getChangeEntryChangeCollections(
		long changeEntryId, int start, int end) {
		return changeEntryPersistence.getChangeCollections(changeEntryId,
			start, end);
	}

	/**
	 */
	@Override
	public List<ChangeCollection> getChangeEntryChangeCollections(
		long changeEntryId, int start, int end,
		OrderByComparator<ChangeCollection> orderByComparator) {
		return changeEntryPersistence.getChangeCollections(changeEntryId,
			start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getChangeEntryChangeCollectionsCount(long changeEntryId) {
		return changeEntryPersistence.getChangeCollectionsSize(changeEntryId);
	}

	/**
	 */
	@Override
	public boolean hasChangeEntryChangeCollection(long changeEntryId,
		long changeCollectionId) {
		return changeEntryPersistence.containsChangeCollection(changeEntryId,
			changeCollectionId);
	}

	/**
	 */
	@Override
	public boolean hasChangeEntryChangeCollections(long changeEntryId) {
		return changeEntryPersistence.containsChangeCollections(changeEntryId);
	}

	/**
	 */
	@Override
	public void setChangeEntryChangeCollections(long changeEntryId,
		long[] changeCollectionIds) {
		changeEntryPersistence.setChangeCollections(changeEntryId,
			changeCollectionIds);
	}

	/**
	 * Returns the change collection local service.
	 *
	 * @return the change collection local service
	 */
	public ChangeCollectionLocalService getChangeCollectionLocalService() {
		return changeCollectionLocalService;
	}

	/**
	 * Sets the change collection local service.
	 *
	 * @param changeCollectionLocalService the change collection local service
	 */
	public void setChangeCollectionLocalService(
		ChangeCollectionLocalService changeCollectionLocalService) {
		this.changeCollectionLocalService = changeCollectionLocalService;
	}

	/**
	 * Returns the change collection persistence.
	 *
	 * @return the change collection persistence
	 */
	public ChangeCollectionPersistence getChangeCollectionPersistence() {
		return changeCollectionPersistence;
	}

	/**
	 * Sets the change collection persistence.
	 *
	 * @param changeCollectionPersistence the change collection persistence
	 */
	public void setChangeCollectionPersistence(
		ChangeCollectionPersistence changeCollectionPersistence) {
		this.changeCollectionPersistence = changeCollectionPersistence;
	}

	/**
	 * Returns the change entry local service.
	 *
	 * @return the change entry local service
	 */
	public com.liferay.change.tracking.engine.service.ChangeEntryLocalService getChangeEntryLocalService() {
		return changeEntryLocalService;
	}

	/**
	 * Sets the change entry local service.
	 *
	 * @param changeEntryLocalService the change entry local service
	 */
	public void setChangeEntryLocalService(
		com.liferay.change.tracking.engine.service.ChangeEntryLocalService changeEntryLocalService) {
		this.changeEntryLocalService = changeEntryLocalService;
	}

	/**
	 * Returns the change entry persistence.
	 *
	 * @return the change entry persistence
	 */
	public ChangeEntryPersistence getChangeEntryPersistence() {
		return changeEntryPersistence;
	}

	/**
	 * Sets the change entry persistence.
	 *
	 * @param changeEntryPersistence the change entry persistence
	 */
	public void setChangeEntryPersistence(
		ChangeEntryPersistence changeEntryPersistence) {
		this.changeEntryPersistence = changeEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.change.tracking.engine.model.ChangeCollection",
			changeCollectionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.change.tracking.engine.model.ChangeCollection");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChangeCollectionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChangeCollection.class;
	}

	protected String getModelClassName() {
		return ChangeCollection.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = changeCollectionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ChangeCollectionLocalService.class)
	protected ChangeCollectionLocalService changeCollectionLocalService;
	@BeanReference(type = ChangeCollectionPersistence.class)
	protected ChangeCollectionPersistence changeCollectionPersistence;
	@BeanReference(type = com.liferay.change.tracking.engine.service.ChangeEntryLocalService.class)
	protected com.liferay.change.tracking.engine.service.ChangeEntryLocalService changeEntryLocalService;
	@BeanReference(type = ChangeEntryPersistence.class)
	protected ChangeEntryPersistence changeEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}