/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NotificationQueueEntryRecipient service. Represents a row in the &quot;NQueueEntryRecipient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.notification.model.impl.NotificationQueueEntryRecipientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.notification.model.impl.NotificationQueueEntryRecipientImpl</code>.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationQueueEntryRecipient
 * @generated
 */
@ProviderType
public interface NotificationQueueEntryRecipientModel
	extends AuditedModel, BaseModel<NotificationQueueEntryRecipient>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification queue entry recipient model instance should use the {@link NotificationQueueEntryRecipient} interface instead.
	 */

	/**
	 * Returns the primary key of this notification queue entry recipient.
	 *
	 * @return the primary key of this notification queue entry recipient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification queue entry recipient.
	 *
	 * @param primaryKey the primary key of this notification queue entry recipient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this notification queue entry recipient.
	 *
	 * @return the mvcc version of this notification queue entry recipient
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this notification queue entry recipient.
	 *
	 * @param mvccVersion the mvcc version of this notification queue entry recipient
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the notification queue entry recipient ID of this notification queue entry recipient.
	 *
	 * @return the notification queue entry recipient ID of this notification queue entry recipient
	 */
	public long getNotificationQueueEntryRecipientId();

	/**
	 * Sets the notification queue entry recipient ID of this notification queue entry recipient.
	 *
	 * @param notificationQueueEntryRecipientId the notification queue entry recipient ID of this notification queue entry recipient
	 */
	public void setNotificationQueueEntryRecipientId(
		long notificationQueueEntryRecipientId);

	/**
	 * Returns the company ID of this notification queue entry recipient.
	 *
	 * @return the company ID of this notification queue entry recipient
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this notification queue entry recipient.
	 *
	 * @param companyId the company ID of this notification queue entry recipient
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this notification queue entry recipient.
	 *
	 * @return the user ID of this notification queue entry recipient
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this notification queue entry recipient.
	 *
	 * @param userId the user ID of this notification queue entry recipient
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notification queue entry recipient.
	 *
	 * @return the user uuid of this notification queue entry recipient
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notification queue entry recipient.
	 *
	 * @param userUuid the user uuid of this notification queue entry recipient
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this notification queue entry recipient.
	 *
	 * @return the user name of this notification queue entry recipient
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this notification queue entry recipient.
	 *
	 * @param userName the user name of this notification queue entry recipient
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this notification queue entry recipient.
	 *
	 * @return the create date of this notification queue entry recipient
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this notification queue entry recipient.
	 *
	 * @param createDate the create date of this notification queue entry recipient
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this notification queue entry recipient.
	 *
	 * @return the modified date of this notification queue entry recipient
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this notification queue entry recipient.
	 *
	 * @param modifiedDate the modified date of this notification queue entry recipient
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the notification queue entry ID of this notification queue entry recipient.
	 *
	 * @return the notification queue entry ID of this notification queue entry recipient
	 */
	public long getNotificationQueueEntryId();

	/**
	 * Sets the notification queue entry ID of this notification queue entry recipient.
	 *
	 * @param notificationQueueEntryId the notification queue entry ID of this notification queue entry recipient
	 */
	public void setNotificationQueueEntryId(long notificationQueueEntryId);

	/**
	 * Returns the type of this notification queue entry recipient.
	 *
	 * @return the type of this notification queue entry recipient
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this notification queue entry recipient.
	 *
	 * @param type the type of this notification queue entry recipient
	 */
	public void setType(String type);

	@Override
	public NotificationQueueEntryRecipient cloneWithOriginalValues();

}