/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NotificationTemplateRecipientSetting service. Represents a row in the &quot;NTemplateRecipientSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.notification.model.impl.NotificationTemplateRecipientSettingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.notification.model.impl.NotificationTemplateRecipientSettingImpl</code>.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see NotificationTemplateRecipientSetting
 * @generated
 */
@ProviderType
public interface NotificationTemplateRecipientSettingModel
	extends AuditedModel, BaseModel<NotificationTemplateRecipientSetting>,
			MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification template recipient setting model instance should use the {@link NotificationTemplateRecipientSetting} interface instead.
	 */

	/**
	 * Returns the primary key of this notification template recipient setting.
	 *
	 * @return the primary key of this notification template recipient setting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification template recipient setting.
	 *
	 * @param primaryKey the primary key of this notification template recipient setting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this notification template recipient setting.
	 *
	 * @return the mvcc version of this notification template recipient setting
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this notification template recipient setting.
	 *
	 * @param mvccVersion the mvcc version of this notification template recipient setting
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the notification template recipient setting ID of this notification template recipient setting.
	 *
	 * @return the notification template recipient setting ID of this notification template recipient setting
	 */
	public long getNotificationTemplateRecipientSettingId();

	/**
	 * Sets the notification template recipient setting ID of this notification template recipient setting.
	 *
	 * @param notificationTemplateRecipientSettingId the notification template recipient setting ID of this notification template recipient setting
	 */
	public void setNotificationTemplateRecipientSettingId(
		long notificationTemplateRecipientSettingId);

	/**
	 * Returns the company ID of this notification template recipient setting.
	 *
	 * @return the company ID of this notification template recipient setting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this notification template recipient setting.
	 *
	 * @param companyId the company ID of this notification template recipient setting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this notification template recipient setting.
	 *
	 * @return the user ID of this notification template recipient setting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this notification template recipient setting.
	 *
	 * @param userId the user ID of this notification template recipient setting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notification template recipient setting.
	 *
	 * @return the user uuid of this notification template recipient setting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notification template recipient setting.
	 *
	 * @param userUuid the user uuid of this notification template recipient setting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this notification template recipient setting.
	 *
	 * @return the user name of this notification template recipient setting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this notification template recipient setting.
	 *
	 * @param userName the user name of this notification template recipient setting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this notification template recipient setting.
	 *
	 * @return the create date of this notification template recipient setting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this notification template recipient setting.
	 *
	 * @param createDate the create date of this notification template recipient setting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this notification template recipient setting.
	 *
	 * @return the modified date of this notification template recipient setting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this notification template recipient setting.
	 *
	 * @param modifiedDate the modified date of this notification template recipient setting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the notification template recipient ID of this notification template recipient setting.
	 *
	 * @return the notification template recipient ID of this notification template recipient setting
	 */
	public long getNotificationTemplateRecipientId();

	/**
	 * Sets the notification template recipient ID of this notification template recipient setting.
	 *
	 * @param notificationTemplateRecipientId the notification template recipient ID of this notification template recipient setting
	 */
	public void setNotificationTemplateRecipientId(
		long notificationTemplateRecipientId);

	/**
	 * Returns the name of this notification template recipient setting.
	 *
	 * @return the name of this notification template recipient setting
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this notification template recipient setting.
	 *
	 * @param name the name of this notification template recipient setting
	 */
	public void setName(String name);

	/**
	 * Returns the value of this notification template recipient setting.
	 *
	 * @return the value of this notification template recipient setting
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this notification template recipient setting.
	 *
	 * @param value the value of this notification template recipient setting
	 */
	public void setValue(String value);

	@Override
	public NotificationTemplateRecipientSetting cloneWithOriginalValues();

}