/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel;
import com.liferay.asset.entry.rel.service.AssetEntryAssetDisplayPageRelLocalService;
import com.liferay.asset.entry.rel.service.persistence.AssetEntryAssetDisplayPageRelPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry asset display page rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.entry.rel.service.impl.AssetEntryAssetDisplayPageRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.entry.rel.service.impl.AssetEntryAssetDisplayPageRelLocalServiceImpl
 * @see com.liferay.asset.entry.rel.service.AssetEntryAssetDisplayPageRelLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetEntryAssetDisplayPageRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AssetEntryAssetDisplayPageRelLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.entry.rel.service.AssetEntryAssetDisplayPageRelLocalServiceUtil} to access the asset entry asset display page rel local service.
	 */

	/**
	 * Adds the asset entry asset display page rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetDisplayPageRel the asset entry asset display page rel
	 * @return the asset entry asset display page rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetDisplayPageRel addAssetEntryAssetDisplayPageRel(
		AssetEntryAssetDisplayPageRel assetEntryAssetDisplayPageRel) {
		assetEntryAssetDisplayPageRel.setNew(true);

		return assetEntryAssetDisplayPageRelPersistence.update(assetEntryAssetDisplayPageRel);
	}

	/**
	 * Creates a new asset entry asset display page rel with the primary key. Does not add the asset entry asset display page rel to the database.
	 *
	 * @param assetEntryAssetDisplayPageId the primary key for the new asset entry asset display page rel
	 * @return the new asset entry asset display page rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetEntryAssetDisplayPageRel createAssetEntryAssetDisplayPageRel(
		long assetEntryAssetDisplayPageId) {
		return assetEntryAssetDisplayPageRelPersistence.create(assetEntryAssetDisplayPageId);
	}

	/**
	 * Deletes the asset entry asset display page rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetDisplayPageId the primary key of the asset entry asset display page rel
	 * @return the asset entry asset display page rel that was removed
	 * @throws PortalException if a asset entry asset display page rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetDisplayPageRel deleteAssetEntryAssetDisplayPageRel(
		long assetEntryAssetDisplayPageId) throws PortalException {
		return assetEntryAssetDisplayPageRelPersistence.remove(assetEntryAssetDisplayPageId);
	}

	/**
	 * Deletes the asset entry asset display page rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetDisplayPageRel the asset entry asset display page rel
	 * @return the asset entry asset display page rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetDisplayPageRel deleteAssetEntryAssetDisplayPageRel(
		AssetEntryAssetDisplayPageRel assetEntryAssetDisplayPageRel) {
		return assetEntryAssetDisplayPageRelPersistence.remove(assetEntryAssetDisplayPageRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AssetEntryAssetDisplayPageRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntryAssetDisplayPageRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryAssetDisplayPageRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetEntryAssetDisplayPageRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryAssetDisplayPageRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetEntryAssetDisplayPageRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntryAssetDisplayPageRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetEntryAssetDisplayPageRelPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AssetEntryAssetDisplayPageRel fetchAssetEntryAssetDisplayPageRel(
		long assetEntryAssetDisplayPageId) {
		return assetEntryAssetDisplayPageRelPersistence.fetchByPrimaryKey(assetEntryAssetDisplayPageId);
	}

	/**
	 * Returns the asset entry asset display page rel with the primary key.
	 *
	 * @param assetEntryAssetDisplayPageId the primary key of the asset entry asset display page rel
	 * @return the asset entry asset display page rel
	 * @throws PortalException if a asset entry asset display page rel with the primary key could not be found
	 */
	@Override
	public AssetEntryAssetDisplayPageRel getAssetEntryAssetDisplayPageRel(
		long assetEntryAssetDisplayPageId) throws PortalException {
		return assetEntryAssetDisplayPageRelPersistence.findByPrimaryKey(assetEntryAssetDisplayPageId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetEntryAssetDisplayPageRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetDisplayPageRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetDisplayPageId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetEntryAssetDisplayPageRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetEntryAssetDisplayPageRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetDisplayPageId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetEntryAssetDisplayPageRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetDisplayPageRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryAssetDisplayPageId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetEntryAssetDisplayPageRelLocalService.deleteAssetEntryAssetDisplayPageRel((AssetEntryAssetDisplayPageRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetEntryAssetDisplayPageRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asset entry asset display page rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryAssetDisplayPageRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry asset display page rels
	 * @param end the upper bound of the range of asset entry asset display page rels (not inclusive)
	 * @return the range of asset entry asset display page rels
	 */
	@Override
	public List<AssetEntryAssetDisplayPageRel> getAssetEntryAssetDisplayPageRels(
		int start, int end) {
		return assetEntryAssetDisplayPageRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry asset display page rels.
	 *
	 * @return the number of asset entry asset display page rels
	 */
	@Override
	public int getAssetEntryAssetDisplayPageRelsCount() {
		return assetEntryAssetDisplayPageRelPersistence.countAll();
	}

	/**
	 * Updates the asset entry asset display page rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetDisplayPageRel the asset entry asset display page rel
	 * @return the asset entry asset display page rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetDisplayPageRel updateAssetEntryAssetDisplayPageRel(
		AssetEntryAssetDisplayPageRel assetEntryAssetDisplayPageRel) {
		return assetEntryAssetDisplayPageRelPersistence.update(assetEntryAssetDisplayPageRel);
	}

	/**
	 * Returns the asset entry asset display page rel local service.
	 *
	 * @return the asset entry asset display page rel local service
	 */
	public AssetEntryAssetDisplayPageRelLocalService getAssetEntryAssetDisplayPageRelLocalService() {
		return assetEntryAssetDisplayPageRelLocalService;
	}

	/**
	 * Sets the asset entry asset display page rel local service.
	 *
	 * @param assetEntryAssetDisplayPageRelLocalService the asset entry asset display page rel local service
	 */
	public void setAssetEntryAssetDisplayPageRelLocalService(
		AssetEntryAssetDisplayPageRelLocalService assetEntryAssetDisplayPageRelLocalService) {
		this.assetEntryAssetDisplayPageRelLocalService = assetEntryAssetDisplayPageRelLocalService;
	}

	/**
	 * Returns the asset entry asset display page rel persistence.
	 *
	 * @return the asset entry asset display page rel persistence
	 */
	public AssetEntryAssetDisplayPageRelPersistence getAssetEntryAssetDisplayPageRelPersistence() {
		return assetEntryAssetDisplayPageRelPersistence;
	}

	/**
	 * Sets the asset entry asset display page rel persistence.
	 *
	 * @param assetEntryAssetDisplayPageRelPersistence the asset entry asset display page rel persistence
	 */
	public void setAssetEntryAssetDisplayPageRelPersistence(
		AssetEntryAssetDisplayPageRelPersistence assetEntryAssetDisplayPageRelPersistence) {
		this.assetEntryAssetDisplayPageRelPersistence = assetEntryAssetDisplayPageRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel",
			assetEntryAssetDisplayPageRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.asset.entry.rel.model.AssetEntryAssetDisplayPageRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntryAssetDisplayPageRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntryAssetDisplayPageRel.class;
	}

	protected String getModelClassName() {
		return AssetEntryAssetDisplayPageRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetEntryAssetDisplayPageRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetEntryAssetDisplayPageRelLocalService.class)
	protected AssetEntryAssetDisplayPageRelLocalService assetEntryAssetDisplayPageRelLocalService;
	@BeanReference(type = AssetEntryAssetDisplayPageRelPersistence.class)
	protected AssetEntryAssetDisplayPageRelPersistence assetEntryAssetDisplayPageRelPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}