spring.cache.type=simple

liferay.oauth.urls.excludes=/ready,/server

liferay.oauth.application.external.reference.codes=\
  liferay-streamhub-etc-spring-boot-oauth-application-user-agent,\
  liferay-streamhub-etc-spring-boot-oauth-application-server

main.liferay.agent.oauth.application = liferay-streamhub-etc-spring-boot-oauth-application-user-agent
main.liferay.server.oauth.application liferay-streamhub-etc-spring-boot-oauth-application-server

# Liferay LXC DXP Configuration
com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.main.domain=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

# OAuth2 Server Configuration
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.authorization.uri=/o/oauth2/authorize
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.headless.server.audience=http://localhost:3000
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.headless.server.client.id=id-40cb11b9-3711-4862-283d-8dec35e8d29
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.headless.server.client.secret=secret-aadf8eec-5a44-a723-97e4-85cd37bfd
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.headless.server.scopes=\
  Liferay.Headless.Admin.User.everything.read,\
  Liferay.Object.Admin.REST.everything,\
  c_message.everything,\
  c_chatbot.everything,\
  liferay-json-web-services.everything
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.introspection.uri=/o/oauth2/introspect
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.jwks.uri=/o/oauth2/jwks
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.redirect.uris=/o/oauth2/redirect
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.token.uri=/o/oauth2/token
liferay-streamhub-etc-spring-boot-oauth-application-server.oauth2.home.page.uri=http://localhost:3000

# OAuth2 User Agent Configuration
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.authorization.uri=/o/oauth2/authorize
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.introspection.uri=/o/oauth2/introspect
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.jwks.uri=/o/oauth2/jwks
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.redirect.uris=/o/oauth2/redirect
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.token.uri=/o/oauth2/token
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.user.agent.audience=http://localhost:3000
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.user.agent.client.id=id-4a572a2c-e7b9-b177-e038-56c7a04e1e7c
liferay-streamhub-etc-spring-boot-oauth-application-user-agent.oauth2.home.page.uri=http://localhost:3000
#
# Spring Boot
#
server.port=3000
socket.path=/server

