create table LayoutSEOEntry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	layoutSEOEntryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	privateLayout BOOLEAN,
	layoutId LONG,
	enabledCanonicalURL BOOLEAN,
	canonicalURL STRING null,
	enabledOpenGraphTitle BOOLEAN,
	openGraphTitle STRING null,
	enabledOpenGraphDescription BOOLEAN,
	openGraphDescription STRING null,
	lastPublishDate DATE null,
	openGraphImageFileEntryId LONG
);