/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.tools.service.builder.test.model.EagerBlobEntity;
import com.liferay.portal.tools.service.builder.test.model.EagerBlobEntityModel;
import com.liferay.portal.tools.service.builder.test.model.EagerBlobEntitySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EagerBlobEntity service. Represents a row in the &quot;EagerBlobEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EagerBlobEntityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EagerBlobEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerBlobEntityImpl
 * @generated
 */
@JSON(strict = true)
public class EagerBlobEntityModelImpl
	extends BaseModelImpl<EagerBlobEntity> implements EagerBlobEntityModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a eager blob entity model instance should use the <code>EagerBlobEntity</code> interface instead.
	 */
	public static final String TABLE_NAME = "EagerBlobEntity";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"eagerBlobEntityId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"field1", Types.VARCHAR}, {"field2", Types.BOOLEAN},
		{"field3", Types.INTEGER}, {"field4", Types.TIMESTAMP},
		{"field5", Types.VARCHAR}, {"fieldBlob", Types.BLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eagerBlobEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("field2", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("field3", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("field4", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field5", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fieldBlob", Types.BLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EagerBlobEntity (uuid_ VARCHAR(75) null,eagerBlobEntityId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,field1 VARCHAR(75) null,field2 BOOLEAN,field3 INTEGER,field4 DATE null,field5 VARCHAR(75) null,fieldBlob BLOB)";

	public static final String TABLE_SQL_DROP = "drop table EagerBlobEntity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eagerBlobEntity.field1 ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EagerBlobEntity.field1 ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = false;

	public static final boolean FINDER_CACHE_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EagerBlobEntity toModel(EagerBlobEntitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EagerBlobEntity model = new EagerBlobEntityImpl();

		model.setUuid(soapModel.getUuid());
		model.setEagerBlobEntityId(soapModel.getEagerBlobEntityId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setField1(soapModel.getField1());
		model.setField2(soapModel.isField2());
		model.setField3(soapModel.getField3());
		model.setField4(soapModel.getField4());
		model.setField5(soapModel.getField5());
		model.setFieldBlob(soapModel.getFieldBlob());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EagerBlobEntity> toModels(
		EagerBlobEntitySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EagerBlobEntity> models = new ArrayList<EagerBlobEntity>(
			soapModels.length);

		for (EagerBlobEntitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.EagerBlobEntity"));

	public EagerBlobEntityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eagerBlobEntityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEagerBlobEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eagerBlobEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EagerBlobEntity.class;
	}

	@Override
	public String getModelClassName() {
		return EagerBlobEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EagerBlobEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EagerBlobEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EagerBlobEntity)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EagerBlobEntity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EagerBlobEntity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EagerBlobEntity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EagerBlobEntity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EagerBlobEntity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EagerBlobEntity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EagerBlobEntity.class.getClassLoader(), EagerBlobEntity.class,
			ModelWrapper.class);

		try {
			Constructor<EagerBlobEntity> constructor =
				(Constructor<EagerBlobEntity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<EagerBlobEntity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EagerBlobEntity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EagerBlobEntity, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<EagerBlobEntity, Object>>();
		Map<String, BiConsumer<EagerBlobEntity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EagerBlobEntity, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object uuid) {

					eagerBlobEntity.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"eagerBlobEntityId",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getEagerBlobEntityId();
				}

			});
		attributeSetterBiConsumers.put(
			"eagerBlobEntityId",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object eagerBlobEntityId) {

					eagerBlobEntity.setEagerBlobEntityId(
						(Long)eagerBlobEntityId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object groupId) {

					eagerBlobEntity.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object companyId) {

					eagerBlobEntity.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object userId) {

					eagerBlobEntity.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object userName) {

					eagerBlobEntity.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object createDate) {

					eagerBlobEntity.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object modifiedDate) {

					eagerBlobEntity.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"field1",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getField1();
				}

			});
		attributeSetterBiConsumers.put(
			"field1",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object field1) {

					eagerBlobEntity.setField1((String)field1);
				}

			});
		attributeGetterFunctions.put(
			"field2",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getField2();
				}

			});
		attributeSetterBiConsumers.put(
			"field2",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object field2) {

					eagerBlobEntity.setField2((Boolean)field2);
				}

			});
		attributeGetterFunctions.put(
			"field3",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getField3();
				}

			});
		attributeSetterBiConsumers.put(
			"field3",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object field3) {

					eagerBlobEntity.setField3((Integer)field3);
				}

			});
		attributeGetterFunctions.put(
			"field4",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getField4();
				}

			});
		attributeSetterBiConsumers.put(
			"field4",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object field4) {

					eagerBlobEntity.setField4((Date)field4);
				}

			});
		attributeGetterFunctions.put(
			"field5",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getField5();
				}

			});
		attributeSetterBiConsumers.put(
			"field5",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object field5) {

					eagerBlobEntity.setField5((String)field5);
				}

			});
		attributeGetterFunctions.put(
			"fieldBlob",
			new Function<EagerBlobEntity, Object>() {

				@Override
				public Object apply(EagerBlobEntity eagerBlobEntity) {
					return eagerBlobEntity.getFieldBlob();
				}

			});
		attributeSetterBiConsumers.put(
			"fieldBlob",
			new BiConsumer<EagerBlobEntity, Object>() {

				@Override
				public void accept(
					EagerBlobEntity eagerBlobEntity, Object fieldBlob) {

					eagerBlobEntity.setFieldBlob((Blob)fieldBlob);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEagerBlobEntityId() {
		return _eagerBlobEntityId;
	}

	@Override
	public void setEagerBlobEntityId(long eagerBlobEntityId) {
		_eagerBlobEntityId = eagerBlobEntityId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getField1() {
		if (_field1 == null) {
			return "";
		}
		else {
			return _field1;
		}
	}

	@Override
	public void setField1(String field1) {
		_field1 = field1;
	}

	@JSON
	@Override
	public boolean getField2() {
		return _field2;
	}

	@JSON
	@Override
	public boolean isField2() {
		return _field2;
	}

	@Override
	public void setField2(boolean field2) {
		if (!_setOriginalField2) {
			_setOriginalField2 = true;

			_originalField2 = _field2;
		}

		_field2 = field2;
	}

	public boolean getOriginalField2() {
		return _originalField2;
	}

	@JSON
	@Override
	public int getField3() {
		return _field3;
	}

	@Override
	public void setField3(int field3) {
		_field3 = field3;
	}

	@JSON
	@Override
	public Date getField4() {
		return _field4;
	}

	@Override
	public void setField4(Date field4) {
		_field4 = field4;
	}

	@JSON
	@Override
	public String getField5() {
		if (_field5 == null) {
			return "";
		}
		else {
			return _field5;
		}
	}

	@Override
	public void setField5(String field5) {
		_field5 = field5;
	}

	@JSON
	@Override
	public Blob getFieldBlob() {
		return _fieldBlob;
	}

	@Override
	public void setFieldBlob(Blob fieldBlob) {
		_fieldBlob = fieldBlob;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EagerBlobEntity.class.getName()));
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EagerBlobEntity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EagerBlobEntity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EagerBlobEntity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EagerBlobEntityImpl eagerBlobEntityImpl = new EagerBlobEntityImpl();

		eagerBlobEntityImpl.setUuid(getUuid());
		eagerBlobEntityImpl.setEagerBlobEntityId(getEagerBlobEntityId());
		eagerBlobEntityImpl.setGroupId(getGroupId());
		eagerBlobEntityImpl.setCompanyId(getCompanyId());
		eagerBlobEntityImpl.setUserId(getUserId());
		eagerBlobEntityImpl.setUserName(getUserName());
		eagerBlobEntityImpl.setCreateDate(getCreateDate());
		eagerBlobEntityImpl.setModifiedDate(getModifiedDate());
		eagerBlobEntityImpl.setField1(getField1());
		eagerBlobEntityImpl.setField2(isField2());
		eagerBlobEntityImpl.setField3(getField3());
		eagerBlobEntityImpl.setField4(getField4());
		eagerBlobEntityImpl.setField5(getField5());

		eagerBlobEntityImpl.resetOriginalValues();

		return eagerBlobEntityImpl;
	}

	@Override
	public int compareTo(EagerBlobEntity eagerBlobEntity) {
		int value = 0;

		value = getField1().compareTo(eagerBlobEntity.getField1());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EagerBlobEntity)) {
			return false;
		}

		EagerBlobEntity eagerBlobEntity = (EagerBlobEntity)obj;

		long primaryKey = eagerBlobEntity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EagerBlobEntityModelImpl eagerBlobEntityModelImpl = this;

		eagerBlobEntityModelImpl._originalUuid = eagerBlobEntityModelImpl._uuid;

		eagerBlobEntityModelImpl._originalGroupId =
			eagerBlobEntityModelImpl._groupId;

		eagerBlobEntityModelImpl._setOriginalGroupId = false;

		eagerBlobEntityModelImpl._originalCompanyId =
			eagerBlobEntityModelImpl._companyId;

		eagerBlobEntityModelImpl._setOriginalCompanyId = false;

		eagerBlobEntityModelImpl._setModifiedDate = false;

		eagerBlobEntityModelImpl._originalField2 =
			eagerBlobEntityModelImpl._field2;

		eagerBlobEntityModelImpl._setOriginalField2 = false;
	}

	@Override
	public CacheModel<EagerBlobEntity> toCacheModel() {
		EagerBlobEntityCacheModel eagerBlobEntityCacheModel =
			new EagerBlobEntityCacheModel();

		eagerBlobEntityCacheModel.uuid = getUuid();

		String uuid = eagerBlobEntityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eagerBlobEntityCacheModel.uuid = null;
		}

		eagerBlobEntityCacheModel.eagerBlobEntityId = getEagerBlobEntityId();

		eagerBlobEntityCacheModel.groupId = getGroupId();

		eagerBlobEntityCacheModel.companyId = getCompanyId();

		eagerBlobEntityCacheModel.userId = getUserId();

		eagerBlobEntityCacheModel.userName = getUserName();

		String userName = eagerBlobEntityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			eagerBlobEntityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			eagerBlobEntityCacheModel.createDate = createDate.getTime();
		}
		else {
			eagerBlobEntityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eagerBlobEntityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eagerBlobEntityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eagerBlobEntityCacheModel.field1 = getField1();

		String field1 = eagerBlobEntityCacheModel.field1;

		if ((field1 != null) && (field1.length() == 0)) {
			eagerBlobEntityCacheModel.field1 = null;
		}

		eagerBlobEntityCacheModel.field2 = isField2();

		eagerBlobEntityCacheModel.field3 = getField3();

		Date field4 = getField4();

		if (field4 != null) {
			eagerBlobEntityCacheModel.field4 = field4.getTime();
		}
		else {
			eagerBlobEntityCacheModel.field4 = Long.MIN_VALUE;
		}

		eagerBlobEntityCacheModel.field5 = getField5();

		String field5 = eagerBlobEntityCacheModel.field5;

		if ((field5 != null) && (field5.length() == 0)) {
			eagerBlobEntityCacheModel.field5 = null;
		}

		return eagerBlobEntityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EagerBlobEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EagerBlobEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EagerBlobEntity)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EagerBlobEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EagerBlobEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EagerBlobEntity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EagerBlobEntity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _eagerBlobEntityId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _field1;
	private boolean _field2;
	private boolean _originalField2;
	private boolean _setOriginalField2;
	private int _field3;
	private Date _field4;
	private String _field5;
	private Blob _fieldBlob;
	private EagerBlobEntity _escapedModel;

}