/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity;
import com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntityModel;
import com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntitySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ManyColumnsEntity service. Represents a row in the &quot;ManyColumnsEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ManyColumnsEntityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ManyColumnsEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ManyColumnsEntityImpl
 * @generated
 */
@JSON(strict = true)
public class ManyColumnsEntityModelImpl
	extends BaseModelImpl<ManyColumnsEntity> implements ManyColumnsEntityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a many columns entity model instance should use the <code>ManyColumnsEntity</code> interface instead.
	 */
	public static final String TABLE_NAME = "ManyColumnsEntity";

	public static final Object[][] TABLE_COLUMNS = {
		{"manyColumnsEntityId", Types.BIGINT}, {"column1", Types.INTEGER},
		{"column2", Types.INTEGER}, {"column3", Types.INTEGER},
		{"column4", Types.INTEGER}, {"column5", Types.INTEGER},
		{"column6", Types.INTEGER}, {"column7", Types.INTEGER},
		{"column8", Types.INTEGER}, {"column9", Types.INTEGER},
		{"column10", Types.INTEGER}, {"column11", Types.INTEGER},
		{"column12", Types.INTEGER}, {"column13", Types.INTEGER},
		{"column14", Types.INTEGER}, {"column15", Types.INTEGER},
		{"column16", Types.INTEGER}, {"column17", Types.INTEGER},
		{"column18", Types.INTEGER}, {"column19", Types.INTEGER},
		{"column20", Types.INTEGER}, {"column21", Types.INTEGER},
		{"column22", Types.INTEGER}, {"column23", Types.INTEGER},
		{"column24", Types.INTEGER}, {"column25", Types.INTEGER},
		{"column26", Types.INTEGER}, {"column27", Types.INTEGER},
		{"column28", Types.INTEGER}, {"column29", Types.INTEGER},
		{"column30", Types.INTEGER}, {"column31", Types.INTEGER},
		{"column32", Types.INTEGER}, {"column33", Types.INTEGER},
		{"column34", Types.INTEGER}, {"column35", Types.INTEGER},
		{"column36", Types.INTEGER}, {"column37", Types.INTEGER},
		{"column38", Types.INTEGER}, {"column39", Types.INTEGER},
		{"column40", Types.INTEGER}, {"column41", Types.INTEGER},
		{"column42", Types.INTEGER}, {"column43", Types.INTEGER},
		{"column44", Types.INTEGER}, {"column45", Types.INTEGER},
		{"column46", Types.INTEGER}, {"column47", Types.INTEGER},
		{"column48", Types.INTEGER}, {"column49", Types.INTEGER},
		{"column50", Types.INTEGER}, {"column51", Types.INTEGER},
		{"column52", Types.INTEGER}, {"column53", Types.INTEGER},
		{"column54", Types.INTEGER}, {"column55", Types.INTEGER},
		{"column56", Types.INTEGER}, {"column57", Types.INTEGER},
		{"column58", Types.INTEGER}, {"column59", Types.INTEGER},
		{"column60", Types.INTEGER}, {"column61", Types.INTEGER},
		{"column62", Types.INTEGER}, {"column63", Types.INTEGER},
		{"column64", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("manyColumnsEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("column1", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column2", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column3", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column4", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column5", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column6", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column7", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column8", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column9", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column10", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column11", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column12", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column13", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column14", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column15", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column16", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column17", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column18", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column19", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column20", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column21", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column22", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column23", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column24", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column25", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column26", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column27", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column28", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column29", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column30", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column31", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column32", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column33", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column34", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column35", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column36", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column37", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column38", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column39", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column40", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column41", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column42", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column43", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column44", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column45", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column46", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column47", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column48", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column49", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column50", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column51", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column52", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column53", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column54", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column55", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column56", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column57", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column58", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column59", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column60", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column61", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column62", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column63", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("column64", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ManyColumnsEntity (manyColumnsEntityId LONG not null primary key,column1 INTEGER,column2 INTEGER,column3 INTEGER,column4 INTEGER,column5 INTEGER,column6 INTEGER,column7 INTEGER,column8 INTEGER,column9 INTEGER,column10 INTEGER,column11 INTEGER,column12 INTEGER,column13 INTEGER,column14 INTEGER,column15 INTEGER,column16 INTEGER,column17 INTEGER,column18 INTEGER,column19 INTEGER,column20 INTEGER,column21 INTEGER,column22 INTEGER,column23 INTEGER,column24 INTEGER,column25 INTEGER,column26 INTEGER,column27 INTEGER,column28 INTEGER,column29 INTEGER,column30 INTEGER,column31 INTEGER,column32 INTEGER,column33 INTEGER,column34 INTEGER,column35 INTEGER,column36 INTEGER,column37 INTEGER,column38 INTEGER,column39 INTEGER,column40 INTEGER,column41 INTEGER,column42 INTEGER,column43 INTEGER,column44 INTEGER,column45 INTEGER,column46 INTEGER,column47 INTEGER,column48 INTEGER,column49 INTEGER,column50 INTEGER,column51 INTEGER,column52 INTEGER,column53 INTEGER,column54 INTEGER,column55 INTEGER,column56 INTEGER,column57 INTEGER,column58 INTEGER,column59 INTEGER,column60 INTEGER,column61 INTEGER,column62 INTEGER,column63 INTEGER,column64 INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ManyColumnsEntity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY manyColumnsEntity.manyColumnsEntityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ManyColumnsEntity.manyColumnsEntityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ManyColumnsEntity toModel(ManyColumnsEntitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ManyColumnsEntity model = new ManyColumnsEntityImpl();

		model.setManyColumnsEntityId(soapModel.getManyColumnsEntityId());
		model.setColumn1(soapModel.getColumn1());
		model.setColumn2(soapModel.getColumn2());
		model.setColumn3(soapModel.getColumn3());
		model.setColumn4(soapModel.getColumn4());
		model.setColumn5(soapModel.getColumn5());
		model.setColumn6(soapModel.getColumn6());
		model.setColumn7(soapModel.getColumn7());
		model.setColumn8(soapModel.getColumn8());
		model.setColumn9(soapModel.getColumn9());
		model.setColumn10(soapModel.getColumn10());
		model.setColumn11(soapModel.getColumn11());
		model.setColumn12(soapModel.getColumn12());
		model.setColumn13(soapModel.getColumn13());
		model.setColumn14(soapModel.getColumn14());
		model.setColumn15(soapModel.getColumn15());
		model.setColumn16(soapModel.getColumn16());
		model.setColumn17(soapModel.getColumn17());
		model.setColumn18(soapModel.getColumn18());
		model.setColumn19(soapModel.getColumn19());
		model.setColumn20(soapModel.getColumn20());
		model.setColumn21(soapModel.getColumn21());
		model.setColumn22(soapModel.getColumn22());
		model.setColumn23(soapModel.getColumn23());
		model.setColumn24(soapModel.getColumn24());
		model.setColumn25(soapModel.getColumn25());
		model.setColumn26(soapModel.getColumn26());
		model.setColumn27(soapModel.getColumn27());
		model.setColumn28(soapModel.getColumn28());
		model.setColumn29(soapModel.getColumn29());
		model.setColumn30(soapModel.getColumn30());
		model.setColumn31(soapModel.getColumn31());
		model.setColumn32(soapModel.getColumn32());
		model.setColumn33(soapModel.getColumn33());
		model.setColumn34(soapModel.getColumn34());
		model.setColumn35(soapModel.getColumn35());
		model.setColumn36(soapModel.getColumn36());
		model.setColumn37(soapModel.getColumn37());
		model.setColumn38(soapModel.getColumn38());
		model.setColumn39(soapModel.getColumn39());
		model.setColumn40(soapModel.getColumn40());
		model.setColumn41(soapModel.getColumn41());
		model.setColumn42(soapModel.getColumn42());
		model.setColumn43(soapModel.getColumn43());
		model.setColumn44(soapModel.getColumn44());
		model.setColumn45(soapModel.getColumn45());
		model.setColumn46(soapModel.getColumn46());
		model.setColumn47(soapModel.getColumn47());
		model.setColumn48(soapModel.getColumn48());
		model.setColumn49(soapModel.getColumn49());
		model.setColumn50(soapModel.getColumn50());
		model.setColumn51(soapModel.getColumn51());
		model.setColumn52(soapModel.getColumn52());
		model.setColumn53(soapModel.getColumn53());
		model.setColumn54(soapModel.getColumn54());
		model.setColumn55(soapModel.getColumn55());
		model.setColumn56(soapModel.getColumn56());
		model.setColumn57(soapModel.getColumn57());
		model.setColumn58(soapModel.getColumn58());
		model.setColumn59(soapModel.getColumn59());
		model.setColumn60(soapModel.getColumn60());
		model.setColumn61(soapModel.getColumn61());
		model.setColumn62(soapModel.getColumn62());
		model.setColumn63(soapModel.getColumn63());
		model.setColumn64(soapModel.getColumn64());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ManyColumnsEntity> toModels(
		ManyColumnsEntitySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ManyColumnsEntity> models = new ArrayList<ManyColumnsEntity>(
			soapModels.length);

		for (ManyColumnsEntitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.ManyColumnsEntity"));

	public ManyColumnsEntityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _manyColumnsEntityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setManyColumnsEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _manyColumnsEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ManyColumnsEntity.class;
	}

	@Override
	public String getModelClassName() {
		return ManyColumnsEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ManyColumnsEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ManyColumnsEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ManyColumnsEntity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ManyColumnsEntity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ManyColumnsEntity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ManyColumnsEntity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ManyColumnsEntity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ManyColumnsEntity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ManyColumnsEntity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ManyColumnsEntity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ManyColumnsEntity.class.getClassLoader(), ManyColumnsEntity.class,
			ModelWrapper.class);

		try {
			Constructor<ManyColumnsEntity> constructor =
				(Constructor<ManyColumnsEntity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ManyColumnsEntity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ManyColumnsEntity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ManyColumnsEntity, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ManyColumnsEntity, Object>>();
		Map<String, BiConsumer<ManyColumnsEntity, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ManyColumnsEntity, ?>>();

		attributeGetterFunctions.put(
			"manyColumnsEntityId", ManyColumnsEntity::getManyColumnsEntityId);
		attributeSetterBiConsumers.put(
			"manyColumnsEntityId",
			(BiConsumer<ManyColumnsEntity, Long>)
				ManyColumnsEntity::setManyColumnsEntityId);
		attributeGetterFunctions.put("column1", ManyColumnsEntity::getColumn1);
		attributeSetterBiConsumers.put(
			"column1",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn1);
		attributeGetterFunctions.put("column2", ManyColumnsEntity::getColumn2);
		attributeSetterBiConsumers.put(
			"column2",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn2);
		attributeGetterFunctions.put("column3", ManyColumnsEntity::getColumn3);
		attributeSetterBiConsumers.put(
			"column3",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn3);
		attributeGetterFunctions.put("column4", ManyColumnsEntity::getColumn4);
		attributeSetterBiConsumers.put(
			"column4",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn4);
		attributeGetterFunctions.put("column5", ManyColumnsEntity::getColumn5);
		attributeSetterBiConsumers.put(
			"column5",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn5);
		attributeGetterFunctions.put("column6", ManyColumnsEntity::getColumn6);
		attributeSetterBiConsumers.put(
			"column6",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn6);
		attributeGetterFunctions.put("column7", ManyColumnsEntity::getColumn7);
		attributeSetterBiConsumers.put(
			"column7",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn7);
		attributeGetterFunctions.put("column8", ManyColumnsEntity::getColumn8);
		attributeSetterBiConsumers.put(
			"column8",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn8);
		attributeGetterFunctions.put("column9", ManyColumnsEntity::getColumn9);
		attributeSetterBiConsumers.put(
			"column9",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn9);
		attributeGetterFunctions.put(
			"column10", ManyColumnsEntity::getColumn10);
		attributeSetterBiConsumers.put(
			"column10",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn10);
		attributeGetterFunctions.put(
			"column11", ManyColumnsEntity::getColumn11);
		attributeSetterBiConsumers.put(
			"column11",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn11);
		attributeGetterFunctions.put(
			"column12", ManyColumnsEntity::getColumn12);
		attributeSetterBiConsumers.put(
			"column12",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn12);
		attributeGetterFunctions.put(
			"column13", ManyColumnsEntity::getColumn13);
		attributeSetterBiConsumers.put(
			"column13",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn13);
		attributeGetterFunctions.put(
			"column14", ManyColumnsEntity::getColumn14);
		attributeSetterBiConsumers.put(
			"column14",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn14);
		attributeGetterFunctions.put(
			"column15", ManyColumnsEntity::getColumn15);
		attributeSetterBiConsumers.put(
			"column15",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn15);
		attributeGetterFunctions.put(
			"column16", ManyColumnsEntity::getColumn16);
		attributeSetterBiConsumers.put(
			"column16",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn16);
		attributeGetterFunctions.put(
			"column17", ManyColumnsEntity::getColumn17);
		attributeSetterBiConsumers.put(
			"column17",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn17);
		attributeGetterFunctions.put(
			"column18", ManyColumnsEntity::getColumn18);
		attributeSetterBiConsumers.put(
			"column18",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn18);
		attributeGetterFunctions.put(
			"column19", ManyColumnsEntity::getColumn19);
		attributeSetterBiConsumers.put(
			"column19",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn19);
		attributeGetterFunctions.put(
			"column20", ManyColumnsEntity::getColumn20);
		attributeSetterBiConsumers.put(
			"column20",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn20);
		attributeGetterFunctions.put(
			"column21", ManyColumnsEntity::getColumn21);
		attributeSetterBiConsumers.put(
			"column21",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn21);
		attributeGetterFunctions.put(
			"column22", ManyColumnsEntity::getColumn22);
		attributeSetterBiConsumers.put(
			"column22",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn22);
		attributeGetterFunctions.put(
			"column23", ManyColumnsEntity::getColumn23);
		attributeSetterBiConsumers.put(
			"column23",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn23);
		attributeGetterFunctions.put(
			"column24", ManyColumnsEntity::getColumn24);
		attributeSetterBiConsumers.put(
			"column24",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn24);
		attributeGetterFunctions.put(
			"column25", ManyColumnsEntity::getColumn25);
		attributeSetterBiConsumers.put(
			"column25",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn25);
		attributeGetterFunctions.put(
			"column26", ManyColumnsEntity::getColumn26);
		attributeSetterBiConsumers.put(
			"column26",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn26);
		attributeGetterFunctions.put(
			"column27", ManyColumnsEntity::getColumn27);
		attributeSetterBiConsumers.put(
			"column27",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn27);
		attributeGetterFunctions.put(
			"column28", ManyColumnsEntity::getColumn28);
		attributeSetterBiConsumers.put(
			"column28",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn28);
		attributeGetterFunctions.put(
			"column29", ManyColumnsEntity::getColumn29);
		attributeSetterBiConsumers.put(
			"column29",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn29);
		attributeGetterFunctions.put(
			"column30", ManyColumnsEntity::getColumn30);
		attributeSetterBiConsumers.put(
			"column30",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn30);
		attributeGetterFunctions.put(
			"column31", ManyColumnsEntity::getColumn31);
		attributeSetterBiConsumers.put(
			"column31",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn31);
		attributeGetterFunctions.put(
			"column32", ManyColumnsEntity::getColumn32);
		attributeSetterBiConsumers.put(
			"column32",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn32);
		attributeGetterFunctions.put(
			"column33", ManyColumnsEntity::getColumn33);
		attributeSetterBiConsumers.put(
			"column33",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn33);
		attributeGetterFunctions.put(
			"column34", ManyColumnsEntity::getColumn34);
		attributeSetterBiConsumers.put(
			"column34",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn34);
		attributeGetterFunctions.put(
			"column35", ManyColumnsEntity::getColumn35);
		attributeSetterBiConsumers.put(
			"column35",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn35);
		attributeGetterFunctions.put(
			"column36", ManyColumnsEntity::getColumn36);
		attributeSetterBiConsumers.put(
			"column36",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn36);
		attributeGetterFunctions.put(
			"column37", ManyColumnsEntity::getColumn37);
		attributeSetterBiConsumers.put(
			"column37",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn37);
		attributeGetterFunctions.put(
			"column38", ManyColumnsEntity::getColumn38);
		attributeSetterBiConsumers.put(
			"column38",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn38);
		attributeGetterFunctions.put(
			"column39", ManyColumnsEntity::getColumn39);
		attributeSetterBiConsumers.put(
			"column39",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn39);
		attributeGetterFunctions.put(
			"column40", ManyColumnsEntity::getColumn40);
		attributeSetterBiConsumers.put(
			"column40",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn40);
		attributeGetterFunctions.put(
			"column41", ManyColumnsEntity::getColumn41);
		attributeSetterBiConsumers.put(
			"column41",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn41);
		attributeGetterFunctions.put(
			"column42", ManyColumnsEntity::getColumn42);
		attributeSetterBiConsumers.put(
			"column42",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn42);
		attributeGetterFunctions.put(
			"column43", ManyColumnsEntity::getColumn43);
		attributeSetterBiConsumers.put(
			"column43",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn43);
		attributeGetterFunctions.put(
			"column44", ManyColumnsEntity::getColumn44);
		attributeSetterBiConsumers.put(
			"column44",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn44);
		attributeGetterFunctions.put(
			"column45", ManyColumnsEntity::getColumn45);
		attributeSetterBiConsumers.put(
			"column45",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn45);
		attributeGetterFunctions.put(
			"column46", ManyColumnsEntity::getColumn46);
		attributeSetterBiConsumers.put(
			"column46",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn46);
		attributeGetterFunctions.put(
			"column47", ManyColumnsEntity::getColumn47);
		attributeSetterBiConsumers.put(
			"column47",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn47);
		attributeGetterFunctions.put(
			"column48", ManyColumnsEntity::getColumn48);
		attributeSetterBiConsumers.put(
			"column48",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn48);
		attributeGetterFunctions.put(
			"column49", ManyColumnsEntity::getColumn49);
		attributeSetterBiConsumers.put(
			"column49",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn49);
		attributeGetterFunctions.put(
			"column50", ManyColumnsEntity::getColumn50);
		attributeSetterBiConsumers.put(
			"column50",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn50);
		attributeGetterFunctions.put(
			"column51", ManyColumnsEntity::getColumn51);
		attributeSetterBiConsumers.put(
			"column51",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn51);
		attributeGetterFunctions.put(
			"column52", ManyColumnsEntity::getColumn52);
		attributeSetterBiConsumers.put(
			"column52",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn52);
		attributeGetterFunctions.put(
			"column53", ManyColumnsEntity::getColumn53);
		attributeSetterBiConsumers.put(
			"column53",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn53);
		attributeGetterFunctions.put(
			"column54", ManyColumnsEntity::getColumn54);
		attributeSetterBiConsumers.put(
			"column54",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn54);
		attributeGetterFunctions.put(
			"column55", ManyColumnsEntity::getColumn55);
		attributeSetterBiConsumers.put(
			"column55",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn55);
		attributeGetterFunctions.put(
			"column56", ManyColumnsEntity::getColumn56);
		attributeSetterBiConsumers.put(
			"column56",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn56);
		attributeGetterFunctions.put(
			"column57", ManyColumnsEntity::getColumn57);
		attributeSetterBiConsumers.put(
			"column57",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn57);
		attributeGetterFunctions.put(
			"column58", ManyColumnsEntity::getColumn58);
		attributeSetterBiConsumers.put(
			"column58",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn58);
		attributeGetterFunctions.put(
			"column59", ManyColumnsEntity::getColumn59);
		attributeSetterBiConsumers.put(
			"column59",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn59);
		attributeGetterFunctions.put(
			"column60", ManyColumnsEntity::getColumn60);
		attributeSetterBiConsumers.put(
			"column60",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn60);
		attributeGetterFunctions.put(
			"column61", ManyColumnsEntity::getColumn61);
		attributeSetterBiConsumers.put(
			"column61",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn61);
		attributeGetterFunctions.put(
			"column62", ManyColumnsEntity::getColumn62);
		attributeSetterBiConsumers.put(
			"column62",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn62);
		attributeGetterFunctions.put(
			"column63", ManyColumnsEntity::getColumn63);
		attributeSetterBiConsumers.put(
			"column63",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn63);
		attributeGetterFunctions.put(
			"column64", ManyColumnsEntity::getColumn64);
		attributeSetterBiConsumers.put(
			"column64",
			(BiConsumer<ManyColumnsEntity, Integer>)
				ManyColumnsEntity::setColumn64);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getManyColumnsEntityId() {
		return _manyColumnsEntityId;
	}

	@Override
	public void setManyColumnsEntityId(long manyColumnsEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manyColumnsEntityId = manyColumnsEntityId;
	}

	@JSON
	@Override
	public int getColumn1() {
		return _column1;
	}

	@Override
	public void setColumn1(int column1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column1 = column1;
	}

	@JSON
	@Override
	public int getColumn2() {
		return _column2;
	}

	@Override
	public void setColumn2(int column2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column2 = column2;
	}

	@JSON
	@Override
	public int getColumn3() {
		return _column3;
	}

	@Override
	public void setColumn3(int column3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column3 = column3;
	}

	@JSON
	@Override
	public int getColumn4() {
		return _column4;
	}

	@Override
	public void setColumn4(int column4) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column4 = column4;
	}

	@JSON
	@Override
	public int getColumn5() {
		return _column5;
	}

	@Override
	public void setColumn5(int column5) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column5 = column5;
	}

	@JSON
	@Override
	public int getColumn6() {
		return _column6;
	}

	@Override
	public void setColumn6(int column6) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column6 = column6;
	}

	@JSON
	@Override
	public int getColumn7() {
		return _column7;
	}

	@Override
	public void setColumn7(int column7) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column7 = column7;
	}

	@JSON
	@Override
	public int getColumn8() {
		return _column8;
	}

	@Override
	public void setColumn8(int column8) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column8 = column8;
	}

	@JSON
	@Override
	public int getColumn9() {
		return _column9;
	}

	@Override
	public void setColumn9(int column9) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column9 = column9;
	}

	@JSON
	@Override
	public int getColumn10() {
		return _column10;
	}

	@Override
	public void setColumn10(int column10) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column10 = column10;
	}

	@JSON
	@Override
	public int getColumn11() {
		return _column11;
	}

	@Override
	public void setColumn11(int column11) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column11 = column11;
	}

	@JSON
	@Override
	public int getColumn12() {
		return _column12;
	}

	@Override
	public void setColumn12(int column12) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column12 = column12;
	}

	@JSON
	@Override
	public int getColumn13() {
		return _column13;
	}

	@Override
	public void setColumn13(int column13) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column13 = column13;
	}

	@JSON
	@Override
	public int getColumn14() {
		return _column14;
	}

	@Override
	public void setColumn14(int column14) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column14 = column14;
	}

	@JSON
	@Override
	public int getColumn15() {
		return _column15;
	}

	@Override
	public void setColumn15(int column15) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column15 = column15;
	}

	@JSON
	@Override
	public int getColumn16() {
		return _column16;
	}

	@Override
	public void setColumn16(int column16) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column16 = column16;
	}

	@JSON
	@Override
	public int getColumn17() {
		return _column17;
	}

	@Override
	public void setColumn17(int column17) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column17 = column17;
	}

	@JSON
	@Override
	public int getColumn18() {
		return _column18;
	}

	@Override
	public void setColumn18(int column18) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column18 = column18;
	}

	@JSON
	@Override
	public int getColumn19() {
		return _column19;
	}

	@Override
	public void setColumn19(int column19) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column19 = column19;
	}

	@JSON
	@Override
	public int getColumn20() {
		return _column20;
	}

	@Override
	public void setColumn20(int column20) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column20 = column20;
	}

	@JSON
	@Override
	public int getColumn21() {
		return _column21;
	}

	@Override
	public void setColumn21(int column21) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column21 = column21;
	}

	@JSON
	@Override
	public int getColumn22() {
		return _column22;
	}

	@Override
	public void setColumn22(int column22) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column22 = column22;
	}

	@JSON
	@Override
	public int getColumn23() {
		return _column23;
	}

	@Override
	public void setColumn23(int column23) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column23 = column23;
	}

	@JSON
	@Override
	public int getColumn24() {
		return _column24;
	}

	@Override
	public void setColumn24(int column24) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column24 = column24;
	}

	@JSON
	@Override
	public int getColumn25() {
		return _column25;
	}

	@Override
	public void setColumn25(int column25) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column25 = column25;
	}

	@JSON
	@Override
	public int getColumn26() {
		return _column26;
	}

	@Override
	public void setColumn26(int column26) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column26 = column26;
	}

	@JSON
	@Override
	public int getColumn27() {
		return _column27;
	}

	@Override
	public void setColumn27(int column27) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column27 = column27;
	}

	@JSON
	@Override
	public int getColumn28() {
		return _column28;
	}

	@Override
	public void setColumn28(int column28) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column28 = column28;
	}

	@JSON
	@Override
	public int getColumn29() {
		return _column29;
	}

	@Override
	public void setColumn29(int column29) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column29 = column29;
	}

	@JSON
	@Override
	public int getColumn30() {
		return _column30;
	}

	@Override
	public void setColumn30(int column30) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column30 = column30;
	}

	@JSON
	@Override
	public int getColumn31() {
		return _column31;
	}

	@Override
	public void setColumn31(int column31) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column31 = column31;
	}

	@JSON
	@Override
	public int getColumn32() {
		return _column32;
	}

	@Override
	public void setColumn32(int column32) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column32 = column32;
	}

	@JSON
	@Override
	public int getColumn33() {
		return _column33;
	}

	@Override
	public void setColumn33(int column33) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column33 = column33;
	}

	@JSON
	@Override
	public int getColumn34() {
		return _column34;
	}

	@Override
	public void setColumn34(int column34) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column34 = column34;
	}

	@JSON
	@Override
	public int getColumn35() {
		return _column35;
	}

	@Override
	public void setColumn35(int column35) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column35 = column35;
	}

	@JSON
	@Override
	public int getColumn36() {
		return _column36;
	}

	@Override
	public void setColumn36(int column36) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column36 = column36;
	}

	@JSON
	@Override
	public int getColumn37() {
		return _column37;
	}

	@Override
	public void setColumn37(int column37) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column37 = column37;
	}

	@JSON
	@Override
	public int getColumn38() {
		return _column38;
	}

	@Override
	public void setColumn38(int column38) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column38 = column38;
	}

	@JSON
	@Override
	public int getColumn39() {
		return _column39;
	}

	@Override
	public void setColumn39(int column39) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column39 = column39;
	}

	@JSON
	@Override
	public int getColumn40() {
		return _column40;
	}

	@Override
	public void setColumn40(int column40) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column40 = column40;
	}

	@JSON
	@Override
	public int getColumn41() {
		return _column41;
	}

	@Override
	public void setColumn41(int column41) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column41 = column41;
	}

	@JSON
	@Override
	public int getColumn42() {
		return _column42;
	}

	@Override
	public void setColumn42(int column42) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column42 = column42;
	}

	@JSON
	@Override
	public int getColumn43() {
		return _column43;
	}

	@Override
	public void setColumn43(int column43) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column43 = column43;
	}

	@JSON
	@Override
	public int getColumn44() {
		return _column44;
	}

	@Override
	public void setColumn44(int column44) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column44 = column44;
	}

	@JSON
	@Override
	public int getColumn45() {
		return _column45;
	}

	@Override
	public void setColumn45(int column45) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column45 = column45;
	}

	@JSON
	@Override
	public int getColumn46() {
		return _column46;
	}

	@Override
	public void setColumn46(int column46) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column46 = column46;
	}

	@JSON
	@Override
	public int getColumn47() {
		return _column47;
	}

	@Override
	public void setColumn47(int column47) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column47 = column47;
	}

	@JSON
	@Override
	public int getColumn48() {
		return _column48;
	}

	@Override
	public void setColumn48(int column48) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column48 = column48;
	}

	@JSON
	@Override
	public int getColumn49() {
		return _column49;
	}

	@Override
	public void setColumn49(int column49) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column49 = column49;
	}

	@JSON
	@Override
	public int getColumn50() {
		return _column50;
	}

	@Override
	public void setColumn50(int column50) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column50 = column50;
	}

	@JSON
	@Override
	public int getColumn51() {
		return _column51;
	}

	@Override
	public void setColumn51(int column51) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column51 = column51;
	}

	@JSON
	@Override
	public int getColumn52() {
		return _column52;
	}

	@Override
	public void setColumn52(int column52) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column52 = column52;
	}

	@JSON
	@Override
	public int getColumn53() {
		return _column53;
	}

	@Override
	public void setColumn53(int column53) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column53 = column53;
	}

	@JSON
	@Override
	public int getColumn54() {
		return _column54;
	}

	@Override
	public void setColumn54(int column54) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column54 = column54;
	}

	@JSON
	@Override
	public int getColumn55() {
		return _column55;
	}

	@Override
	public void setColumn55(int column55) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column55 = column55;
	}

	@JSON
	@Override
	public int getColumn56() {
		return _column56;
	}

	@Override
	public void setColumn56(int column56) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column56 = column56;
	}

	@JSON
	@Override
	public int getColumn57() {
		return _column57;
	}

	@Override
	public void setColumn57(int column57) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column57 = column57;
	}

	@JSON
	@Override
	public int getColumn58() {
		return _column58;
	}

	@Override
	public void setColumn58(int column58) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column58 = column58;
	}

	@JSON
	@Override
	public int getColumn59() {
		return _column59;
	}

	@Override
	public void setColumn59(int column59) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column59 = column59;
	}

	@JSON
	@Override
	public int getColumn60() {
		return _column60;
	}

	@Override
	public void setColumn60(int column60) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column60 = column60;
	}

	@JSON
	@Override
	public int getColumn61() {
		return _column61;
	}

	@Override
	public void setColumn61(int column61) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column61 = column61;
	}

	@JSON
	@Override
	public int getColumn62() {
		return _column62;
	}

	@Override
	public void setColumn62(int column62) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column62 = column62;
	}

	@JSON
	@Override
	public int getColumn63() {
		return _column63;
	}

	@Override
	public void setColumn63(int column63) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column63 = column63;
	}

	@JSON
	@Override
	public int getColumn64() {
		return _column64;
	}

	@Override
	public void setColumn64(int column64) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column64 = column64;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ManyColumnsEntity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ManyColumnsEntity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ManyColumnsEntity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ManyColumnsEntityImpl manyColumnsEntityImpl =
			new ManyColumnsEntityImpl();

		manyColumnsEntityImpl.setManyColumnsEntityId(getManyColumnsEntityId());
		manyColumnsEntityImpl.setColumn1(getColumn1());
		manyColumnsEntityImpl.setColumn2(getColumn2());
		manyColumnsEntityImpl.setColumn3(getColumn3());
		manyColumnsEntityImpl.setColumn4(getColumn4());
		manyColumnsEntityImpl.setColumn5(getColumn5());
		manyColumnsEntityImpl.setColumn6(getColumn6());
		manyColumnsEntityImpl.setColumn7(getColumn7());
		manyColumnsEntityImpl.setColumn8(getColumn8());
		manyColumnsEntityImpl.setColumn9(getColumn9());
		manyColumnsEntityImpl.setColumn10(getColumn10());
		manyColumnsEntityImpl.setColumn11(getColumn11());
		manyColumnsEntityImpl.setColumn12(getColumn12());
		manyColumnsEntityImpl.setColumn13(getColumn13());
		manyColumnsEntityImpl.setColumn14(getColumn14());
		manyColumnsEntityImpl.setColumn15(getColumn15());
		manyColumnsEntityImpl.setColumn16(getColumn16());
		manyColumnsEntityImpl.setColumn17(getColumn17());
		manyColumnsEntityImpl.setColumn18(getColumn18());
		manyColumnsEntityImpl.setColumn19(getColumn19());
		manyColumnsEntityImpl.setColumn20(getColumn20());
		manyColumnsEntityImpl.setColumn21(getColumn21());
		manyColumnsEntityImpl.setColumn22(getColumn22());
		manyColumnsEntityImpl.setColumn23(getColumn23());
		manyColumnsEntityImpl.setColumn24(getColumn24());
		manyColumnsEntityImpl.setColumn25(getColumn25());
		manyColumnsEntityImpl.setColumn26(getColumn26());
		manyColumnsEntityImpl.setColumn27(getColumn27());
		manyColumnsEntityImpl.setColumn28(getColumn28());
		manyColumnsEntityImpl.setColumn29(getColumn29());
		manyColumnsEntityImpl.setColumn30(getColumn30());
		manyColumnsEntityImpl.setColumn31(getColumn31());
		manyColumnsEntityImpl.setColumn32(getColumn32());
		manyColumnsEntityImpl.setColumn33(getColumn33());
		manyColumnsEntityImpl.setColumn34(getColumn34());
		manyColumnsEntityImpl.setColumn35(getColumn35());
		manyColumnsEntityImpl.setColumn36(getColumn36());
		manyColumnsEntityImpl.setColumn37(getColumn37());
		manyColumnsEntityImpl.setColumn38(getColumn38());
		manyColumnsEntityImpl.setColumn39(getColumn39());
		manyColumnsEntityImpl.setColumn40(getColumn40());
		manyColumnsEntityImpl.setColumn41(getColumn41());
		manyColumnsEntityImpl.setColumn42(getColumn42());
		manyColumnsEntityImpl.setColumn43(getColumn43());
		manyColumnsEntityImpl.setColumn44(getColumn44());
		manyColumnsEntityImpl.setColumn45(getColumn45());
		manyColumnsEntityImpl.setColumn46(getColumn46());
		manyColumnsEntityImpl.setColumn47(getColumn47());
		manyColumnsEntityImpl.setColumn48(getColumn48());
		manyColumnsEntityImpl.setColumn49(getColumn49());
		manyColumnsEntityImpl.setColumn50(getColumn50());
		manyColumnsEntityImpl.setColumn51(getColumn51());
		manyColumnsEntityImpl.setColumn52(getColumn52());
		manyColumnsEntityImpl.setColumn53(getColumn53());
		manyColumnsEntityImpl.setColumn54(getColumn54());
		manyColumnsEntityImpl.setColumn55(getColumn55());
		manyColumnsEntityImpl.setColumn56(getColumn56());
		manyColumnsEntityImpl.setColumn57(getColumn57());
		manyColumnsEntityImpl.setColumn58(getColumn58());
		manyColumnsEntityImpl.setColumn59(getColumn59());
		manyColumnsEntityImpl.setColumn60(getColumn60());
		manyColumnsEntityImpl.setColumn61(getColumn61());
		manyColumnsEntityImpl.setColumn62(getColumn62());
		manyColumnsEntityImpl.setColumn63(getColumn63());
		manyColumnsEntityImpl.setColumn64(getColumn64());

		manyColumnsEntityImpl.resetOriginalValues();

		return manyColumnsEntityImpl;
	}

	@Override
	public int compareTo(ManyColumnsEntity manyColumnsEntity) {
		long primaryKey = manyColumnsEntity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ManyColumnsEntity)) {
			return false;
		}

		ManyColumnsEntity manyColumnsEntity = (ManyColumnsEntity)object;

		long primaryKey = manyColumnsEntity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();
	}

	@Override
	public CacheModel<ManyColumnsEntity> toCacheModel() {
		ManyColumnsEntityCacheModel manyColumnsEntityCacheModel =
			new ManyColumnsEntityCacheModel();

		manyColumnsEntityCacheModel.manyColumnsEntityId =
			getManyColumnsEntityId();

		manyColumnsEntityCacheModel.column1 = getColumn1();

		manyColumnsEntityCacheModel.column2 = getColumn2();

		manyColumnsEntityCacheModel.column3 = getColumn3();

		manyColumnsEntityCacheModel.column4 = getColumn4();

		manyColumnsEntityCacheModel.column5 = getColumn5();

		manyColumnsEntityCacheModel.column6 = getColumn6();

		manyColumnsEntityCacheModel.column7 = getColumn7();

		manyColumnsEntityCacheModel.column8 = getColumn8();

		manyColumnsEntityCacheModel.column9 = getColumn9();

		manyColumnsEntityCacheModel.column10 = getColumn10();

		manyColumnsEntityCacheModel.column11 = getColumn11();

		manyColumnsEntityCacheModel.column12 = getColumn12();

		manyColumnsEntityCacheModel.column13 = getColumn13();

		manyColumnsEntityCacheModel.column14 = getColumn14();

		manyColumnsEntityCacheModel.column15 = getColumn15();

		manyColumnsEntityCacheModel.column16 = getColumn16();

		manyColumnsEntityCacheModel.column17 = getColumn17();

		manyColumnsEntityCacheModel.column18 = getColumn18();

		manyColumnsEntityCacheModel.column19 = getColumn19();

		manyColumnsEntityCacheModel.column20 = getColumn20();

		manyColumnsEntityCacheModel.column21 = getColumn21();

		manyColumnsEntityCacheModel.column22 = getColumn22();

		manyColumnsEntityCacheModel.column23 = getColumn23();

		manyColumnsEntityCacheModel.column24 = getColumn24();

		manyColumnsEntityCacheModel.column25 = getColumn25();

		manyColumnsEntityCacheModel.column26 = getColumn26();

		manyColumnsEntityCacheModel.column27 = getColumn27();

		manyColumnsEntityCacheModel.column28 = getColumn28();

		manyColumnsEntityCacheModel.column29 = getColumn29();

		manyColumnsEntityCacheModel.column30 = getColumn30();

		manyColumnsEntityCacheModel.column31 = getColumn31();

		manyColumnsEntityCacheModel.column32 = getColumn32();

		manyColumnsEntityCacheModel.column33 = getColumn33();

		manyColumnsEntityCacheModel.column34 = getColumn34();

		manyColumnsEntityCacheModel.column35 = getColumn35();

		manyColumnsEntityCacheModel.column36 = getColumn36();

		manyColumnsEntityCacheModel.column37 = getColumn37();

		manyColumnsEntityCacheModel.column38 = getColumn38();

		manyColumnsEntityCacheModel.column39 = getColumn39();

		manyColumnsEntityCacheModel.column40 = getColumn40();

		manyColumnsEntityCacheModel.column41 = getColumn41();

		manyColumnsEntityCacheModel.column42 = getColumn42();

		manyColumnsEntityCacheModel.column43 = getColumn43();

		manyColumnsEntityCacheModel.column44 = getColumn44();

		manyColumnsEntityCacheModel.column45 = getColumn45();

		manyColumnsEntityCacheModel.column46 = getColumn46();

		manyColumnsEntityCacheModel.column47 = getColumn47();

		manyColumnsEntityCacheModel.column48 = getColumn48();

		manyColumnsEntityCacheModel.column49 = getColumn49();

		manyColumnsEntityCacheModel.column50 = getColumn50();

		manyColumnsEntityCacheModel.column51 = getColumn51();

		manyColumnsEntityCacheModel.column52 = getColumn52();

		manyColumnsEntityCacheModel.column53 = getColumn53();

		manyColumnsEntityCacheModel.column54 = getColumn54();

		manyColumnsEntityCacheModel.column55 = getColumn55();

		manyColumnsEntityCacheModel.column56 = getColumn56();

		manyColumnsEntityCacheModel.column57 = getColumn57();

		manyColumnsEntityCacheModel.column58 = getColumn58();

		manyColumnsEntityCacheModel.column59 = getColumn59();

		manyColumnsEntityCacheModel.column60 = getColumn60();

		manyColumnsEntityCacheModel.column61 = getColumn61();

		manyColumnsEntityCacheModel.column62 = getColumn62();

		manyColumnsEntityCacheModel.column63 = getColumn63();

		manyColumnsEntityCacheModel.column64 = getColumn64();

		return manyColumnsEntityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ManyColumnsEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ManyColumnsEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ManyColumnsEntity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ManyColumnsEntity)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ManyColumnsEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ManyColumnsEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ManyColumnsEntity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ManyColumnsEntity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ManyColumnsEntity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _manyColumnsEntityId;
	private int _column1;
	private int _column2;
	private int _column3;
	private int _column4;
	private int _column5;
	private int _column6;
	private int _column7;
	private int _column8;
	private int _column9;
	private int _column10;
	private int _column11;
	private int _column12;
	private int _column13;
	private int _column14;
	private int _column15;
	private int _column16;
	private int _column17;
	private int _column18;
	private int _column19;
	private int _column20;
	private int _column21;
	private int _column22;
	private int _column23;
	private int _column24;
	private int _column25;
	private int _column26;
	private int _column27;
	private int _column28;
	private int _column29;
	private int _column30;
	private int _column31;
	private int _column32;
	private int _column33;
	private int _column34;
	private int _column35;
	private int _column36;
	private int _column37;
	private int _column38;
	private int _column39;
	private int _column40;
	private int _column41;
	private int _column42;
	private int _column43;
	private int _column44;
	private int _column45;
	private int _column46;
	private int _column47;
	private int _column48;
	private int _column49;
	private int _column50;
	private int _column51;
	private int _column52;
	private int _column53;
	private int _column54;
	private int _column55;
	private int _column56;
	private int _column57;
	private int _column58;
	private int _column59;
	private int _column60;
	private int _column61;
	private int _column62;
	private int _column63;
	private int _column64;

	public <T> T getColumnValue(String columnName) {
		Function<ManyColumnsEntity, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ManyColumnsEntity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("manyColumnsEntityId", _manyColumnsEntityId);
		_columnOriginalValues.put("column1", _column1);
		_columnOriginalValues.put("column2", _column2);
		_columnOriginalValues.put("column3", _column3);
		_columnOriginalValues.put("column4", _column4);
		_columnOriginalValues.put("column5", _column5);
		_columnOriginalValues.put("column6", _column6);
		_columnOriginalValues.put("column7", _column7);
		_columnOriginalValues.put("column8", _column8);
		_columnOriginalValues.put("column9", _column9);
		_columnOriginalValues.put("column10", _column10);
		_columnOriginalValues.put("column11", _column11);
		_columnOriginalValues.put("column12", _column12);
		_columnOriginalValues.put("column13", _column13);
		_columnOriginalValues.put("column14", _column14);
		_columnOriginalValues.put("column15", _column15);
		_columnOriginalValues.put("column16", _column16);
		_columnOriginalValues.put("column17", _column17);
		_columnOriginalValues.put("column18", _column18);
		_columnOriginalValues.put("column19", _column19);
		_columnOriginalValues.put("column20", _column20);
		_columnOriginalValues.put("column21", _column21);
		_columnOriginalValues.put("column22", _column22);
		_columnOriginalValues.put("column23", _column23);
		_columnOriginalValues.put("column24", _column24);
		_columnOriginalValues.put("column25", _column25);
		_columnOriginalValues.put("column26", _column26);
		_columnOriginalValues.put("column27", _column27);
		_columnOriginalValues.put("column28", _column28);
		_columnOriginalValues.put("column29", _column29);
		_columnOriginalValues.put("column30", _column30);
		_columnOriginalValues.put("column31", _column31);
		_columnOriginalValues.put("column32", _column32);
		_columnOriginalValues.put("column33", _column33);
		_columnOriginalValues.put("column34", _column34);
		_columnOriginalValues.put("column35", _column35);
		_columnOriginalValues.put("column36", _column36);
		_columnOriginalValues.put("column37", _column37);
		_columnOriginalValues.put("column38", _column38);
		_columnOriginalValues.put("column39", _column39);
		_columnOriginalValues.put("column40", _column40);
		_columnOriginalValues.put("column41", _column41);
		_columnOriginalValues.put("column42", _column42);
		_columnOriginalValues.put("column43", _column43);
		_columnOriginalValues.put("column44", _column44);
		_columnOriginalValues.put("column45", _column45);
		_columnOriginalValues.put("column46", _column46);
		_columnOriginalValues.put("column47", _column47);
		_columnOriginalValues.put("column48", _column48);
		_columnOriginalValues.put("column49", _column49);
		_columnOriginalValues.put("column50", _column50);
		_columnOriginalValues.put("column51", _column51);
		_columnOriginalValues.put("column52", _column52);
		_columnOriginalValues.put("column53", _column53);
		_columnOriginalValues.put("column54", _column54);
		_columnOriginalValues.put("column55", _column55);
		_columnOriginalValues.put("column56", _column56);
		_columnOriginalValues.put("column57", _column57);
		_columnOriginalValues.put("column58", _column58);
		_columnOriginalValues.put("column59", _column59);
		_columnOriginalValues.put("column60", _column60);
		_columnOriginalValues.put("column61", _column61);
		_columnOriginalValues.put("column62", _column62);
		_columnOriginalValues.put("column63", _column63);
		_columnOriginalValues.put("column64", _column64);
	}

	private transient Map<String, Object> _columnOriginalValues;
	private ManyColumnsEntity _escapedModel;

}