/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.meris.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the MerisSegment service. Represents a row in the &quot;MerisSegment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.meris.model.impl.MerisSegmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.meris.model.impl.MerisSegmentImpl}.
 * </p>
 *
 * @author Eduardo Garcia
 * @see MerisSegment
 * @see com.liferay.meris.model.impl.MerisSegmentImpl
 * @see com.liferay.meris.model.impl.MerisSegmentModelImpl
 * @generated
 */
@ProviderType
public interface MerisSegmentModel extends BaseModel<MerisSegment>, GroupedModel,
	LocalizedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a meris segment model instance should use the {@link MerisSegment} interface instead.
	 */

	/**
	 * Returns the primary key of this meris segment.
	 *
	 * @return the primary key of this meris segment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this meris segment.
	 *
	 * @param primaryKey the primary key of this meris segment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the meris segment ID of this meris segment.
	 *
	 * @return the meris segment ID of this meris segment
	 */
	public long getMerisSegmentId();

	/**
	 * Sets the meris segment ID of this meris segment.
	 *
	 * @param merisSegmentId the meris segment ID of this meris segment
	 */
	public void setMerisSegmentId(long merisSegmentId);

	/**
	 * Returns the group ID of this meris segment.
	 *
	 * @return the group ID of this meris segment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this meris segment.
	 *
	 * @param groupId the group ID of this meris segment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this meris segment.
	 *
	 * @return the company ID of this meris segment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this meris segment.
	 *
	 * @param companyId the company ID of this meris segment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this meris segment.
	 *
	 * @return the user ID of this meris segment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this meris segment.
	 *
	 * @param userId the user ID of this meris segment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this meris segment.
	 *
	 * @return the user uuid of this meris segment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this meris segment.
	 *
	 * @param userUuid the user uuid of this meris segment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this meris segment.
	 *
	 * @return the user name of this meris segment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this meris segment.
	 *
	 * @param userName the user name of this meris segment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this meris segment.
	 *
	 * @return the create date of this meris segment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this meris segment.
	 *
	 * @param createDate the create date of this meris segment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this meris segment.
	 *
	 * @return the modified date of this meris segment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this meris segment.
	 *
	 * @param modifiedDate the modified date of this meris segment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this meris segment.
	 *
	 * @return the name of this meris segment
	 */
	public String getName();

	/**
	 * Returns the localized name of this meris segment in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this meris segment
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this meris segment in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this meris segment. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this meris segment in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this meris segment
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this meris segment in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this meris segment
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this meris segment.
	 *
	 * @return the locales and localized names of this meris segment
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this meris segment.
	 *
	 * @param name the name of this meris segment
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this meris segment in the language.
	 *
	 * @param name the localized name of this meris segment
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this meris segment in the language, and sets the default locale.
	 *
	 * @param name the localized name of this meris segment
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this meris segment from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this meris segment
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this meris segment from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this meris segment
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the description of this meris segment.
	 *
	 * @return the description of this meris segment
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this meris segment in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this meris segment
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this meris segment in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this meris segment. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this meris segment in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this meris segment
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this meris segment in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this meris segment
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this meris segment.
	 *
	 * @return the locales and localized descriptions of this meris segment
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this meris segment.
	 *
	 * @param description the description of this meris segment
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this meris segment in the language.
	 *
	 * @param description the localized description of this meris segment
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this meris segment in the language, and sets the default locale.
	 *
	 * @param description the localized description of this meris segment
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this meris segment from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this meris segment
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this meris segment from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this meris segment
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the key of this meris segment.
	 *
	 * @return the key of this meris segment
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this meris segment.
	 *
	 * @param key the key of this meris segment
	 */
	public void setKey(String key);

	/**
	 * Returns the active of this meris segment.
	 *
	 * @return the active of this meris segment
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this meris segment is active.
	 *
	 * @return <code>true</code> if this meris segment is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this meris segment is active.
	 *
	 * @param active the active of this meris segment
	 */
	public void setActive(boolean active);

	/**
	 * Returns the type of this meris segment.
	 *
	 * @return the type of this meris segment
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this meris segment.
	 *
	 * @param type the type of this meris segment
	 */
	public void setType(String type);

	/**
	 * Returns the criteria of this meris segment.
	 *
	 * @return the criteria of this meris segment
	 */
	@AutoEscape
	public String getCriteria();

	/**
	 * Sets the criteria of this meris segment.
	 *
	 * @param criteria the criteria of this meris segment
	 */
	public void setCriteria(String criteria);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(MerisSegment merisSegment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MerisSegment> toCacheModel();

	@Override
	public MerisSegment toEscapedModel();

	@Override
	public MerisSegment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}