/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.fragment.model.FragmentEntryContributed;
import com.liferay.fragment.model.FragmentEntryContributedModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FragmentEntryContributed service. Represents a row in the &quot;FragmentEntryContributed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FragmentEntryContributedModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FragmentEntryContributedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentEntryContributedImpl
 * @generated
 */
public class FragmentEntryContributedModelImpl
	extends BaseModelImpl<FragmentEntryContributed>
	implements FragmentEntryContributedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fragment entry contributed model instance should use the <code>FragmentEntryContributed</code> interface instead.
	 */
	public static final String TABLE_NAME = "FragmentEntryContributed";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"fragmentEntryContributedId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fragmentEntryKey", Types.VARCHAR}, {"css", Types.VARCHAR},
		{"html", Types.VARCHAR}, {"js", Types.VARCHAR},
		{"configuration", Types.VARCHAR}, {"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryContributedId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fragmentEntryKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("css", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("html", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("js", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("configuration", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FragmentEntryContributed (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,fragmentEntryContributedId LONG not null,createDate DATE null,modifiedDate DATE null,fragmentEntryKey VARCHAR(75) null,css VARCHAR(75) null,html VARCHAR(75) null,js VARCHAR(75) null,configuration VARCHAR(75) null,type_ INTEGER,primary key (fragmentEntryContributedId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table FragmentEntryContributed";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fragmentEntryContributed.fragmentEntryContributedId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FragmentEntryContributed.fragmentEntryContributedId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRAGMENTENTRYKEY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRAGMENTENTRYCONTRIBUTEDID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FragmentEntryContributedModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fragmentEntryContributedId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFragmentEntryContributedId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fragmentEntryContributedId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FragmentEntryContributed.class;
	}

	@Override
	public String getModelClassName() {
		return FragmentEntryContributed.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FragmentEntryContributed, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FragmentEntryContributed, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FragmentEntryContributed, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FragmentEntryContributed)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FragmentEntryContributed, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FragmentEntryContributed, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FragmentEntryContributed)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FragmentEntryContributed, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FragmentEntryContributed, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FragmentEntryContributed, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<FragmentEntryContributed, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<FragmentEntryContributed, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FragmentEntryContributed, Object>>();
		Map<String, BiConsumer<FragmentEntryContributed, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FragmentEntryContributed, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FragmentEntryContributed::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FragmentEntryContributed, Long>)
				FragmentEntryContributed::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", FragmentEntryContributed::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<FragmentEntryContributed, Long>)
				FragmentEntryContributed::setCtCollectionId);
		attributeGetterFunctions.put(
			"fragmentEntryContributedId",
			FragmentEntryContributed::getFragmentEntryContributedId);
		attributeSetterBiConsumers.put(
			"fragmentEntryContributedId",
			(BiConsumer<FragmentEntryContributed, Long>)
				FragmentEntryContributed::setFragmentEntryContributedId);
		attributeGetterFunctions.put(
			"createDate", FragmentEntryContributed::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FragmentEntryContributed, Date>)
				FragmentEntryContributed::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FragmentEntryContributed::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FragmentEntryContributed, Date>)
				FragmentEntryContributed::setModifiedDate);
		attributeGetterFunctions.put(
			"fragmentEntryKey", FragmentEntryContributed::getFragmentEntryKey);
		attributeSetterBiConsumers.put(
			"fragmentEntryKey",
			(BiConsumer<FragmentEntryContributed, String>)
				FragmentEntryContributed::setFragmentEntryKey);
		attributeGetterFunctions.put("css", FragmentEntryContributed::getCss);
		attributeSetterBiConsumers.put(
			"css",
			(BiConsumer<FragmentEntryContributed, String>)
				FragmentEntryContributed::setCss);
		attributeGetterFunctions.put("html", FragmentEntryContributed::getHtml);
		attributeSetterBiConsumers.put(
			"html",
			(BiConsumer<FragmentEntryContributed, String>)
				FragmentEntryContributed::setHtml);
		attributeGetterFunctions.put("js", FragmentEntryContributed::getJs);
		attributeSetterBiConsumers.put(
			"js",
			(BiConsumer<FragmentEntryContributed, String>)
				FragmentEntryContributed::setJs);
		attributeGetterFunctions.put(
			"configuration", FragmentEntryContributed::getConfiguration);
		attributeSetterBiConsumers.put(
			"configuration",
			(BiConsumer<FragmentEntryContributed, String>)
				FragmentEntryContributed::setConfiguration);
		attributeGetterFunctions.put("type", FragmentEntryContributed::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<FragmentEntryContributed, Integer>)
				FragmentEntryContributed::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getFragmentEntryContributedId() {
		return _fragmentEntryContributedId;
	}

	@Override
	public void setFragmentEntryContributedId(long fragmentEntryContributedId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fragmentEntryContributedId = fragmentEntryContributedId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFragmentEntryKey() {
		if (_fragmentEntryKey == null) {
			return "";
		}
		else {
			return _fragmentEntryKey;
		}
	}

	@Override
	public void setFragmentEntryKey(String fragmentEntryKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fragmentEntryKey = fragmentEntryKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFragmentEntryKey() {
		return getColumnOriginalValue("fragmentEntryKey");
	}

	@Override
	public String getCss() {
		if (_css == null) {
			return "";
		}
		else {
			return _css;
		}
	}

	@Override
	public void setCss(String css) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_css = css;
	}

	@Override
	public String getHtml() {
		if (_html == null) {
			return "";
		}
		else {
			return _html;
		}
	}

	@Override
	public void setHtml(String html) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_html = html;
	}

	@Override
	public String getJs() {
		if (_js == null) {
			return "";
		}
		else {
			return _js;
		}
	}

	@Override
	public void setJs(String js) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_js = js;
	}

	@Override
	public String getConfiguration() {
		if (_configuration == null) {
			return "";
		}
		else {
			return _configuration;
		}
	}

	@Override
	public void setConfiguration(String configuration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_configuration = configuration;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FragmentEntryContributed.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FragmentEntryContributed toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FragmentEntryContributed>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FragmentEntryContributedImpl fragmentEntryContributedImpl =
			new FragmentEntryContributedImpl();

		fragmentEntryContributedImpl.setMvccVersion(getMvccVersion());
		fragmentEntryContributedImpl.setCtCollectionId(getCtCollectionId());
		fragmentEntryContributedImpl.setFragmentEntryContributedId(
			getFragmentEntryContributedId());
		fragmentEntryContributedImpl.setCreateDate(getCreateDate());
		fragmentEntryContributedImpl.setModifiedDate(getModifiedDate());
		fragmentEntryContributedImpl.setFragmentEntryKey(getFragmentEntryKey());
		fragmentEntryContributedImpl.setCss(getCss());
		fragmentEntryContributedImpl.setHtml(getHtml());
		fragmentEntryContributedImpl.setJs(getJs());
		fragmentEntryContributedImpl.setConfiguration(getConfiguration());
		fragmentEntryContributedImpl.setType(getType());

		fragmentEntryContributedImpl.resetOriginalValues();

		return fragmentEntryContributedImpl;
	}

	@Override
	public FragmentEntryContributed cloneWithOriginalValues() {
		FragmentEntryContributedImpl fragmentEntryContributedImpl =
			new FragmentEntryContributedImpl();

		fragmentEntryContributedImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fragmentEntryContributedImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		fragmentEntryContributedImpl.setFragmentEntryContributedId(
			this.<Long>getColumnOriginalValue("fragmentEntryContributedId"));
		fragmentEntryContributedImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fragmentEntryContributedImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fragmentEntryContributedImpl.setFragmentEntryKey(
			this.<String>getColumnOriginalValue("fragmentEntryKey"));
		fragmentEntryContributedImpl.setCss(
			this.<String>getColumnOriginalValue("css"));
		fragmentEntryContributedImpl.setHtml(
			this.<String>getColumnOriginalValue("html"));
		fragmentEntryContributedImpl.setJs(
			this.<String>getColumnOriginalValue("js"));
		fragmentEntryContributedImpl.setConfiguration(
			this.<String>getColumnOriginalValue("configuration"));
		fragmentEntryContributedImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));

		return fragmentEntryContributedImpl;
	}

	@Override
	public int compareTo(FragmentEntryContributed fragmentEntryContributed) {
		long primaryKey = fragmentEntryContributed.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FragmentEntryContributed)) {
			return false;
		}

		FragmentEntryContributed fragmentEntryContributed =
			(FragmentEntryContributed)object;

		long primaryKey = fragmentEntryContributed.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FragmentEntryContributed> toCacheModel() {
		FragmentEntryContributedCacheModel fragmentEntryContributedCacheModel =
			new FragmentEntryContributedCacheModel();

		fragmentEntryContributedCacheModel.mvccVersion = getMvccVersion();

		fragmentEntryContributedCacheModel.ctCollectionId = getCtCollectionId();

		fragmentEntryContributedCacheModel.fragmentEntryContributedId =
			getFragmentEntryContributedId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			fragmentEntryContributedCacheModel.createDate =
				createDate.getTime();
		}
		else {
			fragmentEntryContributedCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fragmentEntryContributedCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			fragmentEntryContributedCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fragmentEntryContributedCacheModel.fragmentEntryKey =
			getFragmentEntryKey();

		String fragmentEntryKey =
			fragmentEntryContributedCacheModel.fragmentEntryKey;

		if ((fragmentEntryKey != null) && (fragmentEntryKey.length() == 0)) {
			fragmentEntryContributedCacheModel.fragmentEntryKey = null;
		}

		fragmentEntryContributedCacheModel.css = getCss();

		String css = fragmentEntryContributedCacheModel.css;

		if ((css != null) && (css.length() == 0)) {
			fragmentEntryContributedCacheModel.css = null;
		}

		fragmentEntryContributedCacheModel.html = getHtml();

		String html = fragmentEntryContributedCacheModel.html;

		if ((html != null) && (html.length() == 0)) {
			fragmentEntryContributedCacheModel.html = null;
		}

		fragmentEntryContributedCacheModel.js = getJs();

		String js = fragmentEntryContributedCacheModel.js;

		if ((js != null) && (js.length() == 0)) {
			fragmentEntryContributedCacheModel.js = null;
		}

		fragmentEntryContributedCacheModel.configuration = getConfiguration();

		String configuration = fragmentEntryContributedCacheModel.configuration;

		if ((configuration != null) && (configuration.length() == 0)) {
			fragmentEntryContributedCacheModel.configuration = null;
		}

		fragmentEntryContributedCacheModel.type = getType();

		return fragmentEntryContributedCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FragmentEntryContributed, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FragmentEntryContributed, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FragmentEntryContributed, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FragmentEntryContributed)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FragmentEntryContributed>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						FragmentEntryContributed.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _fragmentEntryContributedId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _fragmentEntryKey;
	private String _css;
	private String _html;
	private String _js;
	private String _configuration;
	private int _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FragmentEntryContributed, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FragmentEntryContributed)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"fragmentEntryContributedId", _fragmentEntryContributedId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fragmentEntryKey", _fragmentEntryKey);
		_columnOriginalValues.put("css", _css);
		_columnOriginalValues.put("html", _html);
		_columnOriginalValues.put("js", _js);
		_columnOriginalValues.put("configuration", _configuration);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("fragmentEntryContributedId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("fragmentEntryKey", 32L);

		columnBitmasks.put("css", 64L);

		columnBitmasks.put("html", 128L);

		columnBitmasks.put("js", 256L);

		columnBitmasks.put("configuration", 512L);

		columnBitmasks.put("type_", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FragmentEntryContributed _escapedModel;

}