load("ext://uibutton", "cmd_button", "text_input", "location")

# this var will be used to customize the docker volume mapped to
db_container_name = "mysql"
dxp_data_volume = "dxpData"
mysql_data_volume = "mysqlData"

# api docs for adding UIButtons found here: https://docs.tilt.dev/buttons.html
cmd_button(
    "Kill DXP!",
    argv=[
        "sh",
        "-c",
        "docker container rm -f dxp-server",
    ],
    resource="dxp.lfr.dev",
    icon_name="delete",
    text="Kill DXP!",
)

cmd_button(
    "Drop DXP Data Volume!",
    argv=[
        "sh",
        "-c",
        "docker volume rm -f %s" % dxp_data_volume,
    ],
    resource="dxp.lfr.dev",
    icon_name="delete",
    text="Drop DXP Data Volume!",
)

cmd_button(
    "Kill mysql!",
    argv=[
        "sh",
        "-c",
        "docker container rm -f %s" % db_container_name,
    ],
    resource=db_container_name,
    icon_name="delete",
    text="Kill mysql!"
)

cmd_button(
    "Drop mysql Data Volume!",
    argv=[
        "sh",
        "-c",
        "docker volume rm -f %s" % mysql_data_volume,
    ],
    resource=db_container_name,
    icon_name="delete",
    text="Drop mysql Data Volume!",
)

# this map will add additional build args to the dxp-server base image build
# To see all buildargs seeSee
# https://github.com/liferay/liferay-localdev/blob/main/docker/images/dxp-server/Dockerfile
dxp_buildargs = {
    "DXP_BASE_IMAGE": "liferay/dxp:7.4.13-u62",
}


# This map will add additional ENV VARs to the dxp-server docker container
# To see full list of ENV VARs supported see portal.properties for possible ENVs
# https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties
dxp_envs = {
    "LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED": "false",
    "LCP_PROJECT_ENVIRONMENT": "local",
    "LCP_PROJECT_ID": "local",
    "LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME": "com.mysql.cj.jdbc.Driver",
    "LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD": "passw0rd",
    "LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL": "jdbc:mysql://%s/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2"
    % db_container_name,
    "LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME": "dxpcloud",
    "LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN": "true",
    "LIFERAY_DISABLE_TRIAL_LICENSE": "false",
	"LIFERAY_LOCALES_PERIOD_ENABLED": "zh_CN,en_AU,en_US,fr_FR,de_DE,it_IT,ja_JP,pt_BR,es_ES",
	"LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEC__UPPERCASEO__UPPERCASEM__UPPERCASEM__UPPERCASEE__UPPERCASER__UPPERCASEC__UPPERCASEE__MINUS__NUMBER5__NUMBER8__NUMBER9__NUMBER8_": "true",
}

dxp_resource_deps = [db_container_name]

mysql_cmd = [
    "docker container rm -f db &&",
    "docker run",
    "--network k3d-localdev",
    "--name %s" % db_container_name,
    "--rm",
    "-e MYSQL_DATABASE=lportal",
    "-e MYSQL_PASSWORD=passw0rd",
    "-e MYSQL_ROOT_PASSWORD=passw0rd",
    "-e MYSQL_USER=dxpcloud",
    "-e LCP_DBNAME=lportal",
    "-e LCP_MASTER_USER_NAME=dxpcloud",
    "-e LCP_MASTER_USER_PASSWORD=passw0rd",
    "-p 3307:3306",
    "-v %s:/var/lib/mysql" % mysql_data_volume,
    "mysql:5.7",
    "mysqld",
    "--character-set-server=utf8",
    "--collation-server=utf8_general_ci",
    "--character-set-filesystem=utf8",
    "--max_allowed_packet=32M",
]

local_resource(
    db_container_name,
    serve_cmd=" ".join(mysql_cmd),
    trigger_mode=TRIGGER_MODE_MANUAL,
    labels=["DXP"],
    readiness_probe=probe(
        failure_threshold=30,
        exec=exec_action(
            [
                "docker",
                "run",
                "--rm",
                "--network",
                "k3d-localdev",
                "mysql:5.7",
                "mysqladmin",
                "ping",
                "-h",
                db_container_name,
                "-udxpcloud",
                "-ppassw0rd",
            ]
        ),
    ),
)

def on_down():
  local("docker container stop %s" % db_container_name)

trigger_mode(TRIGGER_MODE_MANUAL)