/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import fs from 'fs';
import {createRequire} from 'module';
import path from 'path';
import {PurgeCSS} from 'purgecss';

const require = createRequire(import.meta.url);

// Atlas is Clay's stylesheet (Bootstrap based) and ships at ~800 KB. The widget
// injects it into its shadow root, so shipping it whole would dominate the
// bundle. This purges Atlas down to the rules the widget can actually use,
// scanning both the widget source and the installed @clayui package JS (where
// Clay's component class names live). The purge tracks the @clayui packages
// that are installed, so the bundle grows only when a new Clay component is
// adopted. Correctness of the purge (no over-purged Clay styles) is verified by
// the browser tests; the safelist below covers classes Clay toggles at runtime
// or builds dynamically that static scanning cannot see.

const outDir = path.resolve('src/assets');
const outFile = path.join(outDir, 'atlas.css');

let atlasPath;

try {
	atlasPath = require.resolve('@clayui/css/lib/css/atlas.css');
}
catch (error) {

	// eslint-disable-next-line no-console
	console.warn(
		'Atlas not resolvable; keeping the committed src/assets/atlas.css'
	);

	process.exit(0);
}

const clayDir = path.join(
	atlasPath.split(`${path.sep}@clayui${path.sep}`)[0],
	'@clayui'
);

const [purged] = await new PurgeCSS().purge({
	content: [
		'src/**/*.{ts,tsx}',
		'index.html',
		`${clayDir}/**/lib/**/*.{js,mjs}`,
	],
	css: [{extension: 'css', raw: fs.readFileSync(atlasPath, 'utf8')}],

	// Keep CSS custom properties (the :root variables Atlas defines and the
	// widget re-homes onto :host) and animation keyframes.

	fontFace: false,
	keyframes: false,
	safelist: {

		// Clay builds some class names dynamically (e.g. ClayButton renders
		// `btn-${displayType}`), so static scanning cannot see them; keep the
		// button display-type variants and the icon classes.

		greedy: [/lexicon-icon/, /^btn-/],
		standard: [
			/^:root$/,
			/^:host$/,
			'a',
			'body',
			'button',
			'div',
			'form',
			'h1',
			'h2',
			'h3',
			'html',
			'input',
			'label',
			'li',
			'p',
			'select',
			'span',
			'svg',
			'textarea',
			'ul',
			'use',
		],
	},
	variables: false,
});

fs.mkdirSync(outDir, {recursive: true});

// The leading comment carries an @generated marker so the source formatter
// skips this file; it is rewritten on every build and must not be hand-edited.

fs.writeFileSync(
	outFile,
	`/* @generated by scripts/buildAtlas.mjs */\n${purged.css}`
);

// eslint-disable-next-line no-console
console.log(
	`Wrote purged Atlas (${purged.css.length} bytes) to ${path.relative(
		process.cwd(),
		outFile
	)}`
);
