/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.frontend.view.state.model.FrontendViewStateActiveEntry;
import com.liferay.frontend.view.state.service.FrontendViewStateActiveEntryLocalService;
import com.liferay.frontend.view.state.service.FrontendViewStateActiveEntryLocalServiceUtil;
import com.liferay.frontend.view.state.service.persistence.FrontendViewStateActiveEntryPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the frontend view state active entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.frontend.view.state.service.impl.FrontendViewStateActiveEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.frontend.view.state.service.impl.FrontendViewStateActiveEntryLocalServiceImpl
 * @generated
 */
public abstract class FrontendViewStateActiveEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FrontendViewStateActiveEntryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FrontendViewStateActiveEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FrontendViewStateActiveEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the frontend view state active entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FrontendViewStateActiveEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param frontendViewStateActiveEntry the frontend view state active entry
	 * @return the frontend view state active entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FrontendViewStateActiveEntry addFrontendViewStateActiveEntry(
		FrontendViewStateActiveEntry frontendViewStateActiveEntry) {

		frontendViewStateActiveEntry.setNew(true);

		return frontendViewStateActiveEntryPersistence.update(
			frontendViewStateActiveEntry);
	}

	/**
	 * Creates a new frontend view state active entry with the primary key. Does not add the frontend view state active entry to the database.
	 *
	 * @param frontendViewStateActiveEntryId the primary key for the new frontend view state active entry
	 * @return the new frontend view state active entry
	 */
	@Override
	@Transactional(enabled = false)
	public FrontendViewStateActiveEntry createFrontendViewStateActiveEntry(
		long frontendViewStateActiveEntryId) {

		return frontendViewStateActiveEntryPersistence.create(
			frontendViewStateActiveEntryId);
	}

	/**
	 * Deletes the frontend view state active entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FrontendViewStateActiveEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param frontendViewStateActiveEntryId the primary key of the frontend view state active entry
	 * @return the frontend view state active entry that was removed
	 * @throws PortalException if a frontend view state active entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FrontendViewStateActiveEntry deleteFrontendViewStateActiveEntry(
			long frontendViewStateActiveEntryId)
		throws PortalException {

		return frontendViewStateActiveEntryPersistence.remove(
			frontendViewStateActiveEntryId);
	}

	/**
	 * Deletes the frontend view state active entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FrontendViewStateActiveEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param frontendViewStateActiveEntry the frontend view state active entry
	 * @return the frontend view state active entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FrontendViewStateActiveEntry deleteFrontendViewStateActiveEntry(
		FrontendViewStateActiveEntry frontendViewStateActiveEntry) {

		return frontendViewStateActiveEntryPersistence.remove(
			frontendViewStateActiveEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return frontendViewStateActiveEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FrontendViewStateActiveEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return frontendViewStateActiveEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FrontendViewStateActiveEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return frontendViewStateActiveEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FrontendViewStateActiveEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return frontendViewStateActiveEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return frontendViewStateActiveEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return frontendViewStateActiveEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FrontendViewStateActiveEntry fetchFrontendViewStateActiveEntry(
		long frontendViewStateActiveEntryId) {

		return frontendViewStateActiveEntryPersistence.fetchByPrimaryKey(
			frontendViewStateActiveEntryId);
	}

	/**
	 * Returns the frontend view state active entry with the matching UUID and company.
	 *
	 * @param uuid the frontend view state active entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching frontend view state active entry, or <code>null</code> if a matching frontend view state active entry could not be found
	 */
	@Override
	public FrontendViewStateActiveEntry
		fetchFrontendViewStateActiveEntryByUuidAndCompanyId(
			String uuid, long companyId) {

		return frontendViewStateActiveEntryPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the frontend view state active entry with the primary key.
	 *
	 * @param frontendViewStateActiveEntryId the primary key of the frontend view state active entry
	 * @return the frontend view state active entry
	 * @throws PortalException if a frontend view state active entry with the primary key could not be found
	 */
	@Override
	public FrontendViewStateActiveEntry getFrontendViewStateActiveEntry(
			long frontendViewStateActiveEntryId)
		throws PortalException {

		return frontendViewStateActiveEntryPersistence.findByPrimaryKey(
			frontendViewStateActiveEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			frontendViewStateActiveEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			FrontendViewStateActiveEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"frontendViewStateActiveEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			frontendViewStateActiveEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			FrontendViewStateActiveEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"frontendViewStateActiveEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			frontendViewStateActiveEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			FrontendViewStateActiveEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"frontendViewStateActiveEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<FrontendViewStateActiveEntry>() {

				@Override
				public void performAction(
						FrontendViewStateActiveEntry
							frontendViewStateActiveEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, frontendViewStateActiveEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					FrontendViewStateActiveEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return frontendViewStateActiveEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return frontendViewStateActiveEntryLocalService.
			deleteFrontendViewStateActiveEntry(
				(FrontendViewStateActiveEntry)persistedModel);
	}

	@Override
	public BasePersistence<FrontendViewStateActiveEntry> getBasePersistence() {
		return frontendViewStateActiveEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return frontendViewStateActiveEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns the frontend view state active entry with the matching UUID and company.
	 *
	 * @param uuid the frontend view state active entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching frontend view state active entry
	 * @throws PortalException if a matching frontend view state active entry could not be found
	 */
	@Override
	public FrontendViewStateActiveEntry
			getFrontendViewStateActiveEntryByUuidAndCompanyId(
				String uuid, long companyId)
		throws PortalException {

		return frontendViewStateActiveEntryPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the frontend view state active entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FrontendViewStateActiveEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of frontend view state active entries
	 * @param end the upper bound of the range of frontend view state active entries (not inclusive)
	 * @return the range of frontend view state active entries
	 */
	@Override
	public List<FrontendViewStateActiveEntry> getFrontendViewStateActiveEntries(
		int start, int end) {

		return frontendViewStateActiveEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of frontend view state active entries.
	 *
	 * @return the number of frontend view state active entries
	 */
	@Override
	public int getFrontendViewStateActiveEntriesCount() {
		return frontendViewStateActiveEntryPersistence.countAll();
	}

	/**
	 * Updates the frontend view state active entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FrontendViewStateActiveEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param frontendViewStateActiveEntry the frontend view state active entry
	 * @return the frontend view state active entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FrontendViewStateActiveEntry updateFrontendViewStateActiveEntry(
		FrontendViewStateActiveEntry frontendViewStateActiveEntry) {

		return frontendViewStateActiveEntryPersistence.update(
			frontendViewStateActiveEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FrontendViewStateActiveEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		frontendViewStateActiveEntryLocalService =
			(FrontendViewStateActiveEntryLocalService)aopProxy;

		_setLocalServiceUtilService(frontendViewStateActiveEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FrontendViewStateActiveEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FrontendViewStateActiveEntry.class;
	}

	protected String getModelClassName() {
		return FrontendViewStateActiveEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				frontendViewStateActiveEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FrontendViewStateActiveEntryLocalService
			frontendViewStateActiveEntryLocalService) {

		try {
			Field field =
				FrontendViewStateActiveEntryLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, frontendViewStateActiveEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected FrontendViewStateActiveEntryLocalService
		frontendViewStateActiveEntryLocalService;

	@Reference
	protected FrontendViewStateActiveEntryPersistence
		frontendViewStateActiveEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}