logging.level.com.how.service=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
liferay.oauth.application.external.reference.code=how-oauth-application-user-agent
liferay.portal.url=http://localhost:8080
dxp.domains=localhost
server.port=58082