{{- if and .Values.git.credentials.username .Values.git.credentials.token -}}
{{- $url := .Values.terraformRepo.httpsUrl -}}

{{- $hostname := $url | trimPrefix "https://" | splitList "/" | first -}}
apiVersion: v1
kind: Secret
metadata:
    labels:
    {{- include "liferayBackupRestoreWorkflow.labels" . | nindent 8 }}
    name: {{ .Values.kubernetesSecretName.gitCredentials }}
stringData:
    .git-credentials: |-
        https://{{ .Values.git.credentials.username }}:{{ .Values.git.credentials.token }}@{{ $hostname }}
type: Opaque
{{- end -}}