apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
    annotations:
        {{- toYaml .Values.serviceAccount.annotations | nindent 8 }}
    name: {{ include "liferayBackupRestoreWorkflow.name" . }}
    labels:
    {{- include "liferayBackupRestoreWorkflow.labels" . | nindent 8 }}